### ISSUE TITLE
Crafting calculator horizontal scrollbar

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1006]
Sorry, minor fringe issue: When there are many items added to the crafting calculator, the permalink above the Cost Breakdown becomes the widest element on the page, and creates a horizontal scrolbar. (Eg. on my 1680px wide screen resolution this overflow occurs when I add 21 or more items to the crafting list).

Edit: managed to fix it locally by applying the following css to the page:
```
span.one-click-copy__wrapper,
button.one-click-copy__cta
{
	width: 100%;
	word-wrap: break-word;
}
```

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
