### ISSUE TITLE
Verdarach and Eureka recipes not include some precursors

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#1007]
Hi.
Recipe for Eureka not include crafting Hypothesis  and For Science.
Recipe for Verdarach not include crafting Hifthorn and Lament.

![obraz](https://user-images.githubusercontent.com/12558492/43304413-5314a04e-9174-11e8-9529-291b6c6a5fcd.png)
![obraz](https://user-images.githubusercontent.com/12558492/43304420-578eacdc-9174-11e8-86f6-d254acf31e7b.png)

**Comment by queicherius** [comment]
Thanks for the report, fixed now :)
