### ISSUE TITLE
Add a page for gathering glyph profits

### ISSUE THREAD

**Issue by orenwolf** [gw2efficiency/issues#1020]
With the introduction of another glyph that gives materials, would you consider adding a page for the glyphs that give consistent materials (wood/ore/leather/plants/fine mats/unbound or volatile magic/sprockets) and the 33% harvesting chance glyphs a page to determine what the average yield would be?

Something along the lines of what this spreadsheet used to do?

https://docs.google.com/spreadsheets/d/1YSMIUBOHaw9skv73PdiIWQyiTwkoa3n4QJa8CSGdkTc/edit#gid=0

Essentially, calculate the average yield from each glyph per strike, based on the current values of glyph rewards?

Thanks! :D

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
