### ISSUE TITLE
Farming Tracker shows a loss, while all changes listed are profits

### ISSUE THREAD

**Issue by Kaloell** [gw2efficiency/issues#1027]
I started the tracker to track what Fluctuating Mass dropped.
After opening about 264 of them I waited and this was shown by the tracker:
![screenshot from 2018-08-26 10-18-46](https://user-images.githubusercontent.com/29151272/44626265-aad28500-a919-11e8-9c75-0650d6eae182.png)
Scrolling through the list of changes only showed profits. See the CSV (had to rename it, because github complained):
[farming-difference.txt](https://github.com/gw2efficiency/issues/files/2321353/farming-difference.txt)

**Comment by queicherius** [comment]
What you want is to uncheck "Include items unrelated to farming", else it includes the price fluctuations for all items on your account.
