### ISSUE TITLE
An Idea: on the Exchange courses of Gems add what 400 Gems Cost (as represented in the Game)

### ISSUE THREAD

**Issue by TheMasterofBlubb** [gw2efficiency/issues#1029]
What the title says. Shoudnt be difficult, as just Multiplication, but very neat since i mostly check gw2efficiency before starting the game.

**Comment by queicherius** [comment]
You can just enter that [on the page](https://gw2efficiency.com/currencies/gems?filter.conversion_type=goldToGems_gems&filter.conversion_input=400) :)

![](https://i.imgur.com/gs4pJ8p.png)
