### ISSUE TITLE
Add "Defeat the Ley-Line Anomaly" to the daily page

### ISSUE THREAD

**Issue by Mrblackmagic199** [gw2efficiency/issues#1033]
Would be great if you could get a daily anomaly check box. And/or a custom added check box would be fantastic.

**Comment by queicherius** [comment]
Which anomaly do you mean? If it's the "Sentient Anomaly", that already has a box under "Converters"

**Comment by queicherius** [comment]
Ah cool. Did not know that was a thing, will add it

**Comment by Mrblackmagic199** [comment]
Awesome thanks very much :D

**Comment by queicherius** [comment]
This is now live.

**Comment by Mrblackmagic199** [comment]
Fantastic thanks very much :)
