### ISSUE TITLE
Daily page slow memory leak

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1037]
I recently installed an addon that watches how much memory my tabs use, and the daily page seems to slowly swell in memory use. When I load the page it uses 27-29MB, but this slowly creeps up: in about 3 hours it went up to 129MB. Refreshing the page doesn't seem to fix it (instead it puts the memory use instantly to 45-46MB), only closing the tab, and opening the page in a new one resets the usage back to 27-29.

For reference I use Waterfox 56.2.2, with uBlock enabled (but I have a paid account anyway).

**Comment by kazerniel** [comment]
Though after some checking the addon reports pretty much all non-static websites to slowly increase in memory use, so not sure how accurate it is :man_shrugging:

**Comment by queicherius** [comment]
I can't really figure out why that happens and as long as it's not extreme I don't really have the time to debug it either :( But please let me know if you find a case where it increases very fast.
