### ISSUE TITLE
API Key deletion not working properly

### ISSUE THREAD

**Issue by seark** [gw2efficiency/issues#1041]
I added a new API-Key some days ago and deleted the old one. The key wasn't show for some time but  keeps reappearing on the Manage API Keys page. I deleted it about 3 to 4 time.
Maybe it is an issue with using browsers on different systems to access gw2efficiency.

**Comment by queicherius** [comment]
Yes, you will have to delete the key on all devices you are using, since it keeps syncing the key to your account.
