### ISSUE TITLE
Refactor the daily page

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1052]

**Comment by queicherius** [comment]
Live

**Comment by kazerniel** [comment]
The boxes on the daily page don't shuffle properly for me since the update.

![screenshot](https://user-images.githubusercontent.com/5689996/46491238-1275cd00-c802-11e8-8c66-948aa3c91db9.png)

**Comment by queicherius** [comment]
This is the expected behaviour, at least for now.

**Comment by kazerniel** [comment]
Ah ok, I see :)

**Comment by kazerniel** [comment]
I've been encountering another bug since the update. The hidden elements of sections with changing content don't stay hidden. Eg. I want to only display 'Big Spender' of the WvW section and 'Unbound Magic Gatherer' in Draconis Mons, but both sections keep appearing every day and displaying items I hid a few days before.

**Comment by queicherius** [comment]
Are you sure that items that you hid are reappearing, and those are not
just different dailies?

**Comment by kazerniel** [comment]
I wasn't sure first, but when Reaper's Rumble reappeared yesterday after I specifically remember hiding it in the previous occurrence, my 2-week suspicion got confirmed.

**Comment by kazerniel** [comment]
Today before doing anything I got this response for the script:

`"daily_main_437,daily_main_1845,daily_main_1851,daily_map_3415,daily_map_3409,daily_map_3417,daily_map_draconis_0,daily_map_draconis_1,daily_map_draconis_2,daily_map_draconis_3,daily_map_draconis_4,daily_map_draconis_5,daily_map_draconis_6,daily_map_draconis_7,daily_map_draconis_8,daily_map_3083,daily_map_3055,daily_map_bloodstone_1,daily_map_bloodstone_2,daily_map_bloodstone_3,daily_map_bloodstone_4"`

The after hiding 'Master of Monuments', 'Land Claimer', 'Tower Capturer' and 'Camp Capturer' from the WvW section, hiding 'Event Completer', 'Druid Spirit Boss or Stonehead Boss' and 'Fire Orchid Posy' from the Draconis Mons section, and hiding 'Reaper's Return' again from the Halloween section, I got this response:

`"daily_main_946,daily_main_1849,daily_main_1843,daily_main_1850,daily_map_3413,daily_map_3438,daily_map_3419,daily_map_draconis_0,daily_map_draconis_1,daily_map_draconis_2,daily_map_draconis_3,daily_map_draconis_4,daily_map_draconis_5,daily_map_draconis_6,daily_map_draconis_7,daily_map_draconis_8,daily_map_4451,daily_map_3083,daily_map_3055,daily_map_bloodstone_1,daily_map_bloodstone_2,daily_map_bloodstone_3,daily_map_bloodstone_4"`

**Comment by queicherius** [comment]
@kazerniel Thank you very much for the testing! I think I know what the issue is now, I added a tracking issue here: #1065
