### ISSUE TITLE
Creating App for Android/iOS?

### ISSUE THREAD

**Issue by Mjay94** [gw2efficiency/issues#1055]
Is there any Plan for Creating an apllication for Android/iOS? It would be awesome. So I can calculate on the way back home which item I want to craft or which Daylis i want to make today.

Actually im Using an Application - But its not gw2efficiency - You know :')

**Comment by queicherius** [comment]
There are no plans to create an app for gw2efficiency, but there are plans to improve the mobile version of the website at some point, possibly.
