### ISSUE TITLE
Add Core Tyria Map Completion % to each character

### ISSUE THREAD

**Issue by Shrekenstein** [gw2efficiency/issues#1059]
I make lots of legendary weapons and have over 50 characters.  It would be nice to be able to check and see what % core tyria map completion I have on each character.  I know that it shows on the character select screen but would be nice to be able to use it to sort here on the site who is closest to completion to save time.

**Comment by queicherius** [comment]
I would love to add this, but the information is missing from the official API: https://github.com/arenanet/api-cdi/issues/611

**Comment by Olian04** [comment]
@queicherius couldn't we use the "Been there done that" achievement in order to track atleast some progression?

**Comment by queicherius** [comment]
@Olian04 That only works for the first character on an account, so it's usefulness is pretty limited sadly

**Comment by Shrekenstein** [comment]
I can't say what so ever how the API functions but I can say for sure that if u look in the bottom left corner of the character select screen it tracks core tyria map completion for each and every character on your account.  So I assumed that for it to be able to track/display that info there then I had hoped the API could help as well.

**Comment by queicherius** [comment]
Closing this because realistically we are not getting a feature that has been open on the official API that long. Will open a fresh ticket if we do get it at some point.
