### ISSUE TITLE
Add ability to see which achievements are missing for multiple accounts

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1064]
Would be nice for people that do achievements together

**Comment by queicherius** [comment]
Reopening since it was requested a few times again.

**Comment by ShiningMassXAcc** [comment]
@queicherius - I know you opened and closed.  I agree with your sentiment that this is better for another platform.  I see this more of a discord bot type feature,  probably best in something like aleeva, as they already of some similar cross-account api functionality and good support for various 'events'.  I would want to match your api with theirs, to be able to give a group of five a list of the easiest achievements they could go after.  Both your stuff is closed source, so hard to tell on outside.  Anyway,  just a thought 😀.

**Comment by queicherius** [comment]
Hey, you would be able to use the (undocumented, unsupported and internal) API that you can find when opening the player statistics pages to get the "easiest" achievements. If you are going that route, please ping me on Discord beforehand so we can talk about how the data is used. Usually only some small contribution e.g. like on https://en.gw2treasures.com/achievement/4455 is required.

**Comment by ShiningMassXAcc** [comment]
I see - thanks.  I can't find a discord bot that seems to have a good model of leveraging multiple folks keys seamlessly (as you mentioned, medium complexity but bots built for communities don't seem to have this either).  Thanks though.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
