### ISSUE TITLE
Hidden dailies don't stay hidden if they are not in the rotation

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1065]
This happens because we **overwrite** the hidden ids list with the hidden dailies that are currently in view, which means it removes hidden dailies that are not in the daily rotation on any given day. We should append to the list, not overwrite it.

---

[Debug info](https://github.com/gw2efficiency/issues/issues/1052#issuecomment-431850353)

**Comment by queicherius** [comment]
@kazerniel This should now be fixed (CTRL + F5), please let me know if it happens again.

**Comment by kazerniel** [comment]
After a few days of testing, it does indeed seem fixed, thank you!

**Comment by queicherius** [comment]
Very glad to hear, thank you for confirming and your in-depth bug report 💯

**Comment by kazerniel** [comment]
Sorry, but now it seems that if I unhide a previously hidden section, it gets hidden again after reset. (I tried to unhide some LS3 map sections twice so far, and they reverted on the next day both times.)
