### ISSUE TITLE
Missing Home Nodes

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1070]
There are 4 nodes not present in Home Nodes listing: Supply Cache (Kourna), Mistonium Node (Jahai Bluffs), Black Lion Expedition Contract,  & Black Lion Garden Plot Deed

There are 3 cat-related items that are counted as Home Nodes in the wiki, but are not in the Home Cat or Home Nodes listings: Feline Dispersing Emitter, Feline Water Pistol, Feline Holoscepter

**Comment by queicherius** [comment]
They are missing from the official API: https://github.com/arenanet/api-cdi/issues/567

**Comment by queicherius** [comment]
Closing this because I'll remember to add the nodes once the official API updates.
