### ISSUE TITLE
Black Lion Exclusives Chest

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1072]
The Return of the chest brought 16 old items still have a value of 125 gems or are bound Including:

Armor skins
Exalted Gloves (Bound)
Griffon Hatchling Backpiece (63 gems) (has a glider which isn't in the glider section)
Jackal Pup Backpack (125 gems)
Svanir Gauntlets (Bound)

Weapon skins
Celestial Compass Skin (125 gems)
Hydra Staff (125 gems)

Packages
Fallen Balthazar Package (helms are each 32 gems (96gems total) while outfit is bound)
Fire-Breathing Package (63+61 gems)
Feathers of the Zephyr Package (63 gems and the glider is bound)
Jeweled Scarab Package (63+63gems)
Wild Magic Backpack Glider Combo (bound)

Gizmos (these were forgotten last time)
Bitterfrost Vantage Point (I dont have so I can't check)
Noran's Safe Room Pass and Key (bound)

Minis
Mini Awakened Mounts Pack (Broken in API)
Mini Branded Mounts Pack (Broken in API)
Mini Cozy Wintersday Mounts Pack (Broken in API)
Mini Dwayna's Messenger (125gems)
Mini Spooky Mounts Pack (Broken in API)

**Comment by queicherius** [comment]
Thank you very much for the extensive list. This is now live! They will still show up as their gemstore price, but have the value of the box.
