### ISSUE TITLE
Different Value of Playerbase

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1074]
In Account -> Overview -> Leaderboard
You are higher than XY% of 199,378 accounts.

But in Stats -> Unlock Statistics -> Unlocked by Playerbase
203,258

I would have expected the Value to be the same.
I assume the first ignore the private Accounts, whereas the the second does not.

**Comment by queicherius** [comment]
Good find, yeah the second value does (by error) not exclude the accounts that have been opted out of statistic generation. Will fix that soon.
