### ISSUE TITLE
Add page for max profit from salvaging sigils

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1076]
https://www.reddit.com/r/Guildwars2/comments/2wg4r1/guide_max_profits_with_black_lion_salvage_kits/

**Comment by SaiyanOfDarkness** [comment]
Is this still on the table, or shoved on the backburner for now?

**Comment by queicherius** [comment]
Everything that has a ticket is on the table
Everything that has "Priority: Idea" is unlikely to come anytime soon

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

Very niche feature, if you need that functionality it already exists elsewhere: https://www.datawars2.ie/#/extracting
