### ISSUE TITLE
Add whole inventory display

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1081]
Hi,

A hopefully small feature request:
I would like to see an extra window where I can scroll through all my characters inventories, mostly like the currrent
/account/character/[Name]?filter.navigation=inventory
but with the character name, then their inventory (shown as in the mentioned window) then the next character.
And maybe the option to hide characters (Checkbox by their names)

It could also work like the current item search but without filters (type=craftingMaterial does not show all the things I would like to see).

As I have quite a lot of bank character with lots of materials stored tha would help me.
(Would be even better if I could look/search through multiple accounts in one window)

**Comment by queicherius** [comment]
You can already do that by going to [Account -> Overview (with "Show Account" switched to "Always")](https://gw2efficiency.com/account/overview?filter.showAll=true):

![chrome_2018-12-08_14-11-05](https://user-images.githubusercontent.com/4615516/49686891-20421a00-faf3-11e8-9691-33ed4ecd553c.png)
