### ISSUE TITLE
Safari Technology Preview dark mode issue

### ISSUE THREAD

**Issue by orenwolf** [gw2efficiency/issues#1087]
Dark mode does not work with Safari Technology Preview in OSX Mojave.

Safari Technology Preview: Release 72 (Safari 12.1, WebKit 14607.1.17.1)
OSX Mojave: 0.14.2 (18C54)

Clicking the icon to switch between modes does not change the background colour. It does, however, change everything else, leading to white-on-white text.

While this currently only affects STP, these changes will eventually make it to Safari proper and affect far more users.

**Comment by semspanhaak** [comment]
This also applies to the iOS version of safari. I am thinking it has something to do with webkit. I'll try to fix it this weekend.

**Comment by semspanhaak** [comment]
Probably found the bug @orenwolf can you try to replace `nightmode.css:7` the background to `background-color: #0d0d0d !important;` hope it works! I can't test it because I don't have a mac.

**Comment by queicherius** [comment]
@orenwolf Let me know if this works for you, then I could take the code into the main rep

@semspanhaak Thank you! :)

**Comment by orenwolf** [comment]
I applied the css as a user stylesheet, and while that broke most websites (as expected, of course :D) it didn't have any effect on gw2e.

Let me know if there's another way to test that specifically.

**Comment by darthmaim** [comment]
Adding `html { background: #fff; }`, removing `body { background: #0d0d0d !important; }` from nigthmode.css and changing `body, html { height: 100%; }` to `body, html { min-height: 100%; }` seems to fix it in safari in both light and darkmode and not break chrome…

**Comment by queicherius** [comment]
This is now live. Thanks again to everyone! :)
