### ISSUE TITLE
Add conversion of wallet contents into the value calculation

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#109]
Every currency in the wallet is valued at the currently best _permanent & safe_ conversion rate.

- [X] **Gold:** Direct value
- [ ] **Gems:** Current gems to gold conversion rate (#1058)
- [ ] **Spirit Shards:** Best conversion excluding weapons (since they are not a safe conversion and usually require dungeon tokens as well)
- [ ] **Dungeon Tokens:** Best conversion rate excluding items needing account bound recipes and weapons
- [ ] **Laurels:** Best conversion excluding once-per-account items
- [ ] **Karma / Badges of Honor / Guild Commendations / Claim Tickets:** Best conversion rate

**Comment by queicherius** [comment]
Closing this because it's ever going to be added (with the exclusion of gems)

Many of the conversion methods ignore the time required to convert, are unlikely to sell or are never going to be used. This would also inflate the account value incredibly.

**Comment by kazerniel** [comment]
Ran into a related issue, when trying to forge Onyx Lodestones, the crafting calc now tells me to use Mystic Binding Agents instead of Elonian Wine, even though it costs almost 3 times as much with the current laurel exchange rate.

**Comment by queicherius** [comment]
> Ran into a related issue, when trying to forge Onyx Lodestones, the crafting calc now tells me to use Mystic Binding Agents instead of Elonian Wine, even though it costs almost 3 times as much with the current laurel exchange rate.

-> #1119
