### ISSUE TITLE
Its tells me i have this - but i dont

### ISSUE THREAD

**Issue by someone7909** [gw2efficiency/issues#1090]
Hello, i would like to craft a secound precurser, on effenci its told me i have everything - but the game says otherwise.

Effecteted Item:  Perfektionierter Dolch 

Link: https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-29167

Its lokks like i have to craft from screxh on - but effencit tells me otherwise but Perfektionierter Dolch was reused already onetime and its gone!

**Comment by queicherius** [comment]
> i would like to craft a secound precurser

Precursors are only craftable **once** per account.
