### ISSUE TITLE
Bugs/Issues with Time Machine

### ISSUE THREAD

**Issue by smnkrs** [gw2efficiency/issues#1097]
There are 3 issues/bugs with the Time Machine view (I could separate them out into multiple issues if you want @queicherius)

1. The calculation of the sum of account value on the very bottom doesn't change with the checkbox to hide changes caused by market fluctuations. (Not a bug, but a potential improvement)

2. When checking the checkbox for hiding market fluctuations and keeping the checkbox for grouping into categories checked, the category sum doesn't update and stays the same as if you didn't exclude market fluctuations. This is confusing since when you click to expand a category the individual amounts might not sum up to the shown sum at all. (For example: My bank changed +50g with market fluctuations, but when expanding the category, while having the hide fluctuations checkbox checked, the changes sum up to not even +1g or so).

3. When checking the checkbox for hiding market fluctuations but unchecking the checkbox for grouping into categories, the info shown when hovering over the columns for the "coin" row are confusing. The Account Count shows the correct change, but it also shows me an "Item Value" change, which is strange and confusing, since the gold value of gold is 1:1. It should behave like the other currencies just showing +/- 0 for both "Item Value" and "Account Value".

**Comment by queicherius** [comment]
All three points are fixed in the next release. Better late than never. 😅
