### ISSUE TITLE
Mini Husk-o-Lantern

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1104]
The Mini Husk-o-Lantern value isn't set on its cost but just account bound.
It should be 4 candy corn cobs.
![image](https://user-images.githubusercontent.com/45040966/52180612-d91d9000-27e8-11e9-92e1-1d3aa418c4c7.png) 
![image](https://user-images.githubusercontent.com/45040966/52180617-e63a7f00-27e8-11e9-9496-4f4e1d7ffe70.png)

**Comment by queicherius** [comment]
This is now live.
