### ISSUE TITLE
Add more "Order by" options

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1106]
Would be great, if the "order by" in the followng pages could be extended:

https://gw2efficiency.com/account/recipes
Order by:
Buy price (asc/desc)
Sell price (asc/desc)

Order by each column (like with https://gw2efficiency.com/crafting/zephyrite-supply-boxes)
https://gw2efficiency.com/crafting/recipe-overview
https://gw2efficiency.com/crafting/legendaries
https://gw2efficiency.com/crafting/ascended

**Comment by queicherius** [comment]
This is very much included in the reworks that I am doing page-by-page.

**Comment by queicherius** [comment]
- `account/recipes` can not be ordered by buy/sell easily, because it uses the "value" there
- Added sorting to the recipe search (formerly overview) and ascended page
