### ISSUE TITLE
Mounts missing; Tonics not unlocked; Erroneous value to gliders where none are unlocked

### ISSUE THREAD

**Issue by MedicodiBiscotti** [gw2efficiency/issues#1107]
I'm sorry if I should have made three separate issues.

There are loads of mount skins missing from the list. According to the wiki's gallery (https://wiki.guildwars2.com/wiki/Gallery_of_mount_skins) there are 126 skins. gw2economy has 84 listed, meaning 42 are missing. For instance, all but one Desert Racer skin is missing (Painted Mesa).

While I don't have any expensive tonics, all the endless ones that I do have are listed as not unlocked. This includes:
- Charged
- Hard
- Warm
- Cold
- Monkey King
- Skritt Burglar
- Mordrem Thrasher
and probably a few others.

A few days ago, my account value jumped by exactly 1,420. This corresponds with the value of my gliders which it now lists as 1,420. Funnily enough, I do not have any gliders of any value. I have Feathers of the Zephyr but it is listed as valueless.

While all of this is of very, very little consequence, it is a little annoying.
Unrelated, but it would be nice if you could search the material storage and/or bank.

**Comment by MedicodiBiscotti** [comment]
I now realize you can just search for items on the account page. I hadn't thought of doing that, so that's my bad. It's still a bit out of the way, though, if I know I'm looking for a material. I go to mat storage and try to find it but I cannot search. I would have to go back to account, or have to the foresight to know not to look in the mat storage when looking for a mat, which is a bit counter-intuitive.

**Comment by queicherius** [comment]
> There are loads of mount skins missing from the list.

Official API problem, feel free to 👍 here: https://github.com/arenanet/api-cdi/issues/646

> While I don't have any expensive tonics, all the endless ones that I do have are listed as not unlocked

Tonics can only be seen by gw2efficiency when they are in your inventory, not in the novelties. Those are not in the API, feel free to 👍 here: https://github.com/arenanet/api-cdi/issues/642

> A few days ago, my account value jumped by exactly 1,420. This corresponds with the value of my gliders which it now lists as 1,420. Funnily enough, I do not have any gliders of any value. I have Feathers of the Zephyr but it is listed as valueless.

You can see the change in the [Account Time Machine}(https://gw2efficiency.com/account/time-machine). 

> Unrelated, but it would be nice if you could search the material storage and/or bank.
> I now realize you can just search for items on the account page.

Yes, the search is pretty much just there for now, until the other pages get a rehaul.
