### ISSUE TITLE
"Buy all" sets the root level recipes to "buy" for multiple recipes

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1117]
> it's affecting top/root items too:
get the daily items for instance and set to "Buy all":
https://gw2efficiency.com/crafting/calculator/a~1!b~0!c~0!d~20-46744;20-46742;20-46740;20-46745
instead of setting to buy the sub components,
it just set to buy the item itself.

**Comment by akyryz** [comment]
so, i'm not sure which is the more appropriate way to handle:

    * if the item in question can be bought, set it to buy;
    * or set the root item to craft and set the sub components to buy.

but i think it's too soon to get to any conclusion yet, more tests is needed. xD

**Comment by queicherius** [comment]
The fix for this is now live.
