### ISSUE TITLE
Miscalculating Deaths/hour and/or Playtime

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1120]
I have 4,142h 33m Playtime and 7,666 deaths as per the https://gw2efficiency.com/account/statistics page.

In the https://gw2efficiency.com/account/statistics/statistics.deathCountPerHour Page i have 1.85 deaths/hour which seems correct.

In the https://gw2efficiency.com/account/overview Bottom it shows:
You played a total of 4,038 hours across all characters
During that time you died a total of 7,666 times. That's 1.90 deaths per hour
This is using your account data from 4:01:42 PM.
which is also correct for the given data.

But why is there a difference in the Playtime?
Does the first include deleted characters and the other not?
But if so my deleted characters also had a few deaths, wich don't seem to count as both death values are the same.

**Comment by queicherius** [comment]
Looks like the account statistic is using the actual **account** playtime, and the account overview uses the playtime sum of all characters (which is not correct when you delete characters). The deaths are always the sum of the characters.

**Comment by queicherius** [comment]
Change live.
