### ISSUE TITLE
[Bug] Crafting calc gives buy orders for both refined and unrefined mats

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1122]
A duplicate of  #899, but that got locked. I've been still getting this issue pretty much every week for months now. And it is set to buy orders, so supply limits can't cause the issue. Eg. today's shopping list:

![gw2eff](https://user-images.githubusercontent.com/5689996/53702072-277b7a00-3dfb-11e9-95ce-e54a4ebcea91.jpg)

**Comment by queicherius** [comment]
This is pretty much the result of #223 not being implemented.

If you have e.g. two subrecipes that both need orichalcum ingots, but you have some ores, it will optimize for that:

1. Use up the "owned" ores to do the crafting, because it's cheaper than buying all of the ingots -> ores in the shopping list
2. No more "owned" ores, buy the rest of the ingots, because it's cheaper than buying all of the ores -> ingots in the shopping list.

**Comment by kazerniel** [comment]
I may be misunderstanding what you say, but the calculator is telling me to buy more ores than needed to round it up for the ingot crafting. Say, it would need one Mithril Ore to complete an ingot as I had an odd number of ore, but it makes me buy 199 of them, even if apparently the ingots would be cheaper. (142 vs 135)

This was the full screenshot from yesterday, showing how much I had of each mat: https://imgur.com/JLRloqZ

**Comment by queicherius** [comment]
> I may be misunderstanding what you say, but the calculator is telling me to buy more ores than needed to round it up for the ingot crafting. Say, it would need one Mithril Ore to complete an ingot as I had an odd number of ore, but it makes me buy 199 of them, even if crafting the ingots from my ores, then buying all the rest in ingots would be cheaper. (142 vs 135)

Yes, that is exactly what the ticket I linked is for. ATM it can either "craft entire stack" or "buy entire stack" and not "craft X to use own materials, then buy the rest".

**Comment by kazerniel** [comment]
> 
> 
> > I may be misunderstanding what you say, but the calculator is telling me to buy more ores than needed to round it up for the ingot crafting. Say, it would need one Mithril Ore to complete an ingot as I had an odd number of ore, but it makes me buy 199 of them, even if crafting the ingots from my ores, then buying all the rest in ingots would be cheaper. (142 vs 135)
> 
> Yes, that is exactly what the ticket I linked is for. ATM it can either "craft entire stack" or "buy entire stack" and not "craft X to use own materials, then buy the rest".

Oh I see, thanks for the explanation.
