### ISSUE TITLE
Add Sigil effects to tooltip

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1123]
Equipped sigils show their effects on the Weapon, but the tooltip on a sigil only shows their element.

Also would it be possible to include a dropdownmenu when clicking on a item, to open the sigil/runes/infusions that are equipped like the click on the main item?

**Comment by queicherius** [comment]
> https://gw2efficiency.com/currencies/spirit-shards

Equipped sigils show their effects on the Weapon, but the tooltip on a sigil only shows their element.

> Also would it be possible to include a dropdownmenu when clicking on a item, to open the sigil/runes/infusions that are equipped like the click on the main item?

It would be possible, but I am wondering what the usecase here is? Just to check what they do?

**Comment by MaxG46** [comment]
>     Also would it be possible to include a dropdownmenu when clicking on a item, to open the sigil/runes/infusions that are equipped like the click on the main item?
> 
> It would be possible, but I am wondering what the usecase here is? Just to check what they do?

Mostly to see the value, search for more on account, go to crafting it, or open the wiki. It would be nice to have, but not neccessary.

**Comment by MaxG46** [comment]
Also the upgrades on items in the guild bank does not show sigils, nor runes (in Guild stash and overview)

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
