### ISSUE TITLE
Amalgamated gemstone 251 instead of 250

### ISSUE THREAD

**Issue by axi92** [gw2efficiency/issues#1124]
https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-88576
Sry the text is in german but you can see it yourself with the link
![grafik](https://user-images.githubusercontent.com/1394837/54143577-68dadd80-442a-11e9-89b4-49ee3f77c5d9.png)

**Comment by queicherius** [comment]
Fix is now live
