### ISSUE TITLE
Amalgamated Gemstone x10 recipe?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [gw2efficiency/issues#1126]
So right now gw2efficiency does not allow you to bring up the recipe that lets you craft 10-25 amalgamated gemstones.  Wondering if this could be added?

**Comment by queicherius** [comment]
With the current implementation of recipes, this is technically not possible (since it only shows the one cheapest version), and an extremely big undertaking for very little actual value.

**Comment by seaturtlecode** [comment]
I know it has been a year but can this issue remain open if it is sill an issue?
or checkout [the data here](https://gitlab.com/Silvers_Gw2/Stats_Frontend/-/wikis/forging#gemstones)
on how they were able to achieve the calculations for it.
