### ISSUE TITLE
Lodestone recipes missing

### ISSUE THREAD

**Issue by tr7zw** [gw2efficiency/issues#1128]
A few weeks ago the Lodestone recipes where using the Laural items instead of Elonian Wine(which doesn't make sense since Laurals are worth more than 25s). When trying to fix that it seems to have removed the promotion recipe entirely, the crafting calculator only shows the option to buy them.

**Comment by queicherius** [comment]
This is intended. To convert spirit shards use the [spirit shard](https://gw2efficiency.com/currencies/spirit-shards) page (since there is much better uses than loadstones - atm, for example, iron ingots).
