### ISSUE TITLE
[extremely low priority feature request] Add Keybase proof support

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1129]
https://keybase.io/docs/proof_integration_guide

This seems like something that could be done to link GW2 accounts to other stuff. Possibly via an API key with a specially formatted name, or just with a hash stored in the GW2E database.

**Comment by queicherius** [comment]
Since this is not super easy to do, and I don't think the amount of users that would actually use that is more than a few dozen, this is not something I have the resources to do.
