### ISSUE TITLE
Value of the newly added home nodes

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1135]
The newly added nodes for your home instance didn't have a value assigned to them.
These are the missing nodes with their value:

Black Lion Garden Plot Deed - 1.000 gems (x2)
Black Lion Expedition Contract - 1.000 gems
Supply Cache - 50g
Mistonium Node - 50g

Also the Dragon Crystal Node is missing from ls4 ep5, which should be 50g aswell

**Comment by queicherius** [comment]
This is now live
