### ISSUE TITLE
"API key invalid"

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1138]
> This API key is invalid, has corrupted API data or the API can not be reached.
> This is most commonly caused by a browser extension called "Privacy Badger".
> Error reported by the API: "ErrInternal"

It's the same key that I always use.

**Comment by queicherius** [comment]
The API is currently experiencing problems, which causes this issue. This was already reported to ArenaNet and there is nothing we can do except wait for it to get fixed. 🚒💦 🔥
