### ISSUE TITLE
Add aggregated statistics for accounts/characters

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#114]
- [x] Race
- [x] Gender
- [x] Profession
- [x] Account status (F2P, Core, HoT, PoF)

**Comment by Scath-Enfys** [comment]
what do you mean by this? Most and Least used?

**Comment by queicherius** [comment]
> what do you mean by this? Most and Least used?

I was thinking percentage distributions (a lá 45% of characters are warriors)

**Comment by queicherius** [comment]
Also add playtime stats, so how many hours people played on each on their characters (and find a good way to visualize that)

**Comment by queicherius** [comment]
This is live since yesterday. :)
