### ISSUE TITLE
Provide split up Unlocked Skins stats

### ISSUE THREAD

**Issue by tr7zw** [gw2efficiency/issues#1141]
Hey, it would be really awesome to provide split up Stats for the "Unlocked Skins" Account Statistics. Right now all unlocks are just summed up, but since most skins are weapons(it's way harder to unlock new Armor/Backpieces than just BLC Weapon skins), this is kinda unrepresentative. It would be awesome to show:
- Unlocked Skins(Total)
- Unlocked Weapons
- Unlocked Armor
- Unlocked Backpieces
- Unlocked Aquatic Headgear?

This would put it more in line with Dyes, Outfits, Minis, Gliders, Finishers and what not, since they are also not just summed up.

**Comment by queicherius** [comment]
Implementation notes: This is actually not that easy, because at the spot where the account stats are being calculated, we do not have the info what type a skin is, just a list of IDs that the account unlocked.

**Comment by queicherius** [comment]
This is now live.
