### ISSUE TITLE
Item thumbnails seem broken

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1142]
It has been happening for a few days now. Tried it in Waterfox 56.2.9 and Chrome 73.0.3683.103. Hard reload (Ctrl+F5) doesn't fix it either.

OS: Win7 SP1 x64

**Comment by queicherius** [comment]
The API is currently experiencing problems, which causes this issue. This was already reported to ArenaNet and there is nothing we can do except wait for it to get fixed. 🚒💦 🔥

**Comment by kazerniel** [comment]
Ah, it's still that 😅 Thanks and sorry for all the bugging.
