### ISSUE TITLE
Viewing a shared character during an API outage un-shares all characters on that account

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1143]
This is my hypothesis for what's going on, given that my main account's characters were all un-shared and my NA alt didn't lose any shared characters.

**Comment by queicherius** [comment]
Very interesting. Could you send me the API key the characters were shared under? (support@gw2efficiency.com) Then I can use that to filter the logs to figure out if that is what happened.

**Comment by queicherius** [comment]
Turns out this *can* happen if/when the API returns wrong error messages, which seems to be what happened in this case. Added some code to make sure it doesn't again.

**Comment by queicherius** [comment]
Fix is now live.
