### ISSUE TITLE
Holographic Kitten shows Locked

### ISSUE THREAD

**Issue by WolfSabian** [gw2efficiency/issues#1144]
Holographic Kitten shows incorrect status of "not unlocked".  Not sure when this happened of it's an issue with API.  Showed correct before.

**Comment by queicherius** [comment]
This is an issue with the official API - the WvW kittens and the holographic kittens are missing from there at the moment.

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
