### ISSUE TITLE
Add deaths per hour to each character

### ISSUE THREAD

**Issue by lambada** [gw2efficiency/issues#1145]
Much as the Account Overview page shows Deaths per Hour, it would be great if each character page showed the deaths per hour for that character. The Character apge already shows the number of deaths and the playtime.... so it should be fairly straight forward to calculate ;)

**Comment by queicherius** [comment]
Current Idea:

- Birthday
- Playtime

+ Statistics

```
M 8 years and 2 months old
S Created Aug 25, 2012 10:16
S Next present in 9 months and 1 week

M Played for 7,959 hours
S 1 hour and 41 minutes per day

M 4,705 deaths
S 0.59 deaths per hour
```

**Comment by queicherius** [comment]
This is now live.
