### ISSUE TITLE
Account value fluctuations due to back items

### ISSUE THREAD

**Issue by Irubataru** [gw2efficiency/issues#1158]
I have recently seen some fairly big jumps in my account value, and when I went to investigate (mostly for fun, the time machine is really cool 😄), I found that these spikes are quite often caused by large fluctuations in the value of certain back items.

Here is the first jump from 28/04 to 29/04
![image](https://user-images.githubusercontent.com/5611071/57841748-6cdd0000-77cb-11e9-8731-f19848eb5bb7.png)

And then it jumped back up from 15/05 to 16/05
![image](https://user-images.githubusercontent.com/5611071/57841801-867e4780-77cb-11e9-8d26-8c7c7434fbad.png)

I assume some of these values are tied to the value of gems which fluctuate quite a bit, but I don't understand why they fall to almost zero. I think the value of 2k seems a bit inflated, but I don't even know how one would go about measuring the value of a random drop from a black lion chest (I think that's where I got them from).

I am fairly certain I have seen this behaviour before, but I can't document that, so take that with a grain of salt.

Just wanted to report this in case there is has an unnatural reason. If it is a quirk of the system then that is perfectly fine.

**Comment by queicherius** [comment]
These were (mistakenly) removed from the Black Lion Exclusives Chest a few patches ago (loosing their value), and fixed/readded yesterday (re-gaining their value). Also see #1151
