### ISSUE TITLE
Tiny issue with crafting calculator night mode

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1160]
Hi, the `div.one-click-copy__tooltip` element has white background with light green text even in night mode. It also appears behind the currency icons, not in front.

Browser: Waterfox v56.2.9 (x64)

**Comment by queicherius** [comment]
I can actually not easily fix this because of some weird stacking issue with CSS and filters. I'll close the ticket because it's only a tiny thing :)
