### ISSUE TITLE
Crafting Calculator not breaking down gift reqs

### ISSUE THREAD

**Issue by Vera717** [gw2efficiency/issues#1161]
Starting as of today, the crafting calculator is no longer breaking down most of the various gifts required for legendaries into their component parts, nor calculating their cost, rendering the calculator much less useful. Used it for a long time, never seen this error before. Appears to be unclear what's causing it, as, e.g., gift of wood IS broken down into its parts, but gift of stealth is not. None of the gen2 gifts seem to be. When looking at the small breakdown at the top, it states that those gifts are "not sold or crafted".

https://imgur.com/a/K25sj8E

**Comment by queicherius** [comment]
The API is currently experiencing issues, specifically with outputting recipes (only 25% of recipes are in the API right now). This was already reported to ArenaNet and there is nothing we can do except wait for it to get fixed. 🚒💦 🔥
