### ISSUE TITLE
Add "copy name to clipboard" to dye page

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1164]
In Waterfox (so probably Firefox too) the dye preview popup always appears as if the page was fully scrolled up, so if I open one while not on the top of the page, the top part of the popup hangs off the screen.

Plus a feature request: It would be handy if there was a button next to each dye's name to copy its name to the clipboard, so it can be faster searched on the TP.

**Comment by queicherius** [comment]
I can not reproduce that bug in Firefox: 

![2019-05-21_20-27-52](https://user-images.githubusercontent.com/4615516/58124777-ee3af500-7c06-11e9-9307-163437124602.gif)

>  It would be handy if there was a button next to each dye's name to copy its name to the clipboard, so it can be faster searched on the TP.

👍

**Comment by kazerniel** [comment]
> I can not reproduce that bug in Firefox

Huh, strange. Oh well 🤷‍♂

**Comment by queicherius** [comment]
Copy name is now online.
