### ISSUE TITLE
Add the ability to manually check mark recipe as complete

### ISSUE THREAD

**Issue by Renisil** [gw2efficiency/issues#1171]
Different from checking off things from the shopping list, let us mark a part of the recipie as 100% complete to remove all of it's steps from "Crafting Steps"
Would also hopefully work as a workaround for not being able to replace Gift of Maguuma Mastery with Gift of Desert Mastery, so the Crafting Steps isn't as cluttered.
In this example I would checkmark "Gift of Maguuma Mastery" as complete, so it doesnt show up in the crafting steps or the shopping list.
https://i.gyazo.com/04f7eda8686921c45b58c0d008a071d3.png

**Comment by queicherius** [comment]
This is planned via #58, I'll add a comment there.

> Would also hopefully work as a workaround for not being able to replace Gift of Maguuma Mastery with Gift of Desert Mastery, so the Crafting Steps isn't as cluttered.

Just FYI, you can add the subrecipes to get the full recipe: https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-86097;1-71820;1-85744;1-86036
