### ISSUE TITLE
[Bug] Dailies

### ISSUE THREAD

**Issue by kittenblackfriends** [gw2efficiency/issues#1172]
To the manager of the highly trained quaggans:
`VHlwZUVycm9yOiBDYW5ub3QgcmVhZCBwcm9wZXJ0eSAnaWQnIG9mIHVuZGVmaW5lZAogICAgaW4gawogICAgaW4gawogICAgaW4gdAogICAgaW4gbgogICAgaW4gawogICAgaW4gZGl2CiAgICBpbiB0CiAgICBpbiBzCiAgICBpbiBVbmtub3du`

**Comment by queicherius** [comment]
Pretty sure this was caused by the API and should have fixed itself now :)
