### ISSUE TITLE
Time Machine loading spinner keeps running despite 404s

### ISSUE THREAD

**Issue by scy** [gw2efficiency/issues#1178]
First of all, thank you for GW2Efficiency, it's an awesome tool and I wouldn't want to miss it. You're doing a great job! <3

My account has lost about 2k gold in value in the last 12 hours and I was trying to find out why, using the time machine feature.

After selecting start and end snapshot, the quaggan spinner appears, saying _"Loading snapshot differences..."_. And then nothing happened for minutes. So I've opened up the dev tools to see whether it's actually still loading something. Turns out, no. In fact, it stopped loading after less than half a second, but doesn't tell me about it.

![image](https://user-images.githubusercontent.com/28629/59157475-94ae4380-8aab-11e9-9442-1ca3be9dce3b.png)

Now I guess these API calls 404ing is a bug in and of itself, but the page should handle that case gracefully, remove the spinner and show an error message.

In case you're interested: the `api.gw2efficiency.com` calls return `{"text":"all provided ids are invalid"}`, while the `api.guildwars2.com` call returns `{"text": "all ids provided are invalid"}`.

**Comment by queicherius** [comment]
The API is currently experiencing issues which caused most recipes and item prices to disappear (and is also the reason that those API calls 404). Nothing we can do at the moment, but as soon as it's fixed it will fix itself on the site too.

Agree that it should show an error tho.

**Comment by queicherius** [comment]
This is now live.
