### ISSUE TITLE
Icons broken on some tabs

### ISSUE THREAD

**Issue by joelson174** [gw2efficiency/issues#1180]
Yeah, title pretty much says it! It's on the daily tab and on the crafting tab! The only tabs I've seen 
 and used so far! I'm using Vivaldi browser if that's of any concern and it used to work! Sadly it's broken now :(

![image](https://user-images.githubusercontent.com/26340441/59654492-5fb58700-9164-11e9-8a00-cb3d917e0dfa.png)

**Comment by queicherius** [comment]
This is an issue with the official render service: https://en-forum.guildwars2.com/discussion/78590/render-server-outage
