### ISSUE TITLE
Add flag for crafting calculator to count already-owned items as complete

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1182]
Use case: I want to craft a set of legendary armor. All I need to do is kill Xera and then I'll be able to unlock the second collection. However, I can start working on the gifts now.

https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-78797;6-78936;6-78989;6-78866

This is great, but I need to constantly manually update the goals as I make the gifts. I have 6 gifts of dedication and 1 gift of prowess already made, so the recipe is now asking me to gather a bunch of items I don't need anymore.

This could be a third state for "use own materials", named something like "including results".

**Comment by queicherius** [comment]
I think the additional complexity and the need for "yet another option" make this a no-go, especially since it's fairly easy to just enter the new "needed" amount of gifts.
