### ISSUE TITLE
Allow adding items with no recipe to the crafting calculator

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1183]
(This will be most useful if #1182 is also implemented.)

Use case: I want to make something that GW2E doesn't have a recipe for, and probably never will, such as a guild upgrade. Some of these require raw materials, such as mystic coins, which cannot be crafted in any reliable way. Having the cost of these items included would help me plan how I go about getting them.

If this isn't added to the autocomplete for items that can be crafted, could it at least work via inserting item IDs directly into the URL?

**Comment by queicherius** [comment]
This is something that will extremely likely never be supported, because the crafting calculator expects items to have recipes pretty much throughout, and it's a pretty rare use-case (i would say).
