### ISSUE TITLE
Use owned materials for deepest-nested requirements first

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1184]
![image](https://user-images.githubusercontent.com/4257305/59977623-f89b3680-9598-11e9-9d67-a03d7a94ac74.png)

Not a big deal, but it would make it easier to see when an ingredient can be crafted in a big multi-stage recipe.

**Comment by queicherius** [comment]
Duplicate of #225

**Comment by BenLubar** [comment]
Not quite the same, but related enough that fixing one should fix both.
