### ISSUE TITLE
Account searches with spaces could return too many items

### ISSUE THREAD

**Issue by icy-** [gw2efficiency/issues#1185]
A classic search is "o o" (without quotes), in order to return most of the open-able box items in one's inventory.  These are caught by the in-game search filter because most have the description "to open".

In gw2efficiency, however, a search like "o o" (again, without quotes) is returning many, many false positive items which do not seem to have this string (something internal?).  Every inventory bag container, many pieces of armor and weapons, etc. all getting hit without an obvious reason.

**Comment by icy-** [comment]
Oh, if I just add quotes to the gw2efficiency search,  "o o" (with quotes), I get the results I was looking for.  Is the necessity of quotes desired behavior?  If so, you can close this ;D

**Comment by queicherius** [comment]
Yes, it kind works like the google search:

![](https://i.imgur.com/dngTkpC.png)

(Explained on the Material Storage page, but the Account Search uses the same behaviour)
