### ISSUE TITLE
Add Jorbreaker value to related items

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1190]
The new Dragon Bash items dont have a value pointed to them.

Mini Dragon Gourdod - 10 Jorbreakers.
Holographic Shattered Dragon Wing Cover - 25 Jorbreakers.

And the 3 new Recipes have a value of 20c since you can sell them for 20c to the merchant but they do cost 5 Jorbreakers each.

Recipe: Powerful Potion of Branded Slaying
Recipe: Powerful Potion of Mordrem Slaying
Recipe: Powerful Potion of Slaying Scarlet's Armies

Also maybe update these items to their Jorbreakers aswell since their old way of obtaining and putting them on the TP is discontinued.

Mini Helmed Moa Racer - 25 Jorbreakers
Holographic Dragon Wing Cover - 100 Jorbreakers

**Comment by queicherius** [comment]
Updated by @sutgon - Thanks!
