### ISSUE TITLE
Basic finisher not showing up as unlocked

### ISSUE THREAD

**Issue by Ahrle** [gw2efficiency/issues#1197]
The basic finisher, that every account has as default from the very beginning, is greyed out and doesn't count at /account/finishers. It's the flag icon to the left of the text "Basic finisher".
 
![Namnlös](https://user-images.githubusercontent.com/53276888/61824450-4fc54d00-ae5e-11e9-846d-41d24aed7c52.png)

Using Chrome 75.0.3770.142 x64

**Comment by queicherius** [comment]
Fixed in current version
