### ISSUE TITLE
Wrong Dailies displayed

### ISSUE THREAD

**Issue by bwtay** [gw2efficiency/issues#1202]
PvE Dailies for today are displayed wrongly, with "Daily Completionist" replaced by "Daily Frozen Maw". I also notice it sometimes for Jahai Bluffs.

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/10852326/62845928-b7a0e200-bcfe-11e9-9d7a-69aa788b18da.PNG">

**Comment by queicherius** [comment]
Since that was yesterday and I can not check it anymore I am just going to assume that the API returned the wrong dailies.
