### ISSUE TITLE
Add the ability to customize the order of the API keys

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [gw2efficiency/issues#1207]
Basically a manual way to move the position of each API of where it's located without needing to remove them and re-add them.  However reading up on https://github.com/gw2efficiency/issues/issues/710  I'm not sure if it's possible.

**Comment by queicherius** [comment]
Implementation note: We could implement this without *too* much headache (aka adding another internal API endpoints) by just deleting all keys, and then re-adding them in the correct order.

**Comment by queicherius** [comment]
This is now live.
