### ISSUE TITLE
Add custom recipes for cultivated herbs

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#1210]
This would go with recipe-calculation#8.

I don't know how to add custom recipes, but here are the item IDs to save you some time (pouch -> cultivated):

- Sesame 91681 -> 91701
- Cilantro 91695 -> 91715
- Mint 91749 -> 91793
- Clove 91776 -> 91796
- Peppercorn 91802 -> 91869

**Comment by queicherius** [comment]
Now live.
