### ISSUE TITLE
Daily crafting is lacking certain recipes

### ISSUE THREAD

**Issue by SanderLe** [gw2efficiency/issues#1214]
Currently, the Crafting section of the Daily page is lacking Clay Pot, Dragon Hatchling Doll Adornments, Dragon Hatchling Doll Eye, Dragon Hatchling Doll Frame, Dragon Hatchling Doll Hide, Gossamer Stuffing, Grow Lamp, Heat Stone, Plate of Meaty Plant Food, Plate of Piquant Plant Food, and Vial of Maize Balm

**Comment by queicherius** [comment]
Next release will include all of those except for "Gossamer Stuffing", because that is not actually limited (I think?), the required "Spool of Silk Weaving Thread" is.
