### ISSUE TITLE
Tradingpost price & volume history graph for all cultivated plants & seeds not showing

### ISSUE THREAD

**Issue by seark** [gw2efficiency/issues#1217]
I checked several cultivated plants (e.g. "Cultivated Peppercorn") and seeds (e.g. "Cultivated Sesame Seed") and all I checked just show an empty price and volume history graph. I can see the labels on the right (Price & Volume) but not the labels on the x axis, the graph itself and the zoom range at the bottom. Other ascended items (e.g. "+1 Agony Infusion") still show a correct graph.

**Comment by queicherius** [comment]
We currently just show the graph from gw2spidy, so nothing we can do about this. Also see #117
