### ISSUE TITLE
Buy price for "Pile of Compost Starter" missing

### ISSUE THREAD

**Issue by seark** [gw2efficiency/issues#1218]
In the crafting view of "Pile of Enriched Compost" the 5x "Pile of Compost Starter" are shown as not sold or crafted, but are sold by master chefs 10 for 14s96c

**Comment by queicherius** [comment]
This information is not available in the API, and as such would have to be added manually by us for all available 60.000 items. This is something we might want to do in the future but for now this is the intended behaviour :)
