### ISSUE TITLE
Long term TODO list

### ISSUE THREAD

**Issue by Irubataru** [gw2efficiency/issues#1219]
This is a fairly big feature request, but it would be great if it was possible for users to have some sort of TODO list in gw2efficiency where you can organise plans and remember the things you find that you want to achieve.

Some obvious things that could be in a TODO list:
* Achievements you want to obtain (as an alternative to the ingame watchlist for more long term goals perhaps)
* Things you plan to craft, i.e. if it takes you a couple of weeks to craft something so that you don't have to make sure you never close the tab with the calculator already filled out (this is the reason I would want a TODO list at least)
* Skins you want to unlock
* Misc reminders (maybe)

We have the daily TODO list, but it would be great with a long term one as well.

**Comment by queicherius** [comment]
I personally don't think this is in the scope of the project. What I was thinking about however, was the ability to "favourite" things (e.g. achievements, crafts, skins, dyes, ...) and then filter out only those. Would that already solve your use-case?

**Comment by Irubataru** [comment]
It would help but I wouldn't say it would solve the use-case. My specific use-case are when I create big crafting jobs with multiple objects. For example if I want to create a new build I would use the crafting tool and add all the components I need for that build. This would generally be armour, insignias if I want to craft a different set and stat swap it, weapons, possibly food and utilities depending on the build. Then I would slowly work on this and remove the individual components as I finish. Sometimes this takes a week or more and if I then at any point close the window I'd have to either dig through my browser history and see if I can find the link, or set up the multi-craft again.

To some extent it is solvable by me simply bookmarking the URL, but I started thinking and thought I'd throw the idea out there. Maybe someone else had other ideas for things to use a TODO list for. At least for me I tend to be quite scatterbrained when I play, and it would be useful to make a plan I could stick to that went beyond dailies.

I obviously understand that it could be out of scope given that gw2efficiency mostly focus on stats, but given that you have things such as BL investments you do have some user data on top of what can be gathered from the GW2 account.

**Comment by queicherius** [comment]
I think this is a little outside of the scope of the project, I think.
