### ISSUE TITLE
recipe listing wrong ingredients

### ISSUE THREAD

**Issue by twospirited** [gw2efficiency/issues#1221]
https://wiki.guildwars2.com/wiki/Major_Rune_of_the_Wurm on gw2efficiency shows corrupted core instead of corrupted shard,
![Major rune of thewurm](https://user-images.githubusercontent.com/45153697/66887322-77c0da00-ef8f-11e9-9089-505b5df2085b.png)

**Comment by queicherius** [comment]
This recipe can be crafted with either and it picks the one that is cheapest:

![](https://i.imgur.com/H32owyj.png)
