### ISSUE TITLE
Updated Halloween Cob Prices

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1222]
-SKINS-
"Ghostly Racing Scarf" doesnt have its 30 Cobs Bound to it.

-MINIS-
The 4 new minis are currently set to account bound, instead of:
"Mini Mad Memoires" - 5 Cobs.
"Mini Mad Memoires: Complete Edition" - 5 Cobs.
"Mini Mad Memoires: Complete Ignition" - 5 Cobs.
"Mini Altosius the Flame Raven" - 40 Cobs.

Besides that "Mini Haunted Candle" got a price bound to it now which is 20 Cobs.

Changed Prices for minis are:
"Mini Bloody Prince Thorn", from 6 Cobs to 10 Cobs (since the skritt festival vendors).
"Mini Husk-o-Lantern", doesnt seem to have the correct 4 Cobs to it.
"Mini Ghost Carlotta", able to be bought with 10 Cobs, which is much easier to access than its mystic forge recipe of 500gems (outdated) or 3 mini claim tickets.

**Comment by queicherius** [comment]
Updated by @sutgon - Thanks!
