### ISSUE TITLE
Wrong wardrobe armour skin values for items that unlock all weights

### ISSUE THREAD

**Issue by ghost** [gw2efficiency/issues#1224]
Some items count whole skin price for every armour weight when the unlock item unlocks all 3 weights, meaning a X value skin contributes 3X value to account value. List of those skins I've noticed so far:

- Nightfury (Shoulder skin)
- Winter's Presence (Shoulder skin)
- Eggnog Helmet (Helm skin)
- Southsun Mask (Helm skin)
- And quite a few more, basically any non-gemstore armour piece that unlocks multiple weight skins, gemstore pieces solve it by manually adjusting values.

**Comment by malagus** [comment]
Hey. In my opinion your solution ( setting 0.33 factor) i not good because you set value factor for item that unlocks skin not for skin( for example the Khan-Ur skin). If you don't delete idem and sill own them they contribute to account value only as 1/3 of their real value . The factor should be set in different place.

**Comment by sutgon** [comment]
That certain item contributes to account value at 4/3 if you have the item and unlocked the skins, 1/3 for each skin weight and 1/3 for item itself, AFAIK. 

More ideal solution would be for unlock-all-skin items to ignore the value of first such item that unlocks those skins and add full values for next such items, if the items are bound and skins unlocked. 
Like say you have khan skins unlocked and 1 helmet. Total acc contribution would be based on just skin values, so price of 1 helm box. Helm item value gets ignored. 
2 helmets would be price of 2 helm boxes. First helm value gets ignored, second helm gets valued at box price.

**Comment by queicherius** [comment]
I think I fixed this a while ago, please open a fresh issue if this still happens. We don't do it for every skin in the game, but it should work for most.
