### ISSUE TITLE
Some wardrobe skins (and also corresponing items) have value when shouldn't

### ISSUE THREAD

**Issue by sutgon** [gw2efficiency/issues#1225]
Some items and their skins have gold value when they shouldn't due to container being TPable for a short while. List of those skins I've noticed so far:

- Golden Racing Scarf (Shoulder skin)
- Racing Scarf (Shoulder skin)

A maybe-solution could be a blacklist of items whose TP prices would be ignored.

**Comment by queicherius** [comment]
We actually have an internal list of items that we completely ignore the TP prices of, I would like to extract that list into gw2efficiency/game-data and then it's just adding those two IDs 👍

**Comment by queicherius** [comment]
Done via https://github.com/gw2efficiency/game-data/commit/216ae32172e333924cbf21cc06fd043e0beb53d9
