### ISSUE TITLE
Account search does not display items equipped in character's inactive equipment build template.

### ISSUE THREAD

**Issue by NNBR1** [gw2efficiency/issues#1232]
Tested with a character with two sets of jewellery, one in each equipment build template. GW2Efficiency will only show the currently equipped one.

**Comment by queicherius** [comment]
Build templates are not in the API (yet?) so there is nothing we can do about that until they are. :(

**Comment by robinanthony** [comment]
It looks like Anet add the build template in the API in december 2019.
Is it possible to add this new datas now ?

Source :
https://en-forum.guildwars2.com/discussion/94395/api-updates-december-18-2019
