### ISSUE TITLE
Hatched Chili Node value

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1233]
The tradeable version seems to unlock the same node as the account-bound one, but it currently costs 1/4 the bound one's price on the TP.

**Comment by queicherius** [comment]
Needs another entry here for the tradeable version. https://github.com/gw2efficiency/game-data/blob/master/src/home/nodes/data.ts#L30

**Comment by queicherius** [comment]
This is now fixed in the backend, but in the frontend it still shows the old value.
