### ISSUE TITLE
Add lodestones recipes to crafting menu

### ISSUE THREAD

**Issue by AMessiah** [gw2efficiency/issues#1234]
Currently lodestones do not have their mystic forge recipe at the crafting menu.

As the recipe results in a fixed amount I believe it could be added as a crafting option. The recipes are already listed on menu Currencies ->Spirit Shards

**Comment by queicherius** [comment]
This is a conscious design decision because it requires an additional currency to craft them, and most people are not aware of that that is not the optimal way to use spirit shards in a lot of circumstances. See #1119
