### ISSUE TITLE
New Statistics Ideas

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1239]
- [x] https://wiki.guildwars2.com/wiki/Eitrite_Ingot

**Comment by tr7zw** [comment]
I guess this is the right to request the "New Year, new Quaggan" to become a Statistic like "winterWonderlandCompletions" and "salvagedItems". Under "Account > Achievements > Historical > New Year's Customs > New Year, New Quaggan" The actuall value is already correctly calculated.

**Comment by queicherius** [comment]
Both now live.
