### ISSUE TITLE
Better checking of achievement collections

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1240]
E.g Ad Infinitum III fractal capacitator could be marked as completed by the achievement. Right now it checks for the item, but the item has 20 different ids.

**Comment by Intruder7** [comment]
I am curious, doesn't the wiki do this efficiently? How are they doing it?

This question was prompted by the "Complexity" tag ! 
aaand now I saw the date of the issue...

**Comment by queicherius** [comment]
You can see what the wiki does on the achievement page, they just check the bits of the achievement (like us).

This ticket is for the *result* of the achievement, not the individual parts.

**Comment by queicherius** [comment]
This should be fixed now.
