### ISSUE TITLE
Währung / Rentabelste / Geisterscherbe

### ISSUE THREAD

**Issue by luckyheiko** [gw2efficiency/issues#1241]
Hallo 
ich habe mir die Liste der Rentabelsten Items angeschaut. 
Denke aber hier ist ein Fehler. 
Die Preise der Items die benötigt werden stimmen alle mit dem Auktionshaus über ein, aber ich bin der Meinung das bei den Verkaufspreisen die 15% AH Gebühr nicht abgezogen wird. 
Was bedeutet man bekommt hier vorgerechnet das etwas 'viel' Gewinn macht, was aber nicht stimmt.

Würde mich freuen wenn das jemand überprüfen könnte.

google:
Hi
I looked at the list of the most profitable items.
But think here is a mistake.
The prices of the items needed are all in agreement with the auction house, but I believe that the 15% AH fee will not be deducted from the selling prices.
What does it mean here that predicts something 'a lot' makes profit, but this is not true.

Would be glad if someone could check.

**Comment by queicherius** [comment]
Hey, der Profit der Items beinhaltet die AH Gebuehr.

**Comment by luckyheiko** [comment]
dann kann ich nicht rechnen. 
ich komme auf den 'gewinn' nur wenn ich den VK Preis 1zu1 Übernehme.
aber beim VK Preis müssen ja noch die Gebühren weg.

aber ok, ich lass das einfach mal so stehn

**Comment by queicherius** [comment]
Die genaue Rechnung intern ist 

```
Gewinn = 
  Verkaufspreis (basierend auf den Filtern die du gewaehlt hast) 
  * Wie viele Items im durchschnitt gecraftet werden
  - TP Gebuehren des gesamt Verkaufspreises
  - Crafting Preis (basiderend auf den Filtern die du gewaehlt hast)
```
