### ISSUE TITLE
Gen2 Legendary Weapon Crafting Calculator Improvement

### ISSUE THREAD

**Issue by wjwolf79** [gw2efficiency/issues#1243]
When crafting the tiers of Gen 2 Legendaries, it will list previous tiers as not being completed when they have been, causing the needed material calculations to be much higher than what's actually needed. I would suggest an option on the crafting calculators to remove a step from the calculations.

Example: I have Visiospei crafted already and working on Exitare. It is listing Visiospei as not crafted and counting my shards and other mats towards making it, causing the actual cost of Exitare at this stage in crafting to be much higher than it should. Being able to mark that Visiospei is completed and removing that from the calculation as suggested above would resolve this issue.

**Comment by queicherius** [comment]
It should already take it into account. Do you still have the required
item? If yes, where is it (Bank, Inventory, Equipment)?

**Comment by wjwolf79** [comment]
it was equipped on a character. I have seen it also when I was crafting Ars Goeta, and keeping the true name in my inventory.  I've finished Exitare now, so next Gen 2 legendary I'll keep more tabs on it and and if it works properly.

**Comment by queicherius** [comment]
If it is not equipped in the current build template, then the API will not show that you have the item. It's very likely that that is what is the case here.

**Comment by wjwolf79** [comment]
I understand that.  Still in that situation though, and any others that might occur where it's not recognizing that I have an item, it would be nice to have an option to exclude something from the crafting recipe.

**Comment by queicherius** [comment]
The custom exclusion feature is tracked here: #58
