### ISSUE TITLE
Add PoF Hero's Choice Chests to the leaderboard

### ISSUE THREAD

**Issue by Stonos** [gw2efficiency/issues#1244]
Specifically the following items:

- [Crystal Oasis: Hero's Choice Chest](https://wiki.guildwars2.com/wiki/Crystal_Oasis:_Hero%27s_Choice_Chest)
- [Elon Riverlands: Hero's Choice Chest](https://wiki.guildwars2.com/wiki/Elon_Riverlands:_Hero%27s_Choice_Chest)
- [The Desolation: Hero's Choice Chest](https://wiki.guildwars2.com/wiki/The_Desolation:_Hero%27s_Choice_Chest)
- [Domain of Vabbi: Hero's Choice Chest](https://wiki.guildwars2.com/wiki/Domain_of_Vabbi:_Hero%27s_Choice_Chest)

**Comment by queicherius** [comment]
Now live.
