### ISSUE TITLE
Craft: Tlehco

### ISSUE THREAD

**Issue by MaitrE-ToXiK** [gw2efficiency/issues#1245]
There is a problem on the Tlehco craft.
I see the Anima precursor is needed, but on the wiki you do not need it.
and it's not possible to put five items on the Mystic forge

**Comment by queicherius** [comment]
You need to craft the precursor first, in order to unlock the recipe, as part of the legendary journey. If you already crafted Anima / have the precursor unlocked, you can just craft Tlehco and it will reflect accordingly in the calculator.
