### ISSUE TITLE
Black Lion Contracts not registering

### ISSUE THREAD

**Issue by Versionite** [gw2efficiency/issues#1246]
Maybe it's just on my account, but the Black Lion Expedition Season 3, Season 4, and Hunter's contracts that I have don't show up on my efficiency page.   I don't see a spot for Season 4 so maybe it hasn't hit the API yet.
![image](https://user-images.githubusercontent.com/59490832/71755359-3df9c400-2e58-11ea-886c-bcdc2093d31d.png)
![image](https://user-images.githubusercontent.com/59490832/71755382-58cc3880-2e58-11ea-9bb8-c3f8cb01c651.png)

**Comment by queicherius** [comment]
See https://github.com/arenanet/api-cdi/issues/567#issuecomment-497884872
