### ISSUE TITLE
Account search does not display items equipped in character's inactive equipment build template.

### ISSUE THREAD

**Issue by robinanthony** [gw2efficiency/issues#1249]
It looks like Anet add the build template access in the API in december 2019.
Is it possible to add this new data now ?

Source :
https://en-forum.guildwars2.com/discussion/94395/api-updates-december-18-2019

**Comment by queicherius** [comment]
Yes, this is planned. I have been taking a break from development over Christmas, but I am hoping to find the time to start again soon.

**Comment by queicherius** [comment]
This has been online since Mid-January :)
