### ISSUE TITLE
Add "Primeval" Raptor to Account/Mounts

### ISSUE THREAD

**Issue by bgechachi** [gw2efficiency/issues#1251]
Currently the Primeval Raptor mount appears to be missing from the mount list.  Filtered to Raptors and did not see it.  Did not see it when scrolling through entire mount list.

**Comment by queicherius** [comment]
The raptor is not in the API, so we can not show it. It will automatically show up once it is in there :)

**Comment by bgechachi** [comment]
Figured that stuff was API pulled, which confused me since the mount isn't that new.  Then I thought, "Are they actually building out each peiece?!? I need his connections on info!" 👍 

Thanks for the response.

**Comment by queicherius** [comment]
We appreciate the report :)
It could have been us, we have to manually attach the "unlock item" to the mount, and if that is not done it does not show up. But in this case, it's just the API sadly.
