### ISSUE TITLE
Request - Material Storage Share

### ISSUE THREAD

**Issue by Maliha-Abrek** [gw2efficiency/issues#1259]
I would love to see the ability to share material storage much like how we can share builds etc. Being able to share read-only views of the material storage can help advise new players about economy etc a lot.

**Comment by queicherius** [comment]
This is not currently something I want to pursue:

> This is unlikely to ever happen. The reason for this is that

> - It's a massive amount of work
> - The impact of this change is *very* small, because people just share their API keys (which were MADE for this kind of purpose)

> _Originally posted by @queicherius in https://github.com/gw2efficiency/issues/issues/105#issuecomment-460066709_
