### ISSUE TITLE
Add a blacklist for skins

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1270]
- Backpack Straps (0 people have it)
- Mistward Armor (the one with 5 people having it)
- The legendaries with exotic quality

**Comment by MaxG46** [comment]
There is also the legendary Axe "The Bifrost" as a skin which should be blacklisted.

**Comment by queicherius** [comment]
This is now live.

**Comment by queicherius** [comment]
Seems like Axe-Bifrost is still sticking around 🤔

**Comment by queicherius** [comment]
It's back again...

**Comment by queicherius** [comment]
Fixed in the next release, found the issue
