### ISSUE TITLE
Filter mastery points that can not be achieved anymore

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1271]
https://www.reddit.com/r/gw2efficiency/comments/f6scmw/displaying_hero_points_that_cannot_actually_be/

**Comment by queicherius** [comment]
Closing because I don't want to maintain the static data for which achievements are earnable or not.

**Comment by queicherius** [comment]
https://www.reddit.com/r/gw2efficiency/comments/n0dz72/account_achivements_central_tyria_mastery/

**Comment by queicherius** [comment]
Reopening because it might be worthwhile for the base-story ones.

**Comment by Ecmelt** [comment]
Added a check for personal story parts 1, 2, 3 and 4.
