### ISSUE TITLE
Update WvW Legendary armor precursor component cost

### ISSUE THREAD

**Issue by joaosb** [gw2efficiency/issues#1274]
Hi, can you please extend crafting calculator of GW2efficiency  when you are crafting a WVW armor. 
Include the tickets required, and money to spend on the precussor armor.

thks

**Comment by queicherius** [comment]
I can show the tickets at the ingredient, but not at the top (see https://github.com/gw2efficiency/issues/issues/64).

**Comment by queicherius** [comment]
Multiple currencies are not supported right now, but I added them with their skirmish ticket costs.
