### ISSUE TITLE
Move SAB progress link to nav menu, instead of header on character screen

### ISSUE THREAD

**Issue by penguid** [gw2efficiency/issues#1276]
SAB progress currently gets a prominent header-level link on the Account > Characters page. I wonder if it would be better suited in the nav menu somewhere. It seems to have disproportionate importance and screen real-estate in its current location, for a niche and time-limited feature.

**Comment by queicherius** [comment]
I would be up for that, if I can find the space in the submenu.

**Comment by queicherius** [comment]
This is now live.
