### ISSUE TITLE
Add Equipped Gathering Glyphs

### ISSUE THREAD

**Issue by tawniey** [gw2efficiency/issues#1279]
Currently, gathering glyphs equipped into tools do not show up on the account search, and are not visible when hovering over the tool itself. It'd be great to be able to see what glyphs are where, if possible! Thanks!

**Comment by queicherius** [comment]
Sadly those are not in the API (see the request for them here: https://github.com/arenanet/api-cdi/issues/616), so this is not something we can do :(
