### ISSUE TITLE
Raid Leggy Armor Costs 

### ISSUE THREAD

**Issue by RPostWVU** [gw2efficiency/issues#1283]
I can't tell where one might make a request, but I was wondering if it would be possible to add the map currencies needed (250 each of HoT) for [Gift of the Pact] when shown in crafting. As well as the [50 Provisioner tokens] needed for [Gift of Craftsmanship]

**Comment by queicherius** [comment]
I can add them in the crafting tree, yes

**Comment by queicherius** [comment]
Actually, this is currently not possible (but I am slowly working towards that it will be in the future, in which case items like these will be automatic):

- We can not show multiple currencies attached to one item
- Provisioner tokens are not in the list of supported currencies atm.
