### ISSUE TITLE
Crafting Calculator with Mystic forge

### ISSUE THREAD

**Issue by vipero07** [gw2efficiency/issues#1285]
The current crafting calculator doesn't account for mystic forge use. For example a person can upgrade a Large Scale to an Armored Scale in the forge using 50 Large Scales, 1 Armored Scale, 5 Piles of Crystalline Dust, and 5 Philosopher's Stones. The biggest barrier to entry here to my knowledge is the conversion of .1 spirit shard for 1 philosopher stone. I also guess it could be an issue with the random number of Armored Scales generated.

**Comment by queicherius** [comment]
Yes, that was an intended change for now, until we maybe add a toggle for spirit shard recipes. The reason was that people did not realize that spirit shards may have better conversion rates than what they were crafting. For now, to see those head over to the spirit shard page
