### ISSUE TITLE
New "collectible" statistics

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#1288]
With the Emblems used for legendary trinket crafting in WvW and PvP being repeatable it would be cool to see them having leaderboards on GW2E.

The items are:

- Emblem of the Avenger
- Emblem of the Conqueror
- Emblem of Tournament Victory
- Emblem of Victory

**Comment by queicherius** [comment]
I will add this, but in a later release because 3/4 of these statistics already exist in some other form (wvw kills, wvw objectives, pvp ranked wins)

**Comment by queicherius** [comment]
This is now live.
