### ISSUE TITLE
Fix kaiser snake ascended weapons not having any value

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#129]
"Kaiser Snake" weapons don't have any value either. These should either get the same treatment that ascended items from raids (#5) or get the value of their skins. Need to check where they actually come from to decide.

**Comment by Scath-Enfys** [comment]
They come from super-rare trib mode boss drops OR from trib mode collection achievements. The bauble infusion should also receive a manual value setting, as some may move it to a different weapon.

**Comment by queicherius** [comment]
This is going to be in the next release. Both kinds of ascended weapons and the account bound skins got the value of the non-bound skins now. The infusions didn't get a value, because as soon as you have the skin unlocked it will count (even if you throw the weapon away).
