### ISSUE TITLE
[feature request] export\import settings.

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1293]
because site doesn't store this info in DB, would be great to see some kind of export.

gathering - hidden routes.
daily board - hidden blocks.

**Comment by queicherius** [comment]
If you are having a need of this right now, you can achieve it by exporting the entire `localStorage` and then reimporting it on another browser/computer.

I do want to make saving settings better tho, both with an export function & saving it in the actual DB.

**Comment by queicherius** [comment]
In the next release
