### ISSUE TITLE
Incorrect Prices for a few cooking ingredients

### ISSUE THREAD

**Issue by Cyprex** [gw2efficiency/issues#1296]
Item | GW2Efficiency Price | Actual Price
--------------- | ---------- | ----------
[Pile of Compost Starter](https://wiki.guildwars2.com/wiki/Pile_of_Compost_Starter) | None | 14  96 per 10
[Pile of Powdered Gelatin Mix](https://wiki.guildwars2.com/wiki/Pile_of_Powdered_Gelatin_Mix) | 20c | 2s

**Comment by queicherius** [comment]
Thanks for the report! We add this data manually, so I'll do this when I next go through all of the data.

**Comment by holoxx** [comment]
The 'Pile of Compost Starter' had already been added and probably just didn't show up because of the wrong published modules lately.
The value of 'Pile of Powdered Gelatin Mix' was fixed by gw2efficiency/recipe-calculation@b6b5366.

**Comment by queicherius** [comment]
👍 This will be automatically included in the next release then
