### ISSUE TITLE
Missing cost for sheets of Aurilium in Crafting Calculator

### ISSUE THREAD

**Issue by rockafellah1** [gw2efficiency/issues#1297]
The item needed in the crafting process of Astralaria - Sheet of Aurilium - is missing it's price in the crafting calculator. It costs 5 Lumps of Aurilium and 21s12c per sheet.

**Comment by queicherius** [comment]
Thanks for the report! We add this data manually, so I'll do this when I next go through all of the data.

**Comment by queicherius** [comment]
Will be in the next release.
