### ISSUE TITLE
Missing TP history for several Black Lions skins

### ISSUE THREAD

**Issue by Darkever00** [gw2efficiency/issues#1299]
The price for several Black Lion skins seems to be missing, for example searching "Seven Reapers", "Endless Ocean", "Bioluminescent", and many more. Other BL skins work properly, such as "Orchestral".

It looks like a back-end issue, because the call to "https://www.gw2spidy.com/api/v0.9/json/listings/92124/buy/0?callback=angular.callbacks._17" returns empty results: []

**Comment by queicherius** [comment]
Right now we get our item history from gw2spidy, so nothing we can really do there. We want to move it into our own hands at some point (#117) but it's not a priority.
