### ISSUE TITLE
binding of equipped inventory bags not detected

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#1300]
when searching my account for non-bound inventory bags by changing the "binding" field to "none", and changing the "type" field to "inventory bags", the search shows all bags that are equipped even though many of them are account bound.

Hovering over the item in the list does show it's account bound status, though it is possible this is inferred due to an item which can only ever be account bound (such as a pillager's pack or a 32-slot bag).

It appears that all equipped inventory bags are treated as having no binding. Attached are two screenshots of searching to help explain what I am seeing:

![search-binding-none](https://user-images.githubusercontent.com/874719/80286463-6e53bf80-86e0-11ea-8f85-b97e189e05ab.png)
![search-binding-any](https://user-images.githubusercontent.com/874719/80286467-6eec5600-86e0-11ea-8b30-c8fc12e3392b.png)

**Comment by queicherius** [comment]
Added a ticket here: https://github.com/arenanet/api-cdi/issues/668

**Comment by queicherius** [comment]
Going to close this here since I will be notified once the other ticket is closed. :)
