### ISSUE TITLE
[Feature request] split the tradingpost value stat in half

### ISSUE THREAD

**Issue by torsina** [gw2efficiency/issues#1301]
Hi, would it be possible to make the buy orders and items stuck on tp diferent stats (the current global stat can stay aswell). 
It would be really nice to track over time how much gold get stuck in my sell orders without seeing the jumps with me cancelling/moving my buy orders.

thanks <3

**Comment by torsina** [comment]
Yes! but for the sell orders just the items currently in sell order, the delivery box is kinda irrelevant

**Comment by queicherius** [comment]
This is now live. Also added a `Tradingpost (Delivery Box)` for good measure.
