### ISSUE TITLE
Unstable statictics

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#1302]
Hey. For several days I have been observing instability of statistics. It's look like when new account data is scraped old data is removed and not used for statistics. For me it's like everyday statistic are not available for 2 or more  hours but last day it become even worse (24 h or even more). Maybe it's good idea to always use last successful value for statistics.

**Comment by queicherius** [comment]
In the last 24 hours we have had some server issues, which might be causing this.

But since you said several days, I'll have another look once this is resolved. 👍

**Comment by queicherius** [comment]
Does this still look like its an issue for you?

**Comment by malagus** [comment]
Today this  bug repeat again. Stats for my account where unavailable until new snapshot appear  in time machine tab.

**Comment by queicherius** [comment]
I have a potential fix for this in the pipeline for the next release, I think I found the issue.

**Comment by malagus** [comment]
It's getting even worse now. Before last update number of account vary form 200k to 230k but now I observe 140k to 260k. Most statistic looks like this for all day
![obraz](https://user-images.githubusercontent.com/12558492/82494154-6de4f380-9ae9-11ea-9ef4-418f88de5fff.png)

Also Time Machine stop  working for me.
![obraz](https://user-images.githubusercontent.com/12558492/82494523-04191980-9aea-11ea-8781-54debae1a2fc.png)

**Comment by queicherius** [comment]
I was actively monitoring the situation here, and the system needed to catch up a little. According to my logs, it looks like it was stable for ~3 days now, but I am keeping this open since I want to optimize some more things.

The stats themselves vary a bit (e.g. 250k on account value vs 272k on playtime) since the API keys do not all have full permissions to generate all statistics.

**Comment by queicherius** [comment]
After even more additional logging & optimization, we are now fully stable

![](https://i.imgur.com/NCi9KJ6.png)
