### ISSUE TITLE
Do not show negative y-axis for graphs of absolute values.

### ISSUE THREAD

**Issue by TheMrMilchmann** [gw2efficiency/issues#1311]
Currently, there are situations in which the first negative "step" of the y-axis is shown for graphs displaying absolute values. This is slightly confusing, as the values will always be >= 0 and it would be neat if this could be fixed.

If further information is required to track down why this is happening, please let me know.

![grafik](https://user-images.githubusercontent.com/4029915/82756350-088b4e00-9dda-11ea-992b-a28140c37d07.png)

(I'm aware that this is purely cosmetical, but since it might be straightforward to fix depending on what is used to render the graphs, I figured I'd ask anyway. 🙂)

**Comment by queicherius** [comment]
Thanks for the report, this should be pretty easy. I'll have a look when I
can squeeze it in :)

**Comment by queicherius** [comment]
Fixed now
