### ISSUE TITLE
Primordus talon price shows 0 because it can't see the options to craft the skins for the collection.

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1312]
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-79364

Those skins are all crafted and on sale, just attached to the 9 variants of the weapons. the calculator should pick the cheapest option of those 18 options for each weapon, is it just not hooked up correctly or overloading on the options?

**Comment by queicherius** [comment]
The recipe for this is not handled, since it's referring to the skins and not the actual items. We can setup a recipe for this that handles the different cases.

**Comment by queicherius** [comment]
This is now live.
