### ISSUE TITLE
Improvement for varietal crops/asc food in Crafting calculator

### ISSUE THREAD

**Issue by Arakeem** [gw2efficiency/issues#1313]
Couldn't see that this has been brought up here before but apologies if it's been previously considered. 

Currently all of the cultivated varietal crops incorrectly appear as relatively profitable to make v buying the cultivated plant as they only include the cost of the base seed. They don't include the cost of the 5x Piles of Compost Starter at 7s48c and the Exquisite Extract of Nourishment (and everything that goes into that) shows up as a freebie. Consequently things like the Peppercorn-Crusted Sous-Vide Steak thinks that it only costs 27s30c to make each time, whereas the actual cost is about 44s66c when you make the seeds yourself and the seeds would actually be about 5-6s cheaper at the buy price on the TP. 

I'm presuming the Nourishment is a bit more difficult to deal with as it depends on a varying list of what's cheapest to buy/craft to salvage at the time (certainly something like the calculator at https://food.werdes.net/ doesn't seem like it would be straightforward) and the number of recipes involved doesn't make manual changes enticing but it seems like if any improvement on how it's all calculated at the moment is possible that would be helpful.

**Comment by queicherius** [comment]
> They don't include the cost of the 5x Piles of Compost Starter at 7s48c

This has been fixed some time ago, cant remember when.

> and the Exquisite Extract of Nourishment (and everything that goes into that) shows up as a freebie. 

I think this should be possible by adding the possible components

Implementation notes: Add recipes like `{"name":"Fine Extract of Nourishment", "output_item_id":91838, "output_item_count":1, "ingredients":[{"count":1,"item_id":12210}],"disciplines":["Salvaging"]},` (then the subrecipes & choosing the cheapest option should work by itself)

**Comment by queicherius** [comment]
This is now live.
