### ISSUE TITLE
Small crafting bag value is way off

### ISSUE THREAD

**Issue by samulisoderlund** [gw2efficiency/issues#1314]
https://gw2efficiency.com/currencies/laurels
Small crafting bag value is reported to be (at the time of writing) ~49 silver

https://wiki.guildwars2.com/wiki/Small_Crafting_Bag
According to the wiki the real value is ~24 silver

**Comment by queicherius** [comment]
Fix is already in https://github.com/gw2efficiency/static-data/pull/4 by @Arckange007 :)
