### ISSUE TITLE
Cost of legendary WvW and PvP armor in crafting/calculator

### ISSUE THREAD

**Issue by adrienfallot** [gw2efficiency/issues#1316]
# For WvW armor
## Cost of ascended version
Each piece of armors (mistforged or not) used the ascended version of the piece in recipe. It's well added in calculator, but its indicated as "not sold or crafted", which is wrong. It's sold by "Skirmish Supervisor". 
- For [not mistforged ](https://wiki.guildwars2.com/wiki/Triumphant_Hero%27s_armor) it cost: Gold ; Grandmaster Mark ; WvW Skirmish Claim Ticket ; Memory of Battle (values depend for each pieces).
- For [mistforged](https://wiki.guildwars2.com/wiki/Mistforged_Triumphant_Hero%27s_armor) it cost: Gold ; WvW Skirmish Claim Ticket ; Memory of Battle (values depend for each pieces).

# For PvP armor
## Cost of ascended version
Each piece of armors (mistforged or not) used the ascended version of the piece in recipe. It's well added in calculator, but its indicated as "not sold or crafted", which is wrong. It's sold by "Ascended Armor League Vendor".
- For [not mistforged](https://wiki.guildwars2.com/wiki/Ardent_Glorious_armor) it cost: gold, Grandmaster Mark, Ascended Shard of Glory and Shard of Glory (values depend for each pieces). 
- For [mistforged](https://wiki.guildwars2.com/wiki/Mistforged_Glorious_Hero%27s_armor) it cost: Glob of Ectoplasm, Grandmaster Mark, Ascended Shard of Glory and Shard of Glory (values depend for each pieces). 

## Cost of "Gift of Competitive Prowess"
Each piece need a "Gift of Competitive Prowess" which need a "Record of League Victories". It's well added in calculator, but its indicated as "not sold or crafted", which is wrong. It's sold by "Ascended Armor League Vendor" for 30 PvP League Ticket.

## Cost of "Gift of Competitive Dedication"
Each piece need a "Gift of Competitive Dedication" which need : "Record of League Victories", "Star of Glory" , "Jar of Distilled Glory". It's well added in calculator, but all of them are indicated as "not sold or crafted", which is wrong. They are sold by "Ascended Armor League Vendor" for respectively 20 PvP League Ticket, 400 Ascended Shard of Glory and 1,000 Shard of Glory.

**Comment by queicherius** [comment]
This was released in june
