### ISSUE TITLE
Legendary Trinket statistic is missing an item

### ISSUE THREAD

**Issue by Jong1** [gw2efficiency/issues#1318]
Not sure which one is missing. My guess is Conflux or Slumbering Conflux (probably Slumbering?).

I have Vision, Aurora, Conflux and Slumbering Conflux yet only have a count of 3 in Account Statistics

**Comment by queicherius** [comment]
> Also, I saw item #1318 on the issues page - and I can confirm it must be Slumbering Conflux that isn't included as a legendary trinket because when I had just Conflux it was counted correctly.
> I'm guessing maybe Slumbering Transcendence might also not be counted correctly although I can't confirm.

**Comment by queicherius** [comment]
This is now live.
