### ISSUE TITLE
Rechtschreibfehler in der Tabelle "Statistiken nach Spielzeit"

### ISSUE THREAD

**Issue by elbrodark** [gw2efficiency/issues#1319]
Dort steht "Maxmium" , es sollte "Maximum" heißen.

In German there is a spelling mistake in the table "Statistics by season", there is "Maxmium" instead of "Maximum"

![image](https://user-images.githubusercontent.com/9810157/84703826-2c652e00-af59-11ea-804d-79552098a0b4.png)

**Comment by queicherius** [comment]
Fixed
