### ISSUE TITLE
Show which downscaled resolution the points on the chart are rendered at

### ISSUE THREAD

**Issue by holoxx** [gw2efficiency/issues#1320]
On initial loading, the Delta option of a chart uses a time frame of 6 hours. When you zoom in or out, this time frame changes to e.g. 1 day or 1 week.
That can be quite confusing while comparing absolute delta values, as they scale up and down as well.

So it could be useful to add information about the current time frame which updates after zooming.
Or probably even provide an option to preserve a default timeframe (e.g. 1 day) upon zooming, making the chart look a bit more cluttered but helps keeping it comparable. Or to adjust the time frame just as normal but normalize the delta value to a fixed time frame.

**Comment by queicherius** [comment]
I'll have to see how possible this is, because I am pretty sure the data grouping is provided by the library I use, and I am not sure I can get that information out.

**Comment by queicherius** [comment]
This is now live.
