### ISSUE TITLE
Achievement Nimble Onslaught shouldn't be shown under earnable

### ISSUE THREAD

**Issue by Stiwi** [gw2efficiency/issues#1322]
The achievement 
"Nimble Onslaught" Defeat Drakkar without being hit more than 8 times by its abilities.
was removed and is no longer earnable so it shouldn't be shown if you select "show earnable"

> The Nimble Onslaught achievement is no longer attainable, and it will be hidden if your progress was incomplete.
Source: https://en-forum.guildwars2.com/discussion/97452/game-update-notes-february-11-2020

**Comment by queicherius** [comment]
Similar to https://github.com/gw2efficiency/issues/issues/1271 - right now we just show what the API gives us.

**Comment by queicherius** [comment]
Implementation notes: Add a blacklist similar to #1270 and just filter it out on the backend

**Comment by queicherius** [comment]
Closing because I don't want to maintain the static data for which achievements are earnable or not.
