### ISSUE TITLE
Breadth first/even stacks in shopping list

### ISSUE THREAD

**Issue by gustaphe** [gw2efficiency/issues#1325]
This is a pretty minor thing, but could save a bit of hassle when using the crafting calculator.

Instead of saying "951 (3 stacks and 201)" in the shopping list, it could say "951 (4*238 - 1)". That way, I only have to set the purchase amount once (especially if I don't care about accidentally buying single digits too many, when talking about several stacks). This is pretty easy to implement:

```
N_stacks = ceil( x / 250 )
stack_height = ceil( x / N_stacks )
overshoot = N_stacks*stack_height - x
```

**Comment by queicherius** [comment]
To be honest, I think a feature like this would very likely cause more confusion than not.
Since I am trying to get my support requests down, I'll not implement this one, sorry
