### ISSUE TITLE
Allow 'Agony Resistance' as an "order by" option on character screen

### ISSUE THREAD

**Issue by ShiningMassXAcc** [gw2efficiency/issues#1326]
https://gw2efficiency.com/account/characters?filter.order=agony_resistance

I don't recall who all I've currently moved my AR around onto.  Would be nice to see which of my 4 characters I've kitted with 150 AR at the moment.

Not sure if folks would find being able to sort by other attributes (who are my power / condi / tank / healer chars) - but could consider those while you are there.  Those attributes just signal differently than AR does.

**Comment by queicherius** [comment]
Now live :)
