### ISSUE TITLE
Player Statistic Suggestion: game mode participation and depth/difficulty within that game mode

### ISSUE THREAD

**Issue by ShiningMassXAcc** [gw2efficiency/issues#1336]
It would be interesting to take the individual statistics (many of which are presented in the Account and Unlock statistics, and come up with an aggregate view of various game modes and their perceived participation/difficulty.  You could do this by picking a collection of the account/unlock statistics for a given area - and present them in a similar graphical format that you do for the Player statistics (in particular, the "account type" graphic with % of accounts).  This would show the difficulty/participation dropoff as the content progresses from 'beginning' content to 'end' content.  For each summary, this would be a single achievement/unlock or a combination of achievements/unlocks that would be the simplified measure to communicate this.  For me, I was mainly interested in the split at Story completion and Raid completion, but included others for completeness.  We do see gw2 sub posts pulling summaries like these on occasion - this would help automate that collection / view.

Here's my imagined breakdown for some such categories:

Story Completion:
![image](https://user-images.githubusercontent.com/43765765/88132452-5df29a00-cb94-11ea-9685-efd5061f3d78.png)
Completing the meta cheevo for each map in an arc.

Fractals:
Could do fractal expert/adept/etc for 4 categories, and then a CM completion for a 5th category
Could throw in the mist attunement cheevos, for tier 1-4
Could throw in even a lower bar than expert/adept cheevos - maybe have they even completed a fractal, or have AR on characters

Raids:
Few options here, I almost like simple completion on a per raid basis.  This would give folks a view of what raids are most difficult.
In terms of player overall progression less focused on individual raids, could do something like 'has completed a single raid', 'has completed all raids', 'has completed all CM raids', 'has completed all raid cheevos', something like that
Both the above views could be interesting, the difficulty rating might be interesting for strike missions as well - although that will have a heavy introduction date bias

PVP:
Pvp rank or the per-class cheevos could work, but is subject to farmers
There are various PVP season achievements, could go by high placement or consistent placement and put into buckets.  I'm less familiar here.

WVW:
I feel this is actually a bit more about 'farming' as opposed to PVP.  There isn't much that directly translates to skill at least directly I feel here.
Perhaps bucketing folks at ranklevels - for example % of population with bronze rank or better, silver rank or better, etc

Fashion Wars:
Lots of options here - you already have a whole unlock section, but again, figuring out how to summarize it classify how the population participates.
Could do % of all skins, but I don't think folks focus on that
Legendary skins could work, could do some of the uber rare tier of drop skins or black lion skins
Could be interesting to pull in highly sought out account bound skins that have some measure of skill/time, versus gem buying gold farming ability - not sure if anything comes to mind here.

**Comment by queicherius** [comment]
I am going to close this one.

- It's pretty hard to implement, and something that requires data (e.g. which skins) that we either have to generate or maintain ourselves.
- Different folks will see different things as important, and I don't want do deal with arguments over it (I have seen the arguments in the reddit threads).
