### ISSUE TITLE
Using unlock statistics and sorting the home instance gathering nodes duplicates the "Black Lion Garden Plot Deed"

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1338]
![image](https://user-images.githubusercontent.com/8763688/88642165-ced00f80-d0c8-11ea-96dc-9ea35194a1c6.png)

When sorting by value repeatedly it duplicates the Black Lion Garden Plot Deed.

**Comment by queicherius** [comment]
This is now live.
