### ISSUE TITLE
Time cost for crafting

### ISSUE THREAD

**Issue by blackhawk0258** [gw2efficiency/issues#1339]
Sorry if this has already been brought up, but is it possible to add a time cost for crafting due to ingredients with time gates

**Comment by queicherius** [comment]
When you select "craft" for daily cooldowns (default) it shows the time gated components above the crafting steps: 

![](https://i.imgur.com/Q719ukG.png)

Is that what you wanted?

**Comment by queicherius** [comment]
Assuming solved
