### ISSUE TITLE
Add filter "mastery points" to achievements unlock statistics

### ISSUE THREAD

**Issue by ddcarvalho** [gw2efficiency/issues#1343]
Mastery points are a type of achievement that people who need points to unlock masteries might wanna sort by unlock percentage to choose the easiest/fastest ones to do. There's also the option to include that as a filter on the Unlock Stats "Achievements" section, but it would be suboptimal since some mastery points are given by sub-tiers of an achievement (example: 2 points on Morale Breaker, 1 point on Tengu Weapons).

**Comment by queicherius** [comment]
This is now live.
