### ISSUE TITLE
Royal Flame Weapon collection

### ISSUE THREAD

**Issue by Toluk** [gw2efficiency/issues#1347]
in the Festival collections' page:
https://wiki.guildwars2.com/wiki/Festival_Collections#achievement5004
there is a halloween collection for flame weapons:
https://wiki.guildwars2.com/wiki/Royal_Flame_Weapons
which is absent on Achievements->Collections->Festival Collections
which is a bug i think

**Comment by queicherius** [comment]
This section of the page is populated directly by data from the official API. If you'd like to report it to them, here's the respective repository: https://github.com/arenanet/api-cdi
