### ISSUE TITLE
Add Drakkar worldboss to dailies and timers

### ISSUE THREAD

**Issue by KingRider** [gw2efficiency/issues#1350]
Why dont show Drakkar? api is available

![image](https://user-images.githubusercontent.com/4491180/90913416-a202d580-e3b2-11ea-861e-639a84f1e974.png)

Please add boss Drakkar is each 2 hours

`{id:"drakkar",name:"Drakkar and Spirits of the Wild",icon:"",reward_dragonite:"?",position:"Bjora Marches",times:["22:05","00:05","02:05","04:05","06:05","08:05","10:05","12:05","14:05","16:05","18:05","20:05"],waypoint:"[&BDkMAAA=]",type:"worldboss"}`

How to make add boss? i need other too LeyLine, ChakGerent and Octovine.

Thanks!

**Comment by queicherius** [comment]
I added this for the next release, thanks for including the code already :)

If you'd like to add some more bosses (even if they are not in the API completion), you can add them in this repository https://github.com/gw2efficiency/static-data, here's a sample commit of how to: https://github.com/gw2efficiency/static-data/commit/d61c5b4f5db07a1349c2806a70f42fa5c6a0dffc

**Comment by KingRider** [comment]
Oh!! i see.. thanks bud.

**Comment by queicherius** [comment]
This is now live.
