### ISSUE TITLE
Add Option to Filter Recipes by No Discipline

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1355]
Recipe searches require that a discipline be selected.  I wanted to search for the Stormcaller and Charged Stormcaller Weapon recipes that I did not have and I would like to be able to get results in a single search rather than three.  Request that 'Any' be added as an option in the Discipline drop down box.

**Comment by queicherius** [comment]
The reason for excluding this feature right now is that rendering all recipes at once is actually quite laggy. I was experimenting with a way that would improve rendering performance, but did not get to a reasonable level.

I guess I could add it with the caveat that it would take a second or two to render.

**Comment by queicherius** [comment]
This is now live.
