### ISSUE TITLE
Permanent Gathering Nodes - Add additional filters

### ISSUE THREAD

**Issue by LukeDouglas2** [gw2efficiency/issues#1358]
You have a very useful Permanent Gathering Nodes.  However, it would be great to add a couple filter ranges for Dailies!

A Type filter:

- Ore / Mines
- Forage / Plants
- Lumber / Trees

A Region filter:

- Ascalon
- Crystal Desert
- Heart of Maguuma
- Kryta
- Maguuma Jungle
- Maguuma Wastes
- Ring of Fire
- Ruins of Orr
- Shiverpeak Mountains
- The Mists

With these two, you could easily click on which two you need to get a daily. 

Example: Daily Shiverpeaks Forager nodes could be displayed by clicking 'Forage / Plants' and 'Shiverpeak Mountains'.

Just a thought!

Keep up the great work! :)

Scatmanicus.4582 - Main toon: Lily Le Bama

**Comment by queicherius** [comment]
This is now live.
