### ISSUE TITLE
Value high tier infusions at the value of their "Power" stat version

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1359]
Power -> All other stats

- Crystal Infusion
- Frost Legion Infusion
- Confetti Infusion
- ... etc, all infusions that have a conversion recipe

This fixes the account value (based on most common stat) since some of the lass common stats dont have TP orders.

---

Also make sure all infusion recipes output the Power version (e.g. Frost Legion)

**Comment by holoxx** [comment]
gw2efficiency/custom-recipes#14 should at least fix the the 'Frost Legion Infusion' recipe to output the power version

**Comment by queicherius** [comment]
@holoxx Thanks!

**Comment by queicherius** [comment]
This is now live.
