### ISSUE TITLE
Allow for stat graphs to be overlayed

### ISSUE THREAD

**Issue by qtto** [gw2efficiency/issues#1362]
It would be really useful to be able to overlay graphs for different account statistics! For example, unstable essences and liquid gold or legendary items and character value. It would be a nice way to relate different statistics to eachother or see why something changed.

**Comment by queicherius** [comment]
That is an interesting idea. Would you always want to compare 2 things, or sometimes even more than 2?

**Comment by qtto** [comment]
Ah, sorry for the late response here! I think being able to overlay anything would be the nicest - so, multiple at once. However, 2 would be cool too, if that's much easier to implement.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
