### ISSUE TITLE
Missing Halloween unlocks

### ISSUE THREAD

**Issue by Ahrle** [gw2efficiency/issues#1363]
Account\Mounts\Warclaw - Sand Lion Warclaw Skin - cost: 1600 Gems. https://wiki.guildwars2.com/wiki/Sand_Lion_Warclaw_Skin
Account\Novelties\Chairs - Vermilion Throne - cost: no value (BLC drop). https://wiki.guildwars2.com/wiki/Vermilion_Throne

Thank you :)

**Comment by queicherius** [comment]
These are not in the API, so sadly we can not add them. We will once they get in :)
