### ISSUE TITLE
Add option to set nickname to current and newly added API Keys

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [gw2efficiency/issues#1369]
Basically a little text box area where you can type whatever you want into it while adding or editing an API key in /user/api-keys .. and it would appear next to the account name in parentheses.  Kinda like this example (these are not actual account names just edited for privacy).

![image](https://user-images.githubusercontent.com/24264268/98529654-7a9a0700-2243-11eb-9039-d8fcc2325d60.png)

**Comment by queicherius** [comment]
This is now live.
