### ISSUE TITLE
All in one inventory and bank

### ISSUE THREAD

**Issue by okubiak** [gw2efficiency/issues#137]
Hi !

It would be awesome to have a page with a complete look on all inventory pack from all characters and bank. Perfect for searching a specific item.
Maybe with a search box to make it more simpler or / and with sorting options like:
- By characters
- By items (all items stacked with a popup to indicated in which inventory we can found this item)

I'm pretty sure that there is lot of stuff to do with it :)

**Comment by queicherius** [comment]
Hey!

A page like this already exists, by pressing on *"Show all owned items"* (1) or searching in the search box (2) on the account overview.

![](http://i.imgur.com/5knzDHz.png)

The results look something like this:

![](http://i.imgur.com/xy9ATf5.png)

Is that what you want? :smile:

**Comment by okubiak** [comment]
Oups !! Yeah that's perfect. I never seen this button because I'm not really looking the account overview.
But yes that's what I was looking for. Thanks!!
