### ISSUE TITLE
Add support for Glyphs

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1372]
Glyphs inside a Gathering Tool are not shown when hovering over one. Would be nice to see them and being able to filter for them in the search.

Glyphs (in the inventory) do not have a tooltip, that describes what they do, only that you cann apply them to a tool.

The Accountbound Glyphs also dont have a value. I think they should have the value of the container, if it is not included in one of unlocked Gathering Tool skins/items.

**Comment by queicherius** [comment]
> Glyphs inside a Gathering Tool are not shown when hovering over one. Would be nice to see them and being able to filter for them in the search.

Sadly those are not in the API (see the request for them here: arenanet/api-cdi#616), so this is not something we can do :(

> Glyphs (in the inventory) do not have a tooltip, that describes what they do, only that you cann apply them to a tool.

Do you have an example of that? It should have a description from the API, but I don't have any glyphs so I can't check.

> The Accountbound Glyphs also dont have a value. I think they should have the value of the container, if it is not included in one of unlocked Gathering Tool skins/items.

Would add that once we have them in the API, else it's unfair to only value non-equipped glyphs.

**Comment by MaxG46** [comment]
I have one in here:
https://gw2efficiency.com/account/character/Battlemage%20Genesis/share?filter.navigation=inventory&filter.buildTab=2&filter.equipmentTab=1
![grafik](https://user-images.githubusercontent.com/30660005/100253212-1cf30380-2f41-11eb-96ae-7eddc7d74e91.png)

**Comment by queicherius** [comment]
Sadly still not in the API, so I'm going to close this until it is. For the tooltips it does show what they do for some of them, we just display what the API gives us there.
