### ISSUE TITLE
Add a market depth chart to the tradingpost page

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1373]
![](https://media.discordapp.net/attachments/272911773357572106/779840046181253140/snowflake_depth.png?width=823&height=598)

**Comment by StevenLiekens** [comment]
Hi,

I didn't mention this before, but it makes more sense to display this as a step chart (as opposed to a line chart that follows the shortest path between points).

![snowflake depth 2](https://user-images.githubusercontent.com/1583241/101296877-32600b80-3826-11eb-96b5-07f49450de92.png)
