### ISSUE TITLE
Unstable Time Machine Snapshots and Account Statistics

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#1375]
Hey. It's look like snapshots and account statistic become unable again.
Time Machine page show no snapshots to compare .
Number of accounts for the same statistic is also unstable . 
For example I observe number accounts for wardrobe value statistic in rage from  230k to 290k

**Comment by queicherius** [comment]
Hey, yup I am aware of the issue. I've been trying to resolve it for the past 10 days, and it was looking better till a few days ago when it spiked back up. I'm still working on it.
