### ISSUE TITLE
Include the money and items up for collection in the tradingpost

### ISSUE THREAD

**Issue by Mike-j-t** [gw2efficiency/issues#138]
I may be wrong, but Account doesn't appear to consider uncollected TP. 

e.g. I have something like 600g to be collected but TP shows 16g (sell orders). Amount isn't included in wallet (that matches amount shown in game) and I assume it's not in bank or materials as clicking on them doesn't show this.

I did run through the list of issues and I didn't see this as an issue.

Sorry if I'm wrong and have wasted your time. 

PS fantastic work you've done.

**Comment by queicherius** [comment]
Sadly the API doesn't provide that info yet, [I made an issue here](https://github.com/arenanet/api-cdi/issues/321). So waiting for that. 😃

**Comment by queicherius** [comment]
I forgot to close this, it is already online since a while now. 👍
