### ISSUE TITLE
PvP and WvW legendary armor skins are missing in the statistics

### ISSUE THREAD

**Issue by holoxx** [gw2efficiency/issues#1381]
The PvP and WvW legendary armor pieces share the same skin with their precursors (see e.g. https://api.guildwars2.com/v2/items?lang=en&ids=84508,81365). Currently the skin IDs for the legendary versions are set to 999999.

Therefore the "Legendary Skins (Armor)" statistic doesn't include them (https://gw2efficiency.com/account/statistics/statistics.legendarySkinsArmor lists a maximum of 18 unlocked skins, while theoretically it could be 90 (18 PvE + 2 * 2 * 3 * 6 for PvP and WvW, with each two different versions (Glorious vs. Ardent Glorious and Triumphant Hero's vs. Mistforged Triumphant Hero's) for the 3 weights and 6 slots)).

Since we can't use the skin itself (as it already unlocks upon buying the ascended precursor), one could search the account for each of those legendary items and then award the respective legendary skin to the account once. That is not a perfect solution (e.g. deleted legendary items), but probably the best thing we can get.

**Comment by queicherius** [comment]
Since you get the skin of the legendary version by unlocking the ascended version, it's by (at least my) definition, not a legendary skin (but a ascended one).

Instead, they should count for legendary items.

**Comment by holoxx** [comment]
Yeah, by definition it's not a legendary skin. But I would expect crafting a legendary item to unlock a legendary skin. As all legendary weapons do and especially the legendary PvE armor does. So it feels a bit awkward for the PvP and WvW armor versions to not do that.
Players with the PvE armor get it counted towards the armor and total skin statistic, but players with the other ones do not. It's just that inconsistency which bugs me a bit. :/

**Comment by queicherius** [comment]
That's an inconsistency in the game tho - the PvE armor does unlock a unique legendary skin, the others dont. I think that's weird too tbh, but nothing I can do there 😄
