### ISSUE TITLE
Crafting calculator: consider improving item search performance

### ISSUE THREAD

**Issue by bessgeor** [gw2efficiency/issues#1383]
Inputs in crafting calculator materials list send a request on each change.
This produces lags if typing is fast and typed text length exceeds the maximum number of simultaneous requests browser supports.

I propose two changes:
1) use debouncer between typing and request sending. I haven't read the sources, but idea in general is to use something like https://usehooks.com/useDebounce/
2) cancel previous request on sending the next one from a component instance (would also benefit scenarios when APIs are slow to respond)

**Comment by queicherius** [comment]
I am not sure which page you mean - both the calculator and the recipe search pages are debounced to 250ms

**Comment by queicherius** [comment]
Closing this since there was no response
