### ISSUE TITLE
Visual Bug: Timemachine hours go over 24 (such as 24:37)

### ISSUE THREAD

**Issue by eternalflamez** [gw2efficiency/issues#1384]
![image](https://user-images.githubusercontent.com/5766032/101367454-785cb400-38a6-11eb-86a8-38c75ec9d993.png)

This should be 00:37 instead!

**Comment by queicherius** [comment]
That's curious, could you send your API key to support@gw2efficiency.com, so I can take a look at the backend response?

**Comment by eternalflamez** [comment]
It looks like the response sends the data for GMT, then (I guess) converts it to GMT+1 by adding +1 literally.

Here's the api response.

[{"_id":"5fce1526b3ee28f519aa727f","creationDate":"2020-12-07T11:42:30.384Z"},{"_id":"5fcd6b3e1393e925e0673f24","creationDate":"2020-12-06T23:37:34.358Z"},{"_id":"5fccc106159e1e8047c02ab9","creationDate":"2020-12-06T11:31:18.747Z"},{"_id":"5fcc16afca25f62cd23013cb","creationDate":"2020-12-05T23:24:31.554Z"},{"_id":"5fcb6c6d2c3e1b093f0c432e","creationDate":"2020-12-05T11:18:05.433Z"},{"_id":"5fcac1e58cb1c466d08b69f3","creationDate":"2020-12-04T23:10:29.226Z"},{"_id":"5fca18422282cbf6b15019ba","creationDate":"2020-12-04T11:06:42.092Z"},{"_id":"5fc96e658619a67d20f85f92","creationDate":"2020-12-03T23:01:57.869Z"},{"_id":"5fc8c4aa77a9fcf39bd6e40f","creationDate":"2020-12-03T10:57:46.791Z"},{"_id":"5fc81a4497523c2d5e3176ac","creationDate":"2020-12-02T22:50:44.933Z"},{"_id":"5fc770391bf65f6774e00102","creationDate":"2020-12-02T10:45:13.462Z"},{"_id":"5fc6c6dad4e63b786916fb62","creationDate":"2020-12-01T22:42:34.786Z"},{"_id":"5fc61cdaf575f8daaa47e995","creationDate":"2020-12-01T10:37:14.603Z"},{"_id":"5fc57319dd7c06b832eaadf0","creationDate":"2020-11-30T22:32:57.511Z"},{"_id":"5fc4c8a2c14a614be6efb1f4","creationDate":"2020-11-30T10:25:38.487Z"},{"_id":"5fc41f289c03f3aa6451e754","creationDate":"2020-11-29T22:22:32.025Z"},{"_id":"5fc37574b5dc97dcf5b69032","creationDate":"2020-11-29T10:18:28.519Z"},{"_id":"5fc2caeaa5337790dbf8e85c","creationDate":"2020-11-28T22:10:50.717Z"},{"_id":"5fc220f4889d2539942111c9","creationDate":"2020-11-28T10:05:40.583Z"},{"_id":"5fc17790889d253af82009f6","creationDate":"2020-11-27T22:02:56.481Z"},{"_id":"5fc0cd078517f41f2a19ac32","creationDate":"2020-11-27T09:55:19.630Z"},{"_id":"5fc0233f25e7bcc21c334c34","creationDate":"2020-11-26T21:50:55.106Z"},{"_id":"5fbf79278cffd91f805b7c11","creationDate":"2020-11-26T09:45:11.896Z"},{"_id":"5fbecffa76136f7250722301","creationDate":"2020-11-25T21:43:22.472Z"},{"_id":"5fbe2616458eaccb8552458d","creationDate":"2020-11-25T09:38:30.442Z"}]

I'll send my api key to the support email in a minute!

**Comment by queicherius** [comment]
It feels weird to say, but I believe I can't fix this.

For whatever reason, this is what the browser internal time implementation just decides is correct...

```
const formatter = new Intl.DateTimeFormat('en', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
})

console.log(formatter.format(new Date('2020-12-06T23:37:34.358Z')))
-> 'December 7, 2020, 24:37'
```

Congrats on finding a new hour in the day?
