### ISSUE TITLE
New home instance node: Prismaticite

### ISSUE THREAD

**Issue by scy** [gw2efficiency/issues#1386]
Currently missing from the “home nodes” page. It came into the game in the _Champions: Truce_ patch on 2020-11-17.

* [Wiki page about Prismaticite](https://wiki.guildwars2.com/wiki/Prismaticite_Home_Instance_Node)

**Comment by queicherius** [comment]
This home instance is not in the API yet

**Comment by queicherius** [comment]
Closing this since it's an API issue I can do nothing about: https://github.com/arenanet/api-cdi/issues/671
