### ISSUE TITLE
Achievement unlock stats -> Mastery filter breaks locked/unlocked filter

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1387]
If I filter achievements with any of the mastery options, it shows both locked and unlocked achievements even if that filter is active too.

(Also just noticed that the "Ignore without value" filter hides all achievements, so it's kinda pointless on that page.)

**Comment by queicherius** [comment]
Thanks for the report, fixed it now and will be in the next release 👍 

> (Also just noticed that the "Ignore without value" filter hides all achievements, so it's kinda pointless on that page.)

Yeah, it does nothing for cats either for example, but I'll still leave it there because you can toggle it on and change the type afterwards (so you can go through the types, only showing what's "valueable")
