### ISSUE TITLE
Missing title: 2v2 Contender

### ISSUE THREAD

**Issue by Ahrle** [gw2efficiency/issues#1392]
Hello :)

Noticed this title is missing from Stats\Unlock Statistics\Titles.
2v2 Elite is however there.

https://wiki.guildwars2.com/wiki/Title:_2v2_Contender

Happy new 2021!

**Comment by queicherius** [comment]
We just display the titles the official API provides us with, and the one you mentioned is missing in the output.

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍

Happy 2021 to you too :)
