### ISSUE TITLE
Cannot close Dye Preview in Nightmode when scrolled to bottom of page

### ISSUE THREAD

**Issue by Prodigio** [gw2efficiency/issues#1393]
When opening a dye preview from `/account/dyes`, while you have scrolled down to the bottom of the page, the preview overlay only gets displayed at the "top". This way you can't reach the X to close the overlay, because scrolling get's disabled. Luckily the ESC button is working.

![image](https://user-images.githubusercontent.com/18284425/104000802-104c0700-519f-11eb-9d61-cacb6de721e2.png)

**Comment by queicherius** [comment]
Could you please let me know what Browser/Operating System you are using?

**Comment by Prodigio** [comment]
I'm using Windows 10 Home (20H2, Build 19042.685) with Firefox 84.0.2.

**Comment by kazerniel** [comment]
I have the same issue on Firefox 85.0.2.

**Comment by queicherius** [comment]
I tried to reproduce this on Firefox 81 and 86 and none of them showed the issue. Did it fix itself for you two with the latest update?

**Comment by kazerniel** [comment]
Didn't fix for me :(

![image](https://user-images.githubusercontent.com/5689996/109642112-7bd0a600-7b4a-11eb-9da2-e98ca954f581.png)

**Comment by Prodigio** [comment]
For me neither. I'm running Firefox 86.0 (64-bit) now.

**Comment by queicherius** [comment]
Very weird. Could you try opening a new private window (ctrl+shift+p) and enter your API key there? This should disable any addons you have that might interfere.

**Comment by kazerniel** [comment]
Ha, it works correctly that way.

After some poking around I realised it's not an addon, but toggling Night Mode that breaks it. I can replicate it both in my regular session and a new private window.

**Comment by queicherius** [comment]
Thanks for the debugging, managed to replicate it here too now.

Turns out when using `filter`, Firefox changes `position: fixed` to use the filtered element (in our case, `html`) as the bounding box instead of the viewport. This behaviour is apparently wanted for reasons outside of my imagination. Not sure of a fix yet. Current best idea is to read the viewport scroll position and position the modal absolutely based on that.

**Comment by queicherius** [comment]
Fixed
