### ISSUE TITLE
missing category - Mini Awakened Canid.

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1401]
locked PoF mini. searchable in "all" but have no any category.
https://wiki.guildwars2.com/wiki/Mini_Awakened_Canid

![изображение](https://user-images.githubusercontent.com/1270117/106501470-4184d200-64d4-11eb-9e19-66746fc3c945.png)
![изображение](https://user-images.githubusercontent.com/1270117/106501493-477ab300-64d4-11eb-9e83-3d463896faf9.png)

**Comment by queicherius** [comment]
Fixed, set category to path of fire
