### ISSUE TITLE
Shimmering Aurora Weapon Collection Achievement missing

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1404]
The Shimmering Aurora Weapon Collection Achievement is missing in https://gw2efficiency.com/account/achievements -> Collections -> Black Lion Collections
The ones before (Dark Matter Weapon Collection) and after (Bright Inquisitor Weapon Collection) that are correctly displayed

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
