### ISSUE TITLE
Missing images/text

### ISSUE THREAD

**Issue by sho-87** [gw2efficiency/issues#1406]
It seems the website has a lot of missing images and missing text (Not representable item?):

![items](https://user-images.githubusercontent.com/5199715/109378543-42691380-7888-11eb-9d3a-08edc1e6d0df.PNG)

**Comment by queicherius** [comment]
The CDN we use for images is currently having some issues, I've let them know :)

**Comment by queicherius** [comment]
Should be fixed now.
