### ISSUE TITLE
Guild Blueprints Crafting Profit is innacurate

### ISSUE THREAD

**Issue by brian-mack** [gw2efficiency/issues#1407]
When trying to look at the crafting profit for guild blueprints, the recipe is properly populated, however, the crafting profit/sell price is innacurate.

**Comment by queicherius** [comment]
Which blueprint were you looking at?

**Comment by brian-mack** [comment]
The following blueprints


The recipe tree is correct and the costs for the individual components are correct, but the TP prices are completely inaccurate.





Regards,

Brian Mack

**Comment by queicherius** [comment]
I think if you were sending attachments they did not show up on Github :(

**Comment by brian-mack** [comment]
Dang. It's all of the guild siege blueprints. If you search for them under recipes and open their calculator, you'll see that most have no tp price. However, their recipe and crafting price is correct. On Mar 4, 2021 5:27 PM, David Reeß <notifications@github.com> wrote:
I think if you were sending attachments they did not show up on Github :(

**Comment by brian-mack** [comment]
https://gw2efficiency.com/crafting/recipe-search?filter.search=Guild&filter.rarity=2

**Comment by queicherius** [comment]
Ah, I see the issue: The recipes are referencing the *[schematic](https://wiki.guildwars2.com/wiki/Guild_Ballista_Blueprints_(schematic))* and not the [resulting item](https://wiki.guildwars2.com/wiki/Guild_Ballista_Blueprints).

**Comment by brian-mack** [comment]
What's the timeline for getting this updated? Just curious.

**Comment by queicherius** [comment]
Since this is a side project for me, the time I have heavily depends on my actual work and the amount of "chores" (support requests, server maintenance etc) I have to do. Because of this I principally don't give any deadlines.

If you are interested in this issue, this is the repository: https://github.com/gw2efficiency/custom-recipes. It would need a line in `recipes.json` with the overwrite recipe (the same format as the official one with the output id updated) and a new line in `official-id-overwrite.txt` with `<name> (<item id>) => <recipe id>`.

**Comment by holoxx** [comment]
Currently looking into this.
I noticed that all previous recipe overwrites just add/modify some of the ingredients. As far as I can see none of them overwrites the `output_item_id`. 

So regarding `official-id-overwrite.txt`, does `<item id>` have to be the old one or the overwritten one? Same goes for the name (in case of the catapult they differ: `Guild Catapult Blueprint` for the [item](https://api.guildwars2.com/v2/items?ids=42004&lang=en) and `Guild Catapult` for the [schematic](https://api.guildwars2.com/v2/items?ids=76363&lang=en)).
How does this refer to the entered name when searching for a recipe?

**Comment by queicherius** [comment]
Thanks!

I believe the `<item id>` has to be the overwritten one.

The name does not really matter, it's just for easier editing of the recipe JSON, so probably the item name. The website will pull the (localized) name of the item that is referenced by the `output_item_id` for search.
