### ISSUE TITLE
wrong daily strike [Fraenir of Jormag]

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1408]
2021.03.01 Priority Strike: Fraenir of Jormag
but in game daily - Cold War.
![изображение](https://user-images.githubusercontent.com/1270117/109533012-cdd1e700-7aca-11eb-92b7-ac08e88ebff6.png)
![изображение](https://user-images.githubusercontent.com/1270117/109533032-d3c7c800-7aca-11eb-9d2b-1a99d952fc14.png)

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
