### ISSUE TITLE
scribing recipes in crafting calculator don't include base  decoration cost

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#141]
It appears that when determining the requirements for some scribing recipes, it doesn't take into account the need for base decorations which makes it hard to use for determining everything you need to acquire for the desired decoration.

**Comment by queicherius** [comment]
Thanks for the report, that's indeed a bug. No idea why that happens yet, but I'll look into it.

**Comment by queicherius** [comment]
Alright, guild ingredients that don't result from recipes are included now. :)

---

Tracked time: 2h 37m
