### ISSUE TITLE
Liquid Gold (buy) in Account Overview uses wrong value for Tradingpost: Sell Orders

### ISSUE THREAD

**Issue by acrynx** [gw2efficiency/issues#1412]
The value of "Liquid Gold (buy)" for row "Tradingpost: Sell Orders" in "Account -> Overview" currently uses the following calculation:
Cummulative total current buy price (for all sell listings) * 0.85

Instead, it should use the following calculation, since the listing fee of 5% has already been paid:
Cummulative total current buy price (for all sell listings) * 0.9

The value of "Money (current buy price)" in "Tradingpost -> Current Transactions -> Sell listings", which includes TP taxes already uses this calculation. The value displayed here is therefor correct.

I was not able to verify, if the value of "Liquid Gold" in "Stats -> Account Statistics -> Liquid Gold" uses the correct calculation. This should be checked as well.

**Comment by queicherius** [comment]
Huh. You're completely right. I did the correct thing for "Liquid Gold (sell)", but not buy. I fixed it, will be fixed in the next release (later today) so I'll close this :)
