### ISSUE TITLE
Liquid gold aparently 0

### ISSUE THREAD

**Issue by Mirevea** [gw2efficiency/issues#1413]
Hello there.
I got a problem since February 28th when mi liquid gold went from 2,7k to 0.. for no reason.
The other features of the API are working perfectly, but the liquid gold preview..
![imagen](https://user-images.githubusercontent.com/77887732/110237864-9df96800-7f3e-11eb-9ddb-92e15bddb027.png)

Is smth wrong with API calls or a known error?
Tyvm in advance!

Regards.

**Comment by queicherius** [comment]
Since this is an individual problem, please email your API key to support@gw2efficiency.com so I can have a look :)
