### ISSUE TITLE
New spots for Permanent Gathering Nodes

### ISSUE THREAD

**Issue by Bahamut731lp** [gw2efficiency/issues#1416]
Hello there,
I've been farming some spots that I've noticed aren't on the GW2 daily gathering nodes... so I've made maps for them and added a info below the image.

# Flax
![BE4JAAA=](https://user-images.githubusercontent.com/27443880/112601493-ce804380-8e12-11eb-8395-9379fd6970c4.png)
**Bloodstone Fen, Zealot's Overlook Waypoint ([&BE4JAAA=])**

![BFcLAAA=](https://user-images.githubusercontent.com/27443880/112601661-0091a580-8e13-11eb-8fa6-ea882a6c35b1.png)
**Domain of Kourna, Allied Encampment Waypoint ([&BFcLAAA=])**

![BJkLAAA=](https://user-images.githubusercontent.com/27443880/112601893-49e1f500-8e13-11eb-91f4-4b76d5d4b25e.png)
**Jahai Bluffs, Reclaimed Chantry Waypoint ([BJkLAAA=])**

# Orichalcum
![BFcLAAA=  2](https://user-images.githubusercontent.com/27443880/112601765-20c16480-8e13-11eb-96c2-60a1748a6ddc.png)
**Domain of Kourna, Allied Encampment Waypoint ([&BFcLAAA=])**

![BEMLAAA=](https://user-images.githubusercontent.com/27443880/112601973-61b97900-8e13-11eb-80d7-02d3a878db25.png)
**Sandswept Isles, Atholma Waypoint ([BEMLAAA=])**

# Elder Wood
![BEsJAAA=](https://user-images.githubusercontent.com/27443880/112602079-86adec00-8e13-11eb-8bd6-7f73d09846d1.png)
**Bloodstone Fen, Soulkeeper's Airship Waypoint ([&BEsJAAA=])**

![BHgJAAA=](https://user-images.githubusercontent.com/27443880/112602204-aa713200-8e13-11eb-89b5-faa5b108f96e.png)
**Emberbay, Castaway Circus Waypoint ([&BHgJAAA=])**

![BO8JAAA=](https://user-images.githubusercontent.com/27443880/112602327-cf65a500-8e13-11eb-8bdd-b2e81c27ef62.png)
**Siren's Landing, Camp Reclamation Waypoint ([&BO8JAAA=])**

**Comment by queicherius** [comment]
Wow, thanks! Not sure when I will get to adding them, but the pictures will help a ton!

**Comment by msmolev** [comment]
> Wow, thanks! Not sure when I will get to adding them, but the pictures will help a ton!

Is there a repo for static images? I can't seem to find it among the public ones in gw2efficiency. Otherwise we could do PR? 😄

**Comment by queicherius** [comment]
The gathering node data lives here: https://github.com/gw2efficiency/static-data/blob/master/src/legacy/gathering-permanent-nodes.js

The images are not in a public repo, but are just referenced via `image`, so if you would e.g. upload them as a zip I can just drop them in the folder, that would be awesome!

**Comment by msmolev** [comment]
> The gathering node data lives here: https://github.com/gw2efficiency/static-data/blob/master/src/legacy/gathering-permanent-nodes.js
> 
> The images are not in a public repo, but are just referenced via `image`, so if you would e.g. upload them as a zip I can just drop them in the folder, that would be awesome!

I've created a sample PR https://github.com/gw2efficiency/static-data/pull/6  for just Flax nodes -- if everything is okay I can make changes for other nodes tomorrow.

**Comment by Bahamut731lp** [comment]
I've went and dropped the images into a zip.

I've also omitted the first Orichalcum node in Domain of Kourna, because it is not permanent (it has a chance to spawn, but it is not 100%). And as for the Domain of Kourna Flax, it spawns around 3-4 nodes in those marked spots.

[nodes.zip](https://github.com/gw2efficiency/issues/files/6278001/Nodes.zip)

**Comment by msmolev** [comment]
> I've went and dropped the images into a zip.
> 
> I've also omitted the first Orichalcum node in Domain of Kourna, because it is not permanent (it has a chance to spawn, but it is not 100%). And as for the Domain of Kourna Flax, it spawns around 3-4 nodes in those marked spots.
> 
> [nodes.zip](https://github.com/gw2efficiency/issues/files/6278001/Nodes.zip)

I've updated my pull request with other nodes and put images into an archive there (I've resized them down a bit )
Thanks

**Comment by queicherius** [comment]
This is now live, thanks to you both! :)
