### ISSUE TITLE
Gift of Gliding having no price in the crafting calculator

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1418]
![image](https://user-images.githubusercontent.com/8763688/113484129-5fa88780-94af-11eb-8c36-a30e05c2350e.png)
![image](https://user-images.githubusercontent.com/8763688/113484135-67682c00-94af-11eb-8e0d-4036acb120ae.png)

It is purchasable from Miyani or any other Mystic Forge attendant as seen in the picture below (with the price as well).

![image](https://user-images.githubusercontent.com/8763688/113484157-81a20a00-94af-11eb-8249-5493a1c200dc.png)

**Comment by queicherius** [comment]
Added a price
