### ISSUE TITLE
Include skins in the crafting calculator

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#142]
> Seems to ignore skin items. I just checked Wild Abadon, it does not see my Plated Torch yet I have other parts of that collection.

**Comment by ryujinda** [comment]
also their is no value for ascended back armor for completing HoT related collection like the ascended  Magister's Pack. It just says crafting 0 copper

**Comment by queicherius** [comment]
> also their is no value for ascended back armor for completing HoT related collection like the ascended Magister's Pack. It just says crafting 0 copper

I added an extra issue to track that: #173

**Comment by queicherius** [comment]
Closing this because of the pretty big complexity for very little impact (only the few elite weapon collections depend on the skins). Seems like it should be pretty easy for the user to figure out anyway.

**Comment by BenLubar** [comment]
The Mini Chak Gerent seems related:

https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-71835
https://api.guildwars2.com/v2/achievements/2236
![image](https://user-images.githubusercontent.com/4257305/53117951-a5917400-3511-11e9-891c-7a0b0d2140dc.png)

The calculator currently shows me as needing every weapon on the list. I'm not sure how achievement "crafting recipes" work in the calculator, but the API seems to be showing the skins and the random items the same way:

```
  {
    "id": 2236,
    "bits": [
      0,
      1,
      2,
      3,
      7,
      8,
      10,
      11,
      12,
      13,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25
    ],
    "current": 20,
    "max": 26,
    "done": false
  }
```

So whatever method is being used to determine that I already unlocked the random items should also work for the skins, right?
