### ISSUE TITLE
Chairs missing

### ISSUE THREAD

**Issue by Whip** [gw2efficiency/issues#1420]
There are 2 chairs missing on the site: Volcanic Throne and Wandering Cloud.

Full list is available on this link: https://wiki.guildwars2.com/wiki/Chair

**Comment by queicherius** [comment]
Those two chairs are not in the official API.

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
