### ISSUE TITLE
Add an option to use Gift of Desert Mastery for Gen 2 Legendries (Crafting)

### ISSUE THREAD

**Issue by BlackbirdV2** [gw2efficiency/issues#1423]
It only has gift of Maguuma Mastry. Majority of Gen 2 legendary weapons allow Gift of Desert mastery now. Be nice to see that change.

**Comment by queicherius** [comment]
We do not have internal support for different types of the same recipe.

However, you can build the recipe yourself: https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-90883;1-71820;1-90893;1-86036
