### ISSUE TITLE
Superior Rune of Leadership price is 100 % higher than it is in-game

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1424]
As you can see in the images, the price is different on the site than it is in-game. Not a serious issue by any means, might just scare some crafters away.

![image](https://user-images.githubusercontent.com/8763688/115095735-0585d880-9f2b-11eb-8c6f-abd125629116.png)

![image](https://user-images.githubusercontent.com/8763688/115095754-10d90400-9f2b-11eb-9f40-cee1a4df4187.png)

**Comment by Janitsu** [comment]
Here's the site when crafting only one.

![image](https://user-images.githubusercontent.com/8763688/115095784-3108c300-9f2b-11eb-85a3-014509be8df6.png)

**Comment by Janitsu** [comment]
And with max rank provisions master, you can get them for these prices. Sorry if this was a flood for nothing!
![image](https://user-images.githubusercontent.com/8763688/115096946-1a189f80-9f30-11eb-925c-dd7eedafd5d8.png)

**Comment by queicherius** [comment]
This should fix itself in the next couple of hours :)
