### ISSUE TITLE
Crafting menu could allow you to finish the prompt by pressing "Enter"

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1436]
![image](https://user-images.githubusercontent.com/8763688/121210543-7048f580-c884-11eb-8ac7-e9b1301ecd4e.png)

When you are in this part of the crafting menu, pressing "Enter" could finish the item name according to the most relevant prompt (in this case, the only prompt) below.

**Comment by queicherius** [comment]
Now live
