### ISSUE TITLE
Able to compare player statistics against past snapshots

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1439]
> player statistics to get its own slider bar to view how profession/playtime has changed maybe once every month and have a nice little graph to show how its changed?

- [x] Save snapshots once a week
- [ ] Expose them via a backend
- [ ] Make a frontend to display and compare them to the current ones

**Comment by ShiningMassXAcc** [comment]
@queicherius - Semi-random thought about this one: I think this has the potential to unlock a bunch of usage, and particularly community content that others might be interested in leveraging with you (I'd be curious if they've reached out to you already for this :) ).

Today, you really have only one function that enables the community to engage with others in the community (and exposes folks username directly to others) the lottery.  For the lottery, folks can donate, others win randomly, and others can see who wins.

There are consistently a bunch of other ways that folks or content creators try to engage and award the community, trying to build up GW2 - this has been holding events, competitions, and their own giveaways.  Recently, when I think about what groups like HardStuck have done, trying to lower the bar for people to get into content.  However, they can really only award folks at the very high end of the spectrum - people winning raid clear times or other things like that.  To lift all boats though, you perhaps want the average person

**Comment by queicherius** [comment]
> Semi-random thought about this one: I think this has the potential to unlock a bunch of usage, and particularly community content that others might be interested in leveraging with you (I'd be curious if they've reached out to you already for this :) ).

I'm up for collaborating with others, but so far nobody has reached out with a solid proposal besides the things we are already doing / have done.

> Today, you really have only one function that enables the community to engage with others in the community (and exposes folks username directly to others) the lottery. For the lottery, folks can donate, others win randomly, and others can see who wins.

We have our own community on Discord too, where we sometimes hold competitions.

> Only other item that would really be needed, is if folks had somewhere in their account profile to check a box that says "It's okay to share my account name on top 25 statistics leaderboards, community sponsored events like Lottery, etc".

I actually tested this with the community before via a few polls and the answer was an overwhelming "I would never share my name on the leaderboard", mainly due to concerns of spam/begging in-game.

> Imagine if HardStuck could sponsor giving 50g to 10 people each week, in a lottery, for any accounts with 5k achievement points that cleared a Raid for the first time?

I think the problem with this is that for data privacy reasons, it would have to be opt-in on a per-event basis. I cant image folks wanting to opt in to account data sharing to "anyone", and I wouldn't want the extra responsibility of vetting people building events.

And at that point, why would HardStuck (or anyone else) not just make their own page and ask for an API key to enter?

**Comment by ShiningMassXAcc** [comment]
All great comments - thanks for the reply

**Comment by queicherius** [comment]
@Ecmelt This one is a bit bigger, let's chat before you start with it.
