### ISSUE TITLE
locked recipe: Minotaur Steak

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1440]
![изображение](https://user-images.githubusercontent.com/1270117/122874583-d41af600-d33b-11eb-84cd-1574beed43b2.png)
![изображение](https://user-images.githubusercontent.com/1270117/122874607-d9784080-d33b-11eb-86a7-807c99d42511.png)
![изображение](https://user-images.githubusercontent.com/1270117/122874713-f876d280-d33b-11eb-870e-95f530099a55.png)

it was unlocked very long ago.

**Comment by queicherius** [comment]
For this view we just display 1:1 what the API gives us, so if there is wrong information there's sadly nothing we can do about it. :(
