### ISSUE TITLE
[suggestion] hide or mark not available items

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1441]
some items, for ex. recipes, placed in Historical category at wiki.
maybe create additional option to hide them, or visual notification like badge over icon.

![изображение](https://user-images.githubusercontent.com/1270117/122875457-f2cdbc80-d33c-11eb-96b4-a0855f886873.png)
![изображение](https://user-images.githubusercontent.com/1270117/122875471-f8c39d80-d33c-11eb-9a87-7a7a6d298856.png)

**Comment by queicherius** [comment]
Merged with #1366
