### ISSUE TITLE
Guild Upgrade:  Display Cheapest Route to Desired Item

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1449]
Specifically to obtain Treasure Trove and Deep Cave, but others may have other goals.  I am looking for extra storage for my personal guild and due to the Guild level minimums before building items, there are many paths to a particular goal; it is hard to determine the cheapest route.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
