### ISSUE TITLE
Account Overview navigation items overflow for german translations

### ISSUE THREAD

**Issue by holoxx** [gw2efficiency/issues#1450]
See below. Home Cats, Gliders and Novelties are missing.

The three items are present but wrapped into a third row which overflows outside the container.

<img width="1461" alt="german" src="https://user-images.githubusercontent.com/16797784/125163025-71bf5380-e18b-11eb-9420-00fcf2212477.png">
<img width="1399" alt="english" src="https://user-images.githubusercontent.com/16797784/125163028-72f08080-e18b-11eb-909e-778e97256d1f.png">

**Comment by queicherius** [comment]
This should now be fixed

**Comment by holoxx** [comment]
not quite :(

<img width="1441" alt="adssadasd" src="https://user-images.githubusercontent.com/16797784/126883659-90a2d278-7fdb-4d7b-a361-8873d2c5b0c6.png">

<img width="1228" alt="adasdsa" src="https://user-images.githubusercontent.com/16797784/126883666-426d3339-689d-4638-bab2-01fcf903941e.png">

<img width="1119" alt="asdsadasd" src="https://user-images.githubusercontent.com/16797784/126883669-6cc6dd2b-1930-4bf8-9ccf-ae84f4b6c9d3.png">

**Comment by queicherius** [comment]
Should be fixed in the next release
