### ISSUE TITLE
Heart of Thorns mastery points in statistic shows 0 points for everyone

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1456]
![image](https://user-images.githubusercontent.com/8763688/126582898-789d2c43-8173-463a-8f1a-65ea69231ef2.png)

Heart of Thorns Mastery Points, for whatever reason, are not properly counted. I am supposedly rank 1 with 0 Mastery Points although I have almost all of them.

https://gw2efficiency.com/account/statistics/statistics.masteryPointsMaguuma

**Comment by queicherius** [comment]
This has been missing from the API for nearly 3 years, nothing we can do.

https://github.com/arenanet/api-cdi/issues/639
