### ISSUE TITLE
Improve Season 2 Legedary Crafting -> Add unlocks and recipes

### ISSUE THREAD

**Issue by wienczny** [gw2efficiency/issues#1458]
When crafting season 2 legendaries you are required to build items like "Claw of Execution". This items must be crafted in order to purchase the recipe for "Claw of Retribution".
Currently if you craft it, buy the recipe and then destroy the item (as it is not used any more) the crafting calculator again requires you to craft it as it does not find the item in the inventory any more.

I suggest adding the unlocks and recipe purchases to crafting calculator:

* Claw of Retribution
* * Buy recipe of Claw of Retribution
* * * Craft Claw of Retribution (which should check for the item in the inventory AND the skin unlock)

The skin unlocks could be on their own node, too:

* Claw of Retribution
* * Buy recipe of Claw of Retribution
* * *  Unlock skin for Claw of Retribution
* * * * Craft Claw of Retribution

This is related to #55

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

We could be able to tell if you crafted the item in this specific case based on if you have the skin, but that is really hard to generalize.
