### ISSUE TITLE
Legendary Insight / Total Raid Tokens misscalculation

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1461]
The LI for Items in Inventories is no longer calculated, resulting in me having 300 LI less then I should have, as I have my duplicate Raid armor in my inventory:  https://gw2efficiency.com/c/Asuna%20The%20Undine
I do not know if its value is added to the Account value.

**Comment by queicherius** [comment]
Yeah, right now legendary items on characters that logged in after the legendary armoury release do not count. They will also further not count for value calculation (since you should have received compensation), but they will probably in the future count for LI again

**Comment by Prismaru** [comment]
Any news on raid tokens stats?

**Comment by queicherius** [comment]
@Prismaru Since this is a side project for me, the time I have heavily depends on my actual work and the amount of "chores" (support requests, server maintenance etc) I have to do. Because of this I principally don't give any deadlines, but it's still on the/this list.

**Comment by Prismaru** [comment]
idk if its helpful or even relevant but I just realized why I'm missing li/ld compared to killproof.me, because I have some of it stored in my alt character's inventory. So gw2e only sees li and ld that is in my bank and storage but not on character.

**Comment by queicherius** [comment]
Fixed in next release
