### ISSUE TITLE
Orphaned achievements

### ISSUE THREAD

**Issue by xvwyh** [gw2efficiency/issues#1462]
Any chance of displaying a list of achievements that don't belong to any category? There's a lot of hidden achievements in the game that can be completed by accounts, yet aren't currently listed in any of the visible achievement categories, here's the list of mine, for example:

11,84,104,130,133,146,152,219,358,359,360,361,362,363,364,365,415,416,417,418,419,420,421,422,423,424,427,428,429,430,431,432,460,461,536,537,539,540,541,542,543,544,569,570,571,572,589,590,591,592,593,594,595,596,597,598,599,600,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,649,650,651,652,653,654,655,656,657,658,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,681,682,683,684,685,686,688,689,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,871,872,880,881,882,883,890,897,898,899,915,947,969,970,971,972,973,974,977,979,980,981,982,983,984,985,986,987,988,990,1003,1004,1005,1006,1007,1009,1010,1011,1013,1015,1016,1017,1018,1089,1090,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1154,1155,1156,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1242,1244,1245,1246,1247,1248,1251,1252,1254,1255,1256,1257,1258,1259,1291,1292,1293,1294,1343,1344,1345,1346,1347,1348,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1421,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1537,1538,1539,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1561,1566,1568,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1595,1625,1755,1756,1757,1758,1759,1760,1762,1763,1764,1765,1766,1767,1768,1769,1770,1772,1773,1774,1775,1776,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2074,2075,2076,2077,2078,2154,2161,2167,2208,2209,2226,2284,2312,2318,2358,2482,2539,2764,2767,2770,2771,2773,2778,2779,2780,2781,2783,2784,2788,2790,2791,2793,2794,2795,2800,2804,2805,2806,2809,2814,2818,2996,3046,3154,3155,3159,3161,3163,3164,3165,3166,3168,3169,3251,3257,3269,3273,3274,3275,3276,3277,3278,3279,3843,4193,4202,4408,4997,5459,5460,5462,5464,5465,5484,5529,5592,5603,5625,5670,5689,5695,5702,5755,5759

Yeah, most of them are not whitelisted in the API, so there's nothing really to display, yet some (currently?) slipped through the cracks:

```json
[
  {
    "id": 4202,
    "name": "Beetlemania",
    "description": "Collection: Help Gorrik make a new friend.",
    "requirement": "Collect the items Gorrik asked for to complete Petey's guided evolution.",
    "locked_text": "",
    "type": "ItemSet",
    "flags": [
      "Pvp",
      "RepairOnLogin",
      "Permanent"
    ],
    "bits": [],
    "tiers": [
      {
        "count": 20,
        "points": 10
      }
    ],
    "prerequisites": [
      4271
    ]
  },
  {
    "id": 4408,
    "icon": "https://render.guildwars2.com/file/3FB1AE472DF109D022146F26B0F420140BFC26FE/1824200.png",
    "name": "Words of Mending",
    "description": "",
    "requirement": "",
    "locked_text": "Speak with Amira in Sun's Refuge.",
    "type": "Default",
    "flags": [
      "Pvp",
      "RepairOnLogin",
      "Permanent"
    ],
    "tiers": [
      {
        "count": 1,
        "points": 0
      }
    ]
  },
  {
    "id": 5459,
    "name": "Fractal Rush Community Goal: Tier 5",
    "description": "",
    "requirement": "",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 5,
        "points": 0
      }
    ],
    "rewards": [
      {
        "type": "Item",
        "id": 94104,
        "count": 1
      }
    ]
  },
  {
    "id": 5460,
    "name": "Fractal Rush Community Goal: Tier 4",
    "description": "",
    "requirement": "",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 4,
        "points": 0
      }
    ],
    "rewards": [
      {
        "type": "Item",
        "id": 94099,
        "count": 1
      }
    ]
  },
  {
    "id": 5462,
    "name": "Fractal Rush Community Goal: Tier 3",
    "description": "",
    "requirement": "",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 3,
        "points": 0
      }
    ],
    "rewards": [
      {
        "type": "Item",
        "id": 94100,
        "count": 1
      }
    ]
  },
  {
    "id": 5464,
    "name": "Fractal Rush Community Goal: Tier 1",
    "description": "",
    "requirement": "",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 1,
        "points": 0
      }
    ],
    "rewards": [
      {
        "type": "Item",
        "id": 94101,
        "count": 1
      }
    ]
  },
  {
    "id": 5465,
    "name": "Fractal Rush Community Goal: Tier 2",
    "description": "",
    "requirement": "",
    "locked_text": "",
    "type": "Default",
    "flags": [
      "Permanent"
    ],
    "tiers": [
      {
        "count": 2,
        "points": 0
      }
    ],
    "rewards": [
      {
        "type": "Item",
        "id": 94109,
        "count": 1
      }
    ]
  }
]
```

The first two in particular just showed up today, not visible in-game, yet apparently completed by my account. Would be nice to see such internal achievements visible somewhere for reasons of curiosity. "Beetlemania", for example, apparently awards 10 AP, who knows if it really does or not, but if such achievements were surfaced - people could potentially spot such things.

**Comment by queicherius** [comment]
This is in the next release
