### ISSUE TITLE
Waypoint Link in Gathering/Permanent-Nodes misses a "&"

### ISSUE THREAD

**Issue by TalliahSlavik** [gw2efficiency/issues#1467]
Hi,
on [this ](https://gw2efficiency.com/gathering/permanent-nodes) subpage the last entry to Jahai Bluffs, Reclaimed Chantry Waypoint is neither on German nor does it copy the chat-code correctly. The chatcode it copies [BJkLAAA=] misses an "&", so correct waypoint should be [&BJkLAAA=].

Side note:
Great page. Good Work team. Thanks for your time.

~ Kind regards

**Comment by queicherius** [comment]
Thanks for the report, fixed. Will be live with the next release.

> Great page. Good Work team. Thanks for your time.

Appreciate it :)
