### ISSUE TITLE
New Boss "Dragonstorm (Public)"

### ISSUE THREAD

**Issue by KingRider** [gw2efficiency/issues#1468]
![image](https://user-images.githubusercontent.com/4491180/127779783-19851346-1b78-48b6-a2a9-0e852ed3dfe9.png)

Teleportation Location: `[&BAkMAAA=]`

**TIMER:**
17:00 UTC
19:00 UTC
21:00 UTC
23:00 UTC
01:00 UTC
03:00 UTC
05:00 UTC
07:00 UTC
09:00 UTC
11:00 UTC
13:00 UTC
15:00 UTC

**REWARDS:**
![image](https://user-images.githubusercontent.com/4491180/127779852-08176a7b-d765-4822-88ed-6912700f6d13.png)

**Official URL:**
https://wiki.guildwars2.com/wiki/Dragonstorm

**Comment by queicherius** [comment]
Added, will be live with the next release
