### ISSUE TITLE
Add automatic updating to the transaction page

### ISSUE THREAD

**Issue by MerlinScheurer** [gw2efficiency/issues#147]
It would be nice to see the transaction page beeing updated every 1 to 10 minutes

**Comment by queicherius** [comment]
I agree. That'd tie in with #38.

**Comment by queicherius** [comment]
This is now live. Sorry it took so long x_x

**Comment by MerlinScheurer** [comment]
@queicherius don't worry.

I totally forgot that I added this issue in the first place 😅

But still, thank you 😄
