### ISSUE TITLE
Searching account inventory doesn't update search when another acct selected.

### ISSUE THREAD

**Issue by mwrich4** [gw2efficiency/issues#1472]
Recently, if I type a search term in the overview I see the list of results for that account.  When I use the drop-down for another account, the search results remain the same.

I haven't found a good workaround yet.  Usually I just close the site for now and then go back, but then I have to retype the search.

**Comment by queicherius** [comment]
That's super weird, and I can not reproduce that. What browser are you using? How many API keys do you have in total? Do you have ads showing or not (supporter/adblock)?

**Comment by queicherius** [comment]
Answered via email, seems to have resolved itself and/or be a problem with Firefox.
