### ISSUE TITLE
Gift of Bloodstone Magic and Gift of Dragon Magic show as "Not Sold or Crafted"

### ISSUE THREAD

**Issue by LeJoker** [gw2efficiency/issues#1474]
Gift of Bloodstone Magic and Gift of Dragon Magic show as ["Not Sold or Crafted"](https://i.imgur.com/rVYC5tv.png) when they are in fact sold by Miyani/Mystic Forge attendants for a stack of each of the Season 3 map currencies.

[Gift of Bloodstone Magic](https://wiki.guildwars2.com/wiki/Gift_of_Bloodstone_Magic):
Sold for 250 Blood Rubies, 250 Jade Shards, and 250 Orrian Pearls

[Gift of Dragon Magic](https://wiki.guildwars2.com/wiki/Gift_of_Dragon_Magic):
Sold for 250 Petrified Wood, 250 Fresh Winterberries, and 250 Fire Orchid Blossoms

Additional info: This is found using a logged in account, using an API key and "use own materials" enabled. Also happens with "use own materials" disabled. Chrome v. 92.0.4515.131

**Comment by queicherius** [comment]
The crafting calculator currently does not have support for showing more than one currency, so rather than show a wrong one (e.g. the first one) we just show none at all and rely on people to click on the wiki button.
