### ISSUE TITLE
Bug: Privacy settings move when scrolling in Firefox

### ISSUE THREAD

**Issue by ProfBits** [gw2efficiency/issues#1483]
The Privacy Settings in the bottom right of the screen on Firefox move when scrolling. As far as I have tested this affects all pages wich can be scrolled.

Expected:
As in Chrome, the Privacy Settings should stay at the bottom right hand conrner of the browser sceen regardless of scrolling.

Affected Browser Version:
Firefox 91.0 (64-Bit)

Screenshot (slightly scrolled page on Crafting Calculator):
![grafik](https://user-images.githubusercontent.com/53108880/129703227-4201db1b-1791-43cf-a48f-b91231f9936e.png)

**Comment by queicherius** [comment]
This is a weirdness around how Firefox handles filters (which is how the darkmode works) in regards to elements with fixed positioning.

Sadly since this element is rendered by my advertising provider I don't have too much influence into how it looks.
