### ISSUE TITLE
[Bug] Finite Result: "Charged Clump of Swamp Moss" shown twice

### ISSUE THREAD

**Issue by Hurric4ne** [gw2efficiency/issues#1487]
In the Crafting Breakdown of [Finite Result](https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-73624), "Proof: Finite Result" hast the "Charged Clump of Swamp Moss" twice in it.

**Comment by queicherius** [comment]
Thanks, fixed this. Should be updated in a couple of hours.
