### ISSUE TITLE
Improve time machine "hide changes by market flucuations"

### ISSUE THREAD

**Issue by Hurric4ne** [gw2efficiency/issues#1488]
Checking "Hide changes caused by market fluctuations" could also hide the account value change per category aswell as the value at the bottom.

Example where changes to item values "inflate" the category, even if they're hidden:
![no_change](https://user-images.githubusercontent.com/16904540/130206261-3da108a0-4ef4-4ad8-9175-5a1ef3e4edca.JPG)
![no_change2](https://user-images.githubusercontent.com/16904540/130206625-68b4750f-9f4b-4e74-8cb4-20aa1d091374.JPG)

**Comment by queicherius** [comment]
Note to self, when doing this also fix how the checkbox works to be more logical:

> I think it would be pretty easy to add to have the option to use the values of the newer snapshot also for the old one. So essentially that should then completely ignore market price fluctuations and for items where the quantity changed it should only show the gains. This would also work for gem values.

**Comment by queicherius** [comment]
This is in the next release
