### ISSUE TITLE
Legendary Armory unlock percentage doesn't update with the including/excluding duplicates option

### ISSUE THREAD

**Issue by holoxx** [gw2efficiency/issues#1498]
7/155 = 4,5%, the other one is wrong

<img width="820" alt="asdasdasd" src="https://user-images.githubusercontent.com/16797784/131167052-7cdd40ea-9683-4644-b3ce-beeb671d7b6a.png">

<img width="813" alt="asdsada" src="https://user-images.githubusercontent.com/16797784/131167078-66bee61b-063a-4117-99b7-2d2a1ccca909.png">

**Comment by queicherius** [comment]
Fixed in hotfix (about an hour)
