### ISSUE TITLE
Account statistics: unstable fractal essence, wrong number

### ISSUE THREAD

**Issue by Dediggefedde** [gw2efficiency/issues#1502]
Efficiency shows me 720 UFE in stats/account-statistics and 240 UFE in account/wallet (correct value)

**Comment by queicherius** [comment]
We also count the following things into the statistic:

- Abyssal Fractal Weapon Box
- Abyssal Fractal Weapons
- Abyssal Infusion Chest
- Abyssal Infusion
- Celestial Infusion Chest
- Celestial Infusion (Red)
- Endless Chaos Combat Tonic
- Endless Inner Demon Combat Tonic
- Endless Inner Demon Combat Tonic
