### ISSUE TITLE
Add Bjora & Grothmar metas' countdown timer to Daily page?

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1509]
I find Dragonstorm's countdown timer super helpful, so I was wondering if we could get a similar one for Bjora Marches' Storms of Winter and the 4 Grothmar metas? (I see that Drakkar is already there.)

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
