### ISSUE TITLE
Consider having "Ignore without value" toggle hide 0 AP value achievements in unlock statistics view for achievements

### ISSUE THREAD

**Issue by ShiningMassXAcc** [gw2efficiency/issues#1510]
From unlock statistics page for achievements, "Ignore no value" currently hides everything due to achievements having no value.  Consider filtering out 0 AP achievements, could be useful for AP hunters.

https://gw2efficiency.com/account/unlock-statistics?filter.show=locked&filter.ignoreNoValue=true

**Comment by queicherius** [comment]
Deployed
