### ISSUE TITLE
Add "Collapse" to Used owned materials in Crafting Calculator

### ISSUE THREAD

**Issue by fe6865d3bf** [gw2efficiency/issues#1512]
It would be nice to add "Collapse used owned materials " while using "Use own materials" option "Yes" in crafting calculator. So we don't have to scroll all the way to "Shopping List" section.

**Comment by queicherius** [comment]
Also add the ability to "check off" crafting steps which marks them green + collapses them.

**Comment by queicherius** [comment]
Deployed
