### ISSUE TITLE
Save order parameters in Tradingpost - Overview

### ISSUE THREAD

**Issue by DavSalli** [gw2efficiency/issues#1515]
The order parameters in the Tradingpost - Overview window (descending/ascending as well as the parameter to sort of) don't seem to be saved when you change to a different window. You either have to keep the tab open the whole time you need it, or re-enter all the parameters and wait until the site gets ordered. It would be nice when those parameters were saved until manually changing them.

**Comment by queicherius** [comment]
Tested, they are saved (now?) in the URL so they should be bookmarkable / load when you get back
