### ISSUE TITLE
Number of minis differ between GW2e and the game itself

### ISSUE THREAD

**Issue by Ahrle** [gw2efficiency/issues#1517]
Favorably for the former?
GW2e lists a total of 786 minis, meanwhile the game shows a total of 738...
Number of unlocked minis remain the same for me, though.

Is there a bug or have 48 minis been removed from game?

Regards,
Hans 
![Skärmklipp](https://user-images.githubusercontent.com/53276888/136248909-5060a1fe-626e-4020-8dd0-68db1f6ed284.PNG)

**Comment by queicherius** [comment]
The wardrobe hides some miniatures in older collection sets by default, unless you have them unlocked. We show all of the minis that are available on the site :)
