### ISSUE TITLE
Crafting recipes for multiple disciplines don't show up for some recipes

### ISSUE THREAD

**Issue by Janitsu** [gw2efficiency/issues#1521]
As seen in the pictures, the crafting calculator says that only weaponsmith can craft the Superior Sigil of Torment, but as is evident in the wiki as well as in the crafting station itself, even huntsman and artificer are able to craft them.

![image](https://user-images.githubusercontent.com/8763688/137343623-9c5149bb-62f4-4faf-8659-37666ffa5a10.png)
![image](https://user-images.githubusercontent.com/8763688/137343663-bd9dcd39-26d1-4649-af12-ccd66989f0ca.png)
![image](https://user-images.githubusercontent.com/8763688/137343679-ce70be5f-ce3c-45cf-b841-08060b318391.png)

**Comment by queicherius** [comment]
Interesting. The reason for this is because it's 3 different recipes instead of one recipe with 3 disciplines.

We filter duplicated recipes down to the cheapest one. In that step we could also concatenate the disciplines together if the recipes are the same component wise.

**Comment by Janitsu** [comment]
Sounds like it is one of those anomalies within GW2, probably something to do with the previous recipe system or something. But sounds like a good plan to me! Thanks in advance already.

**Comment by queicherius** [comment]
Going to close this one because the website is technically correct - you do need the recipe on a specific discipline and this is a one-off anomaly that would require quite a bit of work to get right merging.
