### ISSUE TITLE
Incorrect cost for guild upgrade Mission Slot: PvE

### ISSUE THREAD

**Issue by xaho** [gw2efficiency/issues#1530]
Costs stated for the Mission Slot: PvE are: 16 g 10 s 75 c
The costs however include 30 Icy Runestones, but are calculated at a cost of 12 s 50 c each, while it should be 1 g according to https://wiki.guildwars2.com/wiki/Icy_Runestone.
![image](https://user-images.githubusercontent.com/254307/138965950-80fad197-ad95-4bca-8e57-8d42ac0a570c.png)

**Comment by queicherius** [comment]
Fixed this a while ago with #1593
