### ISSUE TITLE
If the mystic forge output is not guaranteed, show a warning

### ISSUE THREAD

**Issue by Iiridayn** [gw2efficiency/issues#1531]
The recipes for "Endless Gift Dolyak Tonic" and "Mini Steam Minotaur" both show they produce 1 of the item, but in reality they instead have a chance at producing one of several items. As with Mystic Clovers and Amalgamated Gemstones, the output is non-integer.

For the former:
- https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-38121
- https://wiki.guildwars2.com/wiki/Endless_Gift_Dolyak_Tonic "has a chance" - unclear if 1/3rd (two painful trials resulted in one of each of the other two listed options).

It is probable that other recipes are impacted; I found these two by coincidence.

Relevant to the https://github.com/gw2efficiency/custom-recipes repo.

**Comment by queicherius** [comment]
Making the output a decimal is confusing (and in some cases not supported), but I'll add a warning so its clear to users that the outcome is not guaranteed.

**Comment by queicherius** [comment]
Deployed
