### ISSUE TITLE
Don't suggest crafting using deprecated recipes without disciplines

### ISSUE THREAD

**Issue by Iiridayn** [gw2efficiency/issues#1532]
https://wiki.guildwars2.com/wiki/Minor_Rune_of_the_Air lists two deprecated recipes. Sadly, https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-24748 lists one of the deprecated recipes as the crafting recipe, which cost me some gold. This is likely not the only example; I stumbled across it by chance.

We need to update the https://github.com/gw2efficiency/custom-recipes repo to not list deprecated recipes.

**Comment by Iiridayn** [comment]
Manually searching around 50 in the wiki shows that in almost every case a deprecated recipe was replaced by an updated recipe on the same id. The only cases I've found are two of the runes of air - so it is indeed reasonable to blacklist or request removal individually from the API as they are found.

**Comment by Iiridayn** [comment]
There are 12 recipes without a discipline; all appear to be uncraftable (I verified 4/5 of the runes, and the duplicate backpack recipes were removed). It seems a safe check to simply filter out recipes with no discipline.

**Comment by queicherius** [comment]
Good to know, I can definitely kick those out 👍

**Comment by queicherius** [comment]
Deployed
