### ISSUE TITLE
Incorrect pre-requisites for guild upgrade(s)

### ISSUE THREAD

**Issue by xaho** [gw2efficiency/issues#1534]
While upgrading a guild I was using the GW2Efficiency tools for guild upgrades to take the cheapest upgrades first, which is working pretty damn nice, except for some small bugs, such as this one.

"Scribing: Invincible Dolyak" shows it doesn't have any prerequisites on GW2Efficiency:
![image](https://user-images.githubusercontent.com/254307/139880716-c4e94a98-e299-4d50-8089-33d2184568bd.png)
But it does have pre-requisites: https://wiki.guildwars2.com/wiki/Scribing:_Invincible_Dolyak (Tower claiming, which has also has camp claiming as a pre-requisite)

**Comment by queicherius** [comment]
The prerequisites are pulled from the API directly, we just display them. Whether they are correct or not seems to be a bit random over time. Please report this here instead: https://github.com/gw2-api/issues/issues

**Comment by xaho** [comment]
My apologies, didn't expect this to be a GW2 API issue, I verified the issue and submitted an [issue on the GW2 API repository](https://github.com/gw2-api/issues/issues/14), thanks for the pointer!
