### ISSUE TITLE
Recipes with Blood Rubies ask you to complete the Bloodstone Sightings achievement multiple times

### ISSUE THREAD

**Issue by SniderThanYou** [gw2efficiency/issues#1537]
Expected behavior:
Shopping list includes 49 Bloodstone Rubies

Actual behavior:
Shopping list shows 5x the requirements for the Bloodstone Sightings Achievement
Crafting list shows the achievement 5x

![Screenshot from 2021-11-16 22-16-41](https://user-images.githubusercontent.com/1890082/142128282-9e998017-b9e1-4c37-9a98-f0b8e6f43c59.png)

![Screenshot from 2021-11-16 22-12-47](https://user-images.githubusercontent.com/1890082/142128301-3ec65484-e7e2-488a-98c4-8cdabb861a26.png)

**Comment by queicherius** [comment]
Fixed, should be updated with next crawl
