### ISSUE TITLE
Value of Account Bound gemstore skins in gold is extremely high

### ISSUE THREAD

**Issue by eternalflamez** [gw2efficiency/issues#1538]
Some examples from my bank:
Vermilion Blaze Greatsword Skin - 125 gems || 2,269 gold
Tempest Gaze Helm Skin - 42 gems || 749 gold
Seven Reapers Pauldrons Skin - 42 gems || 749 gold

But other gem items work fine, like:
Black Lion Instant Level 80 Ticket - 2000 gems || 623 gold

**Comment by queicherius** [comment]
Our definition of the account value is as follows:
> The value of an account should represent how much money/effort a new player would need to replicate that account.

Therefore for items that are currently not available in the gemstore, but through the black lion exclusives chest (which is the case for all the items you mentioned), we use the value of the exclusives chest.
