### ISSUE TITLE
Copy name in crafting buy list is colored in the rarity of the item

### ISSUE THREAD

**Issue by Metin200** [gw2efficiency/issues#154]
I don't know if this is intended, but the copy icon is tinted in the rarity of the item. (Which in my case is hard to see with a LED monitor [the gold one])
![bug](https://cloud.githubusercontent.com/assets/4706504/15829066/5f3ee772-2c12-11e6-9a48-4829d606c1cd.JPG)

**Comment by queicherius** [comment]
It was intended, but I didnt realize the gold one was completely invisible. Fixed!

---

Tracked time: 10m
