### ISSUE TITLE
Add Filter for Stat Prefixes both current and possible

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1546]
With a lot of items being stat-selectable now, it can be a little difficult to sift through a large collection of items when gearing a new build.

What I'd really love to see is being able to filter my items down to, for example, just celestial items, as well as stat-selectable items with celestial in their options.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

Mainly because I think the API does not fully support the logic for what stats are available / chosen right now.
