### ISSUE TITLE
Mistborn mote and such don't get listed in Farming tracker

### ISSUE THREAD

**Issue by julienmonnard** [gw2efficiency/issues#1547]
Hello! 

When I farm Mistborn Motes and Eternal Ice Shard, while having the Farming tracker started, they never show up in the list, at all.

I didn't try the other currencies, so not sure if it's an isolated issue or if they are also affected

**Comment by queicherius** [comment]
Duplicate of https://github.com/gw2efficiency/issues/issues/913
