### ISSUE TITLE
Remove recipes for shards/globs

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#155]
> Globs and shards of condensed mists essence have high values since the site assumes you'll make them out of vials

**Comment by Scath-Enfys** [comment]
there has to be a more elegant solution than this. Perhaps an "Hunt this" or "loot this" option, or simply not enabling the recipe by default?

**Comment by queicherius** [comment]
> simply not enabling the recipe by default?

Yep, that's the plan.
