### ISSUE TITLE
Prevent crafting calculator suggestions from being redundant.

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1552]
Prevent redundant entries when adding additional items, eg. type godskull, select assassin's godskull musket, add new item, type godskull again, this time have the musket filtered out from the list of suggestions.

This would improve the multiple item crafting option, considering the shortness of the suggestion list can get in the way of, say, easily making a list of all of a set of crafted items, or comparing inscription costs.

**Comment by queicherius** [comment]
Note to self: We can easily make the list of suggestions longer as well.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
