### ISSUE TITLE
[feature] Filter Achievements for time gates

### ISSUE THREAD

**Issue by Syphdias** [gw2efficiency/issues#1553]
After just posting [this](https://www.reddit.com/r/Guildwars2/comments/srjnkc/searching_for_a_daily_gates_guide/) on reddit. I realized that it would be great to have this as a filter option on the Achievements page.

I am currently catching up on some achievements (maps, stories, Vison – details on reddit) and I am searching for a resource to find all time-gated stuff to prioritize them while doing non-time-gated stuff.

I don't think this can be done automatically through the API, but the achievements would need to be flagged manually (which is a shame). Note that there would be hard time gates that cannot be done multiple times a day, some things can be done on multiple characters but you lose out on a bonus and some can be done on multiple characters.

I'd be happy to help to dig through all the achievements to flag them, if this is something you were interested in.

**Comment by queicherius** [comment]
Just to leave a comment here: This would require manual data that would need to be kept up-to-date, which makes this very low priority if ever to be added. It's a neat idea tho, so I'll keep the issue open.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
