### ISSUE TITLE
add new rich node

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1554]
permanent both Rich and Mithril nodes.

Domain of Kourna
Allied Encampment Waypoint [&BFcLAAA=]

![изображение](https://user-images.githubusercontent.com/1270117/153779586-5ab99747-30cf-4fe7-8082-5d098bd61221.png)

**Comment by SaiyanOfDarkness** [comment]
> both Rich and Mithril

You didn't specify what Rich node it was.  Is it Orichalcum?

**Comment by malikoth** [comment]
There are five missing permanent rich orichalcum nodes that I know of. Adding maps to each in individual comments.

**Comment by malikoth** [comment]
![image](https://github.com/gw2efficiency/issues/assets/2665937/03830a2e-fbaa-4157-859c-59580d32649b)

**Comment by malikoth** [comment]
Start at Lair of the Forgotten Waypoint in The Desolation
![image](https://github.com/gw2efficiency/issues/assets/2665937/b7e86977-bca6-4583-9f3d-5e1d7b49300a)

**Comment by malikoth** [comment]
Start at Necropolis Waypoint in Vabbi
![image](https://github.com/gw2efficiency/issues/assets/2665937/b4bbf081-c653-46b4-a843-c1fea0de52f9)

**Comment by malikoth** [comment]
Start at Amnoon Waypoint in Crystal Oasis
![image](https://github.com/gw2efficiency/issues/assets/2665937/0e7a1542-003b-4a3e-86ae-74ac590123ef)

**Comment by malikoth** [comment]
Start at Temple of Kormir Waypoint in Crystal Oasis
![image](https://github.com/gw2efficiency/issues/assets/2665937/f6de694d-36d3-414f-b701-2ae4c5aa0024)

**Comment by malikoth** [comment]
@queicherius This issue has been open nearly a year and a half, and I would like to gently encourage you to add these maps, and close the issue. As it is today, I can't use the "Gathering - Permanent Nodes" feature you implemented because it doesn't have half the nodes I care about. I would really love to be able to use your site for my gathering tracking needs!

**Comment by Ecmelt** [comment]
Gathering page is updated.
