### ISSUE TITLE
Add memories of battle cost to Mist Pearl / Mist-Enhanced Mithril

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1560]
https://www.reddit.com/r/gw2efficiency/comments/sz22om/crafting_recipe_for_conflux_missing_memories_of/

**Comment by holoxx** [comment]
IIRC last time this came up (#1528?) your suggestion was not to add items with multiple costs due to it being misleading to have them in the list but with "wrong" costs

**Comment by queicherius** [comment]
Hm, you're right.

I think I changed my stance a bit. If it's a mix between account bound and "tradeable/vendorable" items, we should probably put in the gold items instead of nothing, just so the cost is represented more accurately.

**Comment by holoxx** [comment]
Then also with those here (https://github.com/gw2efficiency/recipe-calculation/blob/9128937003322f554516f41bff7b87729bdedf7d/src/static/vendorItems.js#L133) instead of the tickets take the cost of the memories?

**Comment by queicherius** [comment]
Probably, yeah
