### ISSUE TITLE
Statistic Suggestion: Community Chest

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#1564]
With more "meme"-like statistics such as Broken Spoons, then I do think it would be cool to have an account statistic for [Community Chests](https://wiki.guildwars2.com/wiki/Community_Chest) since they are an example of players that are frequenting and participating in giveaways and events hosted by ArenaNet Partners.

**Comment by queicherius** [comment]
I don't plan to add those, because I don't want to incentivise not opening them over getting the (fairly exclusive) skins, and I dont want to incentivise "hoarding" them instead of giving them away.
