### ISSUE TITLE
Cette clé API n'est pas valide, contient des données API corrompues ou l'API est inaccessible. Erreur signalée par l'API : " "

### ISSUE THREAD

**Issue by triton77** [gw2efficiency/issues#1565]
Foooo, quelque chose s'est mal passé
Notre expert Quaggans à été prévenu du problème et est en train de trouver une solution
Si vous les voyez, faites leur savoir ceci :
Tm90Rm91bmRFcnJvcjogRmFpbGVkIHRvIGV4ZWN1dGUgJ3JlbW92ZUNoaWxkJyBvbiAnTm9kZSc6IFRoZSBub2RlIHRvIGJlIHJlbW92ZWQgaXMgbm90IGEgY2hpbGQgb2YgdGhpcyBub2RlLgogICAgaW4gbgogICAgaW4gYnV0dG9uCiAgICBpbiBVbmtub3duCiAgICBpbiBkaXYKICAgIGluIGRpdgogICAgaW4gdQogICAgaW4gdAogICAgaW4gbgogICAgaW4gZGl2CiAgICBpbiBkaXYKICAgIGluIHgKICAgIGluIHQKICAgIGluIG4KICAgIGluIHMKICAgIGluIGRpdgogICAgaW4gdAogICAgaW4gbAogICAgaW4gcw ==

**Comment by triton77** [comment]
{
  "response": {
    "type": "default",
    "status": 503,
    "ok": false,
    "statusText": "",
    "headers": {
      "map": {
        "content-length": "164",
        "content-type": "text/html; charset=utf-8"
      }
    },
    "url": "https://api.guildwars2.com/v2/account/bank?v=2021-07-24T00%3A00%3A00Z&access_token=AF328CD6-8D8B-D749-BD84-4F6A6C31DC95FB19AC68-5377-4169-BE42-5C73D9C23C3F",
    "_bodyInit": {},
    "_bodyBlob": {},
    "bodyUsed": true
  }
}

**Comment by queicherius** [comment]
The API was offline, as per the banner.
