### ISSUE TITLE
End of Dragons Content Update

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1566]
- [x] Update item updater to handle new item categories
  - [x] Qux = Power Core
  - [x] Quux = Sensory Array
  - [x] ??? = Service Chip
  - [x] Needs another update once API fix is out -> https://github.com/gw2efficiency/issues/issues/1611
- [x] https://github.com/gw2efficiency/issues/issues/1574
- [x] EoD Mastery Points filter
- [x] Dyes: Update the dye preview images
- [x] Update list of legendaries
- [x] Remove ascended value from ascended fish
- [x] Wallet currencies
- [x] Home instance nodes
- [x] https://github.com/gw2efficiency/issues/issues/1573 update gemstore values
- [x] Remove dungeon potions from the dungeon vendors
- [x] Update Currencies -> Dungeons to new dungeon currency
- [x] Statistics: Prophet crystals recoloring (all previous are blue?)
- [x] Update statistics for new dungeon currency
- [x] https://github.com/gw2efficiency/issues/issues/1597
- [x] Add EoD mastery filter to https://gw2efficiency.com/account/unlock-statistics
- [x] Update raid statistics to use the new wallet currency

**Comment by Aguileitus** [comment]
Is it possible to add somewhere what is the cheapest option to get Research Notes? https://wiki.guildwars2.com/wiki/Research_Note

**Comment by freohr** [comment]
Can you add the EOD specific dailies to the Daily Tracker as well?

**Comment by queicherius** [comment]
> Is it possible to add somewhere what is the cheapest option to get Research Notes? [wiki.guildwars2.com/wiki/Research_Note](https://wiki.guildwars2.com/wiki/Research_Note)

I'll think about it, but that might need more research first on droprates

**Comment by queicherius** [comment]
> Can you add the EOD specific dailies to the Daily Tracker as well?

Which ones are those?

**Comment by freohr** [comment]
> > Can you add the EOD specific dailies to the Daily Tracker as well?
> 
> Which ones are those?

Those dailies: https://wiki.guildwars2.com/wiki/Daily_End_of_Dragons

**Comment by queicherius** [comment]
> > > Can you add the EOD specific dailies to the Daily Tracker as well?
> > 
> > 
> > Which ones are those?
> 
> Those dailies: [wiki.guildwars2.com/wiki/Daily_End_of_Dragons](https://wiki.guildwars2.com/wiki/Daily_End_of_Dragons) Edit: I don't know how they are displayed/notified in the GW2 API

Ah it looks like they might be missing in the API, because they should automatically show up

**Comment by nicodemus4802** [comment]
The **Story Journal** (Account > Characters > Story Journal) ends with The Icebrood Saga. Could you add the End of Dragons section?

**Comment by SOL4RIS** [comment]
Hi there! Wondering if you can update the the Account Overview page by adding "Fishing" to the "Sub-Type" list for Gathering items, which would ideally show any lures, poles, and bait items. Thanks in advance!

![image](https://user-images.githubusercontent.com/79487317/157779434-551064a1-a828-4d0e-9385-2bc94dd57130.png)

**Comment by queicherius** [comment]
> Hi there! Wondering if you can update the the Account Overview page by adding "Fishing" to the "Sub-Type" list for Gathering items, which would ideally show any lures, poles, and bait items. Thanks in advance!

Yep this is definitely coming at some point - right now those types are broken in the API so waiting for the fix there.

**Comment by queicherius** [comment]
> The **Story Journal** (Account > Characters > Story Journal) ends with The Icebrood Saga. Could you add the End of Dragons section?

Good point, thats on the list 👍

**Comment by holoxx** [comment]
Can we do a fishing overview page? Which pulls the missing fish for the different collections and then allows to filter by Time of Day and Bait.
Like "it's currently nighttime and I still have plenty of Shrimplings but no Mackerel, where can I go to progress my collections?"

**Comment by Genderdruid** [comment]
would it be possible to get the new EoD Hero's Choice chests for the metas added to the dailies page? I have them added manaually for now but it would be nice to have them automatic like the HoT and PoF ones

**Comment by queicherius** [comment]
> would it be possible to get the new EoD Hero's Choice chests for the metas added to the dailies page? I have them added manaually for now but it would be nice to have them automatic like the HoT and PoF ones

This is not in the API, so currently not possible :(

**Comment by WolfSabian** [comment]
Posting it here cause i think it's best spot.

It's currently possible to search your account for any and all Jade bot cores or sensory upgrades that are not equipped.
Is it possible to see the ones equipped on characters? If so how?

**Comment by queicherius** [comment]
> It's currently possible to search your account for any and all Jade bot cores or sensory upgrades that are not equipped. Don't see an option to search for Service chips though. Is it possible to see the Jade bot cores/arrays/chips equipped on characters? If so how?

Service chips in the API currently have either the same type as cores/upgrades or no type at all (I cant remember which it was).  -> https://github.com/gw2-api/issues/issues/34

There's no way to see equipped components, that data is not in the API :( -> https://github.com/gw2-api/issues/issues/39

**Comment by WolfSabian** [comment]
> > It's currently possible to search your account for any and all Jade bot cores or sensory upgrades that are not equipped. Don't see an option to search for Service chips though. Is it possible to see the Jade bot cores/arrays/chips equipped on characters? If so how?
> 
> Service chips in the API currently have either the same type as cores/upgrades or no type at all (I cant remember which it was).   https://github.com/gw2-api/issues/issues/34
> 
> There's no way to see equipped components, that data is not in the API :(  https://github.com/gw2-api/issues/issues/39

Unfortunate, and what I thought. Thanks for the info. Hopefully they fix this.

**Comment by queicherius** [comment]
Done, API blocked tasks here: https://github.com/gw2efficiency/issues/issues/1611
