### ISSUE TITLE
Crafting Calculator - Provide capability to add raw crafting components as item

### ISSUE THREAD

**Issue by bsinkk** [gw2efficiency/issues#1567]
R/R ability to add raw crafting components to the Crafting Calculator (CC) as you would for adding additional items. This capability would provide a means to rough out a recipe that had not yet been added to the calculator.

As example: Not yet having the recipe for "Scavenger Protocol: Might Trophies", one could use the calculator to determine an estimated cost of crafting by adding items for:
1 Superior Sigil of Luck - CC known item/recipe
1 Ancient Bone - Capable only if this enhancement made
4 Orichalcum Filigree - CC known Item/recipe
(Piece of Dragon Jade recipe not known, although the item is avail via other recipe currently. [Jade Tech Axe])
4 Chunk of Pure Jade - Capable only if this enhancement made and priority to update item lists made otherwise, best guess at cost
30 Loaf of Bread (alternate for Research Notes)
2 Glob of Ectoplasm - CC known item
5 Orichalcum Ingot - CC known Item/recipe

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
