### ISSUE TITLE
When using "use own materials", owned mats should be valued at sell value -tax.

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1568]
One of the biggest benefits of "use own materials" is that you can make a shopping list based on your current hoard, but currently it naively values owned items at sell price, encouraging you to buy intermediate items if it costs more to buy the base materials. But, if you _already have_ those items, and crafting it costs less than buying it and selling the base materials, it should go for the option of crafting the item instead.

Scenario: You want to build fancy stick. it costs 10g to buy the materials. it costs 9g to buy it outright. If you have the materials already, crafting it technically loses 1g value, but you can only get 8.5g if you sold the mats, losing 1.5g to buy the item outright and selling the mats you already have. So, optimally, it should advise crafting the item with materials owned, but buying outright if you don't have the parts. If you have part of the required materials, it should calculate the 'crafting cost' of [owned mats value*0.85]+[unowned mats value] before determining which is optimal.

**Comment by queicherius** [comment]
> Currently it naively values owned items at sell price, encouraging you to buy intermediate items if it costs more to buy the base materials. But, if you already have those items, and crafting it costs less than buying it and selling the base materials, it should go for the option of crafting the item instead.

This is not how it currently works, no. Right now it walks through the tree top to bottom, then reduces the amount of items required by the amount you own, and then calculates the cheapest tree based on that. This means it actually values your owned items at "0".

> So, optimally, it should advise crafting the item with materials owned, but buying outright if you don't have the parts.

It does that (actually somewhat too eagerly, see #1479). If you didn't see that behaviour the most likely explanations are that the materials were used higher up in the tree or that the API didn't report your materials correctly.
