### ISSUE TITLE
Add Filters / sort criteria to recipe overview

### ISSUE THREAD

**Issue by Fulgeri** [gw2efficiency/issues#157]
The item Overview page is coming along well, but filtering and sorting abilities would be nice. I don't like how the items are sorted by total net profit - I would like the ability to filter or at least see a %ROI column.

**Comment by queicherius** [comment]
Is this for the recipe overview? If yes, that's a good point.

**Comment by Scath-Enfys** [comment]
@queicherius yes that is what I meant. Updated title.

**Comment by queicherius** [comment]
More possible filters:

- Recipe unlocked?
- Type (e.g. Weapon, Miniature, ...)

**Comment by Scath-Enfys** [comment]
Indeed. There are a whole variety of filters that could be added, I just 
wanted to throw the essentials for profit-crafting out there. Right now 
I'm stuck using Mystic's site, and it updates slower than gw2e.

**Comment by TehOwn** [comment]
Crafting level would also be a great filter for players leveling their professions.

**Comment by queicherius** [comment]
This is now live. It does not have all of the here suggested funtionality, but it's miles better than the previous page.
