### ISSUE TITLE
Jade Bot Power Cores do not show up in crafting calculator

### ISSUE THREAD

**Issue by sttelv** [gw2efficiency/issues#1571]
Jade Bot Power Cores (example https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-96613) do not show up in the crafting calculator. The link to GW2E in the wiki info box opens a blank crafting calculator, and the power cores can't be searched for manually in the crafting calculator.

**Comment by queicherius** [comment]
Yes, gw2e currently doesnt support recipes that have wallet currencies as part of their requirements.

Tracked in #1566
