### ISSUE TITLE
Missing mount values

### ISSUE THREAD

**Issue by nrone** [gw2efficiency/issues#1573]
Hi.

Seems like the mounts in the recent mount adoption licenses (from the sale) has no values.
Eg. Exalted Way Seeker, Exo-Suit Warclaw, Sunrise Macaw etc.

Not sure if you are aware, but wanted to let you know.

https://wiki.guildwars2.com/wiki/Deep_Wilds_Mount_Adoption_License
https://wiki.guildwars2.com/wiki/Lost_Era_Mount_Adoption_License

**Comment by queicherius** [comment]
Deployed ~2 months ago, forgot to close this
