### ISSUE TITLE
Achievement Page Sub-categories in Chinese

### ISSUE THREAD

**Issue by Kahlya** [gw2efficiency/issues#1575]
Going to the achievement page and expanding some of the categories, I noticed that all the subcategories (except daily) list the names in Chinese. The entire rest of the site, including achievement categories and individual achievements, is displayed in English. I have never changed anything related to GW2 into Chinese, so this probably isn't caused by a setting I changed.

![image](https://user-images.githubusercontent.com/102258842/159792505-0852c585-5134-45ee-acf3-72d97c71456b.png)

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
