### ISSUE TITLE
Add Death Branded Shatterer to the World Bosses

### ISSUE THREAD

**Issue by Chely3ppe2** [gw2efficiency/issues#1577]
PVE Core Tyria Dailies are showed for the next day not the current ones. Also can you add DBS to the world boss tab, please!

**Comment by queicherius** [comment]
The dailies are currently broken in the API. I'm not sure what you mean with DBS?

**Comment by Chely3ppe2** [comment]
> The dailies are currently broken in the API. I'm not sure what you mean with DBS?

Is it possible to add Death Branded Shatterer to the World Bosses tab?

**Comment by queicherius** [comment]
Not automatically tracked in the API, so not going to do this for now.
