### ISSUE TITLE
Fix recipes

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#158]
- Remove recipe for grand weapon crate ([Ref](https://www.reddit.com/r/gw2efficiency/comments/4nnc4u/value_of_grand_weapon_crate/))
- Remove chest of insignia / loyality values

**Comment by Scath-Enfys** [comment]
For those too lazy to click the link: "The value of the Grand Weapon Crate [&AgGOBgEA] seems to be wrong. It is shown as around 1900 gold which seems to be about the cost it takes to craft all the ascended armors to get the achievement Ascended Accoutrement. But you can only get one weapon out of it, so it would seem more logical to use the value of the actual contents, wouldnt't it?"

**Comment by Scath-Enfys** [comment]
I would simply set a manual value rather than removing the recipe. That's the best of both worlds.

**Comment by queicherius** [comment]
> I would simply set a manual value rather than removing the recipe. That's the best of both worlds.

I tend to remove "recipes" that only consist of achievements, since they don't give any useful information the crafting calculator (imo), and even can generate wrong recipes (it was the case before with the "Gift of Ascension" and some others).
