### ISSUE TITLE
Partial Completion of "Aurora II: Awakening" does not compute correctly in the crafting calculator

### ISSUE THREAD

**Issue by Lego6245** [gw2efficiency/issues#1582]
1) Have partial completion of Aurora II: Awakening" on the account
2) Look up crafting calculator for Aurora with "Use own materials" checked

Expected: The amount of Xunlai Ingots required should be 21 - however many steps of Aurora II: Awakening are completed. "Owned" steps should count towards the total as expected. If the account is in possession of less than 21 ingots, they should not need to craft any more.

Actual: While the completed steps show up as "owned", the crafting calculator still calculates as requiring all 21 ingots, with the material amounts to match. Crafting steps suggest to craft the "missing" ingots, despite the steps being done.

![image](https://user-images.githubusercontent.com/1329165/161127998-9903386a-e94e-40fe-bffa-3c3c41f8a042.png)
![image](https://user-images.githubusercontent.com/1329165/161128073-0c0b9ffc-5bcd-49da-a87a-6f0f25afeb98.png)

**Comment by queicherius** [comment]
Hm, weird. Was it using the `13-9 = 4` extra ingots for anything else in the recipe by any chance?

**Comment by Lego6245** [comment]
Nope, not that I could tell. It was just crafting them for no clear reason.

**Comment by queicherius** [comment]
Could not reproduce this during my testing, if anyone else has the same issue let me know.
