### ISSUE TITLE
[Request] Add Newborn Siege Turtle Hatchling under "Home Cats"

### ISSUE THREAD

**Issue by whowantblood** [gw2efficiency/issues#1585]
Once completed the associated achievement of "A Strange Diet" (completed by feeding 11 legendary fish to a hatchling) you can a Newborn Siege Turtle Hatchling into your home instance just like the kitty scavenger hunt. Its non-interactable just nice aesthetics to the instance so I wouldn't classify it as a node. 

Logically speaking i guess it wouldn't appear in the API the same way, but i guess you could run a check against the achievement number to see if its been completed.

**Comment by queicherius** [comment]
Not going to add this, since it's not a cat.

Completion of the hatchling can be tracked with the achievement: https://gw2efficiency.com/account/achievements?filter.search=a%20strange%20diet (which cats cant)
