### ISSUE TITLE
Mist Walker Achievement wiki link is a link to the effect, not the achievement. 

### ISSUE THREAD

**Issue by FeniulaPyra** [gw2efficiency/issues#1587]
On the [stats page](https://gw2efficiency.com/account/unlock-statistics), clicking the wiki link for the Mist Walker achievement 
![image](https://user-images.githubusercontent.com/17858037/165005166-c0779745-ee26-476b-aee1-64a25b90352f.png)
brings the user to this link:
https://wiki.guildwars2.com/wiki/Mist_Walker
rather than (what I think is supposed to be) this link:
https://wiki.guildwars2.com/wiki/PvP_Conqueror#achievement254

**Comment by queicherius** [comment]
The wiki links just search by name, so whatever the wiki resolves the search to is shown:

https://wiki.guildwars2.com/index.php?title=Special%3ASearch&search=Mist%20Walker&go=Go&ns0=1

I am not sure if implementing anything extra on our end would be worth the effort

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
