### ISSUE TITLE
Add alternate crafting for Chunk of Ancient Ambergris

### ISSUE THREAD

**Issue by AMessiah** [gw2efficiency/issues#1589]
The item Chunk of Ancient Ambergris, used for legendary crafting, has an alternate way of "crafting" (5 per day) costing 10 Flawless Fish Fillet each, see [wiki](https://wiki.guildwars2.com/wiki/Chunk_of_Ancient_Ambergris)

Suggestion is just to add this vendor option into the crafting calculator

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

Reason: Confusion of an extra "timegated" craft that is also gated behind an achievement
