### ISSUE TITLE
Missing max Storage expander saving

### ISSUE THREAD

**Issue by JampireX** [gw2efficiency/issues#1590]
On the page https://gw2efficiency.com/account/gemstore-upgrades I see 8 Storage Expanders. My account have 9 of them purchased directly for gems. Maybe there is an error here?

**upd. It's only appearing 8 if material storage currently don't have stacks over 2250 and it's changing to 9 otherwise. looks like site does not save max detected amount so it's likely works in all cases**

**Comment by queicherius** [comment]
Yes, the API does not report how many you have bought - we just make an educated guess based on your current material storage. This is intended, storing the previous max value individually for each account is not feasible for crawling in a performant way.
