### ISSUE TITLE
Ability to search for Glyphs of [Gathering type] that are on Characters tools 

### ISSUE THREAD

**Issue by ReportAnIssue** [gw2efficiency/issues#1592]
Unless I have missed something already available, I am unable to search for Glyphs that are equipped on any of my characters. Would really appreciate the ability to search which characters have what glyphs. Thanks Very Much.

**Comment by queicherius** [comment]
This is currently not possible, because the API does not return this data

See https://github.com/gw2-api/issues/issues/11
