### ISSUE TITLE
Old Description on Prophet Shards/Crystals

### ISSUE THREAD

**Issue by IceQuote** [gw2efficiency/issues#1595]
![image](https://user-images.githubusercontent.com/106877458/172008604-7b23ce11-62ca-407d-9a75-40c95c870523.png)
After the EOD-Update, Prophet Shards/Crystals were changed and red Prophet Shards/Crystals removed from the game. 
On the website, they are, however still shown as they were months ago.

**Comment by queicherius** [comment]
We're just displaying the currencies the API gives us on that page, and there the prophet shards/crystals are still the old versions: https://api.guildwars2.com/v2/currencies?ids=52,53,57

It would be great if you could file an issue with the API: https://github.com/gw2-api/issues/issues
