### ISSUE TITLE
The crafting calculator for Gen 3 legendaries does not seem to recognise if you have the precursor in your inventory

### ISSUE THREAD

**Issue by Jong1** [gw2efficiency/issues#1596]
Tested here on Aurene's Argument.
Interestingly, when I look in the bank the value of Dragon's Argument is struck through. Have no idea what this means!

**Comment by queicherius** [comment]
Hm, that's weird. Do you happen to still be in this state, and if yes could you email your API key to `support@gw2efficiency.com`?

> Interestingly, when I look in the bank the value of Dragon's Argument is struck through. Have no idea what this means!

It means the price it shows does not apply to your current filter - by default this means the sell price does not apply, because it's account or character bound.

**Comment by Jong1** [comment]
Hmm, seems fine now, thanks. Maybe some weird glitch or maybe a timing issue?? I had only very recently acquired the precursor but it was showing in my bank yet not in the calculator. Or maybe **_I_** glitched??? :D

**Comment by queicherius** [comment]
Oh if it was very recent its possible there was a caching issue at play.

Glad it hear it's working now 👍
