### ISSUE TITLE
[Bug] Lottery page last drawings list is scrambled (at the top)

### ISSUE THREAD

**Issue by ProfBits** [gw2efficiency/issues#1599]
The list of last drawings has the first entry (lates drawing) sramble with the header row at least or event more.

Using Firefox 101.0.1, 1440p, Darkmode.

![grafik](https://user-images.githubusercontent.com/53108880/173426869-f9bdeeb0-9d9f-4edd-9fb5-62bdaae504fc.png)

**Comment by queicherius** [comment]
It looks like your page zoom is set to a value below 100% which we don't support:

![image](https://user-images.githubusercontent.com/4615516/173432619-f942a2cc-a381-4d05-be0d-acf549fd14dc.png)
