### ISSUE TITLE
Missing value inheritance

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1601]
- [ ] All stat versions of Jormag/Primordius Left/Right Eye Infusion should be valued at price of the craftable version
- [ ] All stat versions of Echo of the Dragonvoid should be valued at price of the Glob of Dragonvoid Aether
- [ ] All stat versions of Mote of Darkness should be valued at price of the Lingering Darkness

**Comment by Linkaaaaa** [comment]
Question regarind Mote of Darkness, it can be purchased off the fractal merchant for 250 ectos and 50 integrated fractal matrices:
https://wiki.guildwars2.com/index.php?title=Scavenged_Lingering_Darkness

Which is quite less than the 2.2k gold on the trading post for Lingering Darkness. Wouldn't merchant value be a better fit to prevent account value inflation?

The same can be said about the Imperial Everbloom, Clockwork and Jotun costing 100 ectos, if not, these last 3 should be valued base off:

- https://wiki.guildwars2.com/wiki/Imperial_Everbloom_Sprout
- https://wiki.guildwars2.com/wiki/Ever-Spinning_Clockwork
- https://wiki.guildwars2.com/wiki/Vial_of_Cosmic_Energies

**Comment by Ecmelt** [comment]
Merchant values are mostly based on group/squad play time and achievements, not gold.

**Comment by Linkaaaaa** [comment]
What do you mean merchant values are based on playtime and not gold? 
If you set the Mote of Darkness to the value of Lingering Darkness on the trading post, I could do this and inflate my account value by 48k gold with just 4750 ectos spent
![6746](https://github.com/gw2efficiency/issues/assets/23245218/7541919c-1c93-41ee-ad4b-398691a65f8e)

The value of the ectos spent is 1305g30s vs 48000 of the trading post value

**Comment by queicherius** [comment]
We've been handling this consistently for multiple years: If there is a "skill" / "time" based way to acquire an account-bound version of a pricy tradable RNG item, the account-bound version has the same price as the RNG item. This is the case for Kaiser Snake Weapons and Hatched Chili Pepper Home Instance Nodes for example.

The reason for this is our definition of [account value](https://github.com/gw2efficiency/issues/blob/master/docs/account-value.md#account-value): 

> **The value of an account should represent how much money/effort a new player would need to replicate that account.**

In this case, a new player would have to complete 2000 challenge mote fractals -- so the "effort" is represented in the monetary value equivalent of the tradable version of the infusion.

And realistically, I dont think many people would use this to inflate their value, since you can also convert the currency into _real_ gold via celestial infusions.

**Comment by Linkaaaaa** [comment]
How would you convert the currency into real gold through celestial infusions? You can only buy the red version which is account bound.

Anyway, if you guys are fine with the possibility of people complaining that is "not fair" that some can spend 100 ectos to get an everbloom and be valued at about 4.8k gold, then go ahead, just wanted to open the discussion :D. I know of people that have bought 8+ to stack them, which would be a 38.4k value jump.

**Comment by TeplarGw2** [comment]
There's no way to buy celestial infusions, I think queicherius was mistaken.

I see no reason for them to make and modifications because others may possibly have complaints about this. If such people exist, they should be making reasonable arguments as to why and what the alternative should be. Gw2efficency staff can evaluate those arguments and decide on them from there.

Personally, it seems more reasonable that account bound infusions take their value from the trading post.
