### ISSUE TITLE
Update crafting recipes to use new dungeon/raid currencies

### ISSUE THREAD

**Issue by andrew-welch** [gw2efficiency/issues#1603]
As per the game update on [2022-06-07](https://wiki.guildwars2.com/wiki/Game_updates/2022-06-07), Tale of Dungeon Delving replaced all dungeon currency. 

On the crafting utility, for example creating [the Bifrost](https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-30698) the Gift of Zhaitan is represented by its cost in the Arah currency.

Change would be needed to have dungeon items reflected in cost of Tale of Dungeon Delving. I presume there may be some optimisation then available for currency tracking.

**Comment by queicherius** [comment]
Deployed today, should be updated in a few hours
