### ISSUE TITLE
Add Taro Everclaw's "Fish of the Day" to dailies

### ISSUE THREAD

**Issue by Void2258** [gw2efficiency/issues#1606]
For some reason this is not listed in the dailies tab in game, forcing you to either wiki or go to arborstone to find out what it is. As this is often a major goal to aim for with daily fishing, having it easily accessible and listed with other dailies would be very useful (It not being in the tab in-game is yet another way fishing lacks integration with nearly anything else in the game).

**Comment by whowantblood** [comment]
Also to add onto the daily tab, the 4 EoD hero choice chests too =]

**Comment by missymessa** [comment]
I don't think this value is in the API, which means it wouldn't automatically track, so you'd still have to log in and go to Arborstone to see what the fish of the day is. (Although, I agree that it would be useful to have, but only if what the fish is is available via the API)

**Comment by queicherius** [comment]
Hero choice chests: #1622 

The fish that Taro wants is not in the API, and does not seem to follow any pattern. If you'd like to be reminded to go to the NPC and fish, you can add a custom daily for that :)
