### ISSUE TITLE
Please add End of Dragons Masteries to Unlock Statistics

### ISSUE THREAD

**Issue by JammieDodgerr** [gw2efficiency/issues#1609]
Please could you add End of Dragons to the Masteries drop down on the Unlock Statistics page?

This page is super useful for seeing which easy masteries you dont have unlocked, would be nice to be able to use it for EoD.

![image](https://user-images.githubusercontent.com/60801006/180094537-7c346b22-6e5e-44bf-a585-58c303a43ca6.png)

Thanks!

**Comment by queicherius** [comment]
Part of #1566 👍
