### ISSUE TITLE
Detect bought but not collected mats from the traiding post in the crafting calculator

### ISSUE THREAD

**Issue by alea8170** [gw2efficiency/issues#1610]
There is a very neat shopping list in the crafting calculator. I have in my specific case the following shopping list.
![grafik](https://user-images.githubusercontent.com/45290990/180783090-cc9ff842-2bdb-4828-99cd-14166d7ebf45.png)

As a normal behavior I have placed some orders of my items in the traiding post (for example for the 86 Ancient Blood). These items were sold to me and my orders were successful.
You can see my delivery box there.
![grafik](https://user-images.githubusercontent.com/45290990/180783536-f9e353e7-1709-409a-9600-34de185544ea.png)

Unfortunatly, the crafting calculator does not recognize these items as owned, because I dont have the collected yet.

It would be nice, if the crafting calculator could detect those bought and delivered items as owned.

If you would add a traiding post query to the calculator, you could also detect the items that someone has listed to sale and would be used for crafting. So a new location "listed in the traiding post" at the owned materials could be useful too.

**Comment by queicherius** [comment]
The reason that's not on by default is that a non-0 percentage of people uses the delivery box as an extended storage with thousands of items, which makes that page load forever or eventually crash. There's a ticket for "pick and choose where the items are" tho: #230
