### ISSUE TITLE
Cleanup API issues after End of Dragons expansion

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1611]
- [x] #1731
	- https://github.com/gw2-api/issues/issues/30
- [ ] #1687
	- https://github.com/gw2-api/issues/issues/44
- [ ] #1712
	- https://github.com/gw2-api/issues/issues/39

**Comment by lambada** [comment]
FYI The following slots now show up under a characters equipemnt in the API

```
    FishingRod,
    FishingBait,
    FishingLure,
    PowerCore,
    SensoryArray,
    ServiceChip,
    Relic,
```

Think that unblocks the fourth checkbox here :)

**Comment by darthmaim** [comment]
Hey @queicherius, just letting you know that all the underlying issues are now fixed. Masteries and quests are now in the API

**Comment by queicherius** [comment]
Closing, see linked tickets for progress
