### ISSUE TITLE
Add "Ignore 0% unlocked" checkbox on unlock statistics to hide 0% unlocked items

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1615]
Currently there are a lot of things, mainly achievements (65~ pages) with 0 of ... (0%) "unlocked by playerbase". Most of these achievements are dailies, weeklies or things that for some reason are unobtainable/not counting (maybe because of the API I guess). 
I think it would be a good idea to add a "Ignore 0% unlocked" checkbox (or with other name, I'm bad at names) to hide all these items that have not been unlocked (0% unlocked) by any player (similar to the "Ignore without value" checkbox".

**Comment by queicherius** [comment]
I think this would be largely covered by #1510 & #1514

**Comment by Aguileitus** [comment]
#1510 I don't think so, since there are a lot of 0AP achievements that have been completed by a lot of players, for example:
![image](https://user-images.githubusercontent.com/14335637/181937153-afb8ba6b-ec17-4820-929a-63341f2d497d.png)

#1514 is a good candidate but it might not cover all cases because there are also weekly achievements and other things (like the Character Adventure Guide/historical/fractals ones or another things that are not achievements like finishers/recipes/skins/titles) that shows 0% unlocked.

The reason behind my idea is to hide everything that is "unobtainable" or that has not been "obtained" yet by any player.

**Comment by queicherius** [comment]
Deployed
