### ISSUE TITLE
Update gold price for Mystic Runestone

### ISSUE THREAD

**Issue by Inurosen** [gw2efficiency/issues#1619]
Currently calculator shows that Mystic Runestones are not sold, but they actually are sold for 1 gold each. It's very misleading when calculating the Aurene legendaries price.
https://wiki.guildwars2.com/wiki/Mystic_Runestone

**Comment by queicherius** [comment]
We're currently experimenting with better support for merchant-sold items and those ones are clearly not working as intended. We're looking into it! :)

**Comment by queicherius** [comment]
Fixed
