### ISSUE TITLE
open in new (named target) page for items on crafting tree

### ISSUE THREAD

**Issue by daniel-pittman** [gw2efficiency/issues#162]
It would be great to be able to click directly from an item in the crafting tree (eg: "Dragonite Ingot") to the wiki page for it -- that helps when, eg, I want to chase down where to source a recipe I don't know from, or find out more about the item.

Opening in a new page (aka tab) would be ideal because it's very rare that I want to leave the crafting tree for this, but rather, learn more about something as I work through crafting.

**Comment by queicherius** [comment]
Tracked time: 5m
