### ISSUE TITLE
 Dragonstorm Daily Doesn't Mark as Completed

### ISSUE THREAD

**Issue by ix22** [gw2efficiency/issues#1621]
When doing dailies, each world boss marks as green once you've got it.  Dragonstrom doesn't.  I even did it 2x today just to make sure, it doesn't turn green.  Even after other bosses turned green, Dragonstorm remained unchecked and grey.

**Comment by queicherius** [comment]
All dailies that don't have "Auto" below their checkbox have to be manually checked off, since the API does not provide completion information.
