### ISSUE TITLE
Miyani items no longer listed on Shopping List

### ISSUE THREAD

**Issue by Falgar** [gw2efficiency/issues#1623]
Items purchased from Miyani (or other mystic forge attendant NPCs) are no longer listed in the Shopping list. Instead they're listed as some quantity of coins or spirit shards and then in the crafting steps, you are told to convert them into the desired item with the discipline of "Merchant".  The previous behavior was much easier to understand and had the further benefit of having the mouse-over identity and location of the merchant.

**Comment by queicherius** [comment]
This is part of #1593, we're currently testing full merchant support (vs what we had before, which was a small handpicked set of hard-coded items).
