### ISSUE TITLE
Grammar: amount -> number

### ISSUE THREAD

**Issue by asmaloney** [gw2efficiency/issues#1626]
In the crafting calculator:

![Screen Shot 2022-08-30 at 14 31 20](https://user-images.githubusercontent.com/391371/187516529-75200543-9852-4334-b039-312950f4c653.png)

"Amount" should be "Number".

Number is used for "countable" things.

**Comment by Stateless777** [comment]
Isn’t that box to change how many items you want to craft? I feel like “Amount” is correct in this use. Number would be more for listing items out, not quantity.

**Comment by asmaloney** [comment]
Nope. It's the "number of items" to craft, not "amount of items" to craft. The items are discrete - i.e. countable. If it was... e.g. water then it would be "amount" (and it wouldn't be an integer - it would be a decimal).

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

**Comment by asmaloney** [comment]
No problem - I didn't think a one-word fix was that much trouble.
