### ISSUE TITLE
Certificate of Heroics

### ISSUE THREAD

**Issue by sascha-dev** [gw2efficiency/issues#1629]
The "Certificate of Heroics" can be paid with "Testimony of Desert Heroics" or "Proof of Heroics".
Even if I have zero Proof of Heroics and enough Testimony of Desert Heroics the recipe does not switch to the Testimony of Desert Heroics.

Is it possible to include both recipies or give a hint that the item has two possibilities to buy?

**Comment by queicherius** [comment]
Switching recipes is not possible with the calculators current architecture. A hint that it has two possibilities to buy might be doable tho, so I'll leave this open.

**Comment by queicherius** [comment]
@Ecmelt Maybe we save how many recipes an item has and show a little 🔀 symbol if its > 1?
