### ISSUE TITLE
Completed items should disappear from the crafting steps

### ISSUE THREAD

**Issue by slippycheeze** [gw2efficiency/issues#163]
When updating the crafting path and own materials, when something is completed (eg: 10 orichalcum settings crafted and in bank) it shows "craft 0 orichalcum settings", but doesn't remove the item from the list.

Having them vanish would show progress more effectively and, since reloading the page forgets settings like "use own mats", be more efficient at keeping the list clean for seeing what remains on a long craft tree like, say, "Mawdrey" from scratch -- which might take weeks to complete, or more.

**Comment by queicherius** [comment]
That's a strange behaviour. I'll look into it.

**Comment by daniel-pittman** [comment]
obScreenshot showing what I mean, just in case it wasn't clear enough:
![craft zero things](https://cloud.githubusercontent.com/assets/306753/16289135/ccbaf7f6-38af-11e6-86f8-086cb5a4fe8b.PNG)

**Comment by Scath-Enfys** [comment]
I don't see this on my calculator. Perhaps it only applies to crafted ascended mats (Dragonite Bloodstone and Stars)?

**Comment by daniel-pittman** [comment]
I see it for the various "plant food" non-ascended things too, so no, it seems general for me.  Thanks for investigating, though!  I'll see if I can find any JS errors or whatever locally to understand what's going on, and update if I learn more.

**Comment by queicherius** [comment]
This seems to happen with all items if the "Update own materials & best path every minute" option is checked.

**Comment by Scath-Enfys** [comment]
@queicherius that would explain. The list is probably created only once, and lacks code to hide zero-d ingredients.

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
