### ISSUE TITLE
Daily Orr fisher

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1634]
again it not available, only 3\4 here.
![изображение](https://user-images.githubusercontent.com/1270117/190911000-4f898315-f031-4ba6-aa43-d5280f852c6a.png)

**Comment by Stateless777** [comment]
I noticed it missing too. It was also missing from the Account > Achievements panel too.

**Comment by queicherius** [comment]
If it doesnt show up in the achievements it's either missing from the API or flagged in a way that it'd not show up in-game if you have a level 80 character and all expansions. For the latter we have a ticket here #1162
