### ISSUE TITLE
Missing normal Blood Ruby Band

### ISSUE THREAD

**Issue by codesmith47** [gw2efficiency/issues#1637]
The crafting calc is missing the normal version of the Blood Ruby Band.
![image](https://user-images.githubusercontent.com/88629925/193426842-ba0eb0d8-1d91-4ba0-8afa-64c17774d995.png)

**Comment by queicherius** [comment]
The normal blood ruby band can only be bought directly, not crafted.

**Comment by codesmith47** [comment]
the same can be said for 

- Sparking Petrified Wood
- Icebrood Horn Backpack
- Black Ice Earring
- Jade Pendant
- Black Ice Band

but those show up in the crafting calculator [Crafting Accessories](https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-79830;1-79444;1-79745;1-80241;1-79712;1-71387)

**Comment by queicherius** [comment]
True, those show up because they are a part of the limited trial for merchant recipes #1593
