### ISSUE TITLE
typo on recipe page

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1638]
from: https://gw2efficiency.com/account/recipes
> This page only shows *recipes unlocked by recipe sheets*, and no recipes that only need to be discovered by crafting them once. Those discoveries are character-wide, and you can see them on your individual character pages instead.

A few small typos, and a wierd wording, Here's a proposed rewrite:
> This page only contains *recipes unlocked by consuming recipe sheets*. Recipes learned though *discovery* are done on a per-character basis, which can be seen on (individual character pages | <link to https://gw2efficiency.com/account/characters>) under "discovered recipes.

**Comment by queicherius** [comment]
There are no typos. I feel like the current wording is clear enough.
