### ISSUE TITLE
Revisit promotions and demotions in crafting calculator

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#164]
Right now, promotions are disabled in the calculator, because they generate giant crafting trees. Maybe there is some solution to this, like enabling the recipes but collapsing them by default.

**Comment by Scath-Enfys** [comment]
Considering the fact that all recipes are now collapsed by default, I see no issue with adding them back in. Perhaps as a "third" option though, since some promoted materials can also be crafted at a crafting station (e.g: Thin Leather Square)?

**Comment by queicherius** [comment]
> Considering the fact that all recipes are now collapsed by default, I see no issue with adding them back in

The issue is that they will be selected as the cheapest way to acquire things - and that's no the whole truth since they need spirit shards.

**Comment by Scath-Enfys** [comment]
From what it seems to me, we need to have a way to disable a selection of a particular option without disabling the recipe entirely. This would help with #155 as well (even though we "fixed" it by removing the recipe).

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that works that well, since it could cause the user to pay more spirit shards than they are willing, so I am going to close this issue.
