### ISSUE TITLE
German translation in gear tooltip for the stat "concentration" missing

### ISSUE THREAD

**Issue by sascha-dev** [gw2efficiency/issues#1644]
The tooltip for gear misses the translation for the stat "concentration" -> "Konzentration"
![grafik](https://user-images.githubusercontent.com/30441143/201117986-c1338e7c-e134-4f31-bb7f-f5a6bc274299.png)

**Comment by Orihkeks** [comment]
This is the Same for the state "expertise" what would be "Fachkenntnis"
