### ISSUE TITLE
Add Ecto salvage as a means of acquiring Crystaline Dust

### ISSUE THREAD

**Issue by Scath-Enfys** [gw2efficiency/issues#165]
http://gw2profits.com/basic_salvage.php

According to this site, it is usually cheaper to buy ecto and salvage with a mystic kit for dust than to buy dust. Using the average of 1.85 dust / ecto, could we add a recipe for dust here?

**Comment by queicherius** [comment]
While the option for this still exists and is profitable, I think it would be confusing for people to include this into the calculator. It's also hard to answer the question of "how much are the forge stones worth". Going to close this in an effort to clean up. :)
