### ISSUE TITLE
Add which raid is currently Emboldened to the raid page.

### ISSUE THREAD

**Issue by amackenzie** [gw2efficiency/issues#1650]
The raid summary page at https://gw2efficiency.com/dungeons?filter.type=raids could benefit a bit from an additional column showing which raid is Emboldened for the week. Would be nice for an at-a-glance summary of raid stuff!

**Comment by queicherius** [comment]
Not in the API, but TIL it's on a schedule so we could show it fairly easily.

https://wiki.guildwars2.com/wiki/Emboldened#Emboldened_Mode_schedule
