### ISSUE TITLE
API key persisted after logging out and creating a new account

### ISSUE THREAD

**Issue by swixfort** [gw2efficiency/issues#1651]
I recently logged into my account at a friends PC and logged out. When they created an account, my API key was instantly connected with their account.

**Comment by queicherius** [comment]
Interesting. I just looked at the way the logout works (I have not touched that in 6 years), and it's possible there's a race condition where the local keys dont get cleared when the logout is processed. Have not managed to reproduce it in my quick testing so far.

**Comment by swixfort** [comment]
I haven't been able so far as well. They do use Firefox, probably vanilla settings. I'll get back to this when I have reproduced so successfully.

**Comment by queicherius** [comment]
Nobody else reported this, so I'm going to hope this was a one-time incident.
