### ISSUE TITLE
Add current festival achievements to the "earnable" filter

### ISSUE THREAD

**Issue by Nimmidev** [gw2efficiency/issues#1655]
It would be nice if the achievement ["show:  earnable" filter](https://gw2efficiency.com/account/achievements?filter.display=available-points) would include the achievements of the historical category of the respective festival if it is currently taking place. Maybe similar to the way it works ingame: If a festival is active add a "Festival" category with the respective achievements.

I am not sure if this is feasible because i did not find an API endpoint to get information of an active festival. But maybe there is a way, i only did a quick search for it. In case its already clear that no such data can be obtained in a reasonable manner you can close this issue. Manually maintaining and updating the dates does not make sense.

**Comment by queicherius** [comment]
Yeah, sadly this is broken in the API. It used to automatically move the achievements (and was also used to detect which festival was active by other tools) but this is not currently working. :(
