### ISSUE TITLE
Missing prerequisite for Guild Upgrade (Guild Hall Music: Super Adventure Box)

### ISSUE THREAD

**Issue by FoolMeOnce** [gw2efficiency/issues#1656]
The Guild Hall Music: Super Adventure Box guild upgrade requires Tavern Restoration 2 which isn't available until guild level 19.

Source: https://wiki.guildwars2.com/wiki/Guild_Hall_Music:_Super_Adventure_Box

![image](https://user-images.githubusercontent.com/2530459/212165900-92f7ea68-7d26-4da6-aafd-82195d31f0ee.png)

**Comment by queicherius** [comment]
The prerequisites are pulled from the API directly, we just display them. Whether they are correct or not seems to be a bit random over time. Please report this here instead: https://github.com/gw2-api/issues/issues

There is also an existing one there (but for a different one): https://github.com/gw2-api/issues/issues/14

**Comment by FoolMeOnce** [comment]
I see! I'll do that from now on, I see you already referenced this issue in that thread.
Sorry for the inconvenience :)
