### ISSUE TITLE
Account name change removes history of the account

### ISSUE THREAD

**Issue by thilobru** [gw2efficiency/issues#1658]
After changing account name of the Arenanet account all history that was saved with the old name is lost

**Comment by queicherius** [comment]
When changing your account name, as the first step please delete your old API key and create a fresh one. You should now be able to see your new crawling points, but not your old ones anymore. As the second step, please write support@gw2efficiency.com with your old and new account name (including the numbers) to migrate all the old crawled data to the new account name.
