### ISSUE TITLE
Condensed Ley-Line Essence Recipe Recursion

### ISSUE THREAD

**Issue by vipansegrouw** [gw2efficiency/issues#1661]
[Azure](https://wiki.guildwars2.com/wiki/Azure_Condensed_Ley-Line_Essence), [Crimson](https://wiki.guildwars2.com/wiki/Crimson_Condensed-Line_Essence), [Saffron](https://wiki.guildwars2.com/wiki/Saffron_Condensed_Ley-Line_Essence) and [Emerald](https://wiki.guildwars2.com/wiki/Emerald_Condensed_Ley-Line_Essence) all have varying degrees of (wasteful) recursion in their recipes on the crafting calculator.

To craft 1x Crimson, it suggests first crafting 4x Crimson so that you can craft 1 Crimson.
The same is true of Azure. 
Saffron and Emerald both feature recursion of the Azure crafting recipe before resolving into themselves.

My assumption, however baseless, is that there's logic in place to avoid recursion, but it is (presumably) done by avoiding using the same recipe twice. 
Since there are 3 different recipes to acquire each of the different essences, this can end up looping.

**Expected behaviour:**
The recipe should suggest that you acquire 2 of any other Condensed Ley-Line Essence, and stop there.

**Comment by queicherius** [comment]
> My assumption, however baseless, is that there's logic in place to avoid recursion, but it is (presumably) done by avoiding using the same recipe twice.

That is correct!

> The recipe should suggest that you acquire 2 of any other Condensed Ley-Line Essence, and stop there.

👍
