### ISSUE TITLE
Tabs overlap with ad slots

### ISSUE THREAD

**Issue by Georgi-Stavrev** [gw2efficiency/issues#1662]
The two advertisement slots overlap with the menu tabs when loading the page.
![image](https://user-images.githubusercontent.com/119886366/217596326-5ede9df7-ce64-4d1b-b08b-3f4fe7b34725.png)

Zooming in or out by 10% fixes the overlap:
![image](https://user-images.githubusercontent.com/119886366/217596559-b3f396eb-bf56-402f-91df-77c1f3dc0a62.png)

Latest stable Firefox browser. 1680 x 1050 resolution. Tested on my 2k monitor and the issue appears there at 120% zoom.

**Comment by queicherius** [comment]
Yeah we don't really support zooming - the ads hide themselves when the window width is not wide enough to show them and the menu, but with zooming we get the wrong window width.

In this case, it's probably best if you just remove them, either via adblock or via a supporter rank.

**Comment by Georgi-Stavrev** [comment]
Fair enough, but I do want to highlight this issue occurs without zooming and is fixed by zooming. Not the other way around.
