### ISSUE TITLE
Order Membership

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1663]
Would like to see which of the Orders of Tyria each character belonged to on the main Character page

**Comment by UmBottesWillen** [comment]
Is it possible to show the story steps a specific character completed? For vanity's sake, I'd like to play through the complete story with my core character,s but I haven't found a way to track which character completed what story.

**Comment by queicherius** [comment]
> Is it possible to show the story steps a specific character completed? For vanity's sake, I'd like to play through the complete story with my core characters, but I haven't found a way to track which character completed what story.

@UmBottesWillen Yes, head to Characters -> Click on a Character -> Click "Story Journal" in the left side navigation.
However, this is broken in the API if you ever restarted any story.

**Comment by UmBottesWillen** [comment]
How would it break if I restarted any story? Would it show story steps before/after as done/not done erroneously?

**Comment by queicherius** [comment]
I don't quite remember, all I remember is that it's broken
