### ISSUE TITLE
Compare TP prices with cost of skilling up unknown craft skills.

### ISSUE THREAD

**Issue by YouichiHophop** [gw2efficiency/issues#1664]
I was making a Gen3 Legendary, which requires a "Sheet of Premium Paper", TP cost 9 sliver, and the crafting calculator was telling me that I needed to skill-up Scribing to level 400.

I have no character with a single point of Scribing skill, and leveling it up to level 400 would cost ~90 gold, Which is roughly a thousand times more expensive than purchasing from the TP.

Would it be possible for unlearned skills to compare the cost of skilling-up with the TP prices of the required items ?

**Comment by queicherius** [comment]
The costs are not really comparable: For example if you wanted to level Scribe anyway for other reasons, it might still be better to level up and craft it vs your situation where it clearly isn't if you just want a couple of items.

This is a decision the user has to make and I feel like we give you enough information to make it, by showing you the required disciplines and which characters have them in a list, and marking the disciplines in the crafting steps so you can go ahead and just buy those components beforehand.
