### ISSUE TITLE
Include cost of un-owned recipes in Legendary crafting costs.

### ISSUE THREAD

**Issue by YouichiHophop** [gw2efficiency/issues#1665]
I'm in the middle of crafting my first legendary, and requires a "Gift of condensed Might", which is made up of four recipes, Gifts of claws, scales, bones and fangs.

As, this is my first legendary, I've not made any of these items before, and didn't own the recipes, so had to buy them from Miyani, for 10 Gold a piece, which was not calculated for in the cost suggested by the crafting calculator. The same was true for the "Gift of condensed Magic" items, so the actual costs for my legendary were 80 Gold more than calculated.

Would it be possible to add the cost of un-owned recipes to the crafting calculator ?

**Comment by queicherius** [comment]
While we don't plan to add them to the cost of the crafted item (since it's a one-time unlock) we do want to show which recipes you will need + show a warning if they cost gold. -> #55
