### ISSUE TITLE
Mark infusions as upgrades (just like runes / sigils)

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1667]
When displaying infusions on a character, sort them so the uninstalled infusions are all first, and if possible distinguish them from those that are installed.  Perhaps a half-height letter I in the center of the installed ones to indicate "Installed"

**Comment by queicherius** [comment]
Is this for when you are searching for them?

**Comment by SeparGW2** [comment]
Yes during a search on insignia.  I had though insignia would have been an option under 'Type: Upgrade Components, but I searched for 'insignia'

**Comment by queicherius** [comment]
The goal is that the "Item Upgrades" filter works for infusions, e.g. https://gw2efficiency.com/account/overview?filter.upgrades=only should show them together with the other upgrades (runes/sigils).
