### ISSUE TITLE
add overview of time-gated crafted items

### ISSUE THREAD

**Issue by daniel-pittman** [gw2efficiency/issues#167]
wishlist: add overview of time gated crafting items to the site.

generally, all the time-gated items are worth crafting to sell, but it's interesting to see how valuable they are compared to each other, etc, and what the profit is.  http://wiki.guildwars2.com/wiki/Time-gated has the list of a dozen or so items that work that way.

**Comment by queicherius** [comment]
This may or may not be already included in #157 if there would be a filter for daily gated items. Gonna leave this issue here open for reference. Thanks for the suggestion!

**Comment by daniel-pittman** [comment]
If there was a filter included, yes, #157 would exactly solve my problem.  Thank you again for the service.
