### ISSUE TITLE
Main account data is bleeding into alt accs when swapping to them

### ISSUE THREAD

**Issue by ReportAnIssue** [gw2efficiency/issues#1671]
Hi,
I have 18 alt accounts on the one efficiency account. Mostly I am on my main account in efficiency. For some time, when I am on the account overview and then I use the drop down menu switch to another alt account, the data from my main is being carried over. Sometimes it works ok, but frequently I have to go to characters [or other] pages to try to switch it to the correct account overview page. If that doesn't work I have to logout and back a number of times.
There are times when it's all the main acc details including searching for an item.
Is there something that I need to do to stop it from happening?
The attachment of account 11overview show its rank, but the main accounts values and gold.

![acc 11 rank on overview](https://user-images.githubusercontent.com/40881414/227116845-5fc1859f-dc35-418f-a90b-72f8bf8d6973.png)

**Comment by queicherius** [comment]
Super weird, I'll have to investigate what's going on there, from a first glance at the code I cant see anything that could cause this behaviour.

**Comment by queicherius** [comment]
I deployed a change that *might* fix this, could you let me know? I did not manage to reproduce this at all for myself :/

**Comment by ReportAnIssue** [comment]
At Least for now the accounts seem to be maintaining their own data, so thank you for your prompt attention :).

But I have noticed another super weird thing. When I go into the lottery page it's showing the lottery for the 4th Jan 23 and is doing so on all accounts and I have been unable to enter any lottery.

Cheers

**Comment by queicherius** [comment]
> At Least for now the accounts seem to be maintaining their own data, so thank you for your prompt attention :).

Glad to hear that!

> But I have noticed another super weird thing. When I go into the lottery page it's showing the lottery for the 4th Jan 23 and is doing so on all accounts and I have been unable to enter any lottery.

You likely have a supporter account (or someone else has your API key on their supporter account) so you get pre-entered for all lotteries at that date (which is the date it shows).
