### ISSUE TITLE
Update permanent gathering nodes

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1676]
![Permanent Gathering Nodes - Grothmar Valley](https://user-images.githubusercontent.com/4615516/228692154-62bcb99b-1d3f-4601-95fd-d178d782b0ce.png)
![Permanent Gathering Nodes - Seitung Province](https://user-images.githubusercontent.com/4615516/228692158-52d4a14d-93d3-4993-9ae7-37342447dfd1.png)

**Comment by Ecmelt** [comment]
Gathering page is updated.
