### ISSUE TITLE
Fix Warcry/Warbringer's crafting price

### ISSUE THREAD

**Issue by ghJosep** [gw2efficiency/issues#1679]
To craft Warbringer's precursor, Warcry, you need a total of 2,450 WvW Skirmish Claim Ticket. 350 for Recruit's Wings of War, 525 for Soldier's, 700 for General's and 875 for Commander's. In addition to this, in order to buy Commander's Wings of War you also need the Commander's/Catmander's icon, which costs 300 gold + 250 Badges of Honor and it is not stated in the crafting's recipe. I think the recipe should be updated to account for this extra requirements.

![image](https://user-images.githubusercontent.com/121748087/229346019-26afa9a4-d294-464a-8e63-b0fe7d0df16c.png)
![image](https://user-images.githubusercontent.com/121748087/229346190-38cd3f98-6d27-45f1-a692-dc5cff4d7237.png)
![image](https://user-images.githubusercontent.com/121748087/229346306-9f1351ae-c922-44e6-ad16-33fccae84730.png)

**Comment by Ecmelt** [comment]
I don't see a way of checking if an account has Catmander's icon, if there is one and i missed it please let me know. Otherwise till the API is updated this recipe will stay as-is or it could potentially mislead people with a Catmander to buy Commander as well.
