### ISSUE TITLE
Option to choose between multiple recipe choices

### ISSUE THREAD

**Issue by Hatar22** [gw2efficiency/issues#1685]
Hello there,

If possible it would be great if you have an option to choose between different recipe choices in the crafting calculator 
f.e. between "gift of Desert Mastery" and "Gift of Maguuma mastery" at Gen 2 Legendaries.

**Comment by queicherius** [comment]
Out of scope generally, legendaries are tracked in https://github.com/gw2efficiency/issues/issues/1653#issuecomment-1479377137
