### ISSUE TITLE
[Request] Display the cost of Tonic of Icebrood Corruption achievements

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1688]
https://wiki.guildwars2.com/wiki/Tonic_of_Icebrood_Corruption#Related_achievements

There are two recipes, but one is just a x10 multiplier of the other, so the unit cost is still the same.

**Comment by queicherius** [comment]
Basically done via https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-93829

**Comment by kazerniel** [comment]
I meant on the achievement page, like how other collections have the remaining and total cost displayed.
