### ISSUE TITLE
Add Crystal Lodestone recipe.

### ISSUE THREAD

**Issue by Draconicrose** [gw2efficiency/issues#1689]
I noticed that Crystal Lodestone doesn't have a recipe in the calculator. It can be crafted in the MF [like so](https://wiki.guildwars2.com/wiki/Crystal_Lodestone#Recipes).

**Comment by queicherius** [comment]
This is intentional, see #1285, #1234 and #1119 for context.

**Comment by Draconicrose** [comment]
The Crystal Lodestone doesn't seem to be in the Spirit Shards page either. 😟

**Comment by queicherius** [comment]
> The Crystal Lodestone doesn't seem to be in the Spirit Shards page either. 😟

It's there, it's just hidden by default because it's not profitable

![image](https://github.com/gw2efficiency/issues/assets/4615516/3a444fc6-4198-4309-942c-822a68c64bb9)
