### ISSUE TITLE
Recipe calculator can't handle achievements with objective count

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#169]
The [Masterful Toast](https://gw2efficiency.com/crafting/calculator/77633-Masterful-Toast) requires an achievement to drink 10.000 Mugs of Eggnog. Right now it's only "completed" or "not completed", but it could check the count from the achievement API.

**Comment by VariableFlame** [comment]
Not sure if/when they changed this, but Festive Imbiber is now granted for consuming any of the following drinks: 
- Cup of Spiced Apple Cider
- Glass of Buttered Spirits
- Mug of Eggnog
- Snowman Tonic
- Reindeer Tonic
- Festive Golem Tonic
- Cask-Strength Eggnog (counts as 10x drinks)

It would be nice for the crafting calculator to take the prices of all of these into account (not just Mugs of Eggnog).

**Comment by queicherius** [comment]
Closing this because there are relatively few recipes that depend on the objective count. If you want to check those, it's easier to do in the achievement view, e.g. for [Masterful Toast](https://gw2efficiency.com/account/achievements?filter.search=Festive%20Imbiber) (the example in the OP)
