### ISSUE TITLE
Crafting steps don't appear to account for purchased items

### ISSUE THREAD

**Issue by ThomasOwens** [gw2efficiency/issues#1693]
I'm working toward crafting a full set of [Medium Legendary WvW armor](https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-82437;1-82994;1-84578;1-84110;1-82903;1-82093).

You can purchase Grandmaster Leatherworker's Marks from the Mercenary in Armistice Bastion or the Skirmish Supervisor in any of the other WvW maps using Grandmaster Mark Shards. Because I had more than enough, I did this.

However, I still see the crafting step for Grandmaster Leatherworker's Mark, which requires Carbonized Mithrillium Ingots, Squares of Vabbian Silk, Blended Leather Sheets, and Empowered Cured Thick Leather Squares. The crafting steps to create these items are also showing up.

My shopping list also contains items that I need that, as far as I can tell, are only used to craft the Grandmaster Leatherworker's Marks, which are currently in my bank.

At this point, it's not clear to me what is left, so I'll need to sit down and sort that out. Other items also are affected, such as buying Eldritch Scrolls and Certificates of Honor - these are still showing up in the crafting steps even though I own all of the required items.

The last update time under "used own materials" is after the purchases. It's been > 10 minutes since making the purchases and the lists are not reflecting them.

**Comment by queicherius** [comment]
> I had checked it again about 2 hours after making the purchases. It still hadn't updated.

This is sadly something on the GW2 API side - it's fairly rare to take more than an hour to update, but it happens sometimes. Sometimes you can force the cache to refresh by changing characters.

> The "last update time" kept updating a lot faster than the items I own / the shopping list.

Yeah that's a bit misleading - the last update time is the last time we pinged the API, and not the last time the record got updated. There is (AFAIK) no correct way to get the "from when is this data" time from the API (there are some things it provides, but they all don't work correctly).
