### ISSUE TITLE
Living World Season 1 Quests out of order in story journal

### ISSUE THREAD

**Issue by Aryezz** [gw2efficiency/issues#1695]
In the characters story journal the order of the missions in Living World Season 1 are incorrect.

This is probably because the quest IDs from the API are out of order as well. This is the case in some quests of the personal story as well, but in those cases the order on gw2efficiency seems to be correct.  
I have not checked all other quests for the correct order, but season 2 seems to be right on a cursory glance.

## Episode 1 - Flame and Frost: 
**CURRENT ORDER**: New Friends, New Enemies → A Quiet Celebration → The Battle for Cragstead → Alliance Investigation → Molten Furnace
**CORRECT ORDER**: New Friends, New Enemies → The Battle for Cragstead → Alliance Investigation → Molten Furnace → A Quiet Celebration
See reference: https://wiki.guildwars2.com/wiki/Flame_and_Frost#Episode_1_%E2%80%94_Flame_and_Frost

## Episode 2 - Sky Pirates: 
**CURRENT ORDER**: No More Secrets → Ceremony and Acrimony → Hard Boiled → Case Closed → The Aetherblade Retreat → Aether Investigation
**CORRECT ORDER**: Ceremony and Acrimony → Hard Boiled → No More Secrets → Aether Investigation → The Aetherblade Retreat → Case Closed
See reference: https://wiki.guildwars2.com/wiki/Sky_Pirates#Episode_2_—_Sky_Pirates

## Episode 3 - Clockwork Chaos:
**CURRENT ORDER**: Clockwork Invasion → Scarlet's Playhouse → Picking Up the Pieces → The Queen's Address → The Opening Ceremony
**CORRECT ORDER**: The Opening Ceremony → The Queen's Address → Clockwork Invasion → Scarlet's Playhouse → Picking Up the Pieces
See reference: https://wiki.guildwars2.com/wiki/Clockwork_Chaos#Episode_3_%E2%80%94_Clockwork_Chaos

## Episode 4 - The Tower of Nightmares:
**CURRENT ORDER**: The Tower of Nightmares → The Nightmare Unveiled → Awake and Allied → The Nightmare Incarnate → Making the Antitoxin → The Nightmare Ends
**CORRECT ORDER**: The Nightmare Unveiled → Making the Antitoxin → The Tower of Nightmares → The Nightmare Incarnate → The Nightmare Ends → Awake and Allied
See reference: https://wiki.guildwars2.com/wiki/Tower_of_Nightmares_(release)#Episode_4_%E2%80%94_Tower_of_Nightmares

## Episode 5 - The Battle for Lion's Arch:
**CURRENT ORDER**: Battle on the Breachmaker → The Battle For Lion's Arch → Scarlet's End → Connecting the Pieces → The Twisted Marionette → Dawn of the Next Journey → Escape from Lion's Arch → After the Battle
**CORRECT ORDER**: The Twisted Marionette → Connecting the Pieces → Escape from Lion's Arch → The Battle for Lion's Arch → Battle on the Breachmaker → Scarlet's End → After the Battle → Dawn of the Next Journey
See reference: https://wiki.guildwars2.com/wiki/Battle_for_Lion%27s_Arch#Episode_5_%E2%80%94_Battle_for_Lion's_Arch

**Comment by Ecmelt** [comment]
All should be in correct order with next deploy. Also fixed EoD 16. What Lies Beneath order.
