### ISSUE TITLE
[Feature Request] Add 'filter.isGuaranteedWardrobeUnlock' to statistics page

### ISSUE THREAD

**Issue by ShiningMassXAcc** [gw2efficiency/issues#1696]
Love that you've added guaranteed wardrobe unlock - awesome stuff!

It looks like you have already powered custom filters on the statistics page (eg. to handle skin weights).  Can you add 'filter.isGuaranteedWardrobeUnlock' to the below?

https://gw2efficiency.com/account/unlock-statistics?filter.key=skins&filter.show=locked

**Comment by queicherius** [comment]
That would be possible, yeah. I'm curious: why are you specifically interested in that?

**Comment by ShiningMassXAcc** [comment]
Mainly that while gold is a most universal way to value sort, it isn't perfect. There are a bunch of things that while they have a gold value, they are more generally acquired via other currencies (and often account-bound through that method - which you have a value input for if only through that method).  Other gw2 tools that are more directly related to wardrobe unlock will often have features to delve into this a bit by having 'acquisition' filters (that include things like Karma, badges of honor, mostborn mote, etc).  One of the main unique value adds that gw2eff has for me is the sheer volume of users it has that makes its aggregate anonymous data super interesting.  I don't directly care about all the currencies into the acquisition, but the upstream motivation - how much do players value acquiring this skin, is it viewed as prestigious (even if not rare), is it rarely acquired even if gold value is low, etc.  Using this type of filter here helps feed the completionist aspects that the 'stats unlock' tab already does, while aiding in the discovery of content that players commonly do.

Concretely: this helps a user maximize the value wardrobe unlocks more than just buying cheapest skins on the trading post.  Even if item XYZ has high gold value, perhaps more players have acquired it via XYZ content because that path is fun even if expensive.  Even if item XYZ has low gold value, it's perhaps not truly that gold value alone because you have to acquire account bound pieces of it in some obscure way that players have found tedious.

More minor but, the Account/Wardrobe page doesn't have removal of the 'group by' options (eg. the type option has to be specified, and subType option is still group-by'ed even when set to 'any').  I like the ungrouped list that this page would perform.  It could be nice on the account\wardrobe to be able to quickly answer: What is the cheapest item I could buy off the trading post right now to maximize potential value of my guaranteed wardrobe unlock?

**Comment by ShiningMassXAcc** [comment]
One example is https://wiki.guildwars2.com/wiki/Etched_Short_Bow_Skin

One can see from acquisition, that you need to do a reward track.
https://wiki.guildwars2.com/wiki/Shiverpeak_Mountains_Weapon_Skins_Box

A 'stats' based search sort of reveals this that someone could find on the sort parameter of player acquisition.  Otherwise, it just shows as 'account bound' in the account\wardrobe page.
https://gw2efficiency.com/account/unlock-statistics?filter.key=skins&filter.search=etched

**Comment by queicherius** [comment]
Now live, great suggestion thanks!
