### ISSUE TITLE
Renamed Waypoint

### ISSUE THREAD

**Issue by Suven** [gw2efficiency/issues#170]
Hey!

Thanks for your great efforts!

Just wanted to note that in the german translation, the Waypoint "Abfall-Senken" was renamed to "Ödtiefen" ingame. The english name is Hollows Waypoint and located in Malchor's Leap.

**Comment by queicherius** [comment]
Thanks for the report! I'll get on that as soon as the translation servers are back alive. :)

Reference: #161
