### ISSUE TITLE
Statistics page able to toggle by region

### ISSUE THREAD

**Issue by Ryltarr** [gw2efficiency/issues#1700]
The statistics page is fascinating to me, and I could spend hours pouring over it and comparing it to my experiences in game... however, I've noticed that a lot of the implications aren't correlated to my experience and I'm wondering if that's down to region... which got me thinking it would be really cool to be able to toggle which regions are reflected on the page, or even be able to enter a mode like the one further down with profession x gender x race but with region for the whole page.

**Comment by queicherius** [comment]
While I agree that this kind of feature would be quite nice to have, the resources required for this sadly make it not possible for us at the moment.
