### ISSUE TITLE
Secrets of the Obscure Content update

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1701]
> This is a work-in-progress. There will be problems.

**Notes so far:**

- Relics for characters don't show up
- Dailies endpoint is on fire

---

- [x] Update item updater to handle new item categories
- [x] Fix the daily and achievement page by disabling fetching from the daily endpoints
- [x] #1731
- [x] Wallet currencies
- [x] #1642
- [x] Add new hero's choice chests to the daily page (not in the API, but manual)
- [ ] Figure out how daily achievements work now (for the achievements page, also check the filters for "earnable ap")

---

Extra remaining API issues from EoD: #1611

**Comment by BrettBock** [comment]
👍

**Comment by queicherius** [comment]
Done, remaining tasks are their own tickets or depend on API updates.
