### ISSUE TITLE
Karma conversion uses wrong amount for mf items?

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1703]
![image](https://github.com/gw2efficiency/issues/assets/4615516/da48c98e-8ae1-40b7-9e3c-7c6d94959180)

**Comment by Ecmelt** [comment]
[Cloth Garrison Gloves](https://wiki.guildwars2.com/wiki/Cloth_Garrison_Gloves) are not 280 karma, they are 70 karma and so 4 times that makes 280 as stated on website, not 1120.
