### ISSUE TITLE
Account Overview Search does not show results from characters

### ISSUE THREAD

**Issue by wolfgangbures** [gw2efficiency/issues#1705]
Searching for "Weapons" only shows weapons in Bank, ANY search only shows items in bank, not on characters.

**Comment by queicherius** [comment]
It will show weapons in inventories, if you want equipped items you have to switch "Equipment" to "Include".

![image](https://github.com/gw2efficiency/issues/assets/4615516/37e267ca-2e57-431d-baf8-592f61ecbc7f)

**Comment by wolfgangbures** [comment]
Thx for reply, but does not solve it for me:
[cid:62c1a9eb-540f-44ca-bd9f-7908c77e4adf]
also, Gold is zero in this view but not the overview
[cid:2153b157-ca14-49fd-8008-770a88fd1dd8]



________________________________

**Comment by queicherius** [comment]
Your screenshots did not attach :(

**Comment by wolfgangbures** [comment]
Ah, sorry, didnt notice - anyway it's working again!

________________________________
