### ISSUE TITLE
Bank not working

### ISSUE THREAD

**Issue by elias-knodel** [gw2efficiency/issues#1711]
## Problem description:

I wanted to look for an item in my bank, however, I get an error.

## Error code:
`RXJyb3I6IFN0YXR1cyA0MDQKICAgIGluIFVua25vd24KICAgIGluIFVua25vd24KICAgIGluIHMKICAgIGluIGRpdgogICAgaW4gdAogICAgaW4gbAogICAgaW4gbA==`

## Additional Data: 
- Browser: Firefox 117.0.1 (64-Bit)

## Additional Screenshots:
![grafik](https://github.com/gw2efficiency/issues/assets/42189915/70c5cf8c-7ce7-4c33-a540-f703b02b5c0d)

**Comment by queicherius** [comment]
Thank you for the report! That looks like a temporary API outage on ArenaNet's side. Did it fix itself in the meantime? If not, please send your API key to support@gw2efficiency.com and we can take a look :)

**Comment by elias-knodel** [comment]
> Thank you for the report! That looks like a temporary API outage on ArenaNet's side. Did it fix itself in the meantime? If not, please send your API key to [support@gw2efficiency.com](mailto:support@gw2efficiency.com) and we can take a look :)

Okay, thanks for the reply ^^ Yeah, it took a while. but it fixed itself!
