### ISSUE TITLE
Show equipped jade bot / fishing upgrades / relics

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1712]
FYI The following slots now show up under a characters equipment in the API

```
FishingRod,
FishingBait,
FishingLure,
PowerCore,
SensoryArray,
ServiceChip,
Relic,
```

_Originally posted by @lambada in https://github.com/gw2efficiency/issues/issues/1611#issuecomment-1739863308_

**Comment by Ecmelt** [comment]
Done with Relic only showing for active tab due to API limitations.
