### ISSUE TITLE
Vermilion Vambraces Skin not makred as gemstore skin

### ISSUE THREAD

**Issue by strongstancer** [gw2efficiency/issues#1714]
The Vermilion Vambraces Skin is still shown in the wardrobe when selecting gemstore exclude. According to the wiki its only acquisition method is via gemstore

https://wiki.guildwars2.com/index.php?title=Vermilion_Vambraces_Skin

**Comment by queicherius** [comment]
@Ecmelt Could you take a look at this? 🙂

**Comment by Ecmelt** [comment]
It should be fixed with next update. Was never added to the gemstore list, only to guaranteed unlocks list.
