### ISSUE TITLE
Problem with timemachine tab

### ISSUE THREAD

**Issue by paidiua** [gw2efficiency/issues#1719]
The checkbox :
"Hide changes caused by market fluctuations" is not working and generates the following error: 

RXJyb3I6IFN0YXR1cyA0MDQKICAgIGluIG0KICAgIGluIHQKICAgIGluIG4KICAgIGluIFVua25vd24KICAgIGluIHMKICAgIGluIGRpdgogICAgaW4gdAogICAgaW4gbAogICAgaW4gVW5rbm93bg==

**Comment by queicherius** [comment]
Pretty sure this was an API issue that fixed itself, it didnt get reported again.
