### ISSUE TITLE
Gem amount in wallet section doesn't show the correct value

### ISSUE THREAD

**Issue by luriel** [gw2efficiency/issues#172]
Hi! First off I'd like to thank you for this great tool! Now... the issue:

The amount of gems displayed in the wallet section is outdated and would not update with actual changes within GW2. I have bought and spent gems several times already over the past 2 months and the amount has never changed in the gw2efficiency's wallet section (unlike other wallet values that update immediately.)

My GW2 account has been there since the release, my gw2efficiency account is about 3 to 4 months old and the gem value has never changed during that time (and displays the amount of gems I had for the time I quit the game before getting back to it recently.)

I have deleted the API key and create a new one to no avail.

**Comment by queicherius** [comment]
Heya & thanks for using it! :)

This is an issue in the official API and not related to gw2efficiency: arenanet/api-cdi#274

I also asked when it will make it in, but it's in the money-making pipeline (and with that out of the hands of the API developer): [Chatlog](https://gitter.im/arenanet/api-cdi?at=5769d6b4648385b8074c3819)

**Comment by luriel** [comment]
Thanks for the fast reply! 

So I suppose it's all up to anet now.

**Comment by queicherius** [comment]
I am going to close this, since it's out of my hand and everything will just work as soon as the official API gets fixed.
