### ISSUE TITLE
Permanent Mobile Crafting Station does not count towards Permanent Contracts 

### ISSUE THREAD

**Issue by Nimmidev** [gw2efficiency/issues#1721]
I just noticed that the [Permanent Mobile Crafting Station](https://wiki.guildwars2.com/index.php?title=Permanent_Mobile_Crafting_Station) does not count towards the `Permanent Contracts` stat. Is this intended?
The item doesn't directly say that it is a Contract like the others when you buy them but i would put it into the same category.
What is your opinion about this?

**Comment by queicherius** [comment]
Oh yeah for sure this one should count.

**Comment by Ecmelt** [comment]
Inheritance value added and is now part of the contracts stat.
