### ISSUE TITLE
Navigation container has scrolling

### ISSUE THREAD

**Issue by Prodigio** [gw2efficiency/issues#1726]
It's just a minor UI issue, but in german the navigation container is scrollable now.

I use Firefox 120.0 on Windows 10.

![grafik](https://github.com/gw2efficiency/issues/assets/18284425/bbd3a7dd-5cb0-4e2b-93ba-91f97ff486e9)

**Comment by queicherius** [comment]
Ah yeah I introduced that recently, sorry. Will be fixed soon 👍

**Comment by queicherius** [comment]
Fixed
