### ISSUE TITLE
Missing "Dragonstorm" achievements

### ISSUE THREAD

**Issue by robmart** [gw2efficiency/issues#1736]
The achievements "Put Them on Ice," "Light Him Up," and "Steelcaught" are missing from the Dragonstorm category. In fact, they seem to be missing entirely.

**Comment by queicherius** [comment]
Opened an issue here: https://github.com/gw2-api/issues/issues/68

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
