### ISSUE TITLE
crafting recipes incorrect

### ISSUE THREAD

**Issue by StormSurge95** [gw2efficiency/issues#1737]
Over the course of the past few months, I've been using gw2efficiency to keep track of unlocking any and all possible crafting recipes (and it's made things **MUCH** simpler for me). My only issue is that any time a recipe requires an item that has to be purchased from an npc in bulk, said recipe seems to think that it requires the entire bulk purchase. On top of this, some recipes also seem to simply be outdated. For example:  the Simple Tailor's Tools item only requires 2 Spools of Jute Thread, and the gw2efficiency says that it requires 10 because they can only be purchased in packs of 10; the same goes for the Jute Patch item, as it requires only 25 Spools of Jute Thread while the gw2efficiency says that it requires 30.  This same issue applies to intermediary crafts that create more than one item per craft, such as the aforementioned Jute Patch which produces 5 per craft. If I want to craft a single Healing Embroidered Jute Insignia, gw2efficiency says that I need a total of 5 Jute Patches when I only need 1.

**Comment by queicherius** [comment]
Yes, this is intentional because (as you say) you can only buy those in larger sizes. This also shows a red banner at the top of the screen so you can adjust if needed :)

**Comment by StormSurge95** [comment]
There may be some misunderstanding going on here.

Let's say that I want to craft a single **Bowl of Curry Butternut Squash Soup** as well as a single **Bowl of Curry Pumpkin Soup**.
Each of these crafts produce a total of **two** items instead of one. As a result, gw2efficiency states that I will be receiving two of each item instead of one.
I believe *this* is intentional.

However, each craft *also* requires *just one* **Bowl of Herbed Vegetable Stock** as an ingredient (meaning I need a total of two *items*).
gw2efficiency seems to think I need two *crafts* of the stock in order to obtain my two desired items; and this is incorrect.
I believe this to be more akin to oversight.

It seems that the system does not take into account any concurrent crafts and fails to realize that, after a single craft of **Bowl of Herbed Vegetable Stock**, I have a total of 3 items and therefore have enough to craft ***both*** of the two final items I'm looking to craft.

**Comment by StormSurge95** [comment]
The same kind of issue applies to bulk purchased ingredients.
**Bowl of Cream Soup Base** requires only ***one*** item of **Glass of Buttermilk** per craft; however, gw2efficiency thinks that I need ***25*** items for the recipe.
In this example, if I need to craft multiple items of **Bowl of Cream Soup Base**, the crafting engine seems to that I need ***multiples of 25*** and therefore requests that I purchase far more than I need.
