### ISSUE TITLE
Suggestion: Additional order option in crafting calculator buy list

### ISSUE THREAD

**Issue by sascha-dev** [gw2efficiency/issues#1739]
I would like to have an additional buy-list order option in the crafting calculator: "Order by (material) type".
It should order the list by the types of intermediate crafting materials.
This list explains, what I mean: https://wiki.guildwars2.com/wiki/Crafting_material#Intermediate_crafting_materials

Background:
If you have a recipe, that needs one or more Gift of Blood/Bones/... then you mostly need all of the Tiers.
Working through the list to buy everything from the trading post would be much easier, if you could order the list by material type.
So you can search for "bone" in the tp and place all orders for the different tiers of bones.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
