### ISSUE TITLE
Add elder dragons' skins variants and legendary generations to statistics

### ISSUE THREAD

**Issue by Linkaaaaa** [gw2efficiency/issues#1742]
Possibilities for the dragon variants:
- Total variants unlocked
- Zhaitan
- Mordremoth
- Kralkatorrik
- Jormag
- Primordius
- Soo-Won

Legendary generations:
- Total gen-1 unlocked
- Total gen-2 unlocked
- Total gen-3 unlocked

For future:
- Legendary raid armor skins
- Legendary open world armor skins

Having the generation statistics means you don't need to have an aurene-variant type of unlocks, so would only consider the skins from the merchant. 
From the looks of it, the open world armor will have some variants tied to it similar to Aurene's legendaries, there could be a possibility of an addictional section there.

Additionally, would be nice to have a page that shows all of them together similar to the legendary armory, not sure in which section it would fit the most though.

**Comment by queicherius** [comment]
We chatted about it internally and we decided not to add any of those statistics except "Total variants unlocked"

**Comment by queicherius** [comment]
Notes for @Ecmelt:

- Let's implement it using the skin ids, since they are all bound (?)
- Add skin ids via generation to https://github.com/gw2efficiency/game-data (similar to cosmetic auras) as `skins/categories/aurene-legendaries` and pull that in for the account stat generation
