### ISSUE TITLE
Account-bound infusions and bags listed in unbound items

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1743]
Several bags and infusions which are account bound are listed in the account overview when binding is set to "none".

For example https://wiki.guildwars2.com/index.php?title=Special%3ASearch&search=Sturdy%20Boreal%20Duffel&go=Go and https://wiki.guildwars2.com/index.php?title=Special%3ASearch&search=Precise%20%2B9%20Agony%20Infusion&go=Go 

It seems to be like that for all the crafted account-bound bags and non-cosmetic stat infusions, I don't have the inventory to test all these items though.

**Comment by queicherius** [comment]
> @Ecmelt:
> I have a char with Sturdy Boreal Duffel so i tested. Inside bag slot = shows in none. Put it in inventory = shows in account bound.

**Comment by Ecmelt** [comment]
Fixed, just wanted to comment that this is caused by official API.
