### ISSUE TITLE
Several Legendary Statistics Are Incorrect/Strange/Impossible (Pre-armory Caching?)

### ISSUE THREAD

**Issue by yo-wotop** [gw2efficiency/issues#1744]
Wasn't sure whether to make multiple issues about this or not. I've combined them below:

1. [Stats > Legendary Items (Trinkets)](https://gw2efficiency.com/account/statistics/statistics.legendaryItemsTrinket) fails to recognize some trinket (perhaps the 2nd Conflux?).

My account has five trinkets (out of seven if you double-count Conflux) unlocked:
![image](https://github.com/gw2efficiency/issues/assets/72385703/cbe4bdc8-6171-4d5f-8d4d-9e15667a2c69)

But my stats says I only have four:
![image](https://github.com/gw2efficiency/issues/assets/72385703/e7079ad9-1c67-4381-9f90-3a892b41a71b)

And this is despite the number one person in the rankings being recorded for 7:
![image](https://github.com/gw2efficiency/issues/assets/72385703/88591bc4-6f7e-4a20-bea0-a541760f12e0)

Given the extremely low number of 7's, I'm guessing that the site was previously counting things like Slumbering Conflux/Slumbering Transcendance as separate items (yielding a theoretical maximum of 8?) and perhaps these people got cached in? Whatever the case, the numbers here are strange.

2. [Stats > Legendary Items (Armor)](https://gw2efficiency.com/account/statistics/statistics.legendaryItemsArmor) has someone with more than all armors in the game.

In total, there are 108 Legendary Armors obtainable in the game: 6 (1x raid, 2x WvW, 3x PvP) sets of 18. Some guy has 146:
![image](https://github.com/gw2efficiency/issues/assets/72385703/cd5d481f-fe6c-419b-b6a2-adbd32ebd6d3)

Again, I'm guessing that this might be due to some pre-armory shenanigans where people could have more than one copy of armor. There is further strangeness related to this, described below:

3. [Stats > Unlocked Legendaries](https://gw2efficiency.com/account/statistics/statistics.legendaryarmoryCount) has someone with all 269 who verifiably does not have all 269 unique legendaries.

In total, both the [Legendary Armory page](https://gw2efficiency.com/account/legendary-armory) and my own manual calculation indicates there are exactly 269 legendaries in the game that can be bound, which is what the number 1 person has on the leaderboard:
![image](https://github.com/gw2efficiency/issues/assets/72385703/1c4ba025-12cb-461e-a0c3-a7100a5adcbd)

However, since NOBODY has all 108 armor skins, the maximum theoretically possible for anyone to have right now would be 251.

4. [Stats > Legendary Items (Backpieces)](https://gw2efficiency.com/account/statistics/statistics.legendaryItemsBack) appears to just be archaic/obsolete

Some people are noted as having up to nine legendary backpacks:
![image](https://github.com/gw2efficiency/issues/assets/72385703/dfdd5853-550e-4a38-947d-32bd906de5b5)

Of course, only three are possible nowadays due to the legendary armory, as is in alignment with the page for [Stats > Legendary Skins (Backpieces)](https://gw2efficiency.com/account/statistics/statistics.legendarySkinsBack).

On one hand, I can see the value in memorializing people who may have obtained more at one point or quit the game since then and thus have their numbers cached in. If these aren't wanted completely removed for some reason, perhaps a "legacy stats" or something to that effect might be more appropriate - it isn't technically possible to obtain these anymore, and people who previously had more than 3 but DIDN'T quit the game have been squished.

**Comment by Ecmelt** [comment]
Added missing legendary amulet and armor pieces to statistics.

**Comment by Ecmelt** [comment]
@queicherius Not sure if I should close this or keep it open at this point.

**Comment by queicherius** [comment]
We can close this with the fixes, I think its fine to keep "old" account data around for now, we might revisit that in the future.
