### ISSUE TITLE
Terrible performance when dark mode is enabled

### ISSUE THREAD

**Issue by Maffey** [gw2efficiency/issues#1750]
##  Prerequisites
Firefox 122.0 (64-bit)
Windows 11
Example website (same behavior on each one): https://gw2efficiency.com/currencies/dungeon-tokens

## Description
When scrolling through websites in default light mode, everything works smoothly - especialy, scrolling works smooth, no lagging or freezing is experienced. After switching to night mode through clicking the sun icon on the top ("sprite-nightmode-on") scrolling through website causes lagging, the different links load longer, etc. The network load seems similar in both cases, so seems like this is client-side problem.

## Steps to reproduce
1. Enter any link on https://gw2efficiency.com/
2. Select sun icon to turn dark mode
3. The website starts to lag

**Comment by queicherius** [comment]
Hey, this is a known issue with Firefox's rendering engine. Users have reported that it gets better when disabling/enabling (funnily enough, both were reported) hardware acceleration.

**Comment by Maffey** [comment]
I see. Thanks for explaining, I'm sorry for taking your time.

**Comment by queicherius** [comment]
No problem at all, hopefully that fixed it for you :)
