### ISSUE TITLE
Expand Crafting Calculator's Listing Cost Calculation

### ISSUE THREAD

**Issue by TeplarGw2** [gw2efficiency/issues#1751]
Add an option to have the crafting calculator to use trading post listing information for listing and quantity to get a more accurate value of the cost to craft items.

I see this primarily used for low volume acquisition of materials or high volume crafting to get a more accurate cost for the number of crafts desired.

Currently the crafting calculator takes the lowest sell listing and uses that price for the calculation. (Material Cost * Quantity Required)
A material may only have a few at it's current listing and then much higher price for the quantity needed.
The proposed option would parse through the listings and sum up the expected cost until the total quantity required has been met. (Sum of Listings[Cost * Quantity])
I suppose if the quantity on the TP is insufficient, it should provide an error/warning.

**Comment by queicherius** [comment]
This has been requested a few times, but this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
