### ISSUE TITLE
The Path of Most Resistance achievement is missing

### ISSUE THREAD

**Issue by Ellieanna** [gw2efficiency/issues#1757]
The Path of Most Resistance isn't listed under Strikes - EOD Strikes. The title associated with it "The Great Equalizer" is also missing. They both just are not listed under account achievements, nor the title under unlock statistics. 

Upon further looking, the same can be said about the achievement Gazed into the void (XXJ CM achievement and title) is missing from both areas.

**Comment by queicherius** [comment]
Sadly this is an ongoing issue with the official API, nothing we can do.

See https://github.com/gw2-api/issues/issues/68 & https://github.com/gw2-api/issues/issues/54
