### ISSUE TITLE
Missing steps/items in the Obsidian Armor Legendary recipe

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1758]
I don't know if it's too early to report this but the recipe for all the armors are missing the step to craft the Gift of Stormy Skies (https://wiki.guildwars2.com/wiki/Gift_of_Stormy_Skies) (along with the Gift of Astral Ward https://wiki.guildwars2.com/wiki/Gift_of_the_Astral_Ward) and the vendor cost Arcanum of Astral items (https://wiki.guildwars2.com/wiki/Lyhr#Astral_Arcana). These items appear directly in the shopping list.

https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-101129;1-101208;1-101149;1-101258;1-101165;1-101286;1-100485;1-100704;1-100504;1-100665;1-100207;1-100936;1-101544;1-101551;1-101521;1-101609;1-101568;1-101460;1-101614;1-101645;1-101556;1-101570;1-101579;1-101602;1-101516;1-101462;1-101499;1-101536;1-101501;1-101535

![image](https://github.com/gw2efficiency/issues/assets/14335637/e1a1aa3d-d853-48cb-893a-7058f7f93702)

Regards.

**Comment by queicherius** [comment]
Fixed 👍 

https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-101568
