### ISSUE TITLE
Add source filter to legendaries crafting page

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1762]
Add a "source" filter to this page: https://gw2efficiency.com/crafting/legendaries?filter.type=armor

Should be PvP/WvW/PvE and maybe generation / tier (or however the upgrades are called these days)

**Comment by Ecmelt** [comment]
Both should be fixed alongside other updates. Would appreciate a double check. Also source filter as in, PvE PvP WvW?

**Comment by queicherius** [comment]
Yep that looks good. 👍 Yeah, that's what I was thinking. I've renamed this ticket for that.
