### ISSUE TITLE
Obisidan armor crafting recipe possibly inaccurate

### ISSUE THREAD

**Issue by illydemarino** [gw2efficiency/issues#1763]
Hi, I was looking up the light obsidian armor recipe and saw that all of the required armor listed to make it is the heavy version, is this right?

![image](https://github.com/gw2efficiency/issues/assets/63763627/cf00e589-cc2d-485d-a402-32b2a0351868)

**Comment by queicherius** [comment]
All weight skins are automatically unlocked upon selecting a weight, so it does not matter :)
