### ISSUE TITLE
Wrong recipe for Arcanum of Astral items (Obsidian Armor)

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1764]
Currently, each Arcanum of Astral item (https://wiki.guildwars2.com/wiki/Lyhr#Astral_Arcana) asks you buy their respective Astral Ward piece (https://wiki.guildwars2.com/wiki/Astral_Ward_armor) and Oneiros-Spun piece (https://wiki.guildwars2.com/wiki/Oneiros-Spun_armor). This is an issue because if you put in the calculator all 3 Obsidian Armors, it asks you to buy 3 of each piece when you only need 1 of each because crafting 1 item unlocks all the weight variants.
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-101544;1-101551;1-101521;1-101609;1-101568;1-101460;1-101614;1-101645;1-101556;1-101570;1-101579;1-101602;1-101516;1-101462;1-101499;1-101536;1-101501;1-101535
![image](https://github.com/gw2efficiency/issues/assets/14335637/bd93a7bc-ab51-4fd6-86af-875c13f63759)
This inflates the total cost (materials and currencies) for all 3 armors (or the subsequent armor if you have already crafted 1 or acquired the precursors).
Two possible solutions I can think of:
1. Remove the 3 precursors from the cost of the Arcanum of Astral item (leave only the Lesser Vision Crystal) and just have each user add the precursors manually (at the end you only need 1 precursor set regardless of the weight). This might be the best solution.
2. Change the recipe to check for the unlocked skin (but I don't know how this will work if you put all 3 armors at the same time because again, you only need 1 precursor set regardless of the weight).

Regards.

**Comment by queicherius** [comment]
Hey, yes - please observe the massive red warning at the top of the page you linked. Basically, this usage is not supported.

![image](https://github.com/gw2efficiency/issues/assets/4615516/78e4597c-3979-4007-a8ca-625a14d14118)

> Change the recipe to check for the unlocked skin (but I don't know how this will work if you put all 3 armors at the same time because again, you only need 1 precursor set regardless of the weight).

We do this, once you have the skin unlocked they will show up as an "owned material". We suggest making one armor weight at a time, and by armor 2 they will all be marked as completed.
