### ISSUE TITLE
Silk insignia recipes have the wrong number of mats

### ISSUE THREAD

**Issue by Alukah** [gw2efficiency/issues#1769]
Example https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-19885;1-19880

It's 2 silk patches required per craft, but the site lists 5.

**Comment by queicherius** [comment]
![image](https://github.com/gw2efficiency/issues/assets/4615516/5042b627-a8ef-4a9e-b721-f10f06555a52)
See warning at the top

**Comment by Alukah** [comment]
That makes sense if it was one craft, but this is two crafts, aka 2+2 insignias, it asks to craft 2 patches (5+5) instead of one (5), it's not taking into account the total needed. 

Another example https://gw2efficiency.com/crafting/calculator/a~1!b~1!c~0!d~1-45731;1-11121;2-11295;1-11248;1-11167;1-11341;1-11247;1-11126

Is there no way to make it consider how many are needed total (18) instead of just doing 9 crafts of silk patches? I understand that there will be leftovers either way, but crafting 20 patches (4 crafts) with 2 leftover is very different from crafting 45 when only 18 are needed.

**Comment by darthmaim** [comment]
I agree, it showing 5 silk patches as ingredient seems wrong, even when you need to craft multiples of 5.
![Screenshot 2024-03-21 134756](https://github.com/gw2efficiency/issues/assets/2511547/9c0d91ca-2855-4373-ac49-102fdc1e3782)
![Screenshot 2024-03-21 134746](https://github.com/gw2efficiency/issues/assets/2511547/1bac9532-44f8-47f1-9579-7501ef3aec24)
