### ISSUE TITLE
Show rarity for account unlocks (achievements, outfits, skins, titles, etc.)

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#177]
Someone on [reddit](https://www.reddit.com/r/gw2efficiency/comments/4t1ffm/suggestion_achievements_ideas/) suggested something that would be awesome:
- Similar to xbox true achievements, generate a 'trueachievements' score based on what the population has achieved. (e.g. `((Total Players)/(Players with Achievement))^0.5`)
- Instead of 'find me a random achievement' or the in-game 'almost completed' achievements, let people search (by section, if they avoid pvp for instance) on what is the 'easiest' achievement they could do.

**Comment by Scath-Enfys** [comment]
The first would be the easiest to implement, but the second would require a curator or team of curators to set a standard for "easy". And what do we mean by that anyway? An achievement like "Hammer Master" (# of killing blows with hammer) might be "easy" to get, but time consuming.

**Comment by queicherius** [comment]
The "easy" would just be determined by the trueachievement score - the more people have an achievement, the easier it clearly is to get. :)

**Comment by Scath-Enfys** [comment]
Ah, now I see why the two are bound together.

**Comment by kazerniel** [comment]
Adding here as mine was closed as duplicate: When you implement this, can you add titles as a separate listing? It would be interesting to see that out of the titles one owns what is the order of their rarity.

**Comment by queicherius** [comment]
@kazerniel Yes, the idea is to add pretty much all unlocks on the account (including things like achievements, titles, dyes, outfits, gliders, minis, etc.). 👍

**Comment by risingashes** [comment]
Will the implementation of the achievement end of this be similar to 'find me a random achievement' in which the lowest true achievement is displayed, or will it be a list of achievements ordered trueachievement?

**Comment by queicherius** [comment]
Yeah, that's one of the possible usecases when the value exists.

**Comment by nrone** [comment]
This would be awesome, something i often wish for. Sorting achievements by rarity to find what "easy" once you might have missed.

Having this feature would differently be something i would be willing to pay for and be a cool idea for "support feature"

**Comment by thyeggman** [comment]
I'll throw in my comment so hopefully this gets attention again soon :) - I'm really looking forward to this.  I know it probably got put on hold because of PoF

**Comment by queicherius** [comment]
This is now live! Thank you for your feedback. 😄

https://gw2efficiency.com/account/unlock-statistics
