### ISSUE TITLE
Add new Pillager's Packs to crafting calculator

### ISSUE THREAD

**Issue by tuftelien** [gw2efficiency/issues#1770]
Not sure if applicable as they're "crafted" through a vendor, but could be useful to see cost and materials needed in total

https://wiki.guildwars2.com/wiki/Pillager%27s_Pack_(24_slots)
https://wiki.guildwars2.com/wiki/Pillager%27s_Pack_(28_slots)
https://wiki.guildwars2.com/wiki/Pillager%27s_Pack_(32_slots)
https://wiki.guildwars2.com/wiki/Pillager%27s_Pack

**Comment by holoxx** [comment]
They were added in gw2efficiency/custom-recipes#55
