### ISSUE TITLE
Tradingpost deliverybox just endlessly shows loading. 

### ISSUE THREAD

**Issue by gllyons** [gw2efficiency/issues#1771]
Maybe it is just me, but since yesterday when I go yo https://gw2efficiency.com/tradingpost/delivery I just get loading, and it never completes. Everything else I use seems to work/

**Comment by queicherius** [comment]
This is extremely likely to be an issue with the API and not with us, and there's nothing we can do about that :( We can double-check if you send your API key to support@gw2efficiency.com.
