### ISSUE TITLE
Text-engine tags in title-column for unlock statistics for new colored titles

### ISSUE THREAD

**Issue by sobrinth** [gw2efficiency/issues#1772]
I just noticed that for the new colored titles (Ultimate Dominator, etc. ) the text-engine tags (<c>) are not stripped (or interpreted) in the title column.
Just a minor visual "Bug".

![image](https://github.com/gw2efficiency/issues/assets/7988025/e494ba97-2736-4b23-a361-3842bb1db2df)

**Comment by queicherius** [comment]
Thanks, will be fixed in the next release 👍
