### ISSUE TITLE
Support search operators for achievement view

### ISSUE THREAD

**Issue by PetreBogdan55** [gw2efficiency/issues#1773]
Add, as a new feature, the option to hide/unhide daily/weekly achievements from the list. This can be simply as searching in achievement name/category these words.

**Comment by queicherius** [comment]
Hey, could I ask why you would want this feature?

**Comment by PetreBogdan55** [comment]
Hi, sure! As a completionist of achievements, it's a bit annoying that there are some categories or even some lonely achievements left over because there are daily/weekly and the API doesn't recognise them as completed. Of course, this is not important, but a nice to have to show 100% completion when the filter is applied

**Comment by PetreBogdan55** [comment]
Let me give you some examples, why it bothers me. Doesn't matter if the Finished or Unfinished filter is selected because these example will be here always. This is because API limitations

1. Daily category will never be completed
![image](https://github.com/gw2efficiency/issues/assets/70099800/539d3515-036d-4046-aa8d-057d4386a341)

2. There are some dailies achievements hidden in some categories, that will never be completed
![image](https://github.com/gw2efficiency/issues/assets/70099800/743676f4-c244-471b-a4c6-d152cf0964c2)

3. There are weekly subcategories and weekly achievements hidden than will never be completed
![image](https://github.com/gw2efficiency/issues/assets/70099800/a51788c5-66ce-4cba-be70-10a464faef3d)
![image](https://github.com/gw2efficiency/issues/assets/70099800/c00ce40b-9960-4bae-a0e4-d21df8dbdb8f)
![image](https://github.com/gw2efficiency/issues/assets/70099800/3ea186ce-81c3-4f82-bdc8-87303486a493)

4. More, I also didn't mention nothing about Character Adventure Guide that will also never be completed


Again, this is just a nice to have and I don't think it will be a hard way to implement. My suggestions was to search for 'Daily' or 'Weekly' string in any name

**Comment by queicherius** [comment]
OK so this would be solved if we allowed the search operators that we already have (e.g. for miniatures) for achievements, then you could search for `-daily -weekly`.
