### ISSUE TITLE
Missing achievements in the "The Legendary Facets of Aurene" category

### ISSUE THREAD

**Issue by Nemecyst** [gw2efficiency/issues#1774]
The achievements [Aurene's Facet of Persuasion](https://wiki.guildwars2.com/wiki/Aurene%27s_Facet_of_Persuasion) and [Aurene's Facet of Crystal](https://wiki.guildwars2.com/wiki/Aurene%27s_Facet_of_Crystal) are missing from the "The Legendary Facets of Aurene"  achievement category.

As you can see in the screenshot below, the category on GW2Efficiency only adds up to 40 points due to the 2 missing achievements:
![image](https://github.com/gw2efficiency/issues/assets/9501781/8fe38dd8-3095-4705-867f-967dbb2166fa)

According to the wiki however, there should be 60 points: https://wiki.guildwars2.com/wiki/The_Legendary_Facets_of_Aurene#achievement6771

**Comment by queicherius** [comment]
Sadly these seem to be missing from the API, so nothing we can do: https://api.guildwars2.com/v2/achievements?ids=6771
