### ISSUE TITLE
Review/add missing legendary armour skins to the skin list

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1778]
https://gw2efficiency.com/account/statistics/statistics.legendarySkinsArmor seems to be missing at least obsidian armour. Not sure if PvP/WvW armour skins should count, only count them if they dont have the same skins in ascended/exotic.

**Comment by queicherius** [comment]
More context: https://discord.com/channels/231772598801793025/231772598801793025/1236789718688202832

**Comment by Ecmelt** [comment]
Added missing skins, leaving this open as they just now added open world Suffused Obsidian Armor, will wait a bit and see how they work.
