### ISSUE TITLE
Price history graph for Gems is missing

### ISSUE THREAD

**Issue by Vortex1996** [gw2efficiency/issues#1779]
Hello,
The **Price history** graph for the Conversion of Gems (e.g. Gold to Gems) under Currency/Gems is not shown: [https://gw2efficiency.com/currencies/gems](https://gw2efficiency.com/currencies/gems).

Tested for Firefox and Edge.

![Screenshot 2024-05-20 120638](https://github.com/gw2efficiency/issues/assets/170317294/8ff3e65c-bffb-4aa9-95c8-af202c055c08)

**Comment by queicherius** [comment]
Hmm, seems to work for me now - is it back for you as well?
