### ISSUE TITLE
Shared inventory endpoint support in gw2api-client

### ISSUE THREAD

**Issue by hyena** [gw2efficiency/issues#178]
Probable blocker for #1 

Implement an api endpoint for the shared inventory slots as described in https://wiki.guildwars2.com/wiki/API:2/account/inventory

**Comment by queicherius** [comment]
Hey there! This is included in #122, but I am curious - are you using the API client in own projects? If yes, anything you'd like to see improved?

**Comment by queicherius** [comment]
Just to inform you, this is now in `gw2e-gw2api-client` starting at version `2.0.0`.
