### ISSUE TITLE
All second collection's (II) recipes are missing the Bandit Crests and Geodes costs

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1781]
All of the second (II) collections of the achievements for all the precursors are missing the cost of Bandit Crests and Geodes in the calculator.
For example:
https://wiki.guildwars2.com/wiki/Meteorlogicus_II:_The_Perfected_Scepter
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-74125
does not include the cost of https://wiki.guildwars2.com/wiki/Desert_Magics:_Scepter_Edition and https://wiki.guildwars2.com/wiki/Jungle_Magics:_Scepter_Edition
![image](https://github.com/gw2efficiency/issues/assets/14335637/56a43dc7-6040-4cf0-b153-2f4fac57aced)

This is happening for all the precursors.

**Comment by queicherius** [comment]
> all the items are in merchants.js and used to be in the recipes.
> they were kicked out again when added the ignoring of recipes that are officially available.
> they shouldn't have an official recipe, so not sure why they are being ignored
> - @holoxx
