### ISSUE TITLE
Add Suffused Obsidian armor to the calculator

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1784]
Hi,

Is it possible to add https://wiki.guildwars2.com/wiki/Suffused_Obsidian_armor to the calculator? 
You need to buy https://wiki.guildwars2.com/wiki/Runestone_of_Suffusion
This unlocks a collection https://wiki.guildwars2.com/wiki/Tier_2_Legendary_Armor:_Suffused_Obsidian that rewards you with 2 https://wiki.guildwars2.com/wiki/Imbued_Rune_of_Suffusion. You need 1 for each piece meaning that every time you complete the achievement you can buy 2 pieces.

Regards.

**Comment by queicherius** [comment]
What would the benefit of this be to you?

~~For purchasing the item from the vendor you can see the amounts in the wallet (and we generally don't add a recipe for cases where it's a simple purchase from a vendor unless it's used in other, more complex recipes).~~ It does make sense to add the runestone to the recipes, for purposes of this usage: https://github.com/gw2efficiency/issues/issues/1786#issuecomment-2153318412

And for completing the collection, you should be able to use the achievements view: https://gw2efficiency.com/account/achievements?filter.search=suffused

**Comment by Aguileitus** [comment]
Ok, the recipe for the runestone would be enough I think.
