### ISSUE TITLE
Add types to materials and allow sorting/organizing by types.

### ISSUE THREAD

**Issue by ThomasOwens** [gw2efficiency/issues#1785]
For materials, it would be helpful to organize/sort by type. If I could easily see what types of material I need and how many, I could make decisions about which Glory to the Legions track to run in Drizzlewood, what Jade Bot Scavenger Protocol to equip, or similar.

**Comment by queicherius** [comment]
I assume you would want to see this in the crafting calculator?

I'm pretty hesitant to add this, because it's a lot of manually maintained data, since the "type" a material is is not in the API. I'm not sure if all of them are generatable (e.g. "glacial" / "leather" would work, but not sure about others).

**Comment by ThomasOwens** [comment]
Yes, I think the crafting calculator is where this would be the most helpful.

That is a valid point. It probably wouldn't make sense to have to manually maintain the data somehow.

I do see some common themes, but I'd need to check and deconflict: "Scrap", "Bolt of", "Spool of", "Ore", "Lump of", "Ingot", "Leather Section", "Leather Square", "Log", "Plank", "Pouch of * Pigment", "Bone", "Claw", "Pile of * Dust", "* Fang", "* Scale", "* Totem", "* Venom Sac", "Vial of * Blood", "Pile of * Essence", "Onyx *", "Molten *", "Glacial *", "Destroyer *", "Crystal *", "Corrupted *", "Charged *", "Mordrem *", "Evergreen *", "Resonating *", "Vial of * Mists Essence".

I do see at least a few conflicts. Eitrite Ingot and Auric Ingot aren't part of the other metal ingots. Spool of Deldrimor Thread isn't part of the other spools.

I'd have to explore the API more to understand about categories and item names.

**Comment by queicherius** [comment]
Kindof related to https://github.com/gw2efficiency/issues/issues/1739

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
