### ISSUE TITLE
Adding crafteable components on the calculator ignores/resets owned materials

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1786]
I'm currently working on crafting two sets of the Obsidian Legendary armor, I'm using this for tracking: https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-101544;1-101551;1-101521;1-101609;1-101568;1-101460;1-101614;1-101645;1-101556;1-101570;1-101579;1-101602
It shows me my currently owned items such as:
![image](https://github.com/gw2efficiency/issues/assets/14335637/3207fa3c-b5df-447a-aaa5-33a8bacb8956)
![image](https://github.com/gw2efficiency/issues/assets/14335637/4becd945-d9c7-452a-96d4-25db19c69570)
![image](https://github.com/gw2efficiency/issues/assets/14335637/ec72fcab-1444-4bd8-bb4f-5be0c9c87df9)
And it correctly tracks what I'm missing:
![image](https://github.com/gw2efficiency/issues/assets/14335637/813ef1cd-cc6e-44cc-96d5-2a1b71489868)
![image](https://github.com/gw2efficiency/issues/assets/14335637/66286ce4-1078-4def-a682-65323d3818a2)
Because currently there is no recipe available to craft the T2 armor (nor the recipe for the stone), I tried manually adding the cost of the stones (https://wiki.guildwars2.com/wiki/Runestone_of_Suffusion) in the calculator:
https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-101544;1-101551;1-101521;1-101609;1-101568;1-101460;1-101614;1-101645;1-101556;1-101570;1-101579;1-101602;45-100930;18-100267;18-99964;18-100098
![image](https://github.com/gw2efficiency/issues/assets/14335637/28ced03e-1888-4375-9954-70f669b111ea)
But for some reason this causes the owned materials to completely disappear/reset on my list:
![image](https://github.com/gw2efficiency/issues/assets/14335637/c0083524-a444-4eaf-b33d-487872abdbc4)
![image](https://github.com/gw2efficiency/issues/assets/14335637/41baf2b9-752b-4d58-9f93-d1647d72071c)
And if I only put the items on the calculator using "Use own materials: Yes"
https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~45-100930;18-100267;18-99964;18-100098
![image](https://github.com/gw2efficiency/issues/assets/14335637/3d64b702-3a24-4c67-b99e-2b221af6a7a1)
It does not count the already owned materials. (Showing for example that I need 18 of each when I already have more than 50 of each)

Regards.

**Comment by Ecmelt** [comment]
So just to clarify, the issue is calculator cannot find these items in owned materials if they are the top recipe but finds them if they are part of a top recipe am i understanding this correctly?

**Comment by Aguileitus** [comment]
Correct.

**Comment by queicherius** [comment]
Any top level recipe is always **force-set to be crafted** and never bought/used from own materials (since you want to use the crafting calculator for crafting).

Since you added "Pouch of Stardust" to the top level, this sets it to be crafted everywhere, even inside other recipes.

Not sure if we want to fix that (i.e. only force-craft the top level ones), because that's also confusing (you'd assume that your owned materials would reduce the top level recipe amount).

Maybe we just add a recipe for the runestone with #1784 and add an error-level warning for this case (like the other ones at the top that pop up sometimes).

**Comment by Aguileitus** [comment]
Ok, I understand. Maybe yes, it would be better just to add the recipe for the runestone.

**Comment by queicherius** [comment]
Recipe has been added a while ago.
