### ISSUE TITLE
Best path on rare kryptis motivation bugged if together with any other item

### ISSUE THREAD

**Issue by AstanVizu** [gw2efficiency/issues#1787]
![image](https://github.com/gw2efficiency/issues/assets/91348105/cee3c6e6-9721-4f75-a04a-09624e341293)

![image](https://github.com/gw2efficiency/issues/assets/91348105/acae2257-57ff-4ce4-9bc4-b443ea659d8c)

In the crafting calculator, the "Best path" for Rare Kryptis Motivations is shown to be as buy from TP, although this is clearly way more expensive. This happens **only** when there are any other items in the crafting list. It does not happen when there are only Rare Kryptis Motivations.

**Comment by queicherius** [comment]
@Ecmelt I dont even know what's happening there - don't put too much time into it. If you get stuck for a few hours let me know.

**Comment by Lantigarr** [comment]
I think the same thing is happening with Titanplate Light Regalia:

![image](https://github.com/user-attachments/assets/d60c1363-4b31-485f-81f1-9ca65e1355c7)

Interestingly enough it has a negative profit (buy price) that might be causing the flip.

![image](https://github.com/user-attachments/assets/362c37e7-add1-440a-a7df-3cb2413b2815)

**Comment by Ecmelt** [comment]
There will be a new tooltip to explain why this behavior happens, it is not a bug but basically the calculation takes into account currencies that don't actually have a value in some form of "opportunity cost", such as research notes, karma etc.
