### ISSUE TITLE
Kamohoali'i Kotaki missing Jungle Magics: Spear Edition

### ISSUE THREAD

**Issue by maciejstepie** [gw2efficiency/issues#1792]
Buying `Jungle Magics: Spear Edition` from LA merchant is missing in steps and by that also missing amount of geodes to craft spear.

![image](https://github.com/gw2efficiency/issues/assets/56389913/045bf5c7-060e-407e-b7da-8c579bd5ea9c)
![image](https://github.com/gw2efficiency/issues/assets/56389913/3509731f-afd9-4f00-adae-6356835add7e)
![image](https://github.com/gw2efficiency/issues/assets/56389913/e6fb6f09-32df-4bda-900b-c37796c59a8f)

**Comment by Aguileitus** [comment]
Check https://github.com/gw2efficiency/issues/issues/1781

**Comment by queicherius** [comment]
Duplicate of #1781
