### ISSUE TITLE
Incorrect recipe for Suffused Obsidian armors

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1796]
Each armor piece requires only 1 [Imbued Rune of Suffusion](https://wiki.guildwars2.com/wiki/Imbued_Rune_of_Suffusion) but the calculator asks for 2 for each piece:
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-101716;1-101884;1-101809;1-101763;1-101825;1-101831;1-101879;1-101744;1-101899;1-101783;1-101918;1-101815;1-101887;1-101929;1-101745;1-101733;1-101747;1-101892
![image](https://github.com/gw2efficiency/issues/assets/14335637/8c4a225c-bd20-481e-9ddf-2d80a24c4f54)
You only need to craft 18 [Imbued Rune of Suffusion](https://wiki.guildwars2.com/wiki/Imbued_Rune_of_Suffusion) (9 crafts) for all 18 pieces.

Regards.

**Comment by queicherius** [comment]
This is a current limitation of the calculator, rethinking it is in #1686.

Also see the big orange banner at the top of the page.

I removed the recipes for now, to avoid catching people unaware.
