### ISSUE TITLE
Handle multiple recipes in the crafting calculator

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#18]
Currently the system is build on the idea that every item has a single recipe. To achieve this, duplicate recipes are just removed at the generation step. Now, for some recipes (such as "Amalgated Gemstones"), the prices between them are dramatically different. It should use the recipe that is the cheapest in these cases.
- [x] On generating nested recipes, calculate the prices of each recipe in a second step
- [x] Then save the cheapest recipes as the actual cheapest recipes

**Comment by mirtisdyleris** [comment]
At least for the mystic curios it isnt doing it... its using the large claws while the large claws are not the cheapest rn.. neither order nor instabuy

**Comment by mirtisdyleris** [comment]
I tested it by putting the price of the large claws way above the others at 85 copper order price and well... it still said to craft it by large claws :c

**Comment by queicherius** [comment]
After reflecting on this, it should just show a dropdown with all possible recipes and their prices, in cases where there are different recipes that use non-pricable materials (e.g. new legendaries can be built with two different gifts)

**Comment by SaiyanOfDarkness** [comment]
What's going on with this?  Because Amalgamated Gemstones still show doubloons being used.

**Comment by queicherius** [comment]
> Because Amalgamated Gemstones still show doubloons being used.

The ticket is still open = the feature is not yet implemented.

**Comment by queicherius** [comment]
This is now live, by choosing the cheapest recipe tree for any duplicates.
