### ISSUE TITLE
PvP armor prices in crafting calculator are incorrect after recent patch

### ISSUE THREAD

**Issue by Siliron** [gw2efficiency/issues#1800]
The number of Ascended Shards of Glory required for the Ardent Glorious armor (both the ascended armor version and exotic skin version) as well as the Mistforged Glorious Hero's armor have been changed in the game but the crafting calculator has not been updated for these yet.

The new prices can all be seen on https://wiki.guildwars2.com/wiki/Ascended_Armor_League_Vendor but in summary the headgear, shoulders, gloves, and boots now all require 100 Ascended Shards of Glory, the leg pieces all require 150 Ascended Shards of Glory, and the chest pieces require 250 Ascended Shards of Glory

**Comment by Siliron** [comment]
The PvP ascended trinkets have also had their Ascended Shards of Glory costs updated. Mist Talisman requires 100, Mist Pendant requires 125, and Mist Band (Infused) requires 150

**Comment by Siliron** [comment]
I've created a pull request in custom-recipes that updates the values (hopefully that's the right place to put it, not sure how to link the PR to here)

**Comment by queicherius** [comment]
Thank you! :) Will go live on the website in a couple hours.
