### ISSUE TITLE
Add `Copy Purchase Waypoint` for Icy runestone dropdown

### ISSUE THREAD

**Issue by imZeo** [gw2efficiency/issues#1811]
Since you can only buy at one place, a quick link to Earthshake Waypoint — [&BHoCAAA=] would help shave off a good 3-5 seconds!

Instead of:
1. Open Wiki
2. Click vendor
3. Copy WP link

It'd be:
1. Copy WP link

[Item link](https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-19676)

**Comment by queicherius** [comment]
This is somewhat on the list of ideas we have, but since we have to maintain all of the merchant data ourselves (the API has none of it) that's not currently in it it's not in the immediate future.

See #1593
