### ISSUE TITLE
Sentinel's Orichalcum Imbued Inscription is "cheaper" from the vendor.

### ISSUE THREAD

**Issue by Draconicrose** [gw2efficiency/issues#1821]
I'm making the destroyer weapons and the recipe finder is calculating that the Sentinel's Destroyer Greatsword is cheapest of the greatswords. The calculator recommends buying the Inscription from the TP at over 2g a pop, when it can be bought from a guild commendation trader for 80 silver and 10 commendations.

**Comment by queicherius** [comment]
Merchant data is added manually, and this one has not made it's way in yet. See #1593
