### ISSUE TITLE
Keep track of when new decorations were introduced to allow sorting by date

### ISSUE THREAD

**Issue by xvwyh** [gw2efficiency/issues#1825]
One annoying part with guild decorations has always been figuring out what new decorations were being added with every festival, especially when the patch notes only mention e.g. "Added several new guild decorations". With homestead decorations we're still at an early enough point where we can start keeping track of when new decorations show up in the API, storing that date somewhere in gw2efficiency's internal databases, so that the list of decorations could be sorted by the date they were added to the game, allowing users to quickly find which decorations are new and consider crafting them.

It would've been amazing to have that data for all kinds of collections (skins, mounts etc), but the sheer amount of historical data that would need to be manually added defeats the point. It can partly be filled using data IDs (the ordering thereof), but it's hardly a reliable source.

**Comment by Ecmelt** [comment]
This is being implemented. Current ones will all have the date of implementation as their initial date.

**Comment by queicherius** [comment]
Follow up: #1860
