### ISSUE TITLE
When Crafting Legendaries, vendor items in Crafting Steps should be in Shopping List

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1827]
The purchases of Nuhoc Mastery, Itezel Mastery, Exalted Mastery, & Mystic Forge Attendant, and other vendor items should be grouped together and placed at the bottom of the of the Shopping list section instead of the interspersed in the Crafting Steps section.  Items such as, Gift of the Exalted, Gift of the Itzel, Gift of the Nuhoch, Mystic Runestone, Bloodstone Shard, Icy Runestones, etc.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
