### ISSUE TITLE
Search item upgrades exclude does not work on legendary runes/sigils

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#1841]
![image](https://github.com/user-attachments/assets/10b331be-1b69-40c3-b910-c7ab5175527e)

**Comment by queicherius** [comment]
![image](https://github.com/user-attachments/assets/d7945138-15d5-4c13-bd80-8d117b85e91e)
also some infusions while we're at it


> seems to be anything that is equipped/slotted, which is interesting
> as the +9's and infusions in my bank dont appear, but the sigils in my precursors are

**Comment by Ecmelt** [comment]
This is fixed with extra checks, however extra checks are required in the first place because we don't apply an internal logic to all equipment but only to active tab. So that should be fixed next. Extra checks are still nice to have though.
