### ISSUE TITLE
Crafting Calculator can't find items when reopening from bookmark

### ISSUE THREAD

**Issue by Skyy5380** [gw2efficiency/issues#1849]
The crafting calculator seems to have issues reloading projects as it just remains empty. 
I also have to open a new tab before I can manually add more things. 

![Screenshot 2024-11-25 093501](https://github.com/user-attachments/assets/5d245276-054c-445e-8454-72c0e54d837f)
![Screenshot 2024-11-25 093512](https://github.com/user-attachments/assets/59230b70-4a25-49c3-8f35-2482d8116901)

**Comment by queicherius** [comment]
Should be fixed, thanks for the report!
