### ISSUE TITLE
include crafting prices in guild upgrade costs

### ISSUE THREAD

**Issue by JordanJD** [gw2efficiency/issues#198]
Right now there are upgrades that include account bound crafted items. when not added to the gold cost of an upgrade this is very misleading. At the time of this issue being written, GW2E says that "Guild Enhancement: PvP Reward Boost" costs 39.5G, but the crafting of one requirement will cost over 60G. 

http://prntscr.com/c3myrd

**Comment by queicherius** [comment]
Yeah, this was initially done this way, because else it'd have to load loads of items. Nowadays, this would be super easy! Definitely will do this.
