### ISSUE TITLE
Can't enter lottery with multiple accounts

### ISSUE THREAD

**Issue by RLHawk1** [gw2efficiency/issues#199]
I'm not sure if this is a bug or intended.  My wife and I both play GW2 and use GW2efficiency. But we generally log into the same account because we like comparing our stats. However, as it is now, you can only enter the community lottery with the main account you signed up with.

I understand something needs to be done here to protect from creating tons of free accounts and easily entering all of them. Perhaps a check for rather the game has been purchased, if that's possible? I'm not sure.

**Comment by queicherius** [comment]
> I'm not sure if this is a bug or intended.

It's meant as a feature for people to check if they entered already. It was different in the past, and didn't show it - and loads of people sent me emails to ask if they successfully entered.

> However, as it is now, you can only enter the community lottery with the main account you signed up with.

There is a super easy way around that, which is using an [incognito tab](http://www.wikihow.com/Activate-Incognito-Mode). Then you can just navigate to the lottery and enter as many times as you like.

> I understand something needs to be done here to protect from creating tons of free accounts and easily entering all of them.

We allow anyone with a guildwars2 account (or multiple!) to enter the lottery, without any strings attached. We've actually never had a winner with a free-to-play account!

**Comment by RLHawk1** [comment]
Thanks much! You're awesome and I really appreciate your work!

It'd be nice to be able to toggle between accounts to enter each of them that way, but this is an easy workaround. Thanks!
