### ISSUE TITLE
Redirect the `www` subdomain

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#204]
Turns out there can be weird bugs when the subdomain `www` is set. I should probably just redirect to the version without `www` always.

**Comment by Scath-Enfys** [comment]
easy enough:
`server{
     listen 80;
     listen [::]:80;
     server_name www.gw2efficiency.com;
     return 301 https://gw2efficiency.com/$request_uri;
}`

if you want the https to redirect too, that is simple enough to add.

**Comment by queicherius** [comment]
HTTP was already redirected, only had to add it for HTTPS. (Also note: `$request_uri` already includes the first `/`).
