### ISSUE TITLE
Display off TP item quantities

### ISSUE THREAD

**Issue by risingashes** [gw2efficiency/issues#205]
Since accounts are already being queried daily, is it possible to consolidate tradable item results and display yet unlisted items?

This would be a fairly unique offering as currently sites can only display what is currently listed.

While this would be limited due to not all API keys being queried, and delivery box items not being visible to the API, it would at least give an incomplete meta view of how many items truly exist.

**Comment by queicherius** [comment]
While this is a good idea, doable, and pretty interesting from a technical perspective, I am pretty sure something like this will not make it into gw2efficiency. The reason being that it would seriously harm people's privacy and could ruin investments. I might do a poll at some point to ask the community, but for now I'll put this into "very unlikely ideas".
