### ISSUE TITLE
Ad Infinitum not counted as a legendary skin or item on statistics page

### ISSUE THREAD

**Issue by Scath-Enfys** [gw2efficiency/issues#208]
Title says it all. Made ad infinitum last night, and while the value seems to have been added properly, my legendary skins / items count on the detailed statistics page has not increased.

**Comment by queicherius** [comment]
It should definitely be included in both the item and skin count, I just double-checked the code. Care to send me your API key via Mail admin@gw2efficiency.com or post it here?

**Comment by Scath-Enfys** [comment]
Nevermind, must just have been slow to update. It's showing now.
