### ISSUE TITLE
Link to wiki page in crafting tree broken

### ISSUE THREAD

**Issue by NekiCat** [gw2efficiency/issues#211]
When using a non-English language, the link to the wiki page for an item is broken. The link goes to the English wiki, but uses the translated item name as the query, which leads to an empty page, most of the time.

The links should either lead to the localized wiki page by altering the wiki base URI based on the selected locale, or alternatively to the English wiki by using the English item name for the link instead of the localized one.

**Comment by queicherius** [comment]
Oh, whoops. Thanks for the report. D:
