### ISSUE TITLE
Add query string for tradingpost

### ISSUE THREAD

**Issue by Scath-Enfys** [gw2efficiency/issues#214]
Fairly simple, but a must if you want the TP section to compete with dedicated TP sites. you need a way to add the search filters into the page URL. Since you've already done this for the crafting page, it shouldn't be too hard to do for the TP page.

Suggested URL rewrite pattern:
/search-search-string-here/order-invprofit/buymin-20
becomes
/?search="search-string-here"&order="invprofit"&buymin="20"

I could add more params but you get the idea.

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
