### ISSUE TITLE
Add buy and sell velocity as statistics

### ISSUE THREAD

**Issue by Fulgeri** [gw2efficiency/issues#215]
number of items bought or sold in past 24 hours, perhaps with an additional "average" velocity, would be a great enhancement. AFAIK only 2 sites currently show this.

**Comment by queicherius** [comment]
The "number of items sold" would also include the items that just got taken off the TP, since that's not distinguished by the API.

**Comment by Scath-Enfys** [comment]
I understand this. Likewise, the number bought would include canceled 
items. It's not exact, but it's a lot better than no information at all.

**Comment by queicherius** [comment]
Closing for inclusion in #117
