### ISSUE TITLE
Improve choosing account statistics

### ISSUE THREAD

**Issue by risingashes** [gw2efficiency/issues#217]
Feels like a step backwards.

The need for it is understandable as the ability to account for future expansion of categories is important. But the dropdown is fairly clunky both in terms of picking categories and returning to it when wishing to change categories.

Previously you could examine a large swathe of categories without interaction and pick between them (often something catching your eye), now you need to specifically be looking for something and the speed at which you find it is random based on closeness to top.

Is it possible to instead have the menu docked on the left hand side of the screen, expanding instantly once moused over and independently scrollable (the top of the screen could have a 'filter' button that initiates a slightly slower scroll across of the left panel to demonstrate usage if you think that would be an issue)? This would allow for expandability, while still giving the advantage of seeing around 8x as many categories as are viewable in the dropdown, and making the menu available without having the scroll back to the top of the screen every time.

If categories are expanded significantly the same problem of lower categories being more frustrating would occur, but it'd still be 8x better than currently.

The UI placement, in concept would be the left panel taking up 10% screen space while docked, and 80% undocked, with the nonpanel screen taking up 90% and then 20% with a small piece of the chart to demonstrate to the user what is happening and how to return if, for some reason, they wish to simply return to the chart they were already on.

**Comment by queicherius** [comment]
> The need for it is understandable as the ability to account for future expansion of categories is important. But the dropdown is fairly clunky both in terms of picking categories and returning to it when wishing to change categories.

Yes, it's definitely needed since I want to add 34 new statistics just in the new batch coming soon, and even more in the future.

> Is it possible to instead have the menu docked on the left hand side of the screen, expanding instantly once moused over and independently scrollable (the top of the screen could have a 'filter' button that initiates a slightly slower scroll across of the left panel to demonstrate usage if you think that would be an issue)? This would allow for expandability, while still giving the advantage of seeing around 8x as many categories as are viewable in the dropdown, and making the menu available without having the scroll back to the top of the screen every time.

I agree that there is could be a  problem with being able to skim statistics, especially when the list grows. However, I don't agree with your proposed solution. Mouse-over-extend systems are (imo) nearly always a usability nightmare. Also putting anything on the sides of the page is a no-go since that makes the graphs smaller and the personal graph is already quite small.

**Comment by risingashes** [comment]
>and the personal graph is already quite small.

Then are you married to the idea of the graph and Rank/Value/Next text sharing a horizontal space? Seems a row below the graph with the three lines merged onto one would allow the graph to return to it's original size, all for easier viewing of the Rank/Value/Next data while also viewing the leaderboard.

Currently the user eye movement (assuming they'll look at each segment, is a triangle rather than the more comfortable downwards wander.

![image](https://cloud.githubusercontent.com/assets/12869762/18515272/1bc05f2a-7ad8-11e6-808a-fd9a949ec3a8.png)


>proposed solution

Okay, then what about just making the dropdown multitiered based upon platform. PC would easily have three rows once clicked, and the menu could be located below the graph as it'll be then accessable regardless of whether you're looking at the bottom distribution graph or the top historical graph.

![image](https://cloud.githubusercontent.com/assets/12869762/18515203/e3dfde00-7ad7-11e6-9652-910c592b16df.png)



A combination of both would be:

![image](https://cloud.githubusercontent.com/assets/12869762/18515239/fe8e34a4-7ad7-11e6-8e99-07c64d51108e.png)

**Comment by risingashes** [comment]
PS: As an aside, the Next Rank value should probably be the differential from current.

If I have 160 Zhaitan Tokens and want to beat the next rank, who has 167 tokens, the relevant figure is +7 as that's the amount of difference I need to achieve, rather than 167.

**Comment by queicherius** [comment]
> Then are you married to the idea of the graph and Rank/Value/Next text sharing a horizontal space? Seems a row below the graph with the three lines merged onto one would allow the graph to return to it's original size, all for easier viewing of the Rank/Value/Next data while also viewing the leaderboard.

The reason for that is that there will be more values than "Rank/Value/Next", but they are not ready yet. I also think that "Rank" is the most important thing on the page, and not the graph. Also putting the select-box below the graph is a no-go, it always has to be at the top of the page, else it makes 0 sense ("what graph am i looking at?") when you load the page up.

I can try and make the dropdown open in multiple rows, that would be good. However I am using a plugin, so I am not sure that's possible. I can also add "previous" / "next" buttons, so you can scroll through things more easily (since that seems to be your main issue).

> The next rank value should probably be the differential from current.

Good point, I'll do that.

**Comment by queicherius** [comment]
Alright, I kinda hacked that behaviour into the plugin. Looks like this now:

![](http://i.imgur.com/sDTCFQG.png)

I think that's not too agressive, and gives enough data to "browse" :)

**Comment by risingashes** [comment]
Massive improvement.

>I can also add "previous" / "next" buttons, so you can scroll through things more easily (since that seems to be your main issue).

That's not really the issue I'm trying to explain, ny issue is specifically the lack of a smorgestboard feeling that was lacking from the second most recent style.

Think about the user interaction with the menu, do the majority of hypothetical users have a distinct statistic they wish to look at every time they go to the dropdown? I'd think not. There are certainly one or two instinctive insights that players will want to see "I wonder what rank I am in pvp wins", but most users will likely be scrolling through the dropdown, see pvp wins, and think- "hey, that'd be interesting".

A single stream dropdown makes discovery more of a chore, something which the three stream dropdown helps greatly.Ideally the dropdown would, in it's final implementation, take up as much screen space as possible while still allowing the user to click out if they decide against picking an option.

A <next> <previous> button would be horrible in terms of what I'm talking about regardless of how many catagories end up being added as users would then have to re-orientate themselves on each page refresh.

For long term users, who may have less desire for exploration, a customized category listed at the top of the menu, made up of recently (or most frequently) viewed statistics would likely be the best middleground.

**Comment by queicherius** [comment]
> but most users will likely be scrolling through the dropdown, see pvp wins, and think- "hey, that'd be interesting".

Yeah, I realised that as well, which is why I went with something similar to what you to what you suggested.

> A (next) (previous) button would be horrible in terms of what I'm talking about regardless of how many catagories end up being added as users would then have to re-orientate themselves on each page refresh.

Yep, that got scrapped with the new design.

> For long term users, who may have less desire for exploration, a customized category listed at the top of the menu, made up of recently (or most frequently) viewed statistics would likely be the best middleground.

Eh, right now I think it's fine. You can see nearly everything within a few seconds, and the amount of categories is balanced. :)
