### ISSUE TITLE
Feature Request: Add account bound materials and currencies to all crafting 'cost' displays

### ISSUE THREAD

**Issue by dbenoy** [gw2efficiency/issues#234]
When I look up crafting recipes, and I see the 'cost' in gold, I was wondering if I could also mouse over or click or something to display all the account-bound costs, like currencies and materials that you can't buy.

**Comment by dbenoy** [comment]
It would also be nice if it had a tiny blurb beside each one explaining where to find it.

**Comment by queicherius** [comment]
Duplicate of #64
