### ISSUE TITLE
Help available

### ISSUE THREAD

**Issue by stygiansabyss** [gw2efficiency/issues#244]
Noticed on your personal site that gw2eff uses laravel. Figured I would offer to help if you ever needed it.

:)

**Comment by queicherius** [comment]
Hey! That info is actually quite outdated. It uses about 85% node.js now. Feel free to look around and take your pick, if that's your boat! Issues that the code is fully online and are fairly isolated (good starting points) would be for example #223 and #225. :)

**Comment by stygiansabyss** [comment]
Cool. Ill check out the code soon as possible

**Comment by queicherius** [comment]
I'll close this issue, so the issue list is a bit cleaner. However, help would still be appreciated. 😄
