### ISSUE TITLE
Fractal tonics statistics

### ISSUE THREAD

**Issue by etherealdi** [gw2efficiency/issues#250]
I have 4 tonics since I bought one from the new vendor but the site rankings still lists 3.

http://i.imgur.com/na3OCVh.png

I haven't converted any of them.

**Comment by queicherius** [comment]
Did at least 24 hours pass since you bought the item from the vendor? If yes, feel free to pass me your API key and I'll take a look.

**Comment by etherealdi** [comment]
Only 1 hour but the histogram already shows that I have 4 in my possession. Just the leaderboard is not reflecting that.

**Comment by queicherius** [comment]
If the histogram already shows it, then the crawler already picked it up. The leaderboards take a while to update, they get updated around every 6 hours (but they are currently on :fire:, so I am doing it manually - last time was 2 hours ago or so, next time will be tomorrow morning).

Everything is fine, just needs a little time! :)
