### ISSUE TITLE
Add Gold Value in Tooltip to Gemstore Items in Wardrobe

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#257]
I just checked my wardrobe this morning and noticed that it shows how much an item might cost in gems. What would be super cool, is if this gem value could be translated into gold with the current exchange rate and shown in the tooltip.

**Comment by queicherius** [comment]
It is shown in the [tooltip of the item](http://i.imgur.com/JAjzY4u.png), if that fits your usecase?

**Comment by rediche** [comment]
Yes, it's shown in the tooltip when you clicked the item. I would personally prefer that I wouldn't have to click an item to see it's value in gold. 

This is where I feel like the gold value is missing: http://i.imgur.com/j2KvzBS.png

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
