### ISSUE TITLE
Add query string for crafting calculator

### ISSUE THREAD

**Issue by BTooLs** [gw2efficiency/issues#258]
Hello, keep up the good job!!

When I craft heavier stuff (like ascended) I bookmark my item list, to check daily what I need to gather/buy. It's annoying because I need to always select "Use own materials" option and refresh the page/form. If the params were in the URL would be easier.

https://gw2efficiency.com/crafting/calculator/46774-Zojja's-Blade?own_materials=yes,daily_cd=no

Thanks.

**Comment by Scath-Enfys** [comment]
Technically this would be an expansion of the already-existing query string $id-$item-name, but I agree. Perhaps something like /crafting/calcualtor/$id-$item-name(,$id2-$name2,...$idn-$namen),own-$use-own-mats,cd-$daily-cd

**Comment by queicherius** [comment]
This is now live (including amounts and all other options). Thank you for your feedback. 😄
