### ISSUE TITLE
Mini Snuggles and Mini Baron Von Scrufflebutt mystic forge recipes not found

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#264]
The crafting tool is not capable of determining the cost of crafting the Mini Old Tom because it doesn't know about the mystic forge recipes for Mini Snuggles and Mini Baron Von Scrufflebutt

**Comment by queicherius** [comment]
I completely lost this issue out of sight, but this is done in the next release as #271. :)
