### ISSUE TITLE
Tradingpost history is missing prices from collumns 

### ISSUE THREAD

**Issue by Scath-Enfys** [gw2efficiency/issues#266]
As you can see in the below image, everything but current TP prices and quantity is missing. This applies to both collapsed and non-collapsed views.
![image](https://cloud.githubusercontent.com/assets/18603678/19053937/bbbab06c-8982-11e6-9cb5-32b1a98e3f67.png)

**Comment by queicherius** [comment]
Ugh. I thought I fixed that with #247, but I forgot about it. Getting fixed asap.

**Comment by queicherius** [comment]
Fixed.
