### ISSUE TITLE
Allow searching for upgrades that are already put in items

### ISSUE THREAD

**Issue by Archomeda** [gw2efficiency/issues#267]
Currently it only searches for items on an account. It would be helpful to have an option to include upgrades that are already put in items.
My use case for the moment: search for all simple infusions that I have in order to exchange them for the normal +5/+7 infusions.

**Comment by queicherius** [comment]
This is actually super easy since #156. Coming very soon. Thanks for the idea!

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
