### ISSUE TITLE
Show  the total of GEMS assocated with my account

### ISSUE THREAD

**Issue by Rwfrk** [gw2efficiency/issues#269]
This will make it easier to see value swings in gemstore items due to gems->gold

**Comment by queicherius** [comment]
I am not exactly sure what you mean by this. If you want to see the total amount of theoretical gems on your account, there is a value for that. And if you want to see what part of the value swing is attributed tp ge,s, you can just compare the account value incl. gemstore items against the account value excl. gemstore items. Maybe i am misunderstanding?
