### ISSUE TITLE
Old Tom miniatures are "not sold or crafted"

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#271]
https://gw2efficiency.com/crafting/calculator/76761-Mini-Old-Tom

Currently, Professor Mew is shown as buyable from the trading post, but the other three miniatures are shown as "not sold or crafted", which makes the recipe cost 3 silver instead of 200+ gold like it actually does.

**Comment by queicherius** [comment]
Thanks for the report! Looks like that's some mystic forge recipes missing. Looking into it.

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
