### ISSUE TITLE
Crafting Calculator - Use the sell price of items if the buy price is "0c"

### ISSUE THREAD

**Issue by yorii** [gw2efficiency/issues#272]
But can be bought for 19 copper on TP.

**Comment by queicherius** [comment]
This is a bug that happens, because the buy price for "leaf fossil" is 0c. If you swap to the sell price it works as expected.

**Comment by yorii** [comment]
I see! Well that makes sense, but maybe items without buy orders should list the sell price instead?

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
