### ISSUE TITLE
Add initial gold price to guild upgrades

### ISSUE THREAD

**Issue by JordanJD** [gw2efficiency/issues#276]
The market upgrade 'deep cave' costs 100 gold (cash) but no materials. The current system says there is no gold cost.

**Comment by queicherius** [comment]
I thought I did that already. 😞 Going in soon.

**Comment by queicherius** [comment]
Turns out I didn't add that, because the needed data is not in the API. Added a new issue [here](https://github.com/arenanet/api-cdi/issues/389).

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
