### ISSUE TITLE
Build Editor

### ISSUE THREAD

**Issue by MaximDeprez** [gw2efficiency/issues#282]
Since existing build editors our out of date or just have wrong calculations and not being updated, It would be a good idea to have a build editor that had anything you need to theorycraft a new build. Maybe even implement a system like gw2power so you could see the effective power of the build. If this feature was implemented right then I am certain alot of people would use it often especially big theorycrafters

**Comment by queicherius** [comment]
While I agree this would be neat, this is a giant project in itself. I just don't have the resources to take on something like that (on top of gw2efficiency). If someone wants to step up and make one that you can embed, i'd be more than happy to include it into gw2efficiency itself.
