### ISSUE TITLE
Include guild banks into the account search

### ISSUE THREAD

**Issue by daniel-l** [gw2efficiency/issues#283]
Hey, I'd love to have this site include an all-inclusive account search, similiar to http://gw2maps.ch/accountViewer/  which also includes the ability to search all "connected" guild banks. I've got several "old" guild banks with fully upgraded storage caves to store crafting materials, trading post stuff etc which are a horror to keep track of. Such a feature should make it easier to find the stuff you're looking for without checking every guild bank in game or here on gw2efficiency with the current not-so-great guild bank system.

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
