### ISSUE TITLE
Add a Day/Night clock

### ISSUE THREAD

**Issue by BenjaminMWargo** [gw2efficiency/issues#285]
Day/Night system follows real time and certain tasks ( for example Astralaria Precursor Collection IV ) can only be done at night time.  Wiki gives the guide lines for day/night but there is not an active clock for it. https://wiki.guildwars2.com/wiki/Day_and_night

How I would do it is just to have a clock in the corner with the background of it changing based on in-game state.

**Comment by BTooLs** [comment]
+ A clock in the UI with the time remaining of the current state would be great.
Idea: make the background of the page/header/menu or something change , dark vs white

**Comment by queicherius** [comment]
Will be part of #1612
