### ISSUE TITLE
Add a wishlist

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#30]
This is a feature that shines for birthdays / random acts of kindness. Kind of like an amazon wishlist.
- [ ] Add items to your wishlist
- [ ] Able to share / look up other user's wishlist

**Comment by mirtisdyleris** [comment]
would be interesting :)

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

**Comment by tawniey** [comment]
Given that this was closed so many years ago, may I comment to petition it reconsidered? I've been wanting this functionality for a while now, and it seems like there aren't any other wishlists out there that can make use of an API-key to show whether it's been obtained. <3 

Thanks in advance!

**Comment by queicherius** [comment]
I still think this is out of scope for gw2efficiency at this time, and probably better suited as a different project.
