### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by BTooLs** [gw2efficiency/issues#300]
I searched in issues but couldn't find this request, strange, I found an old topic on reddit though.

---
Daily todo list would be awesome, I'm using dailytodo.org now. Could reset at each server reset like dailies. 
Bonus : weekly reset. 
Bonus: items can be links ( external urls or in-game items) or to TP items, or to crafting calculators
Bonus: reminders like the Google inbox ones ( or sort by wheb needs to be done date).

usages:
- time gated actions (collect, crafting, convertors, dailies, etc etc)
- trading reminders (ex buy wensday and sell saturday)
- crafting reminders

**Comment by queicherius** [comment]
This is pretty what is meant with #62. I have a lot of neat ideas for that page, but I have to clean up some things before i can start on new features right now.
