### ISSUE TITLE
Add the recipe for Mini Aurine

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#310]
See [wiki](https://wiki.guildwars2.com/wiki/Gift_of_Aurene)

**Comment by BenLubar** [comment]
`s/Aurine/Aurene/g`

**Comment by Rwfrk** [comment]
Mini Aurine still doesnt show on https://gw2efficiency.com/crafting/calculator for me. The other recipes added in the 12-09 build do.

**Comment by BenLubar** [comment]
@Rwfrk Aurene shows up for me here: https://gw2efficiency.com/crafting/calculator/79766-Mini-Aurene

**Comment by queicherius** [comment]
For reference, the issue of @Rwfrk fixed itself. Probably caching things.
