### ISSUE TITLE
Add notifications on the tradingpost pages

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#38]
When getting overbid / undercut there should be a notification popup and text-to-speech message.

**Comment by Scath-Enfys** [comment]
this should be optional. I don't want this happening randomly.

**Comment by queicherius** [comment]
> this should be optional. I don't want this happening randomly.

Yeah, this would be a toggle similar to on the worldboss page.

**Comment by queicherius** [comment]
Closing for #1365, because that's a better idea.
