### ISSUE TITLE
Save and load filters and daily checkmarks

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#47]
All filters and settings on all pages should be synced with the user account, so when revisiting the page everything is the same

---

Prerequisites: #22

**Comment by nmss** [comment]
does this include saving the collapse state of the daily boxes ?

**Comment by queicherius** [comment]
Yeah, that would be in here too.

**Comment by queicherius** [comment]
Filter states are preserved in the URL since September, so going to close this one out too :)
