### ISSUE TITLE
Add tooltips to tradingpost icons

### ISSUE THREAD

**Issue by mgarin** [gw2efficiency/issues#596]
This might be a really good minor addition to the page (even before any revamps) - allow viewing detailed item information from the "Tracked items" table like you can do in other pages.

Here is a specific example why it is really useful - I'm currently tracking Ghostly and Phospholuminescent infusions and this is how table look like:
![image](https://cloud.githubusercontent.com/assets/2361389/20787047/e0e90968-b7ba-11e6-82d0-4b18b959b029.png)
There is simply no way to distinguish different types (power/condi/...) of infusions between each other except for some really inconvenient workarounds.

Doing a hover tip with detailed info might be an overkill as it is not always required there (mostly not except cases like I've shown) so it might be good to add the tip upon clicking on the item name cell in table and maybe add a small "INFO" button in the same cell near "COPY" button to ensure people know it is there and won't miss it.

**Comment by queicherius** [comment]
Items in the tradingpost section now have tooltips.
