### ISSUE TITLE
Invalid API key when accessing from mobile device after changing API key

### ISSUE THREAD

**Issue by rvgate** [gw2efficiency/issues#615]
When accessing the website through a mobile device right after you changed the key on your account somewhere else, every page results in an invalid API key error page.

Opening the page in incognito and logging in seems to be a solid workaround.

**Comment by queicherius** [comment]
> When accessing the website through a mobile device right after you changed the key on your account somewhere else, every page results in an invalid API key error page.

Could you explain a little more what you mean by that? I can't really follow the steps you are taking.

**Comment by rvgate** [comment]
1) Open gw2efficiency.com on your mobile device
2) Login
3) Go to any page that requires your API key, in my example I went to my wallet
4) Receive a sad quaggan with the message "API key invalid"

This would be fine if my API key is actually invalid, however it works fine when going incognito or when accessing the same page using a desktop.

Note that basically everything requested from the API is either blank or gives me that error page.

**Comment by rvgate** [comment]
Additionally, I noticed I had 2 API keys registered to my account... 1 invalid and 1 valid. Removing the invalid one solved the issue. But could possibly still be a bug (because why use the invalid key if there is a valid one available on the account)

**Comment by queicherius** [comment]
Yeah, if you had an invalid key on your account and that one selected, then that would happen.

It doesn't check the keys for validity on every pageload (just for performance reasons atm), but it does tell you the issue when you load the page (with the "API key is invalid"). :)

**Comment by rvgate** [comment]
I would like to mention, that even with 2 keys on your account (1 valid and 1 invalid) this problem did not happen on my desktop or when browsing the website in incognito.

I think closing this issue is a bit too soon

**Comment by queicherius** [comment]
> I would like to mention, that even with 2 keys on your account (1 valid and 1 invalid) this problem did not happen on my desktop or when browsing the website in incognito.

If I had to guess, you had the invalid key selected in your non-incognito mode, then that error tells you that you have the invalid one selected.
