### ISSUE TITLE
Incomplete crafting list for "Chest of Experimental Armor"

### ISSUE THREAD

**Issue by kraussimon** [gw2efficiency/issues#616]
Only the first 6 items in the collection are shown.

https://gw2efficiency.com/crafting/calculator/77392-Chest-of-Experimental-Armor

**Comment by queicherius** [comment]
You could also fix this one by youself, since you offered to help with #617 😄. Might be a good start into the material.

The recipe is in the same file I linked there.

**Comment by queicherius** [comment]
Implemented by [this PR](https://github.com/gw2efficiency/custom-recipes/pull/1).
