### ISSUE TITLE
Adding crafting overview for legendary armor

### ISSUE THREAD

**Issue by kraussimon** [gw2efficiency/issues#617]
I'm starting to work on legendary armor and I went to gw2efficiency in the hope for something like this: https://gw2efficiency.com/crafting/calculator/30704-Twilight
But I couldn't find it. 

I know that legendary armor is not yet officially obtainable and parts of the required mats/items aren't fixed yet. But since I wish to prepare in advance based on the information we do have, I want to get an overview of the mats that I'm missing still. I was about to make a classic spreadsheet, but before I go ahead with that archaic method of tracking, I wish to ask for a feasibility of such a feature on gw2efficiency.
I think with the use of a disclaimer, that this recipe is not fixed in stone, it's okay to have this very useful feature for anyone that is preparing for it like I am now.

**In addition, I want to offer help to make this happen.** I know a little bit about coding, but not enough to write anything of use, but I'm willing to markup a recipe tree in accordance to what gw2e needs (, if marking up some data is the method of how recipes are done. I was looking at this: https://github.com/gw2efficiency/recipe-nesting).

**Comment by queicherius** [comment]
Hey there! If you want to help to make a recipe for it, be my guest. 😄 

All the custom recipes live in [this repository](https://github.com/gw2efficiency/custom-recipes), in [this file to be exact](https://github.com/gw2efficiency/custom-recipes/blob/master/recipes.json). The format is the same the official API uses, but you should be able to see how it works from the file as well.

**Comment by kraussimon** [comment]
I think I understand what to do after having a quick look. Adding new items to the custom recipy is easy to do as far as I can see.
One question, though: What is an easy way to get bulk api info about a list of items?
I found ways to look for single items like so for example with gw2spidy: http://www.gw2spidy.com/api/v0.9/json/item-search/Infused%20Living%20Crystal
And I know I can use the official api if I have the ID. (Like so: https://api.guildwars2.com/v2/items/77467)
But I have a big list of items I need to know at least the ID (but probably more). Do I really need to go through each single item?

**Comment by queicherius** [comment]
> What is an easy way to get bulk api info about a list of items?

I personally use an internal tool for that, I'll see if I can make it online in a bit (it's currently broken).

The other option (except spidy) you have is checking on the wiki (the item id is encoded in the chat link they display), but that is even more work.

> What do I do for placeholders and how should I name the legendary armor?

The names in that file get ignored by gw2efficiency right now, so feel free to just call it `[LEGENDARY ARMOR]` or similar. For the "how" you do it, just do what you think makes most sense. I didn't even start with the crafting of the legendary armor yet, so your judgement is worth more.

> I assume, I just create a pull request or something in the official repository, or what's the preferred way to get changes like this going?

Yep, just create a PR on that repo when you want to change something and I'll look over it and then give comments if something is off or merge it if it looks good. ☺️

**Comment by kraussimon** [comment]
I think I can plot this together now. My problem is, that there are many items that don't have an ID in the API yet. There are some fields I don't know how to fill out. Here are the recipes for the armor itself and one of the gifts to show what I mean. (I put the names of the items in parenthesis just for the sake of this question.)
The fields I don't know what to do:

- **id** for all items
- **item_id** and **output_item_id** for all items that aren't in the API yet (is there a way to use placeholders?)

```
{"disciplines": ["Mystic Forge"],
"id": "",
"ingredients": [
	{"count": 1, "item_id": 78938}, (Chest of Refined Envoy Armor)
	{"count": 6, "item_id": }, (Gift of Prosperity)
	{"count": 6, "item_id": }, (Gift of Prowess)
	{"count": 6, "item_id": }, (Gift of Dedication)
],
"name": "Legendary Armor Piece",
"output_item_count": 6,
"output_item_id": ,
"type": "Armor"}

{"disciplines": ["Mystic Forge"],
"id": "",
"ingredients": [
	{"count": 1, "item_id": 77451}, (Gift of Craftsmanship)
	{"count": 15, "item_id": 19675}, (Mystic Clover)
	{"count": 1, "item_id": 76530}, (Gift of Condensed Magic)
	{"count": 1, "item_id": 70867}, (Gift of Condensed Might)
],
"name": "Gift of Prosperity",
"output_item_count": 1,
"output_item_id": ,
"type": "Trophy"}
```

**Comment by queicherius** [comment]
> id for all items

The `id` can be whatever you want. It's basically only there to overwrite official recipes if needed. You can use e.g. `-9999999` for all of them.

> item_id and output_item_id for all items that aren't in the API yet (is there a way to use placeholders?)

There is an internal way to add placeholders, but that part of the code is not public yet... Hm. For now you could just use ids > 200000 or something and a list of what is what. I'll try to get that part of the code public soonish and write a note here when it is. If you are done before that I can manually add them as well.

**Comment by kraussimon** [comment]
I tried to make a PR but tbh I don't want to get into it too much. If you wouldn't mind, you could add it for me. Here are the new recipes and a list of the new items: (I didn't use code so its easier to copy). Let me know if this needs to be done differently. Source for the recipes is Dulfy.(http://dulfy.net/2016/06/17/gw2-legendary-armor-collection-crafting-guide/)

{"disciplines": ["Mystic Forge"], "id": "-99999", "ingredients": [{"count": 1, "item_id": 78938}, {"count": 6, "item_id": 200002}, {"count": 6, "item_id": 200003}, {"count": 6, "item_id": 200004}], "name": "Legendary Armor Piece", "output_item_count": 6, "output_item_id": 200001, "type": "Armor"},
  {"disciplines": ["Mystic Forge"], "id": "-99999", "ingredients": [{"count": 1, "item_id": 77451}, {"count": 15, "item_id": 19675}, {"count": 1, "item_id": 76530}, {"count": 1, "item_id": 70867}], "name": "Gift of Prosperity", "output_item_count": 1, "output_item_id": 200002, "type": "Trophy"},
  {"disciplines": ["Mystic Forge"], "id": "-99999", "ingredients": [{"count": 25, "item_id": 77302}, {"count": 1, "item_id": 20852}, {"count": 50, "item_id": 19925}, {"count": 1, "item_id": 73137}], "name": "Gift of Prowess", "output_item_count": 1, "output_item_id": 200003, "type": "Trophy"},
  {"disciplines": ["Mystic Forge"], "id": "-99999", "ingredients": [{"count": 5, "item_id": 73537}, {"count": 5, "item_id": 74356}, {"count": 5, "item_id": 72205}, {"count": 1, "item_id": 200005}], "name": "Gift of Dedication", "output_item_count": 1, "output_item_id": 200004, "type": "Trophy"},
  {"disciplines": ["Merchant"], "id": "-99999", "ingredients": [{"count": 250, "item_id": -19}, {"count": 250, "item_id": -20}, {"count": 250, "item_id": -22}], "name": "Gift of the Pact", "output_item_count": 1, "output_item_id": 200005, "type": "Trophy"}

- 200001, Legendary Armor Piece
- 200002, Gift of Prosperity
- 200003, Gift of Prowess
- 200004, Gift of Dedication
- 200005, Gift of the Pact

**Comment by queicherius** [comment]
Nice, thank you a bunch! I'll see that this gets into the next release.

**Comment by queicherius** [comment]
This is now live. Thank you for your help! 😄
