### ISSUE TITLE
Bugged Script on the TP page

### ISSUE THREAD

**Issue by bic-mag** [gw2efficiency/issues#625]
When working with the TP page for a while there's a JavaScript not responding, showing the following message:
https://gw2efficiency.com/build/script.js:25
It also lags the entire browser (Firefox).
It consistently happens after entering the page, searching for any term (in my case: "Frostforged") and waiting for about 2-3 Minutes.

**Comment by queicherius** [comment]
I found the issue and just deployed and confirmed the fix (at least for my Firefox version). Thank you for the report! 😄
