### ISSUE TITLE
when showing upgrade, display the item which holds the upgrade

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#626]
Currently, when displaying an upgrade, (such as when searching with upgrades enabled) we show only the upgrade itself, rather than showing the item it is attached to. This can make it painful when attempting to search for the location of a specific upgrade, as I have to go in game and check through every item.

It would be nice if the item would show, and when highlighting, the item which holds the upgrade could be shown.

**Comment by queicherius** [comment]
This is now live.
