### ISSUE TITLE
Shared character is 'empty'

### ISSUE THREAD

**Issue by Greaka** [gw2efficiency/issues#628]
Sometimes shared characters don't provide any information to others. Private message for example link. Every tab looks as empty as in the picture

![Imgur](http://i.imgur.com/4CCiKFx.png)

**Comment by queicherius** [comment]
That's super weird. Please send me the example to admin@gw2efficiency.com

**Comment by queicherius** [comment]
Since there was no follow-up and no other reports, I'll close this.
