### ISSUE TITLE
Mystic Clover Recipe is wrong

### ISSUE THREAD

**Issue by Halvaard** [gw2efficiency/issues#640]
It's showing:  4x Obsidian Shard,  4x Mystic Coin ,  4x Glob of Ectoplasm ,  24x Philosopher's Stone 

Should be  1 OS, 1 MC, 1 GoE, 6 PS

**Comment by queicherius** [comment]
The recipe takes the chance of getting a mystic clover into consideration, [which is about 30%](https://wiki.guildwars2.com/wiki/Mystic_Clover/Drop_rate). This is done so resulting items get the correct value attached to them (and you're going to need that many ingredients on average as well).

**Comment by Halvaard** [comment]
Then I suppose it should have a note attached, either about the 30% chance
or "output: 0 to 4 clovers"
