### ISSUE TITLE
Add statistics for the currently active playerbase

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#653]
Since the account statistics get generated about every 24 hours, it would be possible to use the `playtime` statistic to check if a player played a minimum amount (e.g. 30 minutes) in a specific timeframe (e.g. a month). This would allow calculating and graphing the "active" playerbase.

Another interesting use case for this is that we could use this data to generate statistics only from the active players, as suggested in #680, to eliminate the issue of quitting players making new content seem less played percentage wise.

**Comment by vivanov-dp** [comment]
It would also be interesting to see stats about professions and etc played for the last month, 3 months, year, etc. It can give insights about the current meta

**Comment by queicherius** [comment]
Closing this. If you want reasoning, PM me.

**Comment by queicherius** [comment]
Reopened because we got the OK from ArenaNet.

This is also MUCH easier now that we have `lastModified` in the account blob, we can now determine active players via  "`lastModified` < 30 days + at least one character with level 70+".

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
