### ISSUE TITLE
Add value to Living World Season 1 rewards

### ISSUE THREAD

**Issue by Scath-Enfys** [gw2efficiency/issues#654]
https://www.gw2bltc.com/en/item/66216-Mini-Panda

https://www.gw2bltc.com/en/item/66214-Endless-Dolyak-Calf-Tonic

these items have no value. Perhaps add the vendor cost (25 laurels + 15g)?

**Comment by queicherius** [comment]
Turns out all the [LW 1 rewards](https://wiki.guildwars2.com/wiki/Laurel_Merchant#Living_World_Season_1_Rewards) don't have a value attached.

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄
