### ISSUE TITLE
Find a better way to backup the database

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#656]
So right now I backup the database by taking a copy of the entire VM the DB is running on. This is obviously not the best method, since it has the overhead of all the OS files. `mongodump` however, just seems to crash the database outright.

Another issue with doing backups this is that the maximum size of the HDD is ~110 GB, which is already getting critical (~70 GB data size, ~16 GB storage size).

**Comment by rikkuness** [comment]
Be interesting to know what it is that causes the mongodump to crash, perhaps just lack of resources? I think the best bet to not impact performance is to run a 2nd instance of the database on a different VM that's a replica set of the primary, that way you can take backups of the secondary and not impact performance of the primary.

**Comment by queicherius** [comment]
> Be interesting to know what it is that causes the mongodump to crash, perhaps just lack of resources?

I have no idea, but the DB I run it against just gets super unresponsive. :(

> I think the best bet to not impact performance is to run a 2nd instance of the database on a different VM that's a replica set of the primary, that way you can take backups of the secondary and not impact performance of the primary.

I would love to do that, but I don't think I have the resources for that. Do I need to have have a HDD of the size of the storage or the data size in that VM? Because the current VM has ~ 66gb used HDD space...

**Comment by LyannaTarg** [comment]
Which version of mongodb do you run and on which operating system? possibly i can help... I'm a DBA (also for mongo, but mostly an Oracle/MySQL one)

Moreover answering your comment on January 15: in the 2nd VM you have to add the same space of the primary. The data is replicated entirely.

**Comment by queicherius** [comment]
@LyannaTarg 

The issue here is slightly aged. We are currently running on a new server infrastructure, so we don't use VMs anymore, instead, we have a docker container with the host mounting in a volume for the persistent storage. We also have about 30x the storage capabilities than before. So we have no issue getting the data out of mongo anymore. I am doing a write flush/lock -> LVM snapshot -> write unlock -> LVM mount [as advised from Mongo](https://docs.mongodb.com/manual/core/backups/#back-up-with-filesystem-snapshots).

The issue atm is currently that syncing the mounted volume to the backup storage is taking **ages**.

1) The connection to the backup space is _slow_. I am taking with my hosting support here, so nothing I can really do.
2) I tried to do incremental backups using [duplicity](http://duplicity.nongnu.org/index.html), but it's just too slow hashing/diffing. If you have any better tools here, let me know! Should work for ~ 1 TB data with changed ~ 100 GB in < 3 hours.

**Comment by queicherius** [comment]
Thanks to a move to a different infrastructure, backups are handled by the server provider and don't have to rely on hacky bash-scripts anymore! 🎉
