### ISSUE TITLE
Spinal Blade pack crafting lacks mystic forge promotion for watchwork sprockets to blade shards

### ISSUE THREAD

**Issue by slippycheeze** [gw2efficiency/issues#658]
I'm not sure if this is intentional or not, but the promotion path via the mystic forge in crafting https://gw2efficiency.com/crafting/calculator/50056-Synergetic-Tempered-Spinal-Blades for the watchwork sprockets to blade shards is omitted.

**Comment by queicherius** [comment]
This is not intentional, but the result of a other issue - I removed demotions and recursive recipes because the calculation does not handle them propperly.

(Closed as duplicate of #164)
