### ISSUE TITLE
Hide uncompletable dailies based on level

### ISSUE THREAD

**Issue by regendo** [gw2efficiency/issues#659]
Basically, only show the dailies that are actually available for you in-game. If you have a level 80 character, don't display the level 11-59 Daily Plains of Ashford Event Completer. If you don't own Heart of Thorns, don't display the HoT-required Daily Heart of Maguuma Forager. And so on.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
