### ISSUE TITLE
Add "guaranteed wardrobe unlock" filter

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#660]

**Comment by SaiyanOfDarkness** [comment]
Can't wait for this one !

**Comment by valento92** [comment]
Me too!!

**Comment by coldwaterq** [comment]
👍

**Comment by gumadozucia** [comment]
This would be amazing. I've been going through all merchants and TP trying to get every rare or lower mini/dye/skin but the only ones I really care about are the unlocks from guaranteed wardrobe unlock.

**Comment by ShiningMassXAcc** [comment]
+1

**Comment by ShiningMassXAcc** [comment]
In case you haven't seen the following for inspiration:
- https://immortius.net.au/wardrobe-unlock-analyser/
- https://github.com/immortius/gw2-wardrobe-unlock

What this site is missing that you have access to is better projections of cost or ease to obtain for non-gold related items in the "Analyze" feature from the above.

**Comment by queicherius** [comment]
Now (finally) live
