### ISSUE TITLE
Character list link doesn't work

### ISSUE THREAD

**Issue by RafiXWPT** [gw2efficiency/issues#661]
Hiho, I wanted to share my account characters, copied link from website:
https://gw2efficiency.com/account/characters/RafiXWPT.1304

After entering it I have message "No characters found"

Single character link works fine: https://gw2efficiency.com/c/Rafiksiczek

**Comment by queicherius** [comment]
Are you sure you actually shared the character (checked the little boxes at the bottom left)? Even the single character link does not work for me. 
In contrast, mine works fine: https://gw2efficiency.com/account/characters/queicherius.2563

**Comment by RafiXWPT** [comment]
Well, you have right. Didn't know about that checkboxes, lol.
For the future, there should be info about that fact somewhere when you want to copy link. Something like "Cannot copy, there is no data shared on your account, do it by checking out what you want to share inside each character panel"

Sorry for disturbing!

P.S. I am new on your site, but already loved it.
