### ISSUE TITLE
Since Feb08 update own materials are incorrectly counted

### ISSUE THREAD

**Issue by obfuscoder** [gw2efficiency/issues#666]
No matter what recept I look up, some (if not all) materials in my bag are counted incorrectly. It counts more than I actually have. I use an API key with all privileges.

Example: Damask Patch - https://gw2efficiency.com/crafting/calculator/71334-Damask-Patch

For me it shows 129 Silk Scraps owned - yet I have only 88.

I have no materials in the bank, mail, or in other character bags.

This essentially makes the shopping list short of some of the mats which is annoying as I have to buy again the stuff which was calculated incorrectly.

Before the Feb08 update, the calculation was correct.

**Comment by queicherius** [comment]
You can hover over the material to see where it takes the total number from. Could you check if it matches up to your account? Maybe it's in one of your guildbanks?

**Comment by obfuscoder** [comment]
Hovering doesn't really show where the mats are coming from, but it seems it was my fault. I DID have a small stack on silk scrap and cured leather hidden inside of a bag of a character I haven't played for a while. I suppose since Feb08 update the API did take those into calculation account and before they were not considered.
