### ISSUE TITLE
Add option to filter statistics to only include active accounts

### ISSUE THREAD

**Issue by Pluckerpluck** [gw2efficiency/issues#680]
So this issue is vague barbecue I have no idea what's possible and what's not.

It came to my attention when someone messages me that the statistics here aren't necessarily all that useful as they include people who added their API key when they could, and then gave up playing.

As a result, anything new that's get added will be "rarer" just because we include people that don't play.

So is it possible to have an "active" filter? It could simply be a restriction to accounts logged in within the last month, (or had their account update within the last month if last online isn't available) etc.

**Comment by queicherius** [comment]
I will close this in favor of #653, but I added your great idea there. Thanks! 👍
