### ISSUE TITLE
Permanent "Loading..." on account overview

### ISSUE THREAD

**Issue by Maqentaer** [gw2efficiency/issues#686]
and there is "Not crawled yet" status.

in browser console there is a lot of errors fetching guilds info (few guild guids):

> Fetch API cannot load https://api.guildwars2.com/v2/guild/... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gw2efficiency.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

"Refresh now!" button doesn't help.

**Comment by queicherius** [comment]
The API is currently experiencing problems, which causes this issue. This was already reported to ArenaNet and there is nothing we can do except wait for it to get fixed. 🚒 💦 🔥
