### ISSUE TITLE
Dye ordering by brightness seems bugged

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#714]
I didn't check the exact numbers, but visually the order doesn't seem 100% correct.

[Screenshots](http://imgur.com/a/snSzE)

**Comment by queicherius** [comment]
The order there depends on what the [API returns for the brightness value](https://api.guildwars2.com/v2/colors?ids=all), which is part of the [HSL color model](https://en.wikipedia.org/wiki/HSL_and_HSV).
