### ISSUE TITLE
Add a filter for hidden achievements

### ISSUE THREAD

**Issue by coldwaterq** [gw2efficiency/issues#715]
I want to filter on the "hidden" flag.

Edit: Phone auto-correct butchered the original post.

**Comment by queicherius** [comment]
I'm not sure what exactly you mean, could you clarify a bit? :)

**Comment by coldwaterq** [comment]
First, sorry about my original comment, phone auto-correct butchered that post.

Some achievements are "hidden". And they only show up in the API after someone has completed them. They also only show up in a user's panel in-game after a user has started or completed the achievement. So in-game there is no way to see which of these I haven't gotten without first looking up which ones exist. So it would be great if in gw2efficiency if I could see which hidden achievements I haven't gotten yet. 

The bit about random wouldn't be super useful though now that I look because a lot of them are gem store purchases.

**Comment by coldwaterq** [comment]
According to the wiki, https://wiki.guildwars2.com/wiki/API:2/achievements, this can be checked by reading the boolean value from achievment->flags->Hidden

**Comment by queicherius** [comment]
Ah yes, this would be pretty easy to do!

**Comment by coldwaterq** [comment]
thank you

**Comment by queicherius** [comment]
This is now live. Thank you for your report. 😄

**Comment by coldwaterq** [comment]
Thank you
