### ISSUE TITLE
Add armor and weapon sets tracking

### ISSUE THREAD

**Issue by dkalinkov** [gw2efficiency/issues#716]
How about a page/section like the one for achievements, but for tracking progress on collecting all weapon and armor sets. The tab for each set can show all collected armor pieces and the ones that are missing just like some of the achievements do (just like bladed armor collection, ogre weapons). I think we need this, because a lot of armor sets do not have specified collections and it's not easy keeping track which pieces you are missing :)

**Comment by queicherius** [comment]
In essence, this is what the wardrobe page is supposed to be in the future (with #66 implemented and some better page organisation). The main issue is that all that requires a lot of static data, which I have not found someone to provide or time to provide it myself.

---

Closing in favor of #66
