### ISSUE TITLE
"The Real Raiders of Tyria" achievement bug

### ISSUE THREAD

**Issue by Wiella** [gw2efficiency/issues#717]
I'm not sure if this issue is coming from GW2 API or not, but thought it might be worth reporting.

Here is a screenshot displaying the issue:
![image](https://cloud.githubusercontent.com/assets/26770339/24459562/8916ccc4-14a4-11e7-8963-fc41b902c7cd.png)

"The Real Raiders of Tyria" achievement is completed and displayed as completed in-game, but not on the GW2 Efficiency site - it seems that it found some extra objectives there :)

**Comment by queicherius** [comment]
*Uhmmm...* Could you let me know your API key? Either here via a comment or to admin@gw2efficiency.com

**Comment by Wiella** [comment]
Sent an API key to you via email

**Comment by queicherius** [comment]
Thank you for the key, looks like the API does indeed return something weird here:

```js
{
    "id": 3392,
    "bits": [
        0,
        1,
        2,
        3
    ],
    "current": 4,
    "max": 8,
    "done": false
}
```

**Comment by queicherius** [comment]
Atm it looks like this is an API issue https://github.com/arenanet/api-cdi/issues/473 - gonna wait on that a bit. 👍

**Comment by Wiella** [comment]
Thanks!
Then I guess it will work properly as soon as the API is fixed :)

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
