### ISSUE TITLE
Add propper metric logging

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#724]
Right now, I'm only logging job completions, but there are a bunch of other things that would be interesting to be logged. Have to find a way to do this first, possibly with Graphana.

**Comment by rikkuness** [comment]
Wooo Grafana ftw! Hit me up if you need any help :+1:

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
