### ISSUE TITLE
Scale the range selector on charts to long texts

### ISSUE THREAD

**Issue by madmandarin** [gw2efficiency/issues#725]
on page https://gw2efficiency.com/currencies/gems
![2017-04-13 00_44_09- - gems - gw2efficiency](https://cloud.githubusercontent.com/assets/15033833/24976322/6f48858c-1fe2-11e7-94c6-a82097e56608.png)

**Comment by K900** [comment]
Confirming on Firefox Nightly (Windows 10): 

![](https://i.imgur.com/rctDfzK.png)

Looks like the labels are too long and the buttons aren't adjusting correctly.

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
