### ISSUE TITLE
Guild upgrade information not being saved

### ISSUE THREAD

**Issue by lambada** [gw2efficiency/issues#726]
My Primary guild [OoO] keeps losing its upgrade information that I'm manually entering. I'm not sure what's triggering the loss of info, but I'm not a guild leader so can't use the import from API button. 

Here's my character list so you should be able to get my API key from that I think if needed? https://gw2efficiency.com/account/characters/Lambada.7136

**Comment by queicherius** [comment]
The information is attached to `localStorage` and not persisted on the server. This means that if you either have your browser set up in a way that it clears that information (e.g. on restart) or you manually clear the browser storage, it'll get lost. Is this the case for you?

**Comment by lambada** [comment]
Ah, yes that sums up the situation - I'm on a new machine at the moment. Perhaps having a server side store could make more sense than a client side one?

**Comment by queicherius** [comment]
> Perhaps having a server side store could make more sense than a client side one?

Maybe sometime in the future - I'm atm head over feet in other work, so that'll have to wait. I'm secretly still hoping that the API will allow access with guild-member accounts too before I get to this. 😉
