### ISSUE TITLE
Achievements total is not correct

### ISSUE THREAD

**Issue by montss** [gw2efficiency/issues#728]
As of April 22 2017, my in game total AP's (achievement points) is higher than what the site is showing.
![guild wars 2 04 22 2017 - 02 22 21 02](https://cloud.githubusercontent.com/assets/5758149/25299025/9bd176ea-2703-11e7-9a04-f429381d6489.png)

site

![capture](https://cloud.githubusercontent.com/assets/5758149/25299059/e92fb7bc-2703-11e7-866e-02e34943d07f.JPG)

**Comment by queicherius** [comment]
Multiple people already reported this problem, but nobody could put a finger on **where** the points were missing from :(

**Comment by montss** [comment]
@queicherius I guess it is SAB

**Comment by queicherius** [comment]
([Also as a reference, the same question on Reddit](https://www.reddit.com/r/gw2efficiency/comments/67g9us/achievement_point_problem/))

**Comment by queicherius** [comment]
Reported the issue to the API devs. 👍

**Comment by queicherius** [comment]
This will be fixed as soon as the issue in the API will be fixed, which should be sometime next month. Since this will solve itself with that, I'll close it. Thanks for the report! :)

**Comment by montss** [comment]
this is still no fixed yet

**Comment by queicherius** [comment]
Yes, because it's still not fixed in the API. Made an issue [here](https://github.com/arenanet/api-cdi/issues/544) as a reminder, pointing to the forum thread.
