### ISSUE TITLE
Undiscovered Recipes based on Inventory - Feature Request

### ISSUE THREAD

**Issue by jaydeflix** [gw2efficiency/issues#729]
Since you're able to pull the data surrounding the recipes I haven't discovered yet, along with my inventory, I'd love to see a filter on the recipes of all recipes I don't know AND have all but one ingredient (or less) for.

I have an artificer with plenty of '1 item shy' recipes to be discovered. I'd love to filter the recipe list down to see what I'm just missing.

**Comment by queicherius** [comment]
This seems like a pretty neat feature, and I can see why it would be useful. Requires #100 before that.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
