### ISSUE TITLE
Blood ruby backpack infusion recipe is wrong

### ISSUE THREAD

**Issue by jcogilvie** [gw2efficiency/issues#732]
https://gw2efficiency.com/crafting/calculator/79062-Blood-Ruby-Backpack-(Infused)

According to the wiki it should be:  

-backpack
-shard
-250 ecto
-gift of ascension

I dunno if this is pulled from an API or what, but as gw2e displays it, it doesn't work.

**Comment by queicherius** [comment]
Included in #740, should come soon.
