### ISSUE TITLE
Heroe Points (and / or) Specialization completion

### ISSUE THREAD

**Issue by FreezyExp** [gw2efficiency/issues#733]
When you hit 80 you basically have everything done except for specialization.
Heropoints contains a list of locations (usefull, but bothersome)

But there is also:
https://wiki.guildwars2.com/wiki/API:2/characters#Training

A sum total per character on the overview would be useful for knowing which characters are done.
Yes I am that lazy

It seems that it will only show trait lines that are invested in.
A sum total would be fine (just add up all the spent)
A needed total would be usefull (needs to lookup/calculate the required total per class, then subtract the spent amount)
An overview of the trait lines would be nice (as well as presumably, a lot of work)

example Training datas:
[{"id":21,"spent":25,"done":true},{"id":95,"spent":27,"done":true},{"id":71,"spent":27,"done":true},{"id":75,"spent":19,"done":true},{"id":61,"spent":60,"done":true},{"id":66,"spent":60,"done":true},{"id":94,"spent":60,"done":true},{"id":51,"spent":60,"done":true},{"id":32,"spent":60,"done":true},{"id":113,"spent":250,"done":true}]

[{"id":26,"spent":13,"done":true},{"id":74,"spent":24,"done":true},{"id":97,"spent":24,"done":true},{"id":92,"spent":13,"done":true},{"id":104,"spent":24,"done":true},{"id":103,"spent":60,"done":true},{"id":100,"spent":60,"done":true},{"id":24,"spent":60,"done":true},{"id":45,"spent":60,"done":true},{"id":30,"spent":60,"done":true},{"id":85,"spent":40,"done":false}]

[{"id":23,"spent":15,"done":true},{"id":110,"spent":22,"done":true},{"id":29,"spent":24,"done":true},{"id":79,"spent":15,"done":true},{"id":38,"spent":22,"done":true},{"id":44,"spent":60,"done":true},{"id":22,"spent":60,"done":true},{"id":80,"spent":60,"done":true},{"id":28,"spent":60,"done":true},{"id":57,"spent":60,"done":true}]

**Comment by FreezyExp** [comment]
total unlock: 648
250 of which is for the elite

648 - sum spent = training remaining

not sure if you use PHP, but this works well in my personal api sheet ;-)
 ```
static function sumTraining($char)
    {
        $spent = 0;
        if(property_exists($char, 'training'))
		{		
			foreach($char->training as $spec)
            {
                $spent += $spec->spent;
            }
            return $spent;
		}
		return "";
    }
```

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
