### ISSUE TITLE
Show decimals for some statistics in the graph axis labels

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#734]
There are certain statistics that deal with low values or with fractional numbers, these tend to not display too well on the graph, which in its current configuration is much more suited for large integers.

Things like deaths per hour are especially bad, the axis displays 1 for (for example) 0.54, and there are several horizontal lines for that same value.  I guess for certain stats a different graph config could be used.

**Comment by ralesk** [comment]
Unfortunately at the moment there seems to be an API error so I can't make screenshots about the graphs that don't feel right to me.

**Comment by queicherius** [comment]
Ah yes, I see what you mean. I think that's just an issue with the formatter of the labels.

**Comment by ralesk** [comment]
Here are the two issues actually now that I could look:
* graphs that have to display a small amount of change on integers (number of characters tends to be one of those, but number of deaths is a good one unless you die a lot in a particular region)

![image](https://cloud.githubusercontent.com/assets/1564502/26179330/63301840-3b63-11e7-9580-9407bc2358e7.png)

* and graphs that should display non-integer data, but can't quite

![image](https://cloud.githubusercontent.com/assets/1564502/26179362/9ee29840-3b63-11e7-9a7e-b4ec1bedcdd4.png)

But... actually you're correct and it's pretty much the same issue.  The axis label is rounded to integers so it'll repeatedly display the same whole value (while the tooltip will show the correct value, rounded to whatever other unit).  On the other hand (and that seems more a programming than a setup job, unless of course the graph tool is capable of doing this out of the box), when the data is integral, there shouldn't be more level lines between the two possible values (eg. if it's an amount of tokens or characters, there should be nothing for "8.5" characters) — this is shown in the first pic well I think.

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
