### ISSUE TITLE
account value graph not automatically updated

### ISSUE THREAD

**Issue by knarrff** [gw2efficiency/issues#735]
The last update of the total account value of my account is now May 14th (as displayed in the graph). It's May 18th now. Usually there is a data point each day. Clicking 'Refresh now!' on the account overview page (bottom) does not update the graph. The total account value displayed outside of the graph is different, and quite likely current - it seems to be only the graph which isn't updated. I don't know whether this is because of an issue plotting the graph, or (hopefully not) the saved historical data.

**Comment by queicherius** [comment]
Some API keys are currently having issues being crawled in the backend - if you could let me know your key via PM I can try and debug it more effectively.

**Comment by knarrff** [comment]
sent

**Comment by queicherius** [comment]
API key got flagged as invalid for some reason (api error?), keeping an eye open but should be fixed for now.
