### ISSUE TITLE
Add way to delete account

### ISSUE THREAD

**Issue by bkaestner** [gw2efficiency/issues#744]
I haven't found a way to delete an account. It's a small quality of life improvement, which would enable one to get rid of all data at once.

Beside the quality of life improvements, it might be necessary from a legal point of view, but I'm not a lawyer.

**Comment by queicherius** [comment]
> I haven't found a way to delete an account. It's a small quality of life improvement, which would enable one to get rid of all data at once.

If you want to delete your account, please write support (admin@gw2efficiency.com) - a few people already did, but it's more a "1 person per 3 months" kind of thing, so not worth investing development time in :)
