### ISSUE TITLE
[Bug] Previous winners on lottery a bit off when scaling

### ISSUE THREAD

**Issue by Greaka** [gw2efficiency/issues#748]
When you scale your browser smaller than 100%, the previous lottery winners section is a bit off.
I tested only in google chrome 58.

![capture](https://cloud.githubusercontent.com/assets/2805834/26670441/fb81a36c-46b1-11e7-9f3a-62c5d18ff0ca.PNG)

**Comment by queicherius** [comment]
Currently, most pages behave super badly when using smaller browser sizes or browser sizing. Going to close this one out, because I plan to gradually redo most pages, but I don't want to do small "bits" like this at a time.
