### ISSUE TITLE
Suggestion: In the crafting section, allow users to change some entries to "Gather" instead of trading post.

### ISSUE THREAD

**Issue by Honnou** [gw2efficiency/issues#753]
This is merely something I ran into while setting a ridiculous goal for myself, I want to get a legendary and gather as much as possible myself. I entered Sunrise into the crafting section and then had to manually change everything to "Craft"  in stead of "Trading Post." Maybe it's a good idea to add a third option into the mix where users can add the selected item to their "Gathering Shopping List." Afterwards, maybe using the gathering section of the website, an optimal daily route can be spelled out as well.

If this might be overkill, then another option might be to 'save' what the user changed some entries in the recipe to, eg tp or crafting. And maybe even a 'Change all to TP/Craft' option.

**Comment by queicherius** [comment]
I feel like this is farily overkill, but it might be somewhat possible with #58. Going to close this one out tho.
