### ISSUE TITLE
Bag / Salvage custom calculator

### ISSUE THREAD

**Issue by risingashes** [gw2efficiency/issues#754]
Repurpose of the crafting calculator but with recipes determined by the player for the purpose of valuing bags, salvages or anything which starts with one items and ends with multiple random items- could include mystic clover conversion if more than initial component is allowed.

Frayed Rags salvage into 0.1 Silk Scrap, 0.4 Cotton Scrap, 0.3 Linen Scrap.

Frayed Rag should be the focus item with a quantity of 1, silk scrap, cotton scrap, linen scrap should then be enterable with quantities of 0.1, 0.4, and 0.3.

The focus item should then display the buy and sell price, while the combined after-tax value of the component items are displayed for comparison.

If used for bags it would function the same:

Thorned Bags would be the focus item. Components would be added, 0.001 Charged Lodestone, 0.005 Lava Lodestone... etc.

If used for Mystic Clovers:

1 (or 10) Obsidian shard, 1 mystic coin, 1 Glob of Ectoplasm 1 spirit shard added as focus items, tradable items price is combined while non-tradable or ignored.

Component items are then entered. Fangs, Claws, etc. Difference between focus item costs and component item costs would tell you how much you'd lose each forge.

Recipes would be saved against the login profile, a list of created recipes could be displayed with summary data (buy/ sell of focus item, current posttax of contents). With a button to create a new recipe taking you to a new screen.

**Comment by queicherius** [comment]
I feel like you could produce the wanted result easily with an excel/google sheet and it's a fairly rare problem to have. After consideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
