### ISSUE TITLE
some armor showing twice

### ISSUE THREAD

**Issue by Neutra1** [gw2efficiency/issues#768]
![efficiency boots](https://user-images.githubusercontent.com/29493506/27246080-743a870a-52ac-11e7-8a8d-e4bd3b0dcac8.png)
There seems to be a repeat of certain armor pieces as shown in this picture. Specifically the heavy scale and Mistward armor pieces. 

The repeats are 
Mistward all armor pieces
Heavy Scale all armor pieces except shoulder and chest

**Comment by queicherius** [comment]
This page just displays straight what the API outputs, so these are duplicated in the API (and the little 🔒 shows you that they are hidden until unlocked in game). My guess is that they updated the ids when they reworked the WvW rewards.
