### ISSUE TITLE
Statistical ranking summary page

### ISSUE THREAD

**Issue by risingashes** [gw2efficiency/issues#770]
Achievement                                         | Rank |   Value  |Next|
------------ | ------------- | ------------- | ---------- |
Supply Spent on Repairs: | 4,178 | 16,401 | +3   |
Fractal Tonic:                     | 3,104 |     0      | +1   |
Trading Post Buy orders:   |1          |28,893 |nobody! |

(Columns should be sortable.)

Summary:                          AverageRank:  2,145
                                          Ranking rank:  54th

**Comment by queicherius** [comment]
While this would be really cool, I agree, in the current implementation getting the rank and next rank value is very heavy on the DB. Might have to rewrite the logic there a little to allow for this feature as well as the feature to graph the ranks themselves.

**Comment by queicherius** [comment]
I just did a real quick implementation on the frontend of this and I have to say that I really like it.

![chrome_2018-04-29_20-57-18](https://user-images.githubusercontent.com/4615516/39410424-f8b9521c-4bef-11e8-9821-c10c52e98073.png)

Sadly right now just loading this page for one user nearly overloads the API. Will have to change some backend code for this to work efficiently.

**Comment by queicherius** [comment]
This is now live!
