### ISSUE TITLE
Guild Emblem not showing up correctly

### ISSUE THREAD

**Issue by tseward** [gw2efficiency/issues#778]
The guild emblem isn't showing up correctly. The first image is how it appears on GW2Efficiency, while the second is how it looks in-game.

![emblem1](https://user-images.githubusercontent.com/7698997/27835133-95ae59ee-608e-11e7-99da-a7221d93085a.PNG)
![emblem2](https://user-images.githubusercontent.com/7698997/27835132-95aaad1c-608e-11e7-822d-14fd67cce02e.PNG)

**Comment by queicherius** [comment]
gw2e uses https://guilds.gw2w2w.com/ (https://github.com/fooey/node-gw2guilds) to render guild emblems, so maybe you could get a bug report in there? I have no idea what's going wrong there, I just use the service.

**Comment by tseward** [comment]
Thanks, I've contacted the developer.

**Comment by queicherius** [comment]
Sweet, thanks!
