### ISSUE TITLE
Show crafting recipes with the highest ROI for some ingredient

### ISSUE THREAD

**Issue by orenwolf** [gw2efficiency/issues#780]
For the Crafting section, any chance we could have a page that, for a given ingredient, we could be given the highest to-craft ROI? For example, if I select or enter, say, Toxic Spore Sample, have all the recipies listed that use that ingredient, sorted by total ingredient cost vs sell/buy TP profit?

Something similar to: http://www.gw2profits.com/recipes.php

Thanks!

**Comment by queicherius** [comment]
So, in theory, this would be possible, but it would have to load all the recipes in existence on the client, which makes it kind of annoying. Having a think about it.

**Comment by orenwolf** [comment]
Ah, crap. I didn't realize you did this client-side. I suppose you could run the ingredient search server-side and then return the records to the client to sort - or is even that level of server-side load untenable?

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment and technical difficulty for the gained value in my opinion, so I am going to close this ticket.
