### ISSUE TITLE
Add node to Gathering page

### ISSUE THREAD

**Issue by orenwolf** [gw2efficiency/issues#781]
There's a permanent Mithril node in the Bitterfrost frontier, near Koda's Welcome Waypoint ( [&BIEJAAA=] ) - I've attached a handy map image as well! Let me know if there's any other information I can provide. Thanks!

![bitterfrost_frontier_permanent_rich_mithril](https://user-images.githubusercontent.com/1264142/28223948-574facc4-689b-11e7-9f90-f25c02576a32.jpg)

**Comment by orenwolf** [comment]
Waypoint coordinates approximately 21380, 8000.
Node coordinates approximately 21630, 7570.
(estimates from the gw2timer.com map)

**Comment by queicherius** [comment]
Thanks! Also for the picture! 👍

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
