### ISSUE TITLE
Legendary Armor Piece

### ISSUE THREAD

**Issue by feisty69** [gw2efficiency/issues#782]
https://gw2efficiency.com/crafting/calculator/200001-Legendary-Armor-Piece
^ This is handy when you want to look for the gifts individually and for some reason it is not possible to search for it in the crafting calculator anymore.

**Comment by queicherius** [comment]
Since the armor is in the game this recipe is not active anymore. Instead, you can use any of the pieces to achieve essentially the same effect: https://gw2efficiency.com/crafting/calculator/80277-Perfected-Envoy-Tassets

**Comment by feisty69** [comment]
I feel that it is still incredible handy to have the legendary unspecified.
