### ISSUE TITLE
[feature request] add filters to recipe overview

### ISSUE THREAD

**Issue by HackworthCForge** [gw2efficiency/issues#783]
For example if I only want to see Chef recipes, I don't want to sift through the current 131 pages and look for just Chef recipes, I would like to be able to filter the list.

Also, I don't really care about recipes that require a huge upfront investment because I'm poor, so I would like to be able to only show recipes with "crafting cost < x"

**Comment by queicherius** [comment]
This is included in https://github.com/gw2efficiency/issues/issues/157
