### ISSUE TITLE
Mixed up translations

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#784]
<img width="1257" alt="bildschirmfoto 2017-07-24 um 18 43 15" src="https://user-images.githubusercontent.com/4730112/28534189-14f9a1c4-70a0-11e7-82a8-9c5294f228a6.png">

Already since a few weeks, already tried clearing cache and website data!

**Comment by queicherius** [comment]
Not sure what you mean. The english items just dont have a German translation yet. Or do you not want your language to be German, in which case you can switch it at the top?

**Comment by maxOS1104** [comment]
I mean items that were there a long time ago and once were already in German are now in English.
I don't mean the new row, I mean things like Wardrobe, Miniatures, Dyes and Lottery

**Comment by queicherius** [comment]
Yeah these all have the translation flag but no translations, so eventually when I find some time to do a translation pass they'll get the right treatment.

Right now my focus is more on pushing new features out with the very limited time I have, so it might be a while.
