### ISSUE TITLE
Crafting Calculator doesn't update Pile of Crystalline Dust own material

### ISSUE THREAD

**Issue by cyanidecapsule** [gw2efficiency/issues#785]
![capture](https://user-images.githubusercontent.com/30450416/28598238-30ea2e30-719a-11e7-965f-c5c9e533f095.PNG)
![capture](https://user-images.githubusercontent.com/30450416/28598246-41dad136-719a-11e7-9622-d9fe0ed36fff.PNG)

**Comment by queicherius** [comment]
Could you mail me your API key to admin@gw2efficiency.com? This should never happen.

**Comment by cyanidecapsule** [comment]
Bah, ignore me. There's Core to Lodestone promotion which requires Crystalline Dust. All works fine.

**Comment by queicherius** [comment]
Alright, glad to hear. 👍
