### ISSUE TITLE
Home instance cat 'Simon' missing

### ISSUE THREAD

**Issue by Kinsmir** [gw2efficiency/issues#787]
At the moment there are 32 cats you can collect in your home instance.

The cat that is missing is: [https://wiki.guildwars2.com/wiki/Simon](https://wiki.guildwars2.com/wiki/Simon)

While the cat is not listed on the official api, I managed to find the id together with someone who has it unlocked.

The id for this cat is: 35

**Comment by queicherius** [comment]
Wait so the cat id is in the API response of someone who has it unlocked, but not in the list of ids? Could you potentially send me the API key with the unlocked cat to admin@gw2efficiency.com?

Thanks for the report, I knew it was missing, I didn't know it behaved like that.

**Comment by Kinsmir** [comment]
Yes, you're correct. the API gives the correct id once it's unlocked (on the account listing) but on the global one it's missing.

The api key I was testing with was temporarily and has already been deleted again. I will try to poke him again once he's online ingame about it.

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
