### ISSUE TITLE
Fix legendary insight count for more than one armorset

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#788]
Right now, if a user has all 3 legendary armor sets it is counted as 150+150+150 instead of 150+300+300.

@atjeff Wanna give this a shot?

**Comment by atjeff** [comment]
Taking a look @queicherius.

**Comment by queicherius** [comment]
As reference, here is a branch with the failing test cases for this: https://github.com/gw2efficiency/account-statistics/tree/fix/legendary-insight-count
