### ISSUE TITLE
Text is cropped on main page, rus lang

### ISSUE THREAD

**Issue by madmandarin** [gw2efficiency/issues#791]
Link "Зарегистрироваться" cropped "Зарегестрир"
chrome 59.0.3071.115 x64
![2017-08-07 00_45_30-gw2efficiency](https://user-images.githubusercontent.com/15033833/29006468-1b3fd016-7b0a-11e7-9239-5b6eaadb6e42.png)

**Comment by queicherius** [comment]
Hm. Is there any shorter word than "Зарегистрироваться" that fits the "Register" translation?

**Comment by madmandarin** [comment]
"Регистрация", i haven't any idea how do it more shorter.

**Comment by queicherius** [comment]
Does `регистр` not fit? (Thats from google translate)

**Comment by madmandarin** [comment]
`регистр` is cropped to, `Регистрация` is standart word for using in site.
May be moves `Регистрация` to the next line?

**Comment by queicherius** [comment]
`Регистрация` should fit too, I'll try it next time I work on the site 👍 Thanks!

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
