### ISSUE TITLE
performancer on google chrome v.60 x54

### ISSUE THREAD

**Issue by Xtreme89** [gw2efficiency/issues#792]
https://gw2efficiency.com/gathering/permanent-nodes

performance on chrome v.60 x64 is absolutly terrible

**Comment by queicherius** [comment]
For me the page takes about 2 seconds to load and after that any interaction is in the < 50ms area.

- What kind of issues are you seeing?
- Which operating system are you using?

**Comment by JoeMylinn** [comment]
I tested this using latest Chrome Build (Version 60.0.3112.101 (Official Build) (64-bit)), on both macOS High Sierra Version 10.13 Beta (17A352a) and Windows 10 Pro Version 1703, I have no performance issues at all.

**Comment by queicherius** [comment]
Closing this since there was no feedback in a reasonable timeframe (and I didn't get bombarded with emails, which I usually get on performance issues), so I assume the issue either fixed itself or was self-inflicted. 😄
