### ISSUE TITLE
Add WvW/PvP legendary armor recipes

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#794]
I noticed that the crafting calculator does not include the new gifts for the WvW legendary armor. 

Gifts can be found here: https://wiki.guildwars2.com/wiki/Legendary_armor#WvW_Components

Specifically I wasn't able to find the following Gifts on the crafting calculator:

* [ ] [Gift of War Prosperity](https://wiki.guildwars2.com/wiki/Gift_of_War_Prosperity)
* [ ] [Gift of War Prowess](https://wiki.guildwars2.com/wiki/Gift_of_War_Prowess)
* [ ] [Gift of War Dedication](https://wiki.guildwars2.com/wiki/Gift_of_War_Dedication)

These are all mystic forge recipes. I'm unsure how you're handling those (probably hardcoded I'd guess).

**Comment by queicherius** [comment]
Sadly most of the items here are missing from the API. I'm going to wait until they all show up: https://gist.github.com/queicherius/e7fe50ae19479927de48f327a80e3558

**Comment by queicherius** [comment]
Reference: https://github.com/arenanet/api-cdi/issues/568

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
