### ISSUE TITLE
Delivery Box displays 2 items when only one is purchased

### ISSUE THREAD

**Issue by simeonlg** [gw2efficiency/issues#795]
When buying items on buy order, the delivery box sometimes says 2 items have been bought, when only one has been purchased.

As a side question, how often is the commerce/delivery updated?

Another idea would also be to include which items have sold so you know exactly where the funds are coming from.

**Comment by queicherius** [comment]
> When buying items on buy order, the delivery box sometimes says 2 items have been bought, when only one has been purchased.

Could you screenshot that?

> As a side question, how often is the commerce/delivery updated?

Every 5 minutes, roughly.

> Another idea would also be to include which items have sold so you know exactly where the funds are coming from.

Yeah, that would be neat. I am thinking about how to expand the current functionality.

**Comment by simeonlg** [comment]
I will try to get a screenshot of it when it happens. Might take some time since I dont usually sit at my computer and wait for offers to fill

**Comment by simeonlg** [comment]
![gw2efficiency delivery bug 1](https://user-images.githubusercontent.com/8640358/29277336-9ed9a2c8-8111-11e7-9a76-7ad377695ded.png)
![gw2efficiency delivery bug 2](https://user-images.githubusercontent.com/8640358/29277367-b8547aa2-8111-11e7-8cf7-b1aff13b2476.png)

From these images you can see it happens with both items and funds. After some time passes, the additional items/funds disappear.

**Comment by queicherius** [comment]
Okay that is weird. I am not sure if this is an API issue or an issue on my side. Will have to investigate. Thank you for the report and the screenshots!

**Comment by simeonlg** [comment]
The next time I see it happen Ill have a look at what the API reads

**Comment by simeonlg** [comment]
![gw2efficiency delivery bug 3](https://user-images.githubusercontent.com/8640358/29299322-14e39724-816e-11e7-93fb-a4c59c6078cb.png)

The problem does seem to with the official API and not delivery implementation. Will make an official forum post

**Comment by queicherius** [comment]
Alright! Thanks for the follow-up!

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
