### ISSUE TITLE
Scrollbar in top menu, rus lang

### ISSUE THREAD

**Issue by molod** [gw2efficiency/issues#796]
New 'daily' category in the top menu adds a scrollbar and it looks bad.

![gw2efficiency](https://user-images.githubusercontent.com/1084344/29281327-49189da6-8127-11e7-93ab-d9ef8ff63dd8.png)

**Comment by madmandarin** [comment]
Confirming on chrome 60.0.3112.90

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
