### ISSUE TITLE
Password always incorrect

### ISSUE THREAD

**Issue by GlennVanSchil** [gw2efficiency/issues#798]
Every time I try to login I get the following message: These credentials were not correct.
Even when I reset my password, logout and login again to verify if my new password works I get the same message. This also has nothing to do with caching of the server or something like that because when I reset my password and come back after a day or two my credentials still don't work and I'm forced to reset my password again.

# Update
When using my username instead of my email to login it does work.

**Comment by queicherius** [comment]
- Are you using your username to log in, and not your email?
- Which browser & operatring system are you using?
- What is your username? (You can mail me this to admin@gw2efficiency.com if you dont want it linked here)

I heard that report multiple times but so far I could not reproduce it :(

**Comment by GlennVanSchil** [comment]
`Are you using your username to log in, and not your email?` 
I'm using my email, I'll try again with username
`Which browser & operatring system are you using?`
I'm using chrome in both Ubuntu 16 and Windows 10
`What is your username?`
glennvs

**Comment by queicherius** [comment]
Thank you for the update!

This is no bug, but it's clearly confusing. I'll have a think on how to clear up the interaction a bit.

**Comment by GlennVanSchil** [comment]
Maybe some simple improvements can make a huge difference:
* update the placeholder from "username" to "username, ex: johndoe
* update the error message from "These credentials were not correct" to "These credentials were not correct, Make sure you are not using your email"

And in case you have some time on your hand, you could build a system that if the username matches an email regex you first search the username for that email.
