### ISSUE TITLE
Add the new home instance nodes

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#799]
Title :)

**Comment by katubug** [comment]
In addition to the oysters, the home instance nodes Advanced Leather Rack, Advanced Cloth Rack, and Black Lion Hunter's Board are all not yet added.

**Comment by queicherius** [comment]
I just noticed I never commented here, but all these are still missing from the API :(

**Comment by katubug** [comment]
I saw that you tagged this with that, so I got the message. Maybe we ought
to make a reddit/forums post asking about it?

**Comment by queicherius** [comment]
I already noted it in the official chat twice, so I am sure they are aware of it but have not gotten around to it yet.

**Comment by katubug** [comment]
Then I won't clutter things up further. I'm sure it'll be soon enough.
Thank you for all your hard work, btw!

**Comment by queicherius** [comment]
I created an issue for it after all: https://github.com/arenanet/api-cdi/issues/567

They probably have their hands full with PoF things. 😞

**Comment by queicherius** [comment]
This is now online, finally!
