### ISSUE TITLE
Add all time-gated crafts to the Daily page

### ISSUE THREAD

**Issue by samulisoderlund** [gw2efficiency/issues#800]
Currently the Crafting section only contains the time-gated ascended materials. I would like to see all the other time-gated recipes included. They are:

- [Clay Pot](https://wiki.guildwars2.com/wiki/Clay_Pot)
- [Grow Lamp](https://wiki.guildwars2.com/wiki/Grow_Lamp)
- [Heat Stone](https://wiki.guildwars2.com/wiki/Heat_Stone)
- [Plate of Meaty Plant Food](https://wiki.guildwars2.com/wiki/Plate_of_Meaty_Plant_Food)
- [Plate of Piquant Plant Food](https://wiki.guildwars2.com/wiki/Plate_of_Piquant_Plant_Food)
- [Dragon Hatchling Doll Adornments](https://wiki.guildwars2.com/wiki/Dragon_Hatchling_Doll_Adornments)
- [Dragon Hatchling Doll Eye](https://wiki.guildwars2.com/wiki/Dragon_Hatchling_Doll_Eye)
- [Dragon Hatchling Doll Frame](https://wiki.guildwars2.com/wiki/Dragon_Hatchling_Doll_Frame)
- [Dragon Hatchling Doll Hide](https://wiki.guildwars2.com/wiki/Dragon_Hatchling_Doll_Hide)
- [Gossamer Stuffing](https://wiki.guildwars2.com/wiki/Gossamer_Stuffing)

There's also [Vial of Maize Balm](https://wiki.guildwars2.com/wiki/Vial_of_Maize_Balm), but no-one in their right mind would ever craft that, so I think it can be left out.

**Comment by queicherius** [comment]
We thought about adding these, but we decided against it. The tradingpost profit on some of them is very high (like 8 - 10g), but nobody buys them, causing it to be a full net loss, so it'd be confusing esp. for newer players trying to make some coin.

However, you'll be able to add your own things to the lists soon (tm), so you could add them there!

**Comment by samulisoderlund** [comment]
People who are crafting Mawdrey for themselves would find a daily checklist useful. Personally I used one to make sure I don't miss any time-gated crafts. I'm glad to hear that adding my own items will be possible soon :)
