### ISSUE TITLE
Recipe: Warbringer wrong

### ISSUE THREAD

**Issue by moritzdietz** [gw2efficiency/issues#801]
The current recipe of Warbringer seems to be wrong.
GW2Efficiency says: _**2x Gift of Battle**_ 
The official Wiki says: _**4x Gift of Battle**_ instead

https://gw2efficiency.com/crafting/calculator/81462 & https://wiki.guildwars2.com/wiki/Warbringer

**Comment by queicherius** [comment]
![](http://i.imgur.com/GHLhVpZ.png)

Seems to work. Possibly confusing because it used some of your own materials? In any case the recipe is correct :)
