### ISSUE TITLE
Daily hidden Fractals resetting

### ISSUE THREAD

**Issue by JoeMylinn** [gw2efficiency/issues#804]
Right now my daily Fractal section looks like this:

<img width="386" alt="screen shot 2017-08-23 at 8 58 05 pm" src="https://user-images.githubusercontent.com/4973423/29645911-cff7a36a-8845-11e7-92aa-ba9775ed7764.png">

I hide the recommended dailies since I never do them, but since there are new ones every day they reset and I have to hide them again. Maybe make it possible that you can hide certain dailies always, even when they change? I imagine it being similar with PvE, WvW and PvP dailies too, haven't checked that yet tho.

**Comment by JoeMylinn** [comment]
When completely hiding a section, this doesn't happen, just when certain changing dailies within a section get hidden.

**Comment by queicherius** [comment]
Yes, currently hiding dailies are based on the unique identifier. Since the fractal dailies change regularly, you have to hide them once again when they pop up.

Not sure if the extra work for that is worth it.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
