### ISSUE TITLE
Profit Graph Bugg

### ISSUE THREAD

**Issue by Fantash** [gw2efficiency/issues#805]
A while ago the graph of account summary where I counted my benefits entered every 3 minutes worked in my efficiency account, and a week after not using it stopped working. I tried recreating the key or putting all the options of the key but I still can not get that graph, and I only get in return one that says the value of my account and nothing else. Any solution available?

**Comment by queicherius** [comment]
Could you please send me your API key for debugging, either here as a comment or via Mail to admin@gw2efficiency.com (if you don't want it public). Thanks!

**Comment by Fantash** [comment]
1683014A-F88D-AA4C-B81F-55FEE371E2AC37480CAF-7E3E-40DE-9467-0038EBB93936

Thanks for help me

**Comment by queicherius** [comment]
![](http://i.imgur.com/u8LYsXl.png) The graph is showing up for me. Do you have any addons installed (e.g. PrivacyBadger) that can interfere with the request? Could you try with them disabled / in incognito mode?

**Comment by Fantash** [comment]
No, I see that graphic and should see one that I left a few months ago in which money comes out that goes into my inventory in materials every 3 minutes.

**Comment by queicherius** [comment]
> in which money comes out that goes into my inventory in materials every 3 minutes.

Sorry, but I don't know what you mean. Could you please elaborate?

**Comment by Fantash** [comment]
My friend taught me to put some permissions in the key api to get a graph where real time data of the gold value of the items that I made every 3 minutes(farming)
![2017-08-25](https://user-images.githubusercontent.com/31306498/29703386-a86ae8ee-8975-11e7-8e50-0a4b9eebbd5c.png)
, and that graph came out in the place of the one in the photo, It worked for some time but I do not get more and other people do.

**Comment by queicherius** [comment]
The graph on that page updates once a day, if other people have more points it just means that their account is in the system longer. If you are looking for a graph that updates every 3 minutes, you must be thinking of another website, we don't offer that (yet).
