### ISSUE TITLE
Add Daily Completionist to the daily site

### ISSUE THREAD

**Issue by JoeMylinn** [gw2efficiency/issues#806]
Right now I have all the PvE, PvP and WvW dailies hidden, since I usually only do three for the Daily Completionist achievement. 

The Idea is to add that achievement to the site, to be able to easily track when that is done, without having to specifically pick the dailies from the every day list, or even add the functionality, that when any three of the daily PvE/PvP/WvW achievements are done to automatically hide the rest and mark the Daily Completionist as done.

**Comment by queicherius** [comment]
This is now live.
