### ISSUE TITLE
Add value to legendary recipes sold by Miyani

### ISSUE THREAD

**Issue by lemming64** [gw2efficiency/issues#813]
Things like Gift of Color are showing with a vendor price of 1.25g (which is the value) rather than 10g  
![image](https://user-images.githubusercontent.com/31589475/30002853-487fba62-90ab-11e7-8559-978d72b996c9.png)

**Comment by queicherius** [comment]
Oh yeah, good call. I will add them manually.

**Comment by queicherius** [comment]
This was released 2017-10-24 👍
