### ISSUE TITLE
Can't add more than 10 items in crafting calculator

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#814]
Hi, I use crafting calculator to track progress in crafting many items (legendaries etc, ) and my list is longer than 10 items. After recent changes it stop working if list contains more than 10 items .
Also new links is completely not human readable so i can't change order of items :(

**Comment by queicherius** [comment]
Hey there! The old links should still be working even with the new format. The new format should also work with this amount of items. I'll take a look as what is going wrong.

The non-human-readable is true, and it is used for compression, so the links are less long for big lists. I'll see if I can add a small re-order functionality instead (or you can still use the old links).

---

Reference: [A link that broke](https://gw2efficiency.com/crafting/calculator/46042-Assassin's-Godskull-Sickle,46043-Assassin's-Godskull-Kris,46045-Assassin's-Godskull-Slayer,46046-Assassin's-Godskull-Crusher,46049-Assassin's-Godskull-Warclub,46053-Assassin's-Godskull-Targe,46055-Assassin's-Godskull-Impaler,46057-Assassin's-Godskull-Edge,46047-Assassin's-Godskull-Harpoon-Gun,46048-Assassin's-Godskull-Longbow,46050-Assassin's-Godskull-Flintlock,46051-Assassin's-Godskull-Musket,46058-Assassin's-Godskull-Brazier,46054-Assassin's-Godskull-Short-Bow,46060-Assassin's-Godskull-Trumpet,46044-Assassin's-Godskull-Effigy,46052-Assassin's-Godskull-Cesta,46056-Assassin's-Godskull-Crosier,46059-Assassin's-Godskull-Trihorn)

**Comment by queicherius** [comment]
Alright. Old links work again. New links look like this (human readable, but still encoding all the new info):

```
https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-46042;1-46043;1-46045;1-46046;1-46049;1-46053;1-46055;1-46057;1-46047;1-46048;1-46050;1-46051;1-46058;1-46054;1-46060;1-46044;1-46052;1-46056;1-46059
```

⚠️ This means that links generated in the last 8 days will stop working, but I think this is a worthwhile tradeoff.
