### ISSUE TITLE
organize / filter ascended armor crafting costs

### ISSUE THREAD

**Issue by FreezyExp** [gw2efficiency/issues#815]
A simple light / medium / heavy  filter would be wonderful

as a side note, an additional filter for stuff like: berserker/zojja, minstrel/maklain etc
and if it's not too much to ask for, a quick: cheaper with stat change check box

https://gw2efficiency.com/crafting/ascended

**Comment by queicherius** [comment]
This would be solved with the completion of another ticket. Duplicate of #157
