### ISSUE TITLE
Shared characters and 'accounts' not showing

### ISSUE THREAD

**Issue by Meriksen95** [gw2efficiency/issues#816]
When going in to the 'accounts' tab you are not able to get any hits when searching using an account name.
There is no problem when using the character name but account does'nt work. Maybe change the description text? Unless you intend it to become a option again :) cheers good job and keep it up!

**Comment by queicherius** [comment]
Works just fine for me:

<img width="1244" alt="screen shot 2017-09-08 at 19 50 16" src="https://user-images.githubusercontent.com/4615516/30224272-6482d970-94ce-11e7-92d3-5c1fdafd4000.png">

There is potential that it fails the first time you load an account, if the API request takes longer than expected. If this is not the case, please email the the gw2 account name you are searching for to admin@gw2efficiency.com and I'll take a closer look. :)
