### ISSUE TITLE
Recipes not matching

### ISSUE THREAD

**Issue by Greaka** [gw2efficiency/issues#819]
![image](https://user-images.githubusercontent.com/2805834/30453485-4bc99840-9999-11e7-9009-999805885010.png)

![image](https://user-images.githubusercontent.com/2805834/30453419-230c47cc-9999-11e7-8974-5f82e2b672f0.png)
I own the minor sigil of malice but in this view, these both are switched. i dont know if thats a generel bug or an api fail.

**Comment by queicherius** [comment]
We just display the API information there, so its most likely an API bug.
