### ISSUE TITLE
Request: allow query string parameters to set filters

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#820]
I would like to be able to make a link like `https://gw2efficiency.com/account/achievements?filter.display=available-points` that would go directly to earnable achievements, or `https://gw2efficiency.com/account/home-cats?filter.show=locked` to show someone which cats they don't have yet.

**Comment by queicherius** [comment]
Yeah, this is definitely something I had on my mind when doing #814. Should do this soon.

Includes #214 and part of #47

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
