### ISSUE TITLE
button to refresh "use own materials" crafting

### ISSUE THREAD

**Issue by Fishrock123** [gw2efficiency/issues#821]
It'd be really nice to be able to manually kick off re-crawls of my owned items data so I can see an updated crafting price for say, a legendary. :)

This is something I could probably help with? Idk how OSS this is or not.

**Comment by queicherius** [comment]
If you are talking about the crafting calculator, that is already possible:

![](https://i.imgur.com/L69DBVm.png)

**Comment by Fishrock123** [comment]
Oh hmm. I'd suggest that isn't a very intuitive spot for it - at the top with the other options would be better.

Also it would seem to me just a manual button would be fine / better, but if this already exists... 
¯\\\_(ツ)\_/¯

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
