### ISSUE TITLE
Crafting calculator memory leak

### ISSUE THREAD

**Issue by Akababa** [gw2efficiency/issues#823]
![image](https://user-images.githubusercontent.com/4205182/30523524-621803f0-9ba8-11e7-99b7-92c215686df9.png)

I had it open in the background overnight

**Comment by queicherius** [comment]
Did you have the "automatically refresh own materials" enabled?

**Comment by Akababa** [comment]
I don't believe so, although I'll test once more just to make sure.

**Comment by queicherius** [comment]
Another idea I had - do you run an Adblocker of any sorts? If no, then it might have been the ads, because they reload every minute and they probably don't clean up after themselves.

**Comment by Akababa** [comment]
Good idea - I'll try again with ublock off. 
It might have something to do with my laptop's hibernation mode too.
![image](https://user-images.githubusercontent.com/4205182/30678502-442532c0-9e58-11e7-9e2d-b010f8c06f04.png)

**Comment by queicherius** [comment]
If you have ublock off then that the ads are probably the issue. Sadly I have no real influence over that :( Feel free to turn Adblock on if you tend to keep pages open for long amounts of time.
