### ISSUE TITLE
Missing Super Adventure Box achievement cathegory

### ISSUE THREAD

**Issue by Abaranasia** [gw2efficiency/issues#824]
It might be an API issue, but I've noticed that the SAB achievement cathegory is not visible since few months and it seems that, because of that, the total achievement points per account differs from the ones in game.

Thanks a lot for your awesome work and keep rocking!

**Comment by queicherius** [comment]
Sadly that's an API issue: https://github.com/arenanet/api-cdi/issues/544

Thanks for the sweet message :)

**Comment by Abaranasia** [comment]
Wow, thanks a lot for the fast response! How sad that it's an API issue for a long time now :/

Greetings from Tyria!

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
