### ISSUE TITLE
Fix completed dungeons not resetting correctly

### ISSUE THREAD

**Issue by Syviana** [gw2efficiency/issues#828]
Yesterday I stopped doing dungeons 2hours before reset but all of paths I did yesterday still are marked as done. It's both in daily tab and in dungeons tab. Saw this happening few times already.

**Comment by queicherius** [comment]
Hm, that is weird. Did the other daily things reset? Did you have the page open during daily reset?

**Comment by Syviana** [comment]
I had the same problem with fractals one time (probably just once because I like never do them) and I can't recall if I had open page during each of this but last time yes :P rest of dailies i did in those days reset normally.

**Comment by queicherius** [comment]
Fix was fixed about a month ago :)
