### ISSUE TITLE
Investment tracker. Sell custom number of items, instead of complete stacks.

### ISSUE THREAD

**Issue by Zriel88** [gw2efficiency/issues#829]
I think it would be usefull to be able to sell custom number of items of a stack tracked, than having to sell it all in one stack.

Maybe it is already implemented and I fail to see how to do it.

Thanks for the tool BTW, it's quite nice.

**Comment by queicherius** [comment]
This was implemented before and got scrapped when the backend was rewritten. Since the interest is still there, I'll see that I can add it back somehow.

**Comment by mirtisdyleris** [comment]
Would be awesome - would love that feature.

**Comment by queicherius** [comment]
This is now live.
