### ISSUE TITLE
Add a raid planner

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#83]
_No specific idea yet, just that it would be neat to have one._

**Comment by bic-mag** [comment]
I like this idea. Maybe have a composition guideline dependant on the boss you attempt. So you can choose e.g. Vale Guardian and the planner would notify you, that you will need 2-3 condition roles on top of healer, tank and 5-6 zerker DPS players.

**Comment by queicherius** [comment]
This would be a tool on its own, and doesn't really fit into the vision for gw2efficiency.

Closed during cleaning.
