### ISSUE TITLE
Guild hall upgrades: incorrect prerequisites

### ISSUE THREAD

**Issue by RankkaApina** [gw2efficiency/issues#832]
My guildhall available upgrades are incorrect. There are some upgrades that have the correct level, but are missing the prerequisite (for example: Guild hall music: super adventure box and several pvp and wvw upgrades you can get only after lvl2 construction. Also several of the war room upgrades have other prerequisites and are not showing as upgradable. I have marked the lvl2 construction things in the picture, but I'm not sure what the other upgrades need (I forgot to check and I cannot connect to the game at the moment).
![guildhall_updates](https://user-images.githubusercontent.com/7052176/31778848-f78d03ec-b4f1-11e7-98ba-c5c28221df88.png)

**Comment by queicherius** [comment]
This is an API issue, the prerequisites are randomly missing about 2/3 of the time. I already reported it, and as soon as it'll get fixed in the official API (hopefully soon), it'll be fine on gw2e as well. 🙂
