### ISSUE TITLE
Add the ability to sort in the achievement page

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#833]
- Total/remaining cost
- Total/remaining AP
- Completion %

**Comment by KraalFardale** [comment]
Seconded, I'd love to be able to see the next biggest AP returning achievement!

**Comment by ShiningMassXAcc** [comment]
Remaining cost is great here as well

**Comment by queicherius** [comment]
Just a pointer for folks looking at the ticket, sorting by [AP](https://gw2efficiency.com/account/unlock-statistics) is already available.

**Comment by queicherius** [comment]
Tried to implement this for this release, but the reality of the situation is that the old render framework in not able to handle this in a acceptable way. -> #1367
