### ISSUE TITLE
Achievement points statistics

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#835]
Hope this isn't a duplicate...

Would it be possible to get a statistics page for achievement points? We currently have number of achievements only.

**Comment by queicherius** [comment]
I deliberately left that out when I first implemented it, because there are [official leaderboards](https://leaderboards.guildwars2.com/en-gb/eu/achievements) already. Would this feature have any improvements over the official one?

**Comment by Skaldhor** [comment]
Well, it would be easier to access, because it's like 1 one click away, when you're on gw2efficiency already.

**Comment by ralesk** [comment]
Exactly as @Skaldhor said.

The gw2eff stats are also a little different (breaks up by time spent, for example), so it's another way of looking at the same thing really.

**Comment by ralesk** [comment]
Also, I thought: it shows (or would have shown, if it had tracked it in the past) the progression — when did I break 10k? 5k? etc. :)  I think that can be/could have been kinda interesting.

**Comment by samulisoderlund** [comment]
+1 for achievement points graph

**Comment by jacob-keller** [comment]
+1 for a history graph, which is the primary advantage over the main site originally.

**Comment by NaturallyNick** [comment]
I use the "leaderboards" more for comparing the average value of a certain item (AP points in this case) in the different levels of playtime. So +1 from me as well. It would be nice to see what percentage of gw2eefficiency users had 5k AP or so on.

**Comment by derRAV3N** [comment]
I'd also like to see this feature, as there is no graph on the official leaderboard.

**Comment by queicherius** [comment]
Sadly right now this is pretty impossible to implement, because since the API lost it's whitelist all historical achievements are missing from the API, and the API does not give a total of achievement points that an account has ([Issue](https://github.com/arenanet/api-cdi/issues/299)).

**Comment by queicherius** [comment]
Closing this because realistically we are not getting a feature that has been open on the official API that long. Will open a fresh ticket if we do get it at some point.
