### ISSUE TITLE
Wallet - Elegy Mosaic description - text formatting

### ISSUE THREAD

**Issue by Skaldhor** [gw2efficiency/issues#836]
> Earned by completing legendary bounties in the Crystal Desert. Spend at the Tomb of Primeval Kings. <<c=@Flavor>>These markers were used to commemorate great deeds in the Dynastic Era of ancient Elona. <</c >/c>

**Comment by maxOS1104** [comment]
I think that part is provided by the API, so it needs to get fixed there, right?

**Comment by queicherius** [comment]
Nah, gw2e just overwrites the formatting (e.g. making it _italic_)

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
