### ISSUE TITLE
Video ads at the bottom of the page steal focus

### ISSUE THREAD

**Issue by tarwatirno** [gw2efficiency/issues#838]
Often video ads at the bottom of the page will "steal focus" and cause the page to continually scroll to the bottom.

**Comment by queicherius** [comment]
I have specifically requested non-video/audio ads from Sovrn (my advertising partner), but sometimes a few black sheep get through the cracks. Sorry about that.

Next time it happens, please follow [this guide](https://www.sovrn.com/hub/learn/report-bad-ads/) and send the data to admin@gw2efficiency.com, and I will pass it on to Sovrn, which will get the company deploying the ads blacklisted on the entire platform.
