### ISSUE TITLE
Add an option to set everything to craft, trade post or best price

### ISSUE THREAD

**Issue by akyryz** [gw2efficiency/issues#839]
in crafting calculator, the default recipe tree calculation is by best price, is there a way to add an option to set everything to craft, trade post or best price?

also there are 2 problems with that: the first one is changing item by item takes longer based on the list size and it seems that after changing each option, the site freezes for a second. and the second one is the "Update own materials & best path every minute" that resets the list options every time it updates.

**Comment by queicherius** [comment]
I like the idea, possibly ties in with #58

**Comment by queicherius** [comment]
This is now live. Thanks for the feedback! Better late than never 😅

**Comment by VariableFlame** [comment]
Thank you so much for implementing this! I volume craft thousands of gold worth of items a week. You have no idea how many clicks this saves me <3

**Comment by akyryz** [comment]
uh... it's affecting top/root items too.
if you get for instance the daily items:
https://gw2efficiency.com/crafting/calculator/a~1!b~0!c~0!d~20-46744;20-46742;20-46740;20-46745
 and set to "Buy all", instead of setting to buy the sub components,
it just set to buy the item itself.

i'm not sure which is the more appropriate way to handle,
- if the item in question can be bought, set it to buy;
- or set the root item to craft and set the sub components to buy.

**Comment by queicherius** [comment]
> it's affecting top/root items too:

Whoops, I didn't test it with multiple crafting recipes. It should always set those to "craft". I opened another ticket here: #1117

> also if you can't buy the sub components,
it should be set to "Crafting".
"Buy all" is unchecking "Crafting",
setting sub components to none.

That is a bug, it should def. keep those on crafting (and it my tests it did, not sure why those items are breaking.). New ticket for that here: 1118
