### ISSUE TITLE
Add value to the new account bound halloween miniatures

### ISSUE THREAD

**Issue by XanderDrake** [gw2efficiency/issues#840]
The new account bound minies purchased with Candy Corn Cobs (Mini Halloween Gourdon (20 Cobs) and Mini Lord Humphrey Faren (100 Cobs)) have no value.
Edit; While going trough the halloween stuff I also noticed that the lunatic recipes have no value either (1-2 Cobs each).

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄

**Comment by lemming64** [comment]
I was checking today and these items don't have value, did this get released, or did it break after?

**Comment by queicherius** [comment]
@lemming64 These currently don't have a value because they technically don't exist in the API since the recent [whitelist debacle](https://en-forum.guildwars2.com/discussion/45906/current-state-of-the-gw2-api-july-2-2018)
