### ISSUE TITLE
Nightmode Icon not displaying

### ISSUE THREAD

**Issue by LittleAvani** [gw2efficiency/issues#841]
The nightmode icon is not displaying on the page. I'm using Windows 7 and Google Chrome.

**Screenshot:**
![mnaasd92](https://user-images.githubusercontent.com/13744449/32291212-b5d15836-bf3c-11e7-9777-4003f296c906.png)

**Comment by queicherius** [comment]
Are any of the other icons loading?

Cheers,
David

**Comment by LittleAvani** [comment]
I think yes. On my mobile phone (iPhone 6s and Safari) the icon is working as normal.
![chrome_2017-11-02_11-08-32](https://user-images.githubusercontent.com/13744449/32320495-3f305c36-bfbe-11e7-8866-d16b1010fb65.png)

**Comment by queicherius** [comment]
Oh... it's because the icon is an emoji, and emoji support got in with Chrome on Windows 10 :(

I can possibly change it to just be an icon instead.

**Comment by mirtisdyleris** [comment]
Would be awesome if you would make it that the logo changes if u are in darkmode - doesnt look the best because the contrast is quite shitty. ty c:

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
