### ISSUE TITLE
Fix Crystal Desert mastery points achievement filter

### ISSUE THREAD

**Issue by Skaldhor** [gw2efficiency/issues#848]
I can't filter achievements which give crystal desert mastery points.
I can filter the other mastery points, and when filtering by all points, crystal desert ones are included.
![image](https://user-images.githubusercontent.com/31501365/32725596-fc0ccd8e-c875-11e7-940d-f4a762aeadba.png)

**Comment by queicherius** [comment]
Can confirm as a bug, seems like the "region" changed from `Crystal` to `Desert`

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
