### ISSUE TITLE
Crafting calculator displays repeated items incorrectly if they are the only item

### ISSUE THREAD

**Issue by BenLubar** [gw2efficiency/issues#849]
Example: I have 250+40 of the "Tribute" items for both of the legendary weapons released in LW3EP6 in my bank and would like to craft enough Mystic Tributes to make all of the "Shard" items to free up those two slots of 40.

I don't want to force myself to craft the same Mystic Curio recipe over and over if one is going to become cheaper after I use up some of my materials, so I made this monstrosity of a URL:

<https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410;1-79410>

As you can see, the calculator is only showing the recipe for one mystic curio.

However, if I look up the shards directly, like this:

<https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-81961;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069;1-82069>

The calculator correctly displays all 80 items. This can also be done by using the first link and adding a cheap item to it, like a single lemon bar.

**Comment by queicherius** [comment]
Duplicate of #18

**Comment by BenLubar** [comment]
@queicherius oh, that too. Sorry if I wasn't clear, but the bug I'm reporting here is that if you put multiple copies of one of the same item in, it only shows the recipe for one, but if you add any other item, it shows the correct number.
