### ISSUE TITLE
Feature Request: Crafting Calculator time gated craftings

### ISSUE THREAD

**Issue by juhabe** [gw2efficiency/issues#850]
It would be really helpful if I could filter the time gated craftings for a project. I can already select if I buy or make the time gated mats, but that is not what I suggest. If I plan to make e.g. a legendary, there are a lot of time gated craftings I have to craft. And I would start to craft them before anything else and maybe even before I have all other mats together.
Hope thats understandable.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
