### ISSUE TITLE
Gifts (for legendary armor) only visible when in bank

### ISSUE THREAD

**Issue by LokstarValHallen** [gw2efficiency/issues#852]
Hi.
If i place gifts (bones/dust etc) on my character, it is not showing on item search (and thus it is not calculated for crafting as 'owned material'. If i place this items in bank, they are found and properly calculated.

Browsing specific character inventory (not searching) properly shows item in question in their bag slots though.

It might be related to [this issue](https://github.com/gw2efficiency/issues/issues/752)

Items which i tested and are affected:
- Gift of Dust
- Gift of Bones
- Gift of Scales
- Gift of Fangs
- Gift of Blood
- Gift of Totems
- Gift of Claws
- Gift of Venom
- Gift of Dedication
- Eldritch Scroll
- Legendary Insight

Haven't tested more, all of those are used for Legendary Armor which i happend to be crafting when i noticed it.

**Comment by queicherius** [comment]
Could you please send me your API key for debugging, either here as a comment or via Mail to admin@gw2efficiency.com (if you don't want it public). Thanks!

**Comment by queicherius** [comment]
Closing this since there was no feedback in a reasonable timeframe, so I assume the issue fixed itself. 😄
