### ISSUE TITLE
Add Gaeting Crystals and Unstable Cosmic Essence to Statistics

### ISSUE THREAD

**Issue by EchizenKurage** [gw2efficiency/issues#856]
Add [Geating Crystals](https://wiki.guildwars2.com/wiki/Gaeting_Crystal) as new raid currency to the account statistics. 

Also would be nice to know how many people have how many [cosmic essences](https://wiki.guildwars2.com/wiki/Unstable_Cosmic_Essence) from the 100cm fractal. In addition count one red infusion as 90 cosmic essences for the account.

**Comment by queicherius** [comment]
This is now live (but will take 24h to populate). Thank you for your feedback. 😄
