### ISSUE TITLE
Add custom tasks to daily todo list

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#869]
The current Daily page is great, but I have a number of tasks that I have to keep in mind to do every day in addition to the listed ones. It would be nice to be able to add/edit custom tasks to our daily todo list.

**Comment by queicherius** [comment]
Yes, this was planned during the development of the daily page but never made it in due to time constraints. Weird that I never made a ticket for it, thanks for that! :)

**Comment by samulisoderlund** [comment]
Yes! This is the only reason I can't use GW2 Efficiency for my daily checklist. I also don't want to have two separate checklists.

**Comment by MarcusSchwarz** [comment]
![I'm only here to leave an](http://www.reactiongifs.com/r/2013/02/murray_upvote.gif)

**Comment by queicherius** [comment]
This is now live. Sorry it took so long x_x
