### ISSUE TITLE
Login/Password Remind not working

### ISSUE THREAD

**Issue by MokahTGS** [gw2efficiency/issues#870]
Is the login/Password remind feature broken?  I can't get it to send me a remind for resetting my password.

**Comment by MokahTGS** [comment]
https://gw2efficiency.com/password/remind

This does not load for me.

**Comment by queicherius** [comment]
Everything should be back to order, sorry about that. The server crashed while I was not able to read my messages. :(

**Comment by MokahTGS** [comment]
The system is now saying it doesn't have an email associated with my account.  Not possible.  It's still broken.

**Comment by queicherius** [comment]
The system is working fine again, feel free to send a support request to admin@gw2efficiency.com with your username / email / an API key linked to the account.
