### ISSUE TITLE
Set maximum % Demand > Supply

### ISSUE THREAD

**Issue by henryfoster** [gw2efficiency/issues#874]
Hallo,

I want to suggest some features:

1. When you want to mark an buy or sell as investment you need to track the item, type the amount and price. This takes alot of time. It would be faster and easyer when you would have a tickbox in your buy/sell list or in your transactionhistory to mark a buy or sell as an investment.
1.1 When I want to sell an investment I can only sell all the items but when I ordered 100 and got only 50 how Im supposd to mark only 50 as sold? My first sugestion would also help with that If you could mark a finished transaction as investment. The investment itself would still stay in the owerviewtab but the writingwork would be automatized.

2. You have a cool feature in your [search for items tab] which is called [Demand > Supply] the problem is that you also get things like 0supply and 1000000demand which is is bit useless. There should be a second option to set the maximum % Demand > Supply for example I want to find Items where the demand is only 10% higher then the supply but I dont want to see items where the demand is like 100% higher then the supply.

3. Most items are (I call them) dead items which look very promesing on the first sight but if you try to trade them you will notice that noone buys or sell them even if the demand and supply is very high. It would be very cool to see how often item x was traded in the last 24h/7d/14d/month or so to find out if its woth investing money.
Yes I know you can also read this out of the supply/demand chart but it takes a lot of time and its not that clear.

Have anice holidays great work with your site

**Comment by queicherius** [comment]
1. #99 
2. Yeah, that field should be min/max really
3. #215

**Comment by henryfoster** [comment]
Ah thank you for the answer!

**Comment by queicherius** [comment]
This went online 4 days ago :)
