### ISSUE TITLE
Price problem - Recipe: Gift of Blades

### ISSUE THREAD

**Issue by lemming64** [gw2efficiency/issues#875]
On the Recipes tab the 3 versions of this are all listed as 62s50c, however they all currently cost 5g from Miyani 

https://wiki.guildwars2.com/wiki/Recipe:_Gift_of_Blades 

Not sure where the current listed price is coming from.

**Comment by queicherius** [comment]
The 62s is the vendor value. Ill have to manually add the value for these. :)

**Comment by queicherius** [comment]
This is now live.
