### ISSUE TITLE
Add new permanent (?) rich iron ore

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#877]
![gw080](https://user-images.githubusercontent.com/4615516/34469138-6661ed8e-ef10-11e7-9f05-7267ff9ce981.jpg)
![gw079](https://user-images.githubusercontent.com/4615516/34469139-667a1648-ef10-11e7-8586-b8a98ae5ddee.jpg)

**Comment by kazerniel** [comment]
It's not new, and already appears on the Permanent Nodes page. It's one of the ones that can be either Iron or Silver.

**Comment by queicherius** [comment]
Oh, you are correct. Thanks for saving me the effort. 👍 😆
