### ISSUE TITLE
Idea: Be able to set which (if any) expansion packs a user owns

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#879]
This could have multiple uses:
- To hide the unavailable PvE dailies. (Useful even for people who have all expacs, as it currently shows core dailies even when they are not available to HoT/PoF players. I assume manually hiding these would hide them when they are general dailies as well.)
- To hide unavailable [recipes](https://gw2efficiency.com/account/recipes) (eg. I don't have PoF yet, so I can't buy PoF recipes even from the TP. Currently when I'm working on my collection I have to keep in mind which recipes require PoF.)

**Comment by queicherius** [comment]
Technically, the API exposes which expansions you own already (e.g. [with my key](https://api.guildwars2.com/v2/account?access_token=BFCDF695-5D2D-114F-B6A1-FC2466C79A2692147B4D-20B1-4C45-BA25-43808695A041) it's `"access": ["GuildWars2", "HeartOfThorns", "PathOfFire"],`).

**However**

- the API for the dailies just marks everything (wrongly) [as HoT dailies](https://api.guildwars2.com/v2/achievements/daily) - see this official issue: https://github.com/arenanet/api-cdi/issues/574
- the API for the recipes don't exposes the required access information at all

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket. Also the API does not support it currently and I don't really see that changing soon.
