### ISSUE TITLE
Mini Failed Attempt 

### ISSUE THREAD

**Issue by lemming64** [gw2efficiency/issues#888]
Valued at 1g as per vendor sell price on the miniature page, however there is a set ingredient list to craft this in the forge which currently is around 30g of materials.

https://wiki.guildwars2.com/wiki/Mini_Failed_Attempt

![image](https://user-images.githubusercontent.com/31589475/34941186-9b081ad8-f9ea-11e7-9fed-d9a2028752b2.png)

**Comment by queicherius** [comment]
Yeah there is a missing recipe for that in https://github.com/gw2efficiency/custom-recipes

**Comment by maxOS1104** [comment]
Just FYI, the link that leads to the forum thread in the Readme of https://github.com/gw2efficiency/custom-recipes links to the old forum, I don‘t know if there is a thread in the new forum (not yet?)

**Comment by queicherius** [comment]
Oh good point. I don't know, I don't really use Mystic's Version anymore because it ended up being super hard to update my list from it. Should probably remove the link.

**Comment by queicherius** [comment]
This is now live.
