### ISSUE TITLE
Unlock statistics: add value to achievements

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#891]
First of all, great feature! Thank you!
But I noticed something: achievements have no value attached to them. 
Maybe you can use that column to show the maximum of achievement points achievable for this achievement?

**Comment by queicherius** [comment]
I wanted to show the price of the achievement there (basically the completion cost), since that's more inline with how the other unlocks work. However, this needs some extra backend work.

**Comment by RLHawk1** [comment]
Is there any chance you could add Achievement point value also then?  I really like using this screen to show locked achievements sorted by the % unlocked by playerbase to see somewhat low hanging fruit. But it'd be nice to see AP value also.

**Comment by queicherius** [comment]
@RLHawk1 I made a [new issue](https://github.com/gw2efficiency/issues/issues/984) out of your request, since that is a lot easier and might get in on it's own.

**Comment by queicherius** [comment]
Duplicate of #110
