### ISSUE TITLE
Fix redirect to wiki when clicking items on mini/recipe pages

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#898]
On the miniatures page (don't know about other pages), clicking an icon to open the tooltip menu first opens the menu and then redirects to the wiki page of the item. I think that's just the old functionality that has to be disabled.

**Comment by queicherius** [comment]
Oh, whoops. Good find. >_>

**Comment by queicherius** [comment]
This is live since yesterday. :)
