### ISSUE TITLE
Shopping list asking for both logs as well as planks

### ISSUE THREAD

**Issue by Meznuraie** [gw2efficiency/issues#899]
My "Shopping List" is asking me for 8,452 Elder Wood logs as well as 240 Elder Wood planks, for example. It's doing it for all the items in the list, not just that one.

Is there a reason it's asking for both, instead of one or the other?

**Comment by Meznuraie** [comment]
Today it's fixed, only asking for logs not planks. I don't know if you fixed it, but thanks!

**Comment by queicherius** [comment]
I didn't change anything, but if it's working I ain't complaining! 😆

**Comment by Meznuraie** [comment]
This morning it asked for elder wood staffs as well as elder wood logs.... and then I refreshed the page a couple of hours later, and it went back to just asking for logs. I have no idea why it's doing it, unless it has something to do with purchase price?

**Comment by queicherius** [comment]
Well it tries to optimize the crafting tree entirely by buy price. Do you use "use own materials"? Because in that case it tries to use as many of your materials as possible as well as be as cheap as possible, potentially resulting in a case where it tells you to craft some out of what you have and then buy some because they are cheaper.

**Comment by Meznuraie** [comment]
I've told it to "Use own materials" because I'm intending to farm it all... Which means it's hard to keep track of how much more I need to get when it's asking for things like planks or staffs, rather than the raw materials.

**Comment by kazerniel** [comment]
I got the same bug just now:
what I own:
![screenshot 1](https://user-images.githubusercontent.com/5689996/50727900-eaa44700-1119-11e9-84ab-ff7354c760df.png)
what it tells me to buy:
![screenshot](https://user-images.githubusercontent.com/5689996/50727902-eb3cdd80-1119-11e9-9f0f-caae74da44ed.png)
