### ISSUE TITLE
Statistics: Completed Dungeons displays 0

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#905]
I have plenty of tokens which means I've definitely done dungeons before — yet it displays 0 for me, and I suspect the table on the bottom of the page is also distorted by this (I mean, there are probably multiple accounts having this issue).

Is this a new field in the statistics page? Can't remember it from before anyways.

**Comment by queicherius** [comment]
The completed dungeon count can only get calculated once you finish the "Dungeon Master" achievement.
