### ISSUE TITLE
Statistics: Mastery Points (Crystal Desert) dropped to 0 on Jan 25 2018

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#906]
Wonder what happened, it was however 8 days ago when you released https://github.com/gw2efficiency/issues/issues/897 so my suspicions are with that bugfix causing a regression.

**Comment by queicherius** [comment]
Oh whoops, thanks for the notice!

**Comment by queicherius** [comment]
Turns out this is an official API issue: https://github.com/arenanet/api-cdi/issues/599

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
