### ISSUE TITLE
Add "delta" into statistic graphs

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#907]
We have an average play time and a total play time panel, but I was thinking maybe a new kind of stat "how many hours did I play last day".  Of course that's more of a bar chart kind of thing — could well be a toggleable overlay on the main line chart (no idea if the current chart tool is able to do that).  Similarly: "how many times did I die last day" (though that's just easily countable from the main death count stat, so not so useful/important).  Maybe there are other long-running accumulation graphs that could do with an optional "delta" overlay?

There are some possible problems with this, including: when does the player tend to play inside the day, when does the refresh run for the particular account (if not multiple times if the API key is registered multiple times) (also the refresh time skews currently, when everything is smooth it seems it's every 24h15m), and possibly more.

**Comment by queicherius** [comment]
This is kindof integrated with #653 but it's a lot of work I can't justify right now. Nice idea for the future tho!

**Comment by queicherius** [comment]
Actually, this is much more doable than I first thought, essentially I just need to be able to switch the graph from "accumulated" to "delta".

**Comment by queicherius** [comment]
This is included in #954
