### ISSUE TITLE
Extreme lag in dark theme

### ISSUE THREAD

**Issue by ProjectPatatoe** [gw2efficiency/issues#911]
The page animations are extremely laggy when using the dark theme on the Daily page. This is especially when the boxes are shifting around.

Happens on Firefox 58.0.1

Chrome 63.0.3239.132 is OK

Edge 40.15063.0.0 doesn't lag while animating but does have a delay.

**Comment by queicherius** [comment]
Could reproduce, super weird that it only happens with dark mode...

**Comment by queicherius** [comment]
Fix for this is now live.
