### ISSUE TITLE
track total achievement points over time

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#912]
In the account statistics, there's a statistic for "finished achievements" but there isn't one similar for "total achievement points".

I know that as a leaderboard, it's not very valuable because there is an official leaderboard run by ArenaNet. However, this doesn't show your personal history.

I'd love to be able to see at what point I reached certain milestones, and I can do that for other statistics in the gw2 efficiency website interface, but not for achievement points themselves.

**Comment by queicherius** [comment]
Duplicate of #835
