### ISSUE TITLE
Invalid API key error on new key

### ISSUE THREAD

**Issue by Klikzorz** [gw2efficiency/issues#914]
Lately I started to have "Invalid api key" error when using trading post -> Transaction history. Any option I pick there (like order by) is showing me api key error.  Other account I have work normal. I even removed old key and made new one but that did not fix the error.
Gw2 ID-  klikzorz.2697

What I tried:
-make new api key
-change browser (chrome)
-clear cache(firefox 56.0.2 (64-bit) ).

Is it only me or anyone else have this problem?

**Comment by Klikzorz** [comment]
Sent!  I also added old removed api key and key from 2nd account.

**Comment by queicherius** [comment]
Thanks. This is an official API bug, which I will report to the developer with your key. Please do not delete that key. 👍

**Comment by Klikzorz** [comment]
Sure, no problem can leave it on- other stuff still works perfectly fine. : )

**Comment by Klikzorz** [comment]
Look like trading post options work again even though some items have double numbers.

**Comment by queicherius** [comment]
Tracking issue in the official repo: https://github.com/arenanet/api-cdi/issues/606

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
