### ISSUE TITLE
Items in TP not shown

### ISSUE THREAD

**Issue by seePyou** [gw2efficiency/issues#916]
I have an exotic crafted item in TP that is not shown in the tradepost entries in any section. What exactly can I provide to help with diagnosing this?

**Comment by queicherius** [comment]
- If you are talking about the current transactions - that is a known official API bug
- If you are talking about any other page, which item?

**Comment by seePyou** [comment]
I am talking about current transactions :) Thank you for getting back to me!

**Comment by queicherius** [comment]
Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
