### ISSUE TITLE
Feature Request: Farming page, flash updated or inserted rows

### ISSUE THREAD

**Issue by GeeWizWow** [gw2efficiency/issues#920]
Hey, 

I'd love to see some kind of animation played when rows are updated or added.
I can't remember what app / website does this, but they change the row background to a "yellow-ish" background then fade it back to white to indicate a change.

Bonus points for using requestAnimationFrame, so the animations are queued if the user doesn't have the browser tab / window in focus.

**Comment by queicherius** [comment]
That seems like a cool feature, but might be pretty hard to implement since not all rows are actually rendered to the screen at all times (only the rows the user can see are).

**Comment by queicherius** [comment]
Since the rows are not rendered until in the viewport this is super annoying to implement. 
This is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
