### ISSUE TITLE
Add values to magnetite shard weapons

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#925]
The normal weapons traded for magnetite shards all have no value listed. Could this be updated to the average cost of a weapon of their type, get a fixed value like the raid drop weapons, or at least their gold cost?
I have not testet it, but the buyable weapons from fractals will most likely also have no value.

**Comment by queicherius** [comment]
Are those ascended weapons?

**Comment by MaxG46** [comment]
yes, they all are.

**Comment by MaxG46** [comment]
How could I help you with this?

**Comment by queicherius** [comment]
For reference:

- https://wiki.guildwars2.com/wiki/Basic_Magnetite_Exchange_Operative
- https://wiki.guildwars2.com/wiki/Scholar_Glenna_(Spirit_Vale)
- https://wiki.guildwars2.com/wiki/Scholar_Glenna_(Salvation_Pass)
- https://wiki.guildwars2.com/wiki/Scholar_Glenna_(Stronghold_of_the_Faithful)
- https://wiki.guildwars2.com/wiki/Scholar_Glenna_(Bastion_of_the_Penitent)
- https://wiki.guildwars2.com/wiki/Scholar_Glenna_(Hall_of_Chains)

**Comment by MaxG46** [comment]
I have found some more itmes without values:

- The Chest of Slothasor Gloves has a value, but the items yout get from it does not.
- The Armour form "Chest of Raider's xyz"

**Comment by queicherius** [comment]
I am going to close this for #997 instead, to clean up all the issues regarding this.
