### ISSUE TITLE
Update Sigil of Mischief Recipes 

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#926]
Sigil of Mischief Recipes  still uses old [Snowflake](https://wiki.guildwars2.com/wiki/Pristine_Snowflake) instead of new [one](https://wiki.guildwars2.com/wiki/Snowflake).
Please update it for consistency :)

**Comment by queicherius** [comment]
[Online now](https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-86180) thanks to @CuriousCharr 💯
