### ISSUE TITLE
Use chat link instead of item name when linking to wiki

### ISSUE THREAD

**Issue by Zimbaland** [gw2efficiency/issues#927]
Looking for missing recipes for my **jeweler**, I stumbled across the linking of _Recipe: Owl Amulet_ and _Recipe: Owl Amulet (Jeweled Broach)_ which both link to the same recipe (the one first mentioned). Maybe searching the wiki by id may be the solution and not by name (guessing thats the implement).

**Comment by queicherius** [comment]
Yeah atm we are seaching by name. We could also search by chatlink, but then you take longer to load it. Might be worth for the better detection of which page we want.

**Comment by Zimbaland** [comment]
If it is worth the time going through the items or react on user reports, it would be better to set a flag for specific items to search with chat link and leave the rest to searching by name.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

The main reason for this is that we use the same functionality to search for unlocks (e.g. skins / pvp heroes / gliders / ...) and for those the search by the chat code does not work on the wiki. I attempted to implement this twice and stopped both times, so it's probably best as it is right now (with a best-effort based on the item name)

**Comment by queicherius** [comment]
Let's try once more. It should be much easier now in the new codebase.
