### ISSUE TITLE
Farming Tracker: Export Results to CSV file

### ISSUE THREAD

**Issue by MOUZU** [gw2efficiency/issues#935]
Hello there,

another (minor) suggestion: You might want to consider building a feature to export the results to a file on the frond end. This would enable users to keep track of their data for as long as they want to, which gives the possibilities to comparing farming results.

A simple csv format would suffice from my perspective.

Best regards.

**Comment by queicherius** [comment]
Definitely on the to-do list! ATM just monitoring which features are used most to see where to put my time.

**Comment by queicherius** [comment]
This went online 4 days ago :)
