### ISSUE TITLE
Exclude Non-Tracked items from Tradingpost search

### ISSUE THREAD

**Issue by bic-mag** [gw2efficiency/issues#936]
Currently non-tracked items on the TP site are only excluded if the filter is clear.
I want to be able to filter **only** my tracked items by e.g. rarity without simultaneously searching the entire TP for all items of that rarity, because that takes very long.

**Comment by queicherius** [comment]
Optimally the search itself should be near-instant (#42) but this is a good idea to quickly fix the main issue (that I have been pushing in front of me for ages)

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
