### ISSUE TITLE
[Bug] Gem to Gold Graph is showing incorrect values

### ISSUE THREAD

**Issue by bic-mag** [gw2efficiency/issues#942]
The Gem to Gold graph is not updating correctly anymore and shows flat-line for about the last 2.5 months.

**Comment by queicherius** [comment]
ATM we use the gem/gold history provided by gw2spidy and their updater broke recently. Luckily nothing to do with the API bug (tho that one does exist)

**Comment by kazerniel** [comment]
Thanks, good to know.

**Comment by queicherius** [comment]
This turned out to be not an issue with gw2spidy, but an API caching bug. It's now semi-"fixed" because @Archomeda is crawling it (effectively flushing the cache?). Not sure, but it seems to work for now.

[Advanced Reading](https://gitter.im/arenanet/api-cdi?at=5acc4055109bb04332a710d8)
