### ISSUE TITLE
Disable the tradingpost part of the account value

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#943]
gw2efficiency will temporarily calculate the account value without including the tradingpost sell orders, the tradingpost buy orders, and the tradingpost delivery box. This change is due to two bugs in the official API:

---

**Bug 1) The buy/sell orders are not being updated** ([Official Issue](https://github.com/arenanet/api-cdi/issues/605))

Since some time in January 2018, the sell/buy orders (the things you are currently trying to sell/buy on the tradingpost) have not been updated. This means that your value was calculated with your tradingpost as it was in January 2018, even tho you most likely sold/ordered other items in the meantime, **which caused the value to be incorrect**.

---

**Bug 2) The tradingpost sell/buy orders may return wrong page numbers** ([Official Issue](https://github.com/arenanet/api-cdi/issues/606))

Also since some time in January 2018, the tradingpost API could return wrong page numbers. These numbers tell gw2efficiency how many pages (each page is 200 transactions) of transactions you have. Since the numbers were wrong, **we could not calculate the account value at all in some cases**.

---

We were waiting for the official API to fix the issues, but according to reports they now appear more regularly. To make it fair for all users and to fix the calculation for the users suffering from those issues, we decided to completely remove tradingpost values from the account value till the problems are fixed. Thank you for your understanding.

**Comment by kenofnz** [comment]
A workaround for bug 1 I've come across was to quickly query the gw2api twice, around 3 seconds apart, would update my trading post listings.

I haven't tried anything to verify if the workaround to update your tp listings would fix bug 2.

**Comment by 1moere1** [comment]
@kenofnz Workaround for bug 1 I can't confirm to be working for sell, only for buy. The only way to get an updated buy listing is by using a newly created api key (sometimes).

**Comment by queicherius** [comment]
> A workaround for bug 1 I've come across was to quickly query the gw2api twice, around 3 seconds apart, would update my trading post listings.

The entire account update takes about 3 seconds and it's already tricky getting all updates into 24h with the resources I have, so doubling it is pretty much impossible. 😞

**Comment by kenofnz** [comment]
Is it possible to execute only the TP api query twice?

That is assuming you can build the ``commerce`` map entry in ``accountData``   rather than doing the whole account in one call.

i just tested the workaround with my own TP listings using **no sleeps** and appears to work.

Here's a quick marshaled result of the workaround with no sleeps between queries.
```
Buy Listings
250 ---- for 856
125 ---- for 856
250 ---- for 856
106 ---- for 863
238 ---- for 863
250 ---- for 966
250 ---- for 966
198 ---- for 966
1 ---- for 8030003
Value: 953g 61s 43c <- Previous total buy value

Sell Listings
250 ---- for 944
248 ---- for 944 <- Previous listing amount
10 ---- for 8449
221 ---- for 8449
60 ---- for 2676
250 ---- for 950
115 ---- for 950
Value: 263g 62s 26c <- Previous total sell value

Buy Listings
Value: 0g 0s 0c <- Updated total buy value

Sell Listings
250 ---- for 944
244 ---- for 944 <- Updated listing amount
10 ---- for 8449
221 ---- for 8449
60 ---- for 2676
250 ---- for 950
115 ---- for 950
Value: 263g 28s 28c <- Updated total sell value

Listings refreshed
```

Seems like the API goes **inactive** on an API Key if it's not hit within a couple minutes.
Hitting it again while its **inactive** puts it back to **active** but doesn't update the data.
Hitting it multiple times while it's **active** seems to work fine.
Maybe it's a caching issue on gw2 api's end, this is just my speculation though.

**Comment by queicherius** [comment]
Hm, I'd rather wait until the official API properly works again instead of resorting to hacky fixes, but we will see how long it'll be until it's fixed. :/

**Comment by DxCx** [comment]
From my testing this looks like cacheing info,
Can you try append to each request ?ts=timestamp to skip cacheing?

**Comment by queicherius** [comment]
@DxCx I had reports of people refreshing the page daily and still not getting the items they listed 4+ days ago

**Comment by DxCx** [comment]
well since gw2efficency didnt work for me as well, i was writing a little script of my own
and im using ?ts= trick there and it works for me,
thats why i suggest it here as well

**Comment by queicherius** [comment]
> and im using ?ts= trick there and it works for me,

Interesting. I wonder if it works because of the query string or because you are requesting your data multiple times (as suggested above). I'll give it a shot when the API is fully recovered.

**Comment by queicherius** [comment]
I just re-enabled the tradingpost bit (for now without the trick that @DxCx mentioned), just to see how it will go. **Please let me know if the tradingpost parts of your account value are not correct!**

**Comment by DxCx** [comment]
did you had the chance to test it tho?
did it work for you too?

**Comment by queicherius** [comment]
It seemed to work for me without the trick as well. I can at least not see any jobs failing in the last 10 hours, but of course this does not say if the data is actually correct or not

**Comment by DxCx** [comment]
i can see the issue with buy/sell listing in trading post
it doesnt refersh correctly right now (/buys and /sells)
this is effecting account value isn't it?

**Comment by queicherius** [comment]
Yes, it should. I'll try it with the query parameter with the next deploy.

**Comment by queicherius** [comment]
@DxCx I added the query parameter - do the buy/sell listings in the tradingpost section now work correctly for you?

**Comment by DxCx** [comment]
Im not with the laptop atm (so cant really test it with the game) but ill give it a try tomorrow and report back

**Comment by queicherius** [comment]
> it took like 5 minutes after i made the change in game and till it was showen,
but that is much better then before where it didn't update the day after aswell. ;)

5 minutes is the internal cache time of the API, nothing can go past that.

> right now it will fetch a new data only when refereshing the page,
maybe adding a refersh now button like delivery box will be easier then refershing the whole page..

Yeah might add that in the future

---

Sadly I am still getting reports that people's stuff is not showing up, even after 24+ hours. 😞

**Comment by queicherius** [comment]
[**This issue was fixed in the official API!**](https://github.com/arenanet/api-cdi/issues/605#issuecomment-406752467) 🎉
