### ISSUE TITLE
Crafting order bug

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#957]
Not sure if this has been reported before: I had 4 Bolts of Gossamer, and a couple hundred Scraps. I needed 25 Bolts of Gossamer for 25 Guild Insignias, but the calculator first told me to craft the Guild Insignias out of the nonexistent Bolts, while making the Bolts out of the Scraps was only step 3.

**Comment by queicherius** [comment]
I have never seen that before or heard of that before. Can you reproduce the problem when you try to craft them again?

**Comment by kazerniel** [comment]
When I try again it shows the steps in the correct order, so maybe it was an one-off anomaly. Though this time I don't have any Bolts to start with, not sure if that influences the result. It was this crafting page btw: https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-72708;1-70984;1-74095;1-70962;1-73811;1-73589;1-75879

**Comment by maxOS1104** [comment]
<img width="873" alt="bildschirmfoto 2018-05-03 um 22 27 50" src="https://user-images.githubusercontent.com/4730112/39601126-46419970-4f21-11e8-9991-820ae727e1d9.png">
got the same bug... 

https://gw2efficiency.com/crafting/calculator/a~1!b~0!c~0!d~1-11348;1-11271;1-11229

**Comment by queicherius** [comment]
I could not figure out how to replicate this bug. Please let me know if it pops up again, preferably with "own materials" off (so I can reproduce it).
