### ISSUE TITLE
Wrong value for Mini Celestial Rooster

### ISSUE THREAD

**Issue by Tiavor** [gw2efficiency/issues#963]
Mini Celestial Rooster is listed as 1100 gold. I've looked through the patch notes and it was noted that it got inserted with the price of one BLC key. (it is account bound)

**Comment by queicherius** [comment]
The only way to get a Mini Celestial Rooster right now is through the "Black Lion Exclusives Chest", which is worth 1100 gold. Did that change?

**Comment by Tiavor** [comment]
oh, ok, nevermind then.
