### ISSUE TITLE
crafting recipe for stat +9 infusions is misleading

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#971]
If you attempt to have gw2efficiency craft the various +9 infusions, it actually shows you the stat-swap based recipes. This is likely because either (a) the regular recipes are more "expensive" or (b) the regular recipes aren't available.

For example, it ends up showing me that I can "craft" a Might +9 agony infusion by stat swapping a Malign infusion. And to craft that infusion, we stat swap it from another type, repeating for some loop.

This is pretty misleading and confusing, since none of those recipes actually create a new +9 stat infusion, so it essentially went many layers deep.

**Comment by queicherius** [comment]
Thanks for letting me know, I will take a look.

**Comment by queicherius** [comment]
The recipes are now removed.
