### ISSUE TITLE
[Bug] Daily page

### ISSUE THREAD

**Issue by whowantblood** [gw2efficiency/issues#972]
When i click "Collapse All" it only collapses one menu at a time, i have to repeatedly click it to actually collapse all

**Comment by queicherius** [comment]
I noticed this the other day as well, will take a look next time I touch the page.

**Comment by queicherius** [comment]
To save my thoughts here: Also need to fix grouping & text trimming for languages other than english.

**Comment by queicherius** [comment]
This is now fixed
