### ISSUE TITLE
Add value to "Bench of the Final Judge"

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#974]
Should inherit value of https://wiki.guildwars2.com/wiki/Shrouded_Bench_of_the_Final_Judge

**Comment by wayne-liang** [comment]
Would adding the inheritance relationship in [item-value#itemInheritance.js](https://github.com/gw2efficiency/item-value/blob/master/src/static/itemInheritance.js) solve the issue? 

Sorry if this is a stupid question, still exploring the other GW2Efficiency repos :sweat_smile:

**Comment by queicherius** [comment]
Yes, that would be exactly right :)

On 10 Jun 2018 at 12:50, <Wayne <notifications@github.com>> wrote:

Would adding the inheritance relationship in item-value#itemInheritance.js
<https://github.com/gw2efficiency/item-value/blob/master/src/static/itemInheritance.js>
solve the issue?

Sorry if this is a stupid question, still exploring the other GW2Efficiency
repos 😅

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gw2efficiency/issues/issues/974#issuecomment-396042865>,
or mute the thread

**Comment by wayne-liang** [comment]
Thanks! :)

**Comment by queicherius** [comment]
This should now be released, could you confirm? :)

**Comment by wayne-liang** [comment]
Yup, sounds good! 😄

**Comment by queicherius** [comment]
👍
