### ISSUE TITLE
Tizlak's Footwear doesn't show up in 'Ascended Weapons & Armor' section.

### ISSUE THREAD

**Issue by wayne-liang** [gw2efficiency/issues#976]
![capture](https://user-images.githubusercontent.com/21271725/41163075-cc81be80-6b8b-11e8-82e0-e3401e71b534.PNG)

Seaching for Tizlak's gear in the 'Ascended Weapons & Armor' section shows everything but the footwear. However, searching in the 'Crafting Calculator' section does show the footwear.

![untitled](https://user-images.githubusercontent.com/21271725/41163275-51447310-6b8c-11e8-88ea-66503651094b.png)

Tested across Firefox and Chrome, both show the same behaviour.

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
