### ISSUE TITLE
Trivia for today on daily page is not scaling

### ISSUE THREAD

**Issue by Lorthiz** [gw2efficiency/issues#987]
![triviafortoday](https://user-images.githubusercontent.com/31590000/42101915-d6558b32-7bc4-11e8-9d69-c1be2f32b48a.png)

When browsing content of daily page on my phone I saw that "trivia for every day" is not scaled properly and I even thou I had one column of dailies I could still scroll offscreen.
After invastigating the problem seems to be in this div where we have hardcoded value for width:
`<div class="flex items-center justify-center pa2 mb4 mt2" style="border: 1px solid rgb(73, 125, 176); margin-left: 0.5rem; width: 1154px;"><img src="/assets/zommoros.png"><div style="margin-left: 10px; font-style: italic; color: rgb(73, 125, 176);">It's dangerous to go alone! Unlock a new mini pet!</div></div>`

After removing this width property and addind right margin everything works properly:
`<div class="flex items-center justify-center pa2 mb4 mt2" style="border: 1px solid rgb(73, 125, 176); margin-left: 0.5rem; margin-right: 0.5rem;"><img src="/assets/zommoros.png"><div style="margin-left: 10px; font-style: italic; color: rgb(73, 125, 176);">It's dangerous to go alone! Unlock a new mini pet!</div></div>`

![triviafortoday2](https://user-images.githubusercontent.com/31590000/42102299-c846c5c8-7bc5-11e8-9a5c-3715056456ab.png)

**Comment by queicherius** [comment]
The daily page is actually due a redesign soon-ish, just going to keep this ticket open to remind me to check mobile compatibility.

**Comment by queicherius** [comment]
The rework is now live
