### ISSUE TITLE
Missing recipes for Rare Crafted Armor

### ISSUE THREAD

**Issue by autochthe** [gw2efficiency/issues#988]
It appears that the recipes for rare crafted armor are missing

https://wiki.guildwars2.com/wiki/Rare_crafted_armor

**Comment by queicherius** [comment]
The official API is currently completely broken, which results in items, skins, mailcarriers, minis, recipes, and outfits not displaying or calculating value correctly, and pretty much all features on gw2efficiency not working properly.

You can check the current status here: https://status.gw2efficiency.com/ - if the first column is anything else but a green checkmark, stuff is on :fire:
