### ISSUE TITLE
Add a button to instantly generate investments

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#99]
On the "buy orders" and "buy history" pages, there should be a button to instantly add investments without typing in anything.

**Comment by Irubataru** [comment]
Sorry for a shameless bump, but I think this would be great because generating investment as is now is somewhat tedious.

**Comment by Moyashipu** [comment]
> Sorry for a shameless bump, but I think this would be great because generating investment as is now is somewhat tedious.

Agree, this is something I would love to have!

**Comment by queicherius** [comment]
This is now live. Sorry it took so long x_x
