### ISSUE TITLE
Add "The Twins" ascended items to the ascended list

### ISSUE THREAD

**Issue by Pazns** [gw2efficiency/issues#994]
When I use the Crafting calculator,
I type "The Twins' Masque" into the"Search for an item" text field,
Then no item is found.

Apart from 4 items, those from Path Of Fire appear to be missing : 
https://wiki.guildwars2.com/wiki/The_Twins%27_armor 
https://wiki.guildwars2.com/wiki/The_Twins%27_weapons

**Comment by Pazns** [comment]
Suddenly light armor appeared.

@queicherius What are those labels "Help Wanted" and "Chore" ?
What needs to be done, how and where ?

**Comment by queicherius** [comment]
The "Help Wanted" is an indicator that this is something that the community could do (e.g. in this case add the recipe to [the custom recipes](https://github.com/gw2efficiency/custom-recipes).

However, it is actually possible that this is still from the fallout of the API [losing it's whitelist](https://en-forum.guildwars2.com/discussion/45906/current-state-of-the-gw2-api-july-2-2018) if stuff is appearing on its own.

**Comment by Pazns** [comment]
Indeed !
A (partial) set of the light armor appeared out of nowhere just this morning.

Still, nothing of the Twins' set appears in the [Ascended stuff catalogue](https://gw2efficiency.com/crafting/ascended?filter.search=The%20Twins%27&filter.type=0).
Is this in another API

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄

**Comment by Pazns** [comment]
Thank you for your work.
