### ISSUE TITLE
Add names to API keys (for people with multiple accounts)

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#995]

**Comment by BenLubar** [comment]
Don't accounts already have names?

![image](https://user-images.githubusercontent.com/4257305/46331324-ff35e800-c5dc-11e8-8721-240a3563f086.png)

**Comment by queicherius** [comment]
This ticket means the ability to give your keys custom "descriptions" so to speak. E.g. "main", "twink NA", "from Bob", ...

**Comment by queicherius** [comment]
Closing this because in reality, people should know which API key is which account based on their account names.
