### ISSUE TITLE
Time Machine : Page number {0,number}

### ISSUE THREAD

**Issue by Lokeri** [gw2efficiency/issues#998]
Hi ! 

On the Time machine there are a little display problem of the page number. See the screen.

![image](https://user-images.githubusercontent.com/29477823/42615721-bbefdf40-85ab-11e8-8c0b-1be15abe000c.png)

This should display a correct page number.

**Comment by queicherius** [comment]
Argh, I must have broken that yesterday. 😞

**Comment by queicherius** [comment]
Fixed now :)
